//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDUSBRES_H
#define UIFLOWWNDUSBRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,319,239,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin3Rect,0,0,271,27,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin3)
SHOW_MAP_BODY(Skin3Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin3,0,0,271,27)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text5,0,0,271,27,STRID_NULL,0,0,0,0,2,1,1,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal2)
SHOW_MAP_BODY(Skin3)
SHOW_MAP_BODY(Text5)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal2,24,106,295,133)

SHOW_MAP_BEGIN(UIFlowWndMSDC_StaticTxt_MassStorage)
SHOW_MAP_BODY(Normal2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndMSDC_StaticTxt_MassStorage)
CREATE_STATIC_DATA(UIFlowWndMSDC_StaticTxt_MassStorage,STRID_NULL_)
CREATE_STATIC_CTRL(UIFlowWndMSDC_StaticTxt_MassStorage,0,24,106,295,133)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin8Rect,0,0,194,77,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin8)
SHOW_MAP_BODY(Skin8Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin8,0,0,194,77)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon9, 0, 0, 194,77, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal7)
SHOW_MAP_BODY(Skin8)
SHOW_MAP_BODY(Icon9)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal7,64,79,258,156)

SHOW_MAP_BEGIN(UIFlowWndMSDC_StaticIcon_MassStorage)
SHOW_MAP_BODY(Normal7)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndMSDC_StaticIcon_MassStorage)
CREATE_STATIC_DATA(UIFlowWndMSDC_StaticIcon_MassStorage,ICON_USB)
CREATE_STATIC_CTRL(UIFlowWndMSDC_StaticIcon_MassStorage,0,64,79,258,156)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndUSB)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndUSB)
DECLARE_CTRL_LIST(UIFlowWndUSB)
CREATE_CTRL(UIFlowWndUSB,UIFlowWndUSB,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
