//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYFILETYPE_H
#define UIMENUWNDPLAYFILETYPE_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayFileTypeCtrl;//Panel type 

extern VControl UIMenuWndPlayFileType_Static_TitleCtrl;//Static type 

extern VControl UIMenuWndPlayFileType_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayFileType_Menu_STRID_VIDEO_FLIE,
UIMenuWndPlayFileType_Menu_STRID_PHOTO_FILE,
UIMenuWndPlayFileType_Menu_MAX
}UIMenuWndPlayFileType_Menu_Setting;

extern VControl UIMenuWndPlayFileType_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndPlayFileType_TipsIconReturnCtrl;//Static type 

extern VControl UIMenuWndPlayFileType_TipsIconUpCtrl;//Static type 

extern VControl UIMenuWndPlayFileType_TipsIconDownCtrl;//Static type 

extern VControl UIMenuWndPlayFileType_TipsIconOKCtrl;//Static type 

//---------------------UIMenuWndPlayFileTypeCtrl User Export---------------------------

extern void UIMenuWndPlayFileType_SetFileType(UINT32 FileType);
extern UINT32 UIMenuWndPlayFileType_GetFileType(void);

#endif
