#ifndef UI_CFG_DEFAULT_H
#define UI_CFG_DEFAULT_H

#include "PrjInc.h"

// Photo
#define DEFAULT_PHOTO_CAPTURE           SELFTIMER_OFF
#define DEFAULT_PHOTO_SIZE              PHOTO_MAX_CAP_SIZE
#define DEFAULT_PHOTO_QUALITY           QUALITY_FINE
#define DEFAULT_PHOTO_COLOR             COLOR_EFFECT_STANDARD
#define DEFAULT_SCENE                   SCENE_AUTO
#define DEFAULT_EV                      EV_00
#define DEFAULT_EV2                     EV_00
#define DEFAULT_ISO                     ISO_AUTO
#define DEFAULT_WB                      WB_AUTO
#define DEFAULT_METERING                METERING_AIAE
#define DEFAULT_SHARPNESS               SHARPNESS_NORMAL
#define DEFAULT_SATURATION              SATURATION_NORMAL
#define DEFAULT_FD                      FD_OFF
#define DEFAULT_ANTISHAKING             ANTISHAKE_OFF
#if defined(_Gyro_None_)
#define DEFAULT_RSC                     RSC_OFF
#else
#define DEFAULT_RSC                     RSC_OFF
#endif
#define DEFAULT_WDR                     WDR_OFF
#define DEFAULT_QUICK_REVIEW            QUICK_REVIEW_0SEC
#define DEFAULT_DATE_STAMP              DATE_STAMP_DATE_TIME
#define DEFAULT_SELFTIMER               SELFTIMER_OFF
#define DEFAULT_FLASH_MODE              FLASH_OFF
#define DEFAULT_CONTINUE_SHOT           CONTINUE_SHOT_OFF
#define DEFAULT_SHDR                    SHDR_OFF
#define DEFAULT_DEFOG                   DEFOG_OFF
#if (PIP_VIEW_LR == ENABLE)
#define DEFAULT_DUAL_CAM                DUALCAM_LR_16_9
#else
#if (SENSOR_CAPS_COUNT == 1)
#define DEFAULT_DUAL_CAM                DUALCAM_BOTH
#endif
#if (SENSOR_CAPS_COUNT == 2)
#define DEFAULT_DUAL_CAM                DUALCAM_BOTH
#endif
#if (SENSOR_CAPS_COUNT == 3)
#define DEFAULT_DUAL_CAM                DUALCAM_BOTH
#endif
#if (SENSOR_CAPS_COUNT == 4)
#define DEFAULT_DUAL_CAM                DUALCAM_BOTH
#endif
#endif
// Movie
#if (SENSOR_CAPS_COUNT >= 2)

#if (_BOARD_DRAM_SIZE_ == 0x04000000)
#define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_DUAL_1920x1080P30_848x480P30
#else
#define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30 //MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30
#endif

#else

#if (defined(_NVT_ETHREARCAM_TX_))
#define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_CLONE_3840x2160P30_848x480P30//MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30
#elif (defined(_NVT_ETHREARCAM_RX_))
#if defined(_MODEL_580_CARDV_ETHCAM_RX_EVB_)
#define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_FRONT_2560x1440P30//////MOVIE_SIZE_FRONT_3840x2160P30
#else
#define DEFAULT_MOVIE_SIZE               MOVIE_SIZE_FRONT_2560x1440P30
#endif

#else
    #if defined(_sen_imx415_) || defined(_sen_imx317_)
    #define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_FRONT_3840x2160P30
    #elif (defined(_sen_imx335_) && (defined(_MODEL_580_SDV_C300_) || defined(_MODEL_580_SDV_C300_FAST_BT_)))
    #define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_FRONT_3840x2160P30
    #else
    #define DEFAULT_MOVIE_SIZE              MOVIE_SIZE_FRONT_3840x2160P30
    #endif
#endif

#endif

#define DEFAULT_MOVIE_SIZE_DUAL         MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30
#define DEFAULT_MOVIE_SIZE_SINGLE       MOVIE_SIZE_FRONT_3840x2160P30

#define DEFAULT_MOVIE_QUALITY           MOVIE_QUALITY_FINE
#define DEFAULT_MOVIE_COLOR             MOVIE_COLOR_NORMAL
#define DEFAULT_MOVIE_SELFTIMER         MOVIE_SELFTIMER_OFF
#define DEFAULT_MOVIE_EV                EV_00
#define DEFAULT_MOVIE_VIVILINK          VIVILINK_NONE
#define DEFAULT_MOVIE_LDWS              ADAS_LDWS_MID
#define DEFAULT_MOVIE_FCWS              ADAS_FCW_MID
#define DEFAULT_ADAS_LCAWS              ADAS_LCAWS_MID
#define DEFAULT_SNG            			ADAS_SNG_MID
#define DEFAULT_ADAS_VIRTUAL_BUMPER     ADAS_VIRTUAL_BUMPER_MID
#define DEFAULT_ADAS_PANEL     			ADAS_PANEL_OFF
#define DEFAULT_MOVIE_CYCLICREC         MOVIE_CYCLICREC_1MIN
#define DEFAULT_MOVIE_MOTION_DET        MOVIE_MOTIONDET_OFF
#define DEFAULT_MOVIE_AUDIO             MOVIE_AUDIO_ON
#if defined(COUNTRY_JP)
#define DEFAULT_MOVIE_VOICE             MOVIE_VOICE_ON
#define DEFAULT_ASR             		ASR_STANDARD
#else
#define DEFAULT_MOVIE_VOICE             MOVIE_VOICE_ON
#define DEFAULT_ASR             		ASR_STANDARD
#endif
#define DEFAULT_ASR_CONTENT            	ASR_TAKEPHOTO
#define DEFAULT_MOVIE_DATEIMPRINT       MOVIE_DATEIMPRINT_ON
#if (SHDR_FUNC==ENABLE)
#define DEFAULT_MOVIE_HDR               MOVIE_HDR_ON
#else
#define DEFAULT_MOVIE_HDR               MOVIE_HDR_OFF
#endif
#define DEFAULT_MOVIE_WDR               MOVIE_WDR_ON
#define DEFAULT_MOVIE_DEFOG               MOVIE_DEFOG_OFF
#define DEFAULT_MOVIE_REC_VOLUME        MOVIE_VOL_MAX
#define DEFAULT_MOVIE_REC_AUD           MOVIE_AUD_REC_ON
#define DEFAULT_MOVIE_CONTRAST          MOVIE_CONTRAST_MIDDLE
#define DEFAULT_MOVIE_AUDIOIN           MOVIE_AUDIOIN_ON
#define DEFAULT_MOVIE_AUDIOIN_SR        MOVIE_AUDIOIN_SR_8000
#define DEFAULT_MOVIE_FLIP_MIRROR       MOVIE_FLIP_MIRROR_NONE
#define DEFAULT_MOVIE_QUALITY_SET       MOVIE_QUALITY_SET_MAX
#define DEFAULT_MOVIE_SBS_MODE          MOVIE_SBS_LR
#if defined(_Gyro_None_)
#define DEFAULT_MOVIE_RSC               MOVIE_RSC_OFF //RSC not Ready
#else
#define DEFAULT_MOVIE_RSC               MOVIE_RSC_OFF
#endif

#define DEFAULT_MCTFINDEX               MOVIE_MCTF_ON

#define DEFAULT_IR_CUT                  MOVIE_IR_CUT_OFF

#define DEFAULT_MOVIE_TIMELAPSE_REC     MOVIE_TIMELAPSEREC_OFF
#define DEFAULT_MOVIE_PIM               MOVIE_PIM_ON

#define DEFAULT_MOVIE_PTZ                   MOVIE_PTZ_OFF
#define DEFAULT_MOVIE_URGENT_PROTECT_AUTO   MOVIE_URGENT_PROTECT_AUTO_ON
#define DEFAULT_MOVIE_URGENT_PROTECT_MANUAL MOVIE_URGENT_PROTECT_MANUAL_ON
#define DEFAULT_MOVIE_DDD                   MOVIE_DDD_OFF
#define DEFAULT_MOVIE_ADAS_CAL              MOVIE_ADAS_CAL_OFF
#define DEFAULT_MOVIE_CODEC                 MOVIE_CODEC_H264
#if(defined(_NVT_ETHREARCAM_RX_))
//#undef DEFAULT_MOVIE_CODEC
//#define DEFAULT_MOVIE_CODEC                 MOVIE_CODEC_H265 //for 671
#endif
#define DEFAULT_MOVIE_DECODE                MOVIE_DECODE_H264//MOVIE_DECODE_H264

#define DEFAULT_MOVIE_TIMERLAPS             MOVIE_TIMER_LAPS_OFF
#define DEFAULT_MOVIE_BITRATE               MOVIE_BITRATE_MED
#define DEFAULT_MOVIE_HDR_DET               MOVIE_HDR_DET_OFF

// Playback
#define DEFAULT_PROTECT                 PROTECT_ONE
#define DEFAULT_MOVIE_PLAY_VOLUME       MOVIE_AUDIO_VOL_9//(MOVIE_AUDIO_VOL_SETTING_MAX-1)

// System
#define DEFAULT_AUDIO_PLAY_VOLUME       AUDIO_VOL_MAX
#define DEFAULT_AUTO_POWER_OFF          POWER_ON
#define DEFAULT_LCD_OFF                 LCDOFF_1MIN
#define DEFAULT_BEEP                    BEEP_ON
#if defined(COUNTRY_JP)
#define DEFAULT_LANGUAGE                LANG_JP
#else
#define DEFAULT_LANGUAGE                LANG_EN
#endif

#define DEFAULT_FREQUENCY               FREQUENCY_60HZ
#define DEFAULT_TV_MODE                 TV_MODE_NTSC
#define DEFAULT_HDMI_MODE               VIDEOOUT2_AUTO
#define DEFAULT_DUALDISP                DUALDISP_OFF
#define DEFAULT_SENSOR_ROTATE           SEN_ROTATE_OFF
#if defined(COUNTRY_JP)
#define DEFAULT_DATE_FORMAT             DATE_FORMAT_DMY
#else
#define DEFAULT_DATE_FORMAT             DATE_FORMAT_MDY
#endif
#define DEFAULT_OPENING_LOGO            OPENING_LOGO_ON
#define DEFAULT_LCD_DISPLAY             DISPOUT_NORMAL
#define DEFAULT_LCD_BRIGHTNESS          LCDBRT_LVL_05
#define DEFAULT_MACRO                   MACRO_OFF
#define DEFAULT_USB_MODE                USB_MODE_MSDC
#if (GSENSOR_FUNCTION == ENABLE)
#define DEFAULT_GSENSOR                 GSENSOR_MED
#else
#define DEFAULT_GSENSOR                 GSENSOR_OFF
#endif
#define DEFAULT_EDGE                    MOVIE_EDGE_ON
#define DEFAULT_NR                      MOVIE_NR_LV_NORMAL
#define DEFAULT_LED                     LED_ON
#define DEFAULT_SYS_SOFT_RESET          SOFT_RESET_OFF
#define DEFAULT_GPS                     GPS_ON
#if defined(COUNTRY_JP)
#define DEFAULT_TIME_ZONE               GMT_P9
#else
#define DEFAULT_TIME_ZONE               GMT_0
#endif
#define DEFAULT_SPEED_UNIT              SPEED_UNIT_KPH
#define DEFAULT_GPS_STAMP               GPS_STAMP_BOTH
#define DEFAULT_FORMAT_WARNING          FORMAT_WARNING_60_DAY
#define DEFAULT_FORMAT_WARNING_DATE     20250101
#define DEFAULT_FIRSTPOWERON            FIRSTPOWERON_FALSE
#define DEFAULT_BOOT_DELAY              BOOT_DELAY_5SEC
#define DEFAULT_MODEL_STAMP             MODEL_STAMP_ON
#define DEFAULT_PARKING_MODE			PARKING_MODE_OFF
#define DEFAULT_PARKING_MODE_TIMELAPSE_REC  PARKING_MODE_TIMELAPSEREC_OFF
#define DEFAULT_PARKING_GSENSOR         PARKING_GSENSOR_MED
#define DEFAULT_PARKING_MOTION_DET      PARKING_MOTIONDET_MED
#define DEFAULT_VIDEO_FORMAT            VIDEO_FORMAT_MP4
#define DEFAULT_VOLUME                  VOLUME80
#define DEFAULT_IR_REAR_COLOR           IR_REAR_COLOR_BW
#define DEFAULT_REAR_SENSOR_MIRROR      REAR_SENSOR_MIRROR_OFF
#define DEFAULT_ADAS_CORDON             MOVIE_CORDON_HIGH
#define DEFAULT_PCW                     ADAS_PCW_MID
#define DEFAULT_RCW                     ADAS_RCW_MID
#define DEFAULT_SHUTDOWN_TIMER          SHUTDOWN_TIMER_48HOUR
#define DEFAULT_LAST_DATETIME           2025010100
#define DEFAULT_ENTER_PARKING_TIMER     ENTER_PARKING_TIMER_OFF
#define DEFAULT_REAR_MIRROR_DISPLAY     REAR_MIRROR_DISPLAY_OFF
#define DEFAULT_TIME_START              700//07:00
#define DEFAULT_TIME_STOP               1900//19:00
#define DEFAULT_PARKING_OFF_GPS  		PGPS_FALSE
#define DEFAULT_EDOG_OVERSPEED_ALARM    EDOG_OVERSPEED_ALARM_OFF//EDOG_OVERSPEED_ALARM_ON

//-----------------------------------------------------------------------------
// System
//-----------------------------------------------------------------------------
#define UIDFT_FS_STATUS                 FS_NOT_INIT
#define UIDFT_CARD_STATUS               CARD_REMOVED
#define UIDFT_BATTERY_LVL               0
#define UIDFT_AUDIO_VOLUME              AUDIO_VOL_7

// Wi-Fi
#if(WIFI_FUNC==ENABLE)
#define DEFAULT_MOVIE_WIFI_AUTO_RECORDING_OPTION    WIFI_AUTO_RECORDING_ON
#define DEFAULT_WIFI_MODE                           NET_AP_MODE
#if (WIFI_FINALCAM_APP_STYLE == ENABLE || UCTRL_APP_MOVIE_FEATURE_SETGET == ENABLE || YOUKU_SDK == ENABLE)
#define DEFAULT_MOVIE_WIFI_APP_PREVIEW_SIZE    WIFI_MOVIE_APP_PREVIEW_SIZE_VGA_16_9
#endif
#endif
#define DEFAULT_WIFI                    WIFI_ON_52G//WIFI_OFF
#define DEFAULT_WIFI_AUTO               WIFI_AUTO_OFF
#define DEFAULT_WIFI_BAND               WIFI_BAND_52G
#define DEFAULT_CLONE_REC               CLONE_REC_OFF

//fw_ui_reset
#define DEFAULT_FW_UI_RESET				FW_UI_RESET_ON

//HDR state change
#define DEFAULT_HDR_STATE_CHANGE		MOVIE_HDR_STATE_DISCHANGE
//HDR Before 
#define DEFAULT_HDR_CHANGE_BEFSIZE    	MOVIE_SIZE_FRONT_2560x1440P30

#define DEFAULT_ETHCAM_TX_IP_ADDR    	0 //0xc00a8c0

#endif
