//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndEdogMsgRes.c"
#include "UIFlowWndEdogMsg.h"
#include "UIWnd/UIFlow.h"
#include "PrjInc.h"
#include "PrjCfg.h"
#if defined(_GPS_EDOG_UNIQUE_SKY_)
#include "Edog/EDogGlobal.h"
#else
#include "DxGPS.h"
#endif
#define __MODULE__          UIFlowWndEodgMsg
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__			"*"      // *=All
#include <kwrap/debug.h>
//---------------------UIFlowWndEdogMsgCtrl Global Variables -----------------------------

//---------------------UIFlowWndEdogMsgCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndEdogMsgCtrl Public API  ----------------------------------

//---------------------UIFlowWndEdogMsgCtrl Private API  ---------------------------------
//---------------------UIFlowWndEdogMsgCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndEdogMsg)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_Panel)
CTRL_LIST_END

//----------------------UIFlowWndEdogMsgCtrl Event---------------------------
INT32 UIFlowWndEdogMsg_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndEdogMsg_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndEdogMsg_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndEdogMsg_OnEdogShowUI(VControl *, UINT32 , UINT32 *);
INT32 UIFlowWndEdogMsg_OnTimer(VControl *, UINT32 , UINT32 *);
INT32 UIFlowWndEdogMsg_OnCustom1(VControl *, UINT32 , UINT32 *);
extern INT32 UIFlowWndMovie_OnCustom1(VControl *, UINT32, UINT32 *);
extern INT32 UIFlowWndWiFiMovie_OnCustom1(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndEdogMsg)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndEdogMsg_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndEdogMsg_OnClose)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndEdogMsg_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndEdogMsg_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndEdogMsg_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndEdogMsg_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndEdogMsg_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_EDOG_ALARM,UIFlowWndEdogMsg_OnEdogShowUI)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndEdogMsg_OnTimer)
EVENT_ITEM(NVTEVT_KEY_CUSTOM1,UIFlowWndEdogMsg_OnCustom1)
EVENT_END

//varaible
static UINT32  gUIGPSSignalDetTimerID = NULL_TIMER;
#if 0
//static char  siSpeed[32] = {0};
//static char  siDistanc[32] = {0};
//static char  siRGCapture[] = "Red Green Capture";
//static char  siRadar[] = "Radar FQ";

//static char  siE[32] = {0};
//static char  siN[32] = {0};
//static char  siSpeedLimit[32] = {0};
#endif
static UINT16 Cur_GPS_Speed;//	
//extern BOOL g_bEdogShowUI;//
extern BOOL g_bManualCloseEdogWnd;
//BOOL g_bEdogMsgOff = FALSE;
static UINT32 AlarmTypePrev = 0xff, AlarmTypeNow = 0xff;
static UINT32 DisplayDigital_YellowBig(UINT8 Value)
{
    UINT32 ICON_ID = ICONID_NULL;

    switch(Value)
    {
    case 0:
        ICON_ID = ICON_EDOG_NUM_YELLOW_0;
        break;
    case 1:
        ICON_ID = ICON_EDOG_NUM_YELLOW_1;
        break;
    case 2:
        ICON_ID = ICON_EDOG_NUM_YELLOW_2;
        break;
    case 3:
        ICON_ID = ICON_EDOG_NUM_YELLOW_3;
        break;
    case 4:
        ICON_ID = ICON_EDOG_NUM_YELLOW_4;
        break;
    case 5:
        ICON_ID = ICON_EDOG_NUM_YELLOW_5;
        break;
    case 6:
        ICON_ID = ICON_EDOG_NUM_YELLOW_6;
        break;
    case 7:
        ICON_ID = ICON_EDOG_NUM_YELLOW_7;
        break;
    case 8:
        ICON_ID = ICON_EDOG_NUM_YELLOW_8;
        break;
    case 9:
        ICON_ID = ICON_EDOG_NUM_YELLOW_9;
        break;
    }
    return ICON_ID;
}

static UINT32 DisplayDigital_RedBig(UINT8 Value)
{
    UINT32 ICON_ID = ICONID_NULL;

    switch(Value)
    {
    case 0:
        ICON_ID = ICON_EDOG_NUM_RED_0;
        break;
    case 1:
        ICON_ID = ICON_EDOG_NUM_RED_1;
        break;
    case 2:
        ICON_ID = ICON_EDOG_NUM_RED_2;
        break;
    case 3:
        ICON_ID = ICON_EDOG_NUM_RED_3;
        break;
    case 4:
        ICON_ID = ICON_EDOG_NUM_RED_4;
        break;
    case 5:
        ICON_ID = ICON_EDOG_NUM_RED_5;
        break;
    case 6:
        ICON_ID = ICON_EDOG_NUM_RED_6;
        break;
    case 7:
        ICON_ID = ICON_EDOG_NUM_RED_7;
        break;
    case 8:
        ICON_ID = ICON_EDOG_NUM_RED_8;
        break;
    case 9:
        ICON_ID = ICON_EDOG_NUM_RED_9;
        break;

    }
    return ICON_ID;
}
static UINT32 DisplayDigital_YellowSmall(UINT8 Value)
{
    UINT32 ICON_ID = ICONID_NULL;

    switch(Value)
    {
    case 0:
        ICON_ID = ICON_OK;////harrison ds315
        break;
    case 1:
        ICON_ID = ICON_OK;
        break;
    case 2:
        ICON_ID = ICON_OK;
        break;
    case 3:
        ICON_ID = ICON_OK;
        break;
    case 4:
        ICON_ID = ICON_OK;
        break;
    case 5:
        ICON_ID = ICON_OK;
        break;
    case 6:
        ICON_ID = ICON_OK;
        break;
    case 7:
        ICON_ID = ICON_OK;
        break;
    case 8:
        ICON_ID = ICON_OK;
        break;
    case 9:
        ICON_ID = ICON_OK;
        break;
    }
    return ICON_ID;
}
void Display_SpeedLimit(UINT8 Value)
{
	UINT32 ICON_ID = ICONID_NULL;

    switch(Value)
    {
    case 0:
		ICON_ID = ICON_EDOG_00KM;
        break;
    case 1:
		ICON_ID = ICON_EDOG_00KM;
        break;
    case 2:
        ICON_ID = ICON_EDOG_20KM;
        break;
    case 3:
        ICON_ID = ICON_EDOG_30KM;
        break;
    case 4:
        ICON_ID = ICON_EDOG_40KM;
        break;
    case 5:
        ICON_ID = ICON_EDOG_50KM;
        break;
    case 6:
        ICON_ID = ICON_EDOG_60KM;
        break;
    case 7:
        ICON_ID = ICON_EDOG_70KM;
        break;
    case 8:
        ICON_ID = ICON_EDOG_80KM;
        break;
    case 9:
        ICON_ID = ICON_EDOG_90KM;
        break;
	case 10:
		ICON_ID = ICON_EDOG_100KM;
		break;
	case 11:
		ICON_ID = ICON_EDOG_110KM;
		break;
	case 12:
		ICON_ID = ICON_EDOG_120KM;
		break;
	default:
		ICON_ID = ICON_EDOG_00KM;
		break;

    }
	UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedLimitCtrl,STATIC_VALUE,ICON_ID);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedLimitCtrl,TRUE);
}
void Display_EdogType(UINT8 type)
{
	UINT32 ICON_ID = ICON_EDOG_CAPTUR;
	DBG_IND("^G========Display_EdogType====0x%x\r\n",type);
	if(type!=0xff)
	{
		if((type>=0x00)&&(type<=0xBf))
		{
			if((type>=0x00)&&(type<=0x0F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP1_TONE_CAMERA_OVERSPEED); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x10)&&(type<=0x1F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP2_TONE_CAMERA_FXIED); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x20)&&(type<=0x2F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP3_TONE_RADAR_SPEED_DETECT); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x30)&&(type<=0x3F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP8_TONE_CAMERA_BRIDGE_FIXED); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x40)&&(type<=0x4F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP25_TONE_SPEED_TEST_START); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x60)&&(type<=0x6F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP4_TONE_CAMERA_BRIDGE_UP); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x70)&&(type<=0x7F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP14_TONE_CAMERA_BRIDGE_DOWN); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x80)&&(type<=0x8F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP10_TONE_CAMERA_HIGHWAY_RADAR); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0x90)&&(type<=0x9F))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP9_TONE_CAMERA_HIGHWAY_FIXED); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
			else if((type>=0xA0)&&(type<=0xAF))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP13_TONE_DIANZIJIANKONG); 
				 ICON_ID = ICON_EDOG_TYPE_POLICE;
			}
			else if((type>=0xB0)&&(type<=0xBF))
			{
				 //UISound_Play(DEMOSOUND_SOUND_EP14_TONE_CAMERA_BRIDGE_DOWN); 
				 ICON_ID = ICON_EDOG_CAPTUR;
			}
		}
		else 
		{
			switch(type)
			{
				case 0xC2:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP6_TONE_HIGHWAY_ENTER);
					//UISound_Play(DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD);
					ICON_ID = ICON_EDOG_TYPE_ENTRY;
					break;
				case 0xC3:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP39_TONE_HIGHWAY_EXIT);
					//UISound_Play(DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD);
					ICON_ID = ICON_EDOG_TYPE_EXIT;
					break;
				case 0xC4:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP35_TONE_END_TESTSPEED_AREA);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_REDGREEN;
					break;
				case 0xC5:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP16_TONE_TIELUKOU);
					//UISound_Play(DEMOSOUND_SOUND_EP36_TONE_PLEASE_SLOW_DOWN);
					ICON_ID = ICON_EDOG_TYPE_TRAIN_WAY;
					break;
				case 0xC7:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP11_TONE_BIG_BEND);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_DAWANDAO;
					break;
				case 0xC8:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP31_TONE_FORBID_TURNLEFT);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_NO_LEFT_TURN;
					break;
				case 0xD2:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP18_TONE_DANGE_ROAD);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_ACCIDENT;
					break;
				case 0xD3:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP29_TONE_DOWNHILL);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_DOWN_HILL;
					break;
				case 0xD4:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP30_TONE_JIAOLIUDAO);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_JIAOLIUDAO;
					break;
				case 0xD6:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP33_TONE_ON_LINE_PHOTO);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_REDGREEN;
					break;
				case 0xD7:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP26_TONE_SCHOOL_AREA);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_SCHOOL;
					break;
				case 0xD9:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP27_TONE_CHECK_TRAFFIC_LAW);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_POLICE;
					break;
				case 0xDA:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP37_TONE_DRINK_DRIVE);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_NO_DRINKING;
					break;
				case 0xDB:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP23_TONE_HOLE_ENTER);
					//UISound_Play(DEMOSOUND_SOUND_EP20_TONE_TURNON_LIGHT);
					ICON_ID = ICON_EDOG_TYPE_TUNNEL;
					break;
				case 0xE1:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP38_TONE_GAS_STATION);
					//UISound_Play(DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD);
					ICON_ID = ICON_EDOG_TYPE_OIL_STATION;
					break;
				case 0xE2:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP7_TONE_OIL_STATION);
					//UISound_Play(DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD);
					ICON_ID = ICON_EDOG_TYPE_OIL_STATION;
					break;
				case 0xE3:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP34_TONE_TOLL_STATION);
					//UISound_Play(DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD);
					ICON_ID = ICON_EDOG_TYPE_POLICE;
					break;
				case 0xE4:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP22_TONE_REST_STATION);
					//UISound_Play(DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD);
					ICON_ID = ICON_EDOG_TYPE_SERVICE_CENTER;
					break;
				case 0xE5:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP28_TONE_FORBID_PARKING);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_NO_PARKING;
					break;
				case 0xE7:
					//UISound_Play(DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1);	
					//UISound_Play(DEMOSOUND_SOUND_EP15_TONE_SINGLE_ROAD);
					//UISound_Play(DEMOSOUND_SOUND_EP0_TONE_WRONGDIRECT);
					ICON_ID = ICON_EDOG_TYPE_STRAIGHT_LINE;
					break;
				case 0xE8:
					//UISound_Play(DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2);	
					//UISound_Play(DEMOSOUND_SOUND_EP17_TONE_BUS_ROAD);
					//UISound_Play(DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE);
					ICON_ID = ICON_EDOG_TYPE_BUS;
					break;
				default:
					break;
			}
		}
	}
	UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_TypeCtrl,STATIC_VALUE,ICON_ID);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_TypeCtrl,TRUE);
}
void UIFlowWndEdogMsg_UpdateUI(void)
{
    UINT16 Speed0=0,Speed1=0,Speed2=0,Distanc0=0,Distanc1=0,Distanc2=0,Distanc3=0;
	UINT32 edogDistance = 0;
	edogDistance = (EdogInfo_SentenceA.EDOG_Distance2<<8)|EdogInfo_SentenceA.EDOG_Distance1;

	Speed2 = (Cur_GPS_Speed/100)%10;
	Speed1 = (Cur_GPS_Speed/10)%10;
	Speed0 = Cur_GPS_Speed%10;

	Distanc3 = (edogDistance/1000)%10;
	Distanc2 = (edogDistance/100)%10;
	Distanc1 = (edogDistance/10)%10;
	Distanc0 = edogDistance%10;

	DBG_IND("Cur_GPS_Speed = %d %d%d%d EdogInfo_SentenceA.EDOG_Distance=%d %d%d%d\r\n",Cur_GPS_Speed,Speed2,Speed1,Speed0,edogDistance,Distanc2,Distanc1,Distanc0);
	
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl,FALSE);
    
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number0Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl,FALSE);
	UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,FALSE);

    UxCtrl_SetShow(&UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KMCtrl,TRUE);
    //UxCtrl_SetShow(&UIFlowWndEdogMsg_StatusIcn_DistanceCtrl,TRUE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StatusIcn_Distance_MCtrl,TRUE);
	
	if(Cur_GPS_Speed > EdogInfo_SentenceA.EDOG_SpeedLimit*10)
    {
    	if((Cur_GPS_Speed>=0)&&(Cur_GPS_Speed<10))	
		{
        	UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,STATIC_VALUE,DisplayDigital_RedBig(Speed0));
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,TRUE);
		}
		else if ((Cur_GPS_Speed>=10)&&(Cur_GPS_Speed<=99))
		{
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl,STATIC_VALUE,DisplayDigital_RedBig(Speed1));	
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl,STATIC_VALUE,DisplayDigital_RedBig(Speed0));
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl,TRUE);
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl,TRUE);
		}
		else if ((Cur_GPS_Speed>=100)&&(Cur_GPS_Speed<=999))
		{
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,STATIC_VALUE,DisplayDigital_RedBig(Speed1));
        	UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,STATIC_VALUE,DisplayDigital_RedBig(Speed0));
        	UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,STATIC_VALUE,DisplayDigital_RedBig(Speed2));
        	UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,TRUE);
        	UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,TRUE);
        	UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,TRUE);
		}
		#if 0
        UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed0Ctrl,STATIC_VALUE,UIFlowWndEdogMsg_DisplayUIDigitalOverSpeed(Speed0));
        UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed1Ctrl,STATIC_VALUE,UIFlowWndEdogMsg_DisplayUIDigitalOverSpeed(Speed1));
        UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed2Ctrl,STATIC_VALUE,UIFlowWndEdogMsg_DisplayUIDigitalOverSpeed(Speed2));
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed0Ctrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed1Ctrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed2Ctrl,TRUE);
       	if((Speed2 == 0)&&(Speed1 == 0))
        {
            UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed1Ctrl,FALSE);
            UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed2Ctrl,FALSE);
        }
        else if(Speed2 == 0)
        {
            UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_NumberOverSpeed2Ctrl,FALSE);
        }
		#endif
	}
	else
	{
		if((Cur_GPS_Speed>=0)&&(Cur_GPS_Speed<10))	
		{
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,STATIC_VALUE,DisplayDigital_YellowBig(Speed0));
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,TRUE);
		}
		else if ((Cur_GPS_Speed>=10)&&(Cur_GPS_Speed<=99))
		{
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl,STATIC_VALUE,DisplayDigital_YellowBig(Speed1));	
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl,STATIC_VALUE,DisplayDigital_YellowBig(Speed0));
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl,TRUE);
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl,TRUE);
		}
		else if ((Cur_GPS_Speed>=100)&&(Cur_GPS_Speed<=999))
		{
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,STATIC_VALUE,DisplayDigital_YellowBig(Speed1));
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,STATIC_VALUE,DisplayDigital_YellowBig(Speed0));
			UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,STATIC_VALUE,DisplayDigital_YellowBig(Speed2));
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,TRUE);
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,TRUE);
			UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,TRUE);

		}
		#if 0
        UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,STATIC_VALUE,UIFlowWndEdogMsg_DisplayUIDigital(Speed0));
        UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,STATIC_VALUE,UIFlowWndEdogMsg_DisplayUIDigital(Speed1));
        UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,STATIC_VALUE,UIFlowWndEdogMsg_DisplayUIDigital(Speed2));
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,TRUE);
        
        if((Speed2 == 0)&&(Speed1 == 0))
        {
            UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,FALSE);
            UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,FALSE);
        }
        else if(Speed2 == 0)
        {
            UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,FALSE);
        }
		#endif
	}

    UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_Distance_Number0Ctrl,STATIC_VALUE,DisplayDigital_YellowSmall(Distanc0));
    UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl,STATIC_VALUE,DisplayDigital_YellowSmall(Distanc1));
    UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl,STATIC_VALUE,DisplayDigital_YellowSmall(Distanc2));
    UxStatic_SetData(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,STATIC_VALUE,DisplayDigital_YellowSmall(Distanc3));

    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number0Ctrl,TRUE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl,TRUE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl,TRUE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,TRUE);
	if((Distanc3==0)&&(Distanc2==0)&&(Distanc1==0))
	{
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl,FALSE);
		UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,FALSE);
    }
    else if((Distanc3==0)&&(Distanc2==0))
    {
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,FALSE);
    }
    else if(Distanc3==0)
    {
        UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,FALSE);
    }
    //UxCtrl_SetShow(&UIFlowWndEdogMsg_ModeCtrl,TRUE);
}
void UIFlowWndEdogMsg_HideNumUI(void)
{
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl,FALSE);
    
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number0Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl,FALSE);
	UxCtrl_SetShow(&UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl,FALSE);
	
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KMCtrl,FALSE);
    //UxCtrl_SetShow(&UIFlowWndEdogMsg_StatusIcn_DistanceCtrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndEdogMsg_StatusIcn_Distance_MCtrl,FALSE);
}

void UIFlowWndEdogMsg_DisplayUIMsg(void)
{
	#if 0
	//float ftmpval = 0;
	
	//clear buffer
	memset(siDistanc, 0, 32);
	memset(siSpeedLimit, 0, 32);
	
	//distance or radar FQ show
	Cur_GPS_Speed = (UINT16)GPSRec_GetGPS_Speed();
	
	//speed limit show
    if( EdogInfo_Alarm.Alarm_LimitSpeed == 0)
    {
        //memset(siSpeed, 0, 32);	//unshow
        sprintf(siSpeedLimit,"%d",(UINT16)Cur_GPS_Speed);//EdogInfo_Alarm.Alarm_LimitSpeed
    }
    else
    {
        sprintf(siSpeedLimit,"%d",(UINT16)Cur_GPS_Speed);
    }
    
    if( EdogInfo_Alarm.Alarm_Distance== 0)
    {
        Ux_CloseWindow(&UIFlowWndEdogMsgCtrl,0);
    }
    else
    {
        sprintf(siDistanc,"%d",EdogInfo_Alarm.Alarm_Distance);
    }
    //UIFlowWndEdogMsg_UpdateUI();
    #endif
	
	AlarmTypeNow = EdogInfo_SentenceA.EDOG_AlarmType;
	if(AlarmTypeNow==0xff) //close window
	{
	    //g_bEdogShowUI=FALSE;
    	Ux_CloseWindow(&UIFlowWndEdogMsgCtrl,0);
    	UISound_Play(DEMOSOUND_SOUND_EP43_TONE_DONDDD);
	}
	else 
	{
		if(AlarmTypeNow != AlarmTypePrev)
		{
			FlowMovie_WakeUpLCDBacklight();
			//Show Edog Alarm UI & Play Voice
			if(((AlarmTypeNow>=0x40)&&(AlarmTypeNow<=0x4F))||(AlarmTypeNow==0xC4))
			{
				Ux_CloseWindow(&UIFlowWndEdogMsgCtrl,0);
				Ux_Redraw();
    			UISound_Play(DEMOSOUND_SOUND_EP43_TONE_DONDDD);
				Ux_OpenWindow(&UIFlowWndEdogMsg_UniqueSkyCtrl,1,AlarmTypeNow);
				FlowMovie_EdogAlarmVoice(AlarmTypeNow);
			}
			else
			{
				FlowMovie_EdogAlarmVoice(AlarmTypeNow);
				Cur_GPS_Speed = (UINT16)GPSRec_GetGPS_Speed();
				Display_SpeedLimit(EdogInfo_SentenceA.EDOG_SpeedLimit);
				UIFlowWndEdogMsg_UpdateUI();
				Display_EdogType(AlarmTypeNow);
			}
		}
		else
		{
			Cur_GPS_Speed = (UINT16)GPSRec_GetGPS_Speed();
			Display_SpeedLimit(EdogInfo_SentenceA.EDOG_SpeedLimit);
			UIFlowWndEdogMsg_UpdateUI();
			Display_EdogType(AlarmTypeNow);
		}
		#if 0
        switch (EdogInfo_SentenceA.EDOG_AlarmType) {
        case 0x00:
            UIFlowWndEdogMsg_UpdateUI();
            break;
        case 0x01:
        case 0x02:
        case 0x04:
        case 0x05:
        case 0x08:
        case 0x0A:
        case 0x0B:
            UIFlowWndEdogMsg_UpdateUI();
            break;
		case 0x0C:
            UIFlowWndEdogMsg_UpdateUI();
			break;
        case 0x06:
            UIFlowWndEdogMsg_UpdateUI();
            break;

        case 0xE8:
            UIFlowWndEdogMsg_HideNumUI();
            break;

        default:
            UIFlowWndEdogMsg_HideNumUI();
            break;
        }
		#endif
	}
	AlarmTypePrev = AlarmTypeNow;
    Ux_Redraw();
}


INT32 UIFlowWndEdogMsg_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT8 type  = EdogInfo_SentenceA.EDOG_AlarmType;
	if (paramNum > 0){
		AlarmTypePrev = paramArray[0];
		AlarmTypeNow =  paramArray[0];
	}else{
		AlarmTypePrev = type;
		AlarmTypePrev = type;
	}
    DBG_IND("^G UIFlowWndEdogMsg_OnOpen---AlarmTypePrev=%d---AlarmTypeNow=%d paramNum=%d\r\n",AlarmTypePrev,AlarmTypeNow,paramNum);

    UIFlowWndEdogMsg_DisplayUIMsg();

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndEdogMsg_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_IND("^G UIFlowWndEdogMsg_OnClose---------- \r\n");
    if(gUIGPSSignalDetTimerID != NULL_TIMER)
    {
        GxTimer_StopTimer(&gUIGPSSignalDetTimerID);
    }

    //g_bEdogMsgOff = TRUE;
	Ux_FlushEventByRange(NVTEVT_KEY_EDOG_ALARM, NVTEVT_KEY_EDOG_ALARM);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndEdogMsg_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;
    uiKeyAct = paramArray[0];

    switch (uiKeyAct)
    {
    case NVTEVT_KEY_RELEASE:
        g_bManualCloseEdogWnd = TRUE;
        Ux_CloseWindow(&UIFlowWndEdogMsgCtrl,0);	
        break;
    }	
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndEdogMsg_OnEdogShowUI(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//DBG_IND("***********UIFlowWndEdogMsg_OnEdogShowUI\r\n");
	UIFlowWndEdogMsg_DisplayUIMsg();

	return NVTEVT_CONSUME;
}

INT32 UIFlowWndEdogMsg_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;    
	uiEvent = paramNum ? paramArray[0] : 0;

	switch(uiEvent)
	{
    case NVTEVT_1SEC_TIMER:
        //DBG_IND("UIFlowWndEdogMsg_OnTimer -> NVTEVT_1SEC_TIMER \r\n");
        UIFlowWndEdogMsg_DisplayUIMsg();
        break;
    }
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndEdogMsg_OnCustom1(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_WIFI) {
        return UIFlowWndWiFiMovie_OnCustom1(pCtrl, paramNum, paramArray);
    } else {
        return UIFlowWndMovie_OnCustom1(pCtrl, paramNum, paramArray);
    }
}


//---------------------UIFlowWndEdogMsg_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndEdogMsg_Panel)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcon_BG_Single)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_SpeedLimit)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_Type)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_Distance_Number0)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_Distance_Number1)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_Distance_Number2)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StaticIcn_Distance_Number3)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StatusIcn_Distance_M)
CTRL_LIST_ITEM(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single)
CTRL_LIST_END

//----------------------UIFlowWndEdogMsg_PanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_Panel)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcon_BG_SingleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcon_BG_Single)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_SpeedLimitCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedLimit)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_TypeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_Type)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_Distance_Number0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number0)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number1)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number2)
EVENT_END

//----------------------UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number3)
EVENT_END

//----------------------UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KMCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM)
EVENT_END

//----------------------UIFlowWndEdogMsg_StatusIcn_Distance_MCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StatusIcn_Distance_M)
EVENT_END

//----------------------UIFlowWndEdogMsg_StatusIcon_Distance_Title_SingleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single)
EVENT_END

