//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDEDOGMSGRES_H
#define UIFLOWWNDEDOGMSGRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
//#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,619,239,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,619,239)

SHOW_ITEM_RECT(CMD_Rectangle,Rect4,0,1,619,239,16,2,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin2)
SHOW_MAP_BODY(Rect4)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin2,0,0,619,239)

SHOW_MAP_BEGIN(Skin6)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin6,0,0,619,239)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon7, 0, 0, 619,239, ICONID_NULL,83886080,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Normal5)
SHOW_MAP_BODY(Skin6)
SHOW_MAP_BODY(Icon7)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal5,0,0,619,239)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcon_BG_Single)
SHOW_MAP_BODY(Normal5)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcon_BG_Single)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcon_BG_Single,ICON_EDOG_WARN_BG_SINGLE)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcon_BG_Single,0,0,0,619,239)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin10)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin10,0,0,78,78)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon11, 0, 0, 78,78, ICONID_NULL,83886080,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Normal9)
SHOW_MAP_BODY(Skin10)
SHOW_MAP_BODY(Icon11)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal9,5,14,83,92)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedLimit)
SHOW_MAP_BODY(Normal9)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_SpeedLimit)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_SpeedLimit,ICON_EDOG_20KM)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_SpeedLimit,0,5,14,83,92)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin14)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin14,0,0,59,60)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon15, 0, 0, 59,60, ICONID_NULL,83886080,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Normal13)
SHOW_MAP_BODY(Skin14)
SHOW_MAP_BODY(Icon15)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal13,245,87,304,147)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_Type)
SHOW_MAP_BODY(Normal13)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_Type)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_Type,ICON_EDOG_CAPTUR)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_Type,0,245,87,304,147)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin18)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin18,0,0,40,64)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon19, 0, 0, 40,64, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal17)
SHOW_MAP_BODY(Skin18)
SHOW_MAP_BODY(Icon19)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal17,98,97,138,161)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0)
SHOW_MAP_BODY(Normal17)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0,ICON_EDOG_NUM_YELLOW_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0,0,98,97,138,161)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin22Rect,0,0,40,64,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin22)
SHOW_MAP_BODY(Skin22Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin22,0,0,40,64)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon23, 0, 0, 40,64, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal21)
SHOW_MAP_BODY(Skin22)
SHOW_MAP_BODY(Icon23)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal21,139,97,179,161)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1)
SHOW_MAP_BODY(Normal21)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1,ICON_EDOG_NUM_YELLOW_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1,0,139,97,179,161)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin26Rect,0,0,40,64,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin26)
SHOW_MAP_BODY(Skin26Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin26,0,0,40,64)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon27, 0, 0, 40,64, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal25)
SHOW_MAP_BODY(Skin26)
SHOW_MAP_BODY(Icon27)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal25,57,97,97,161)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2)
SHOW_MAP_BODY(Normal25)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2,ICON_EDOG_NUM_YELLOW_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2,0,57,97,97,161)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin30)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin30,0,0,40,64)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon31, 0, 0, 40,64, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal29)
SHOW_MAP_BODY(Skin30)
SHOW_MAP_BODY(Icon31)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal29,77,97,117,161)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3)
SHOW_MAP_BODY(Normal29)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3,ICON_EDOG_NUM_RED_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3,0,77,97,117,161)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin34)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin34,0,0,40,64)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon35, 0, 0, 40,64, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal33)
SHOW_MAP_BODY(Skin34)
SHOW_MAP_BODY(Icon35)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal33,119,97,159,161)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4)
SHOW_MAP_BODY(Normal33)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4,ICON_EDOG_NUM_RED_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4,0,119,97,159,161)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin38Rect,0,0,26,39,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin38)
SHOW_MAP_BODY(Skin38Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin38,0,0,26,39)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon39, 0, 0, 26,39, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal37)
SHOW_MAP_BODY(Skin38)
SHOW_MAP_BODY(Icon39)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal37,487,105,513,144)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number0)
SHOW_MAP_BODY(Normal37)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_Distance_Number0)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_Distance_Number0,ICON_EDOG_NUM_RED_SMALL_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_Distance_Number0,0,487,105,513,144)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin42Rect,0,0,26,39,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin42)
SHOW_MAP_BODY(Skin42Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin42,0,0,26,39)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon43, 0, 0, 26,39, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal41)
SHOW_MAP_BODY(Skin42)
SHOW_MAP_BODY(Icon43)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal41,461,105,487,144)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number1)
SHOW_MAP_BODY(Normal41)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_Distance_Number1)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_Distance_Number1,ICON_EDOG_NUM_RED_SMALL_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_Distance_Number1,0,461,105,487,144)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin46Rect,0,0,26,39,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin46)
SHOW_MAP_BODY(Skin46Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin46,0,0,26,39)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon47, 0, 0, 26,39, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal45)
SHOW_MAP_BODY(Skin46)
SHOW_MAP_BODY(Icon47)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal45,435,105,461,144)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number2)
SHOW_MAP_BODY(Normal45)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_Distance_Number2)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_Distance_Number2,ICON_EDOG_NUM_RED_SMALL_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_Distance_Number2,0,435,105,461,144)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin50Rect,0,0,26,39,0,0,208,208,0,0,0)
SHOW_MAP_BEGIN(Skin50)
SHOW_MAP_BODY(Skin50Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin50,0,0,26,39)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon51, 0, 0, 26,39, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal49)
SHOW_MAP_BODY(Skin50)
SHOW_MAP_BODY(Icon51)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal49,409,105,435,144)

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StaticIcn_Distance_Number3)
SHOW_MAP_BODY(Normal49)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StaticIcn_Distance_Number3)
CREATE_STATIC_DATA(UIFlowWndEdogMsg_StaticIcn_Distance_Number3,ICON_EDOG_NUM_RED_SMALL_8)
CREATE_STATIC_CTRL(UIFlowWndEdogMsg_StaticIcn_Distance_Number3,0,409,105,435,144)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin54)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin54,0,0,49,24)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon55, 0, 0, 49,24, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal53)
SHOW_MAP_BODY(Skin54)
SHOW_MAP_BODY(Icon55)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal53,97,171,146,195)

CREATE_STATE_ITEM_DATA(ICON_EDOG_KMH_BIG56,STRID_NULL,ICON_EDOG_KMH_BIG,NULL) 
SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM)
SHOW_MAP_BODY(Normal53)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM)
STATE_LIST_BEGIN(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM)
STATE_LIST_ITEM(ICON_EDOG_KMH_BIG56)
STATE_LIST_END

CREATE_STATE_DATA(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM,0)
CREATE_STATE_CTRL(UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM,0,97,171,146,195)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin58)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin58,0,0,49,24)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon59, 0, 0, 49,24, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal57)
SHOW_MAP_BODY(Skin58)
SHOW_MAP_BODY(Icon59)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal57,521,112,570,136)

CREATE_STATE_ITEM_DATA(ICON_EDOG_M60,STRID_NULL,ICON_EDOG_M,NULL) 
SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StatusIcn_Distance_M)
SHOW_MAP_BODY(Normal57)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StatusIcn_Distance_M)
STATE_LIST_BEGIN(UIFlowWndEdogMsg_StatusIcn_Distance_M)
STATE_LIST_ITEM(ICON_EDOG_M60)
STATE_LIST_END

CREATE_STATE_DATA(UIFlowWndEdogMsg_StatusIcn_Distance_M,0)
CREATE_STATE_CTRL(UIFlowWndEdogMsg_StatusIcn_Distance_M,0,521,112,570,136)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(Skin62)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin62,0,0,57,26)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon63, 0, 0, 57,26, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal61)
SHOW_MAP_BODY(Skin62)
SHOW_MAP_BODY(Icon63)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal61,341,112,398,138)

CREATE_STATE_ITEM_DATA(ICON_EDOG_DIS64,STRID_NULL,ICON_EDOG_DIS,NULL) 
SHOW_MAP_BEGIN(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single)
SHOW_MAP_BODY(Normal61)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single)
STATE_LIST_BEGIN(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single)
STATE_LIST_ITEM(ICON_EDOG_DIS64)
STATE_LIST_END

CREATE_STATE_DATA(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single,0)
CREATE_STATE_CTRL(UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single,0,341,112,398,138)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndEdogMsg_Panel)
SHOW_MAP_BODY(Skin2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg_Panel)
DECLARE_CTRL_LIST(UIFlowWndEdogMsg_Panel)
CREATE_CTRL(UIFlowWndEdogMsg_Panel,UIFlowWndEdogMsg_Panel,CTRL_WND,NULL,0 ,0,0,619,239)
SHOW_MAP_BEGIN(UIFlowWndEdogMsg)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndEdogMsg)
DECLARE_CTRL_LIST(UIFlowWndEdogMsg)
CREATE_CTRL(UIFlowWndEdogMsg,UIFlowWndEdogMsg,CTRL_WND,NULL,0 ,0,0,619,239)
#endif
