//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDEDOGMSG_UIQUESKY_H
#define UIFLOWWNDEDOGMSG_UIQUESKY_H

#include "UIFramework.h"

extern VControl UIFlowWndEdogMsg_UniqueSkyCtrl;//Panel type 

extern VControl UIFlowWndEdogMsg_UniqueSky_PanelCtrl;//Panel type 

extern VControl UIFlowWndEdogMsg_StaticIcon_BGCtrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedLimitCtrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedCurrent_Num0Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedCurrent_Num1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedCurrent_Num2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedCurrent_Num3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedCurrent_Num4Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StatusIcon_SpeedUnitCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_SpeedUnit_ICON_EDOG_KMH_BIG,
UIFlowWndEdogMsg_StatusIcon_SpeedUnit_MAX
}UIFlowWndEdogMsg_StatusIcon_SpeedUnit_Setting;

extern VControl UIFlowWndEdogMsg_StaticIcon_BG1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_BG2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_BG3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StatusIcon_Speed_TitleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_Speed_Title_ICON_EDOG_AVERAGE_SPEED,
UIFlowWndEdogMsg_StatusIcon_Speed_Title_MAX
}UIFlowWndEdogMsg_StatusIcon_Speed_Title_Setting;

extern VControl UIFlowWndEdogMsg_StatusIcon_Distance_TitleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_Distance_Title_ICON_EDOG_DISTANCE,
UIFlowWndEdogMsg_StatusIcon_Distance_Title_MAX
}UIFlowWndEdogMsg_StatusIcon_Distance_Title_Setting;

extern VControl UIFlowWndEdogMsg_StatusIcon_Time_TitleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_Time_Title_ICON_EDOG_TIME,
UIFlowWndEdogMsg_StatusIcon_Time_Title_MAX
}UIFlowWndEdogMsg_StatusIcon_Time_Title_Setting;

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedAve_Num0Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedAve_Num1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedAve_Num2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Time_Num0Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Time_Num1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Time_Num2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num0Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StatusIcon_SpeedUnit_TitleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_SpeedUnit_Title_ICON_EDOG_KMH_SMALL,
UIFlowWndEdogMsg_StatusIcon_SpeedUnit_Title_MAX
}UIFlowWndEdogMsg_StatusIcon_SpeedUnit_Title_Setting;

extern VControl UIFlowWndEdogMsg_StatusIcon_DistanceUnit_TitleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_DistanceUnit_Title_ICON_EDOG_M_SMALL,
UIFlowWndEdogMsg_StatusIcon_DistanceUnit_Title_ICON_EDOG_KM_SMALL,
UIFlowWndEdogMsg_StatusIcon_DistanceUnit_Title_MAX
}UIFlowWndEdogMsg_StatusIcon_DistanceUnit_Title_Setting;

extern VControl UIFlowWndEdogMsg_StatusIcon_TimeUnit_TitleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_TimeUnit_Title_ICON_EDOG_MIN_SMALL,
UIFlowWndEdogMsg_StatusIcon_TimeUnit_Title_ICON_EDOG_SEC_SMALL,
UIFlowWndEdogMsg_StatusIcon_TimeUnit_Title_MAX
}UIFlowWndEdogMsg_StatusIcon_TimeUnit_Title_Setting;

extern VControl UIFlowWndEdogMsg_StaticIcon_Time_Num3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Time_Num4Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedAve_Num3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_SpeedAve_Num4Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num4Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num5Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcon_Distance_Num6Ctrl;//Static type 

//---------------------UIFlowWndEdogMsg_UniqueSkyCtrl User Export---------------------------
#endif
