//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDEDOGMSG_H
#define UIFLOWWNDEDOGMSG_H

#include "UIFramework.h"

extern VControl UIFlowWndEdogMsgCtrl;//Panel type 

extern VControl UIFlowWndEdogMsg_PanelCtrl;//Panel type 

extern VControl UIFlowWndEdogMsg_StaticIcon_BG_SingleCtrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_SpeedLimitCtrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_TypeCtrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number0Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_SpeedCurrent_Number4Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_Distance_Number0Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_Distance_Number1Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_Distance_Number2Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StaticIcn_Distance_Number3Ctrl;//Static type 

extern VControl UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KMCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM_ICON_EDOG_KMH_BIG,
UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM_MAX
}UIFlowWndEdogMsg_StatusIcn_SpeedLimit_KM_Setting;

extern VControl UIFlowWndEdogMsg_StatusIcn_Distance_MCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcn_Distance_M_ICON_EDOG_M,
UIFlowWndEdogMsg_StatusIcn_Distance_M_MAX
}UIFlowWndEdogMsg_StatusIcn_Distance_M_Setting;

extern VControl UIFlowWndEdogMsg_StatusIcon_Distance_Title_SingleCtrl;//Status type 

typedef enum
{
UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single_ICON_EDOG_DIS,
UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single_MAX
}UIFlowWndEdogMsg_StatusIcon_Distance_Title_Single_Setting;

//---------------------UIFlowWndEdogMsgCtrl User Export---------------------------
#endif
