//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIWnd/UIFlow.h"
#include "UIWnd/SPORTCAM/UIFlow/UIFlowPlay/UIFlowWndPlayRes.c"
#include "PlaybackTsk.h"
#include "ImageApp/ImageApp_Play.h"
#include "ImageApp/ImageApp_MoviePlay.h"
#include "UIApp/Play/UIAppMoviePlay.h"
#include "FileDB.h"
#include "GxVideoFile.h"
#include "UIApp/Play/UIAppPlay.h" 

//#include "SMediaPlayAPI.h"

//#include "../../audio_common/include/Audio.h"
//#include "Audio.h"
#include "UIApp/AppDisp_PBView.h"

#define FLOW_MOV_PLAY_REAET		DISABLE
#if (FLOW_MOV_PLAY_REAET == ENABLE)
#include "kwrap/util.h"
#endif
#include "UIApp/Play/UIPlayComm.h"

#define THIS_DBGLVL         2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
///////////////////////////////////////////////////////////////////////////////
#if _TODO
#define __MODULE__          UIFlowWndPlay
#define __DBGLVL__          ((THIS_DBGLVL>=PRJ_DBG_LVL)?THIS_DBGLVL:PRJ_DBG_LVL)
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include <kwrap/debug.h>
#endif
///////////////////////////////////////////////////////////////////////////////

#if 1//_TODO
#define PLAY_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
#define PLAY_KEY_RELEASE_MASK      (FLGKEY_KEY_MASK_DEFAULT)//FLGKEY_KEY_MASK_NULL//(FLGKEY_UP | FLGKEY_DOWN | FLGKEY_LEFT | FLGKEY_RIGHT)
#define PLAY_KEY_CONTINUE_MASK     FLGKEY_KEY_CONT_MASK_DEFAULT

#define FULL_FILE_PATH_LEN      64

#define BROWSER_VIEW			ENABLE

BOOL           g_bUIFlowWndPlayNoImgWndOpened   = FALSE;
UINT32         g_uiUIFlowWndPlayCurrentVolume   = 5;//AUDIO_VOL_5;
UINT32         g_uiUIFlowWndPlayCurrenSpeed     = SMEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
MOVIEPLAY_FILEPLAY_INFO gMovie_Play_Info        = {0};
FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;

typedef enum {
	UIFLOW_PLAY_DISP_ID_1 = 0,
	UIFLOW_PLAY_DISP_ID_2,
	UIFLOW_PLAY_DISP_ID_MAX,
	ENUM_DUMMY4WORD(UIFLOW_PLAY_DISP_ID)
} UIFLOW_PLAY_DISP_ID;

MOVIEPLAY_DISP_INFO  gUIFlowWndPlayDispConfig[4] = {
    //enable  disp_id       w     h      ratio     rotate dir
	{TRUE, MOVIEPLAY_DISP_ID_1, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_2, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_3, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_4, 960,  240  ,  4 ,  3  ,  0},
};


//---------------------UIFlowWndPlayCtrl Function ---------------------------
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel);
void UIFlowWndPlay_ConfigDispInfo(void);
#else
#define PLAY_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
#define PLAY_KEY_RELEASE_MASK      FLGKEY_KEY_MASK_NULL//(FLGKEY_UP | FLGKEY_DOWN | FLGKEY_LEFT | FLGKEY_RIGHT)
#define PLAY_KEY_CONTINUE_MASK     FLGKEY_KEY_CONT_MASK_DEFAULT
#define FULL_FILE_PATH_LEN      64
#define BROWSER_VIEW			ENABLE

UINT32         g_uiUIFlowWndPlayCurrenSpeed     = SMEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
BOOL           g_bUIFlowWndPlayNoImgWndOpened   = FALSE;
FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;
extern void FlowPB_IconDrawTabNavi(BOOL bShow);
#endif
#if (BOOT_RECOVERY_FILE==ENABLE)
extern UINT8 g_FileRecoveryFlag;
extern UINT8 g_FileRecoverDouFlag;
#endif
extern void FlowPB_IconDrawTabNavi(BOOL bShow);

//---------------------UIFlowWndPlayCtrl Function ---------------------------
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel);

//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_DSCMode)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Size)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Battery)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Filename)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Date)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Time)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionPanel)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_VideoTotalTime)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_UnProtect)
CTRL_LIST_ITEM(UIFlowWndPlay_Static_Speed)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_MovPlayTime)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_Return)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_PLAY_FF_B)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_COLN0)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_DEL)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusIcon_Play)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_Option_StaticOK)
CTRL_LIST_ITEM(UIFlowWndPlay_Option_StaticReturn)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_UP)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_Down)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_COLN1)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_LockStd)
CTRL_LIST_ITEM(UIFlowWndPlay_OptionStaticIcon_PLAY_FF_F)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusIcon_PowerKey)
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeySelect(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPrev(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieError(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageChange(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIFlowWndPlay_OnClose)
EVENT_ITEM(NVTEVT_KEY_NEXT, UIFlowWndPlay_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_SELECT, UIFlowWndPlay_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_PREV, UIFlowWndPlay_OnKeyPrev)
EVENT_ITEM(NVTEVT_KEY_UP, UIFlowWndPlay_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN, UIFlowWndPlay_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN, UIFlowWndPlay_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT, UIFlowWndPlay_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_MENU, UIFlowWndPlay_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DISPLAY, UIFlowWndPlay_OnKeyDisplay)
EVENT_ITEM(NVTEVT_KEY_MODE, UIFlowWndPlay_OnKeyMode)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, UIFlowWndPlay_OnChildClose)
//EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndPlay_OnBattery)
//EVENT_ITEM(NVTEVT_BATTERY_LOW,UIFlowWndPlay_OnBatteryLow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIFlowWndPlay_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIFlowWndPlay_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK, UIFlowWndPlay_OnKeyPlayback)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH, UIFlowWndPlay_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC, UIFlowWndPlay_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_MOVIE_ERR, UIFlowWndPlay_OnMovieError)
EVENT_ITEM(NVTEVT_STORAGE_INIT, UIFlowWndPlay_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIFlowWndPlay_OnStorageChange)
EVENT_END
#if (BOOT_RECOVERY_FILE==ENABLE)
static void UIFlowWndPlay_FileRecovery(void)
{
    UINT32 uiStatus, uiCurrMode;
    uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
    PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);

    // Decode Error & Read Error
    if( uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE) )
    {
        if(uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG)
        {
            UINT32  uiBuffAddr, uiBuffSize;
            CHAR    chaFullName[64] = { 0 };

            //UxState_SetData(&UIFlowWndPlay_StatusTxt_FileRecoveryRemindCtrl,STATE_CURITEM,UIFlowWndPlay_StatusTxt_FileRecoveryRemind_STRID_RECOVERING);
            //UxCtrl_SetShow(&UIFlowWndPlay_StatusTxt_FileRecoveryRemindCtrl, TRUE);
            //Ux_RedrawAllWind();
            PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
            PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
            PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
            SMediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
            FileDB_Refresh(0);//2016/04/11
            uiStatus = UIPlay_PlaySingle(PB_SINGLE_CURR);
            /*
            if( uiStatus == PB_STA_DONE)
            {
                UxState_SetData(&UIFlowWndPlay_StatusTxt_FileRecoveryRemindCtrl,STATE_CURITEM,UIFlowWndPlay_StatusTxt_FileRecoveryRemind_STRID_MVRECOVER_OK);
                UxCtrl_SetShow(&UIFlowWndPlay_StatusTxt_FileRecoveryRemindCtrl, TRUE);
                return;
            }
            else
            {
                UxState_SetData(&UIFlowWndPlay_StatusTxt_FileRecoveryRemindCtrl,STATE_CURITEM,UIFlowWndPlay_StatusTxt_FileRecoveryRemind_STRID_MVRECOVER_FAIL);
                UxCtrl_SetShow(&UIFlowWndPlay_StatusTxt_FileRecoveryRemindCtrl, TRUE);
                return;
            }*/
        }
        //Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_PICTURE_ERR,FLOWWRNMSG_TIMER_KEEP);
    }
}
#endif
static void UIFlowWndPlay_CheckStatus(void)
{
	UINT32 uiStatus, uiCurrMode;

	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
	PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);

	// Decode Error & Read Error
	if (uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE)) {
		if (uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG) {
			UINT32	uiBuffAddr=0, uiBuffSize=0;
			CHAR	chaFullName[64] = { 0 };

			PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
			PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
			PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
			SMediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
			FileDB_Refresh(0);//2016/04/11
			DBG_DUMP("SMediaPlay_FileRecovery is skipped.\r\n");
			uiStatus = UIPlay_PlaySingle(PB_SINGLE_CURR);
			if (uiStatus == PB_STA_DONE) {
				return;
			}
		}
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_PICTURE_ERR, FLOWWRNMSG_TIMER_2SEC);
	}
}

static BOOL uiShowFileType = TRUE;
void UIFlowPlayShowFileTypeEnable(BOOL En)
{
    uiShowFileType = En;
}
BOOL UIPlayGet_FileType(void)
{
    return uiShowFileType;
}

#if PLAY_THUMB_AND_MOVIE // play thumbnail and movie together
INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiFileNum = 0;
	PLAY_SINGLE_OBJ FlowPlaySingleObj;
	UINT32  uiStatus = E_OK;

	PB_WaitCommandFinish(PB_WAIT_INFINITE);  // Will this affect the OSD screen? By KS Hung on 20190805.
	//After playback ready, point to the last file
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
	//PB_OpenSpecFileBySeq(uiFileNum, TRUE);
	PB_OpenSpecFileBySeq(1, TRUE);
	FlowPlaySingleObj.PlayCommand = PB_SINGLE_CURR;
	FlowPlaySingleObj.PlayCommand |= PB_SINGLE_PRIMARY;
	FlowPlaySingleObj.JumpOffset  = 1;

	//disable video2 and enable video 1
	Display_ShowPreview();

	if (uiStatus & PB_STA_NOIMAGE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
		g_bUIFlowWndPlayNoImgWndOpened = TRUE;
	} else {
		Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		g_PlbData.State = PLB_ST_FULL;
		UxTab_SetData(&UIFlowWndPlay_TabNaviCtrl, TAB_FOCUS, UIFlowWndPlay_TabNavi_ButtonPlay);
		UIFlowWndPlay_CheckStatus();
		//FlowPB_UpdateIcons(1);
		FlowPB_UpdateIcons(0);
	}

	// Set mask key
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
#else // normal mode
INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiStatus;
	UINT32 uiFileNum = 0;
#if 1//(SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_KEEP);
		return NVTEVT_CONSUME;
	}
#endif
	g_bUIFlowWndPlayNoImgWndOpened = FALSE;
#if (BOOT_RECOVERY_FILE==ENABLE)
    if (g_FileRecoveryFlag)
    {
        PB_WaitCommandFinish(PB_WAIT_INFINITE);
        //After playback ready, point to the last file
        PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
        //    PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);
        PB_OpenSpecFileBySeq(uiFileNum, TRUE);
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

        //disable video2 and enable video 1
        Display_ShowPreview();

        UpdateVdoWinForPB();
        //GxDisplay_Set(LAYER_OSD1, LAYER_STATE_ENABLE, 1);
        //GxDisplay_Set(LAYER_OSD2, LAYER_STATE_ENABLE, 1);
        FlowPB_UpdateIcons(0);

        if (uiStatus & PB_STA_NOIMAGE) {
            g_FileRecoveryFlag = 0;
            Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
            Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
            return NVTEVT_CONSUME;
        }

        UIFlowWndPlay_FileRecovery();
        //Ux_RedrawAllWind();
        //Display_SetEnable(LAYER_VDO1, TRUE);
        //Delay_DelayMs(1000);
        g_FileRecoveryFlag = FALSE;
         if(g_FileRecoverDouFlag==2)
        {
            g_FileRecoverDouFlag = FALSE;
            UIPlay_PlaySingle(PB_SINGLE_PREV);
            UIFlowWndPlay_FileRecovery();
        }
        //FlowPB_UpdateIcons(1);            
        //Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);

        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
    
        Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
        return NVTEVT_CONSUME;
    }
#endif
    if (UIPlayGet_FileType()) {
        /*
        if (uiStatus == PB_STA_NOIMAGE &&uiFirst) {
            //Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_3SEC);
            uiFirst = FALSE;
        }
        else*/
        {
            Ux_OpenWindow((VControl *)(&UIMenuWndPlayFileTypeCtrl), 0);
            UIFlowPlayShowFileTypeEnable(FALSE);
            //uiFirst = TRUE;
        }
    } else {
        PB_WaitCommandFinish(PB_WAIT_INFINITE);
        //After playback ready, point to the last file
        PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
        //PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);
        PB_OpenSpecFileBySeq(uiFileNum, TRUE);
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

        //disable video2 and enable video 1
        Display_ShowPreview();

        UpdateVdoWinForPB();

        if (uiStatus & PB_STA_NOIMAGE)
            //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT) == 0)
        {
            if (UIMenuWndPlayFileType_GetFileType() == 1) {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_3SEC);
            } else {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_VIDEO, FLOWWRNMSG_TIMER_3SEC);
            }
            g_bUIFlowWndPlayNoImgWndOpened = TRUE;
            g_PlbData.State = PLB_ST_FULL;
        } else {
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            //g_PlbData.State = PLB_ST_FULL;
            //UxTab_SetData(&UIFlowWndPlay_TabNaviCtrl, TAB_FOCUS, UIFlowWndPlay_TabNavi_ButtonPlay);
            //UIFlowWndPlay_CheckStatus();
            g_PlbData.State = PLB_ST_THUMB;
            //FlowPB_UpdateIcons(1);
            Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
        }
	}

	// Set mask key
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
#endif

INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		break;

	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		// stop movie play
		g_PlbData.State 	   = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
		Ux_SendEvent(0, NVTEVT_EXE_CLOSEPLAY, 0);
		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}
		break;
	}

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable sound key tone
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end
	//g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    #if 0//_TODO
	INT32 vdo_idx = -1;

	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
    DBG_DUMP("%s: g_PlbData.State = %d\r\n", __func__, g_PlbData.State);
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		Ux_SendEvent(&UIFlowWndPlay_TabNaviCtrl, NVTEVT_NEXT_ITEM, 0);
		break;
	case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
		#if 1//_TODO
        if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
        {
            g_PlbData.VideoPBSpeed ++;

            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

            if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_FWD_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }
            else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
            {
                if (g_PlbData.VideoPBSpeed == PLB_BWD_MOV_1x) {
                    g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                } else {
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
                }
            }
            else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
            {
                g_PlbData.State = PLB_ST_PLAY_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }

			// Set speed and direction
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			#if _TODO
			vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
			#endif
			ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);

            //FlowPB_IconDrawMovSpeed();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        }
		#endif
        break;
	case PLB_ST_PAUSE_MOV:
		#if _TODO
		vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_FORWARD, vdo_idx);
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
		#endif
        break;
	default:
		break;
	}
#endif
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	#if 0//_TODO
	INT32 vdo_idx = -1;

	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}

	DBG_DUMP("%s: g_PlbData.State = %d\r\n", __func__, g_PlbData.State);
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		Ux_SendEvent(&UIFlowWndPlay_TabNaviCtrl, NVTEVT_PREVIOUS_ITEM, 0);
		break;
	case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
		#if 1//_TODO
		DBG_DUMP("OnKeyPrev g_PlbData.VideoPBSpeed %x, g_uiUIFlowWndPlayCurrenDirection %d\r\n", g_PlbData.VideoPBSpeed, g_uiUIFlowWndPlayCurrenDirection);
        if(g_PlbData.VideoPBSpeed > PLB_BWD_MOV_8x)
        {
            if (g_PlbData.VideoPBSpeed == PLB_FWD_MOV_1x) {
                g_PlbData.VideoPBSpeed -= 2;
            } else {
                g_PlbData.VideoPBSpeed--;
            }

            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

            if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_FWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }
            else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_BWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
            }
            else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
            {
                g_PlbData.State = PLB_ST_PLAY_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }

			// Set speed and direction
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			#if _TODO
			vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
			#endif
			ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);


            //FlowPB_IconDrawMovSpeed();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        }
		#endif
        break;
	case PLB_ST_PAUSE_MOV:
		#if _TODO
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_BACKWARD, vdo_idx);
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
		#endif
        break;
	default:
		break;
	}
	#endif
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
    UINT32 Tabfocus;
	char   pFilePath[FULL_FILE_PATH_LEN] = {0};
	UINT32 uiPBFileFmt = PBFMT_MP4;
	UINT32 uiPBFileSize = 0;

	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
			PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
			if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
				UINT32 u32CurrPbStatus = 0;

			    PB_GetParam(PBPRMID_PLAYBACK_STATUS, &u32CurrPbStatus);
				if (u32CurrPbStatus != PB_STA_DONE){
					return NVTEVT_CONSUME;
				}

				// Open Video File
				if (gphUIFlowMovPlay_Filehdl) {
					FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
					gphUIFlowMovPlay_Filehdl = NULL;
				}
				if (uiPBFileFmt & PBFMT_TS) {
					PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
					if (uiPBFileSize <= 0x10000) {
						DBG_DUMP("Wrong video file format!! \r\n");
						break;
					}
				}
				// Get Current index
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);

				// Open Test Media File
				gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

				if (!gphUIFlowMovPlay_Filehdl) {
					DBG_DUMP("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
					break;
				}

				FlowPB_UpdateIcons(0); /* FlowPB_IconDrawImageSize needs exif buffer, should be invoked before NVTEVT_EXE_CLOSE */

				Ux_SendEvent(0, NVTEVT_EXE_CLOSE, 0); //CustomPlayObjCmdMap

				//flush event first
				Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

				//stop scan


			// Wake up CustomMoviePlayObjCtrl obj.
				Ux_SetActiveApp(&CustomMoviePlayObjCtrl);
				Ux_SendEvent(0, NVTEVT_EXE_OPENPLAY, 1, (UINT32)gphUIFlowMovPlay_Filehdl);
				Ux_SendEvent(0, NVTEVT_EXE_STARTPLAY, 0);


				//set movie volumn
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);

				g_PlbData.State = PLB_ST_PLAY_MOV;
				FlowPB_IconDrawLeftBtn(TRUE);
				FlowPB_IconDrawRightBtn(TRUE);
				FlowPB_IconDrawMovPlayTime(TRUE);
			} else {
				g_PlbData.State = PLB_ST_MAGNIFY;
				FlowPB_UpdateIcons(0);
				FlowPB_IconDrawLeftBtn(TRUE);

				//#NT#2017/11/17#Adam Su -begin
				//#NT#AUTO_TEST
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/17#Adam Su -end
			}
			break;
	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
		#if 1//_TODO
		g_PlbData.State 	   = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;

		Ux_SendEvent(0, NVTEVT_EXE_CLOSEPLAY, 0);
		Ux_SetActiveApp(&CustomPlayObjCtrl);


		Ux_SendEvent(0, NVTEVT_EXE_OPEN, 0);

		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}

		// Play 1st video frame image
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		FlowPB_UpdateIcons(1);
        #endif
		break;
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		#if _TODO
		KeyScan_EnableMisc(FALSE);

		// Set to Normal Play
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

		// Start Play
		vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
		g_PlbData.State = PLB_ST_PLAY_MOV;
		#endif
		break;
	}
#endif
	return NVTEVT_CONSUME;
}

INT32	vdo_idx = -1;
INT32 UIFlowWndPlay_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        switch (g_PlbData.State) {
        case PLB_ST_FULL:
            Ux_OpenWindow((VControl *)(&UIMenuWndPlayQuickConfirmDelCtrl), 0);
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            if (g_PlbData.VideoPBSpeed > PLB_BWD_MOV_4x) //PLB_BWD_MOV_8x
            {
                //g_PlbData.VideoPBSpeed --;
				if (g_PlbData.VideoPBSpeed == PLB_FWD_MOV_1x) {
					g_PlbData.VideoPBSpeed -= 2;
				} else {
					g_PlbData.VideoPBSpeed--;
				}

                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                }

                // Set speed and direction
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                #if 0//(NMEDIAPLAY_FUNC == DISABLE)
                ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
                ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
                ImageApp_MoviePlay_UpdateAll();
                #else //(NMEDIAPLAY_FUNC == ENABLE)
                //UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
                ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
                #endif

                FlowPB_IconDrawMovSpeed();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
            break;

		case PLB_ST_PAUSE_MOV:
	        break;
		default:
			break;
        }
        break;
    }
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;
    UINT32  uiLockStatus;
	//INT32 vdo_idx = -1;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        switch (g_PlbData.State) {
        case PLB_ST_FULL:
            PB_GetParam(PBPRMID_FILE_ATTR_LOCK, &uiLockStatus);
            if (uiLockStatus) {
                UIPlay_Protect(PLAY_UNPROTECT_ONE);
            } else {
                UIPlay_Protect(PLAY_PROTECT_ONE);
            }
            UIPlay_PlaySingle(PB_SINGLE_CURR);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            if (g_PlbData.VideoPBSpeed < PLB_FWD_MOV_4x)//PLB_FWD_MOV_8x
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
	                if (g_PlbData.VideoPBSpeed == PLB_BWD_MOV_1x) {
	                    g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
	                    g_PlbData.State = PLB_ST_PLAY_MOV;
	                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
	                } else {
	                    g_PlbData.State = PLB_ST_BWD_MOV;
	                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
	                }
            	}
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                }

                // Set speed and direction
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                #if 0//(NMEDIAPLAY_FUNC == DISABLE)
                ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
                ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
                ImageApp_MoviePlay_UpdateAll();
                #else //(NMEDIAPLAY_FUNC == ENABLE)
                //UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
                ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
                #endif

                FlowPB_IconDrawMovSpeed();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
            break;

		case PLB_ST_PAUSE_MOV:
	        break;
		default:
			break;
        }
        break;
    }
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_RELEASE:
        switch(g_PlbData.State)
        {
        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            // stop movie play
            UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);
            break;

        case PLB_ST_FULL:
            Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
            break;
        }
        break;

    /*
    case NVTEVT_KEY_LONG_PRESS:
        switch(g_PlbData.State)
        {
        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            // stop movie play
            UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);
            //break;

        case PLB_ST_FULL:
            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
            Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
            Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_NULL);
            UIFlowPlayShowFileTypeEnable(TRUE);
            Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
            break;
        }
        break;*/
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiStatus;

	//#NT#2012/12/27#Hideo Lin -begin
	//#NT#Fix close child window hang up as card removed
	if (Ux_IsForceCloseWindow()) {
		return NVTEVT_CONSUME;
	}
	//#NT#2012/12/27#Hideo Lin -end

	if (paramNum > 0) {
		//Return from thumbnail, magnify or delete mode and play current image again.
		switch (paramArray[0]) {
		case NVTRET_THUMBNAIL:
		case NVTRET_MAGNIFY:
			UIPlay_PlaySingle(PB_SINGLE_CURR);
			UIFlowWndPlay_CheckStatus();
			FlowPB_UpdateIcons(1);
			break;
		case NVTRET_DELETE:
		case NVTRET_DELETEALL:
			uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

			if (uiStatus & PB_STA_NOIMAGE)
				//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
			{
				if (!g_bUIFlowWndPlayNoImgWndOpened) {
                    if (UIMenuWndPlayFileType_GetFileType() == 1) {
                        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_3SEC);
                    } else {
                        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_VIDEO, FLOWWRNMSG_TIMER_3SEC);
                    }
					g_bUIFlowWndPlayNoImgWndOpened = TRUE;
				}
			} else {
				UIPlay_PlaySingle(PB_SINGLE_CURR);
				UIFlowWndPlay_CheckStatus();
				FlowPB_UpdateIcons(1);
			}
			break;
		case NVTRET_ENTER_MENU:
            #if 0
			// Reset specific menu items
			SysSetFlag(FL_PROTECT, PROTECT_ONE);
			// Open common item menu
			Ux_OpenWindow(&MenuCommonItemCtrl, 0);
			g_bUIFlowWndPlayNoImgWndOpened = FALSE;
            #endif
			break;
		case NVTRET_WARNING:
			Ux_PostEvent(paramArray[1], 0);
			break;
		}
	} else {
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
		if (uiStatus & PB_STA_NOIMAGE)
			//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
		{
			if (!g_bUIFlowWndPlayNoImgWndOpened) {
                if (UIMenuWndPlayFileType_GetFileType() == 1) {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_3SEC);
                } else {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_VIDEO, FLOWWRNMSG_TIMER_3SEC);
                }
				g_bUIFlowWndPlayNoImgWndOpened = TRUE;
			} else {
                #if 0
				g_PlbData.State = PLB_ST_MENU;
				Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
				// Reset specific menu items
				SysSetFlag(FL_PROTECT, PROTECT_ONE);
				// Open common item menu
				Ux_OpenWindow(&MenuCommonItemCtrl, 0);
				Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
                #endif
			}
		} else { //file error
			//UIPlay_PlaySingle(PB_SINGLE_CURR);
			FlowPB_UpdateIcons(1);
			//UIFlowWndPlay_CheckStatus();
		}
	}
	g_PlbData.State = PLB_ST_FULL;

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable sound key tone flag
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end

	// set mask key
	//Ux_FlushEvent();
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if _TODO
	static volatile BOOL bBatteryOn = FALSE;

	UxState_SetData(&UIFlowWndPlay_StatusICN_BatteryCtrl, STATE_CURITEM, GetBatteryLevel());
	if (KeyScan_IsACIn()) {
		bBatteryOn = !bBatteryOn;
		UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl, bBatteryOn);
	} else {
		UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl, TRUE);
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_2SEC);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}

	switch (g_PlbData.State) {
	case PLB_ST_PLAY_MOV:
        #if 1//_TODO
		Ux_SendEvent(0, NVTEVT_EXE_PAUSEPLAY, 0);
		g_PlbData.State = PLB_ST_PAUSE_MOV;
		//FlowPB_IconDrawRightBtn(TRUE);

		//KeyScan_EnableMisc(TRUE);
		#endif
		break;
	case PLB_ST_PAUSE_MOV:
        #if 1//_TODO
        //KeyScan_EnableMisc(TRUE);

		// Start to Play
		//set movie volumn again to avoid volumn changed by beep sound
		Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
		Ux_SendEvent(0, NVTEVT_EXE_RESUMEPLAY, 0);
		g_PlbData.State = PLB_ST_PLAY_MOV;
		//FlowPB_IconDrawRightBtn(TRUE);
		#endif
		break;
#if (BROWSER_VIEW == ENABLE)
	case PLB_ST_FULL:
		Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
		break;
#endif
	default:
		break;
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiKeyAct;
    char   pFilePath[FULL_FILE_PATH_LEN];
    //UINT32 fileType = DCF_FILE_TYPE_JPG;
    UINT32 uiPBFileFmt = PBFMT_MP4;
    UINT32 uiPBFileSize = 0;
	if (!UIMenuWndPlayFileType_GetFileType()) {

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        switch (g_PlbData.State) {
        case PLB_ST_FULL:
        default:
			PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
			if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
				UINT32 u32CurrPbStatus = 0;

			    PB_GetParam(PBPRMID_PLAYBACK_STATUS, &u32CurrPbStatus);
				if (u32CurrPbStatus != PB_STA_DONE){
					return NVTEVT_CONSUME;
				}

				// Open Video File
				if (gphUIFlowMovPlay_Filehdl) {
					FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
					gphUIFlowMovPlay_Filehdl = NULL;
				}
				if (uiPBFileFmt & PBFMT_TS) {
					PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
					if (uiPBFileSize <= 0x10000) {
						DBG_DUMP("Wrong video file format!! \r\n");
						break;
					}
				}
				// Get Current index
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);

				// Open Test Media File
				gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

				if (!gphUIFlowMovPlay_Filehdl) {
					DBG_DUMP("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
					break;
				}

				//FlowPB_UpdateIcons(0); /* FlowPB_IconDrawImageSize needs exif buffer, should be invoked before NVTEVT_EXE_CLOSE */

				Ux_SendEvent(0, NVTEVT_EXE_CLOSE, 0); //CustomPlayObjCmdMap

				//flush event first
				Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

				//stop scan


			// Wake up CustomMoviePlayObjCtrl obj.
				Ux_SetActiveApp(&CustomMoviePlayObjCtrl);
				Ux_SendEvent(0, NVTEVT_EXE_OPENPLAY, 1, (UINT32)gphUIFlowMovPlay_Filehdl);
				Ux_SendEvent(0, NVTEVT_EXE_STARTPLAY, 0);

				//set movie volumn
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);

				g_PlbData.State = PLB_ST_PLAY_MOV;
				FlowPB_IconDrawMovPlay(TRUE);
			   	//FlowPB_IconDrawMovStop(TRUE);
			   	FlowPB_IconDrawMovPlayTime(TRUE);
			   	FlowPB_IconDrawMovBwd(TRUE);
			   	FlowPB_IconDrawMovFwd(TRUE);
                FlowPB_IconDrawMovPlay_HideShowIcon(FALSE);
			} else {
				g_PlbData.State = PLB_ST_MAGNIFY;
				//FlowPB_UpdateIcons(0);
				//FlowPB_IconDrawLeftBtn(TRUE);

				//#NT#2017/11/17#Adam Su -begin
				//#NT#AUTO_TEST
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/17#Adam Su -end
			}
			break;	
        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            //Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
			Ux_SendEvent(0, NVTEVT_EXE_PAUSEPLAY, 0);
            g_PlbData.State = PLB_ST_PAUSE_MOV;
            FlowPB_IconDrawMovPlay(TRUE);
            //FlowPB_IconDrawMovStop(TRUE);
            //FlowPB_IconDrawMovBwd(TRUE);
            //FlowPB_IconDrawMovFwd(TRUE);
            //#NT#2012/10/23#Philex Lin - begin
            // enable auto power off/USB detect timer
            // enable sound key tone flag
            KeyScan_EnableMisc(TRUE);
            //#NT#2012/10/23#Philex Lin - end
            break;

    	case PLB_ST_PAUSE_MOV:
            //#NT#2012/10/23#Philex Lin - begin
            // disable auto power off/USB detect timer
            // disable key tone flag
            KeyScan_EnableMisc(FALSE);
            //#NT#2012/10/23#Philex Lin - end
            // Start to Play
            //set movie volumn again to avoid volumn changed by beep sound
			//Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
			Ux_SendEvent(0, NVTEVT_EXE_RESUMEPLAY, 0);
			//g_PlbData.State = PLB_ST_PLAY_MOV;

			if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
			{
				g_PlbData.State = PLB_ST_FWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
			}
			else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
			{
				g_PlbData.State = PLB_ST_BWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
				
			}
			else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
			{
				//Ux_SendEvent(0, NVTEVT_EXE_RESUMEPLAY, 0);
				g_PlbData.State = PLB_ST_PLAY_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1); 		
			}
			//DBG_DUMP("======%d=====\r\n",g_PlbData.State);
            FlowPB_IconDrawMovPlay(TRUE);
            FlowPB_IconDrawMovPlay_HideShowIcon(FALSE);
            break;
        }
		break;
	    }
	}	
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch (g_PlbData.State) {
    case PLB_ST_FULL:
        break;

    case PLB_ST_PLAY_MOV:
    case PLB_ST_PAUSE_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
#if 1//_TODO
    	g_PlbData.State 	   = PLB_ST_FULL;
    	g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;

#if 0
    	UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
    	g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
#endif


    	Ux_SendEvent(0, NVTEVT_EXE_CLOSEPLAY, 0);
    	Ux_SetActiveApp(&CustomPlayObjCtrl);

    	#if 0
    	ImageApp_Play_Open();
    	#else // Wakeup playback task and ImageApp_Play module.
    	Ux_SendEvent(0, NVTEVT_EXE_OPEN, 0);
    	#endif

    	#if 0
    	KeyScan_EnableMisc(TRUE);

    	if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
    		SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
    	}
    	#endif

    	if (gphUIFlowMovPlay_Filehdl) {
    		FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
    		gphUIFlowMovPlay_Filehdl = NULL;
    	}

    	// Play 1st video frame image
    	UIPlay_PlaySingle(PB_SINGLE_CURR);

    	FlowPB_IconDrawMovPlay_HideShowIcon(TRUE);
    	FlowPB_UpdateIcons(1);

    	#if FLOW_MOV_PLAY_REAET // Repeat play test only. To be removed.
    	vos_util_delay_ms(1000);
    	Ux_PostEvent(NVTEVT_KEY_SELECT, 1, NVTEVT_KEY_PRESS);
    	#endif

    	//#NT#2016/11/10#Niven Cho -begin
    	//#NT#AUTO_TEST
    	//exam_msg("OnMovieFinish\r\n");
    	//#NT#2016/11/10#Niven Cho -end
#endif
        break;

    default:
        break;
    }

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_PlbData.State != PLB_ST_FULL) {
        FlowPB_IconDrawVideoTotalTime(FALSE);
        FlowPB_IconDrawMovPlayTime(TRUE);
    }

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_PICTURE_ERR, FLOWWRNMSG_TIMER_2SEC);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif

	return NVTEVT_CONSUME;
}

void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel)
{
	switch (uiChangeSpeedLevel) {
	default:
	case PLB_FWD_MOV_1x:
	//case PLB_BWD_MOV_1x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_NORMAL;
		break;

	case PLB_FWD_MOV_2x:
	case PLB_BWD_MOV_2x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_2X;
		break;

	case PLB_FWD_MOV_4x:
	case PLB_BWD_MOV_4x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_4X;
		break;

	case PLB_FWD_MOV_8x:
	case PLB_BWD_MOV_8x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_8X;
		break;

	}
}

//----------------------UIFlowWndPlay_StaticICN_DSCModeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_DSCMode)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SizeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Size)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_BatteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Battery)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_FilenameCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Filename)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Protect)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_DateCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Date)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_TimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Time)
EVENT_END

//---------------------UIFlowWndPlay_OptionPanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_OptionPanel)
CTRL_LIST_END

//----------------------UIFlowWndPlay_OptionPanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionPanel)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_VideoTotalTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_VideoTotalTime)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_UnProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_UnProtect)
EVENT_END

//----------------------UIFlowWndPlay_Static_SpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Static_Speed)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_MovPlayTime)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_ReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_Return)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_PLAY_FF_BCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_PLAY_FF_B)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_COLN0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_COLN0)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_DELCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_DEL)
EVENT_END

//----------------------UIFlowWndPlay_StatusIcon_PlayCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusIcon_Play)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_Protect)
EVENT_END

//----------------------UIFlowWndPlay_Option_StaticOKCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Option_StaticOK)
EVENT_END

//----------------------UIFlowWndPlay_Option_StaticReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Option_StaticReturn)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_UPCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_UP)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_DownCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_Down)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_COLN1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_COLN1)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_LockStdCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_LockStd)
EVENT_END

//----------------------UIFlowWndPlay_OptionStaticIcon_PLAY_FF_FCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_OptionStaticIcon_PLAY_FF_F)
EVENT_END

//----------------------UIFlowWndPlay_StatusIcon_PowerKeyCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusIcon_PowerKey)
EVENT_END

