//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIWnd/UIFlow.h"
#include "NVTToolCommand.h"
#include "UIWnd/SPORTCAM/UIFlow/UIFlowPlay/UIFlowWndPlayThumbRes.c"
#include "PlaybackTsk.h"
#include "FileDB.h"
#include "exif/Exif.h"
#include "UIApp/Play/UIPlayComm.h"
#include "SysCommon.h"

#define __MODULE__          UIPlayThumb
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include <kwrap/debug.h>

#define PBX_SLIDE_EFFECT_NONE                       0

//---------------------UIFlowWndPlayThumbCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel0)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel1)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel2)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel3)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel4)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel5)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel6)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel7)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel8)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect0)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect1)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect2)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect3)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect4)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect5)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect6)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect7)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_Protect8)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm0)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm1)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm2)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm3)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm4)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm5)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm6)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm7)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticICN_FileFilm8)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_ThumbID)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_StaticFileList)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_ThumbFileDateTime)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_TipsBar)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumbCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyPrev(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyNext(VControl *, UINT32, UINT32 *);
#if PLAY_THUMB_AND_MOVIE // play thumbnail and movie together
INT32 UIFlowWndPlayThumb_OnKeySelect(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnMovieFinish(VControl *, UINT32, UINT32 *);
#endif
EVENT_BEGIN(UIFlowWndPlayThumb)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIFlowWndPlayThumb_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIFlowWndPlayThumb_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPlayThumb_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_UP, UIFlowWndPlayThumb_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN, UIFlowWndPlayThumb_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIFlowWndPlayThumb_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_RIGHT, UIFlowWndPlayThumb_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIFlowWndPlayThumb_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU, UIFlowWndPlayThumb_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIFlowWndPlayThumb_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN, UIFlowWndPlayThumb_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIFlowWndPlayThumb_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_PREV, UIFlowWndPlayThumb_OnKeyPrev)
EVENT_ITEM(NVTEVT_KEY_NEXT, UIFlowWndPlayThumb_OnKeyNext)
#if PLAY_THUMB_AND_MOVIE // play thumbnail and movie together
EVENT_ITEM(NVTEVT_KEY_SELECT, UIFlowWndPlayThumb_OnKeySelect)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH, UIFlowWndPlayThumb_OnMovieFinish)
#endif
EVENT_END

static void UIFlowWndPlayThumb_IconDrawDCFFileID(BOOL bShow);

extern PURECT FlowPB_ThumbDisplay(void);
static void UIFlowWndPlayThumb_NaviKey(UINT32 key)
{
	BROWSE_NAVI_INFO BrowseNavi;
	FlowPB_ClearAllThumbIcon();
	SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, FALSE);
	BrowseNavi.NaviKey = key;
	BrowseNavi.HorNums = FLOWPB_THUMB_H_NUM2;
	BrowseNavi.VerNums = FLOWPB_THUMB_V_NUM2;

	BrowseThumbNaviKey(&BrowseNavi);

    UIFlowWndPlayThumb_IconDrawDCFFileID(TRUE);
	FlowPB_ShowAllThumbIcon();
	SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, TRUE);

    //@Ken b-begin
    Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
    Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //@Ken b-end
}

CHAR  g_chaFullName[60] = { 0 };
int   g_FileNumIndex = 0;
int   g_FileTotalNum = 0;
static void UIFlowWndPlayThumb_IconDrawDCFFileID(BOOL bShow)
{
    FILEDB_HANDLE fileDbHandle = 0;
    //UINT32  CurrIndex;
    PFILEDB_FILE_ATTR  pFileAttr;
    static char item1_Buf[32] = {0};
    static char DateTime[32] = {0};
    UINT32 i, j, full_path_len, file_name_len;
    char *file_name_pos;

    //hide icon
    if (bShow == FALSE) {
        UxCtrl_SetShow(&UIFlowWndPlayThumb_ThumbFileDateTimeCtrl, FALSE);
        return;
    }

    //CurrIndex = FileDB_GetCurrFileIndex(fileDbHandle);

    pFileAttr = FileDB_SearhFile(fileDbHandle, g_FileNumIndex);
    // A:\DCIM\Movie\RO\20190302152637_000001.MP4

    sprintf(g_chaFullName,"%s", pFileAttr->filePath);
    //debug_msg("*** g_chaFullName = %s ***\r\n",g_chaFullName);

    memset(item1_Buf, 0, 32);
    memset(DateTime, 0, 32);

	// search last '\' in full file path
	full_path_len = strlen(g_chaFullName);
	for (i = 0; i < full_path_len; i++) {
		if (g_chaFullName[full_path_len - i] == '\\') {
			break;
		}
	}

	// search last '.' in full file path
	for (j = 0; j < full_path_len; j++) {
		if (g_chaFullName[full_path_len - j] == '.') {
			break;
		}
	}

	file_name_pos = &g_chaFullName[full_path_len - i + 1]; // string behind last '\'
	file_name_len = strlen(file_name_pos);
	if (file_name_len > j) {
		file_name_len -= j; // exclude extension name
	}
	if (file_name_len > 31) { // buffer limitation
		file_name_len = 31;
	}
	strncpy(item1_Buf, file_name_pos, file_name_len);
	item1_Buf[file_name_len] = '\0';
    //debug_msg("*** item1_Buf= %s ***\r\n",item1_Buf);

    DateTime[0] = item1_Buf[4];
    DateTime[1] = item1_Buf[5];
    DateTime[2] = '/';
    DateTime[3] = item1_Buf[6];
    DateTime[4] = item1_Buf[7];
    DateTime[5] = ' ';
    DateTime[6] = ' ';
    DateTime[7] = ' ';
    DateTime[8] = item1_Buf[8];
    DateTime[9] = item1_Buf[9];
    DateTime[10] = ' ';
    DateTime[11] = ':';
    DateTime[12] = ' ';
    DateTime[13] = item1_Buf[10];
    DateTime[14] = item1_Buf[11];
    DateTime[15] = '\0';

    UxStatic_SetData(&UIFlowWndPlayThumb_ThumbFileDateTimeCtrl, STATIC_VALUE, Txt_Pointer(DateTime));
    UxCtrl_SetShow(&UIFlowWndPlayThumb_ThumbFileDateTimeCtrl, TRUE);
}

static void UIFlowWndPlayThumb_ThumOpenGetFileIndex(void)
{
    FILEDB_HANDLE fileDbHandle = 0;

    g_FileNumIndex = FileDB_GetCurrFileIndex(fileDbHandle);
    g_FileTotalNum = FileDB_GetTotalFileNum(fileDbHandle);
}

INT32 UIFlowWndPlayThumb_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	PURECT          pThumbRect;
	PLAY_BROWSER_OBJ     FlowPBBrowserObj = {0};
	UINT32 FileNumsInDir = 0, NumsPerPage;
	UINT8  HorNums, VerNums;
	UINT32 uiStatus = E_OK;

    uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
    if (uiStatus & PB_STA_NOIMAGE) {
        if (UIMenuWndPlayFileType_GetFileType()) {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_3SEC);
        } else {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_VIDEO, FLOWWRNMSG_TIMER_3SEC);
        }
        return NVTEVT_CONSUME;
    }

    UIFlowWndPlayThumb_ThumOpenGetFileIndex();

	FlowPB_ClearAllThumbIcon();
	pThumbRect = FlowPB_ThumbDisplay();
	HorNums = FLOWPB_THUMB_H_NUM2;
	VerNums = FLOWPB_THUMB_V_NUM2;
	PB_SetParam(PBPRMID_THUMB_LAYOUT_ARRAY, (UINT32)pThumbRect);
//#NT#2012/11/27#Scottie -begin
//#NT#Support Dual Display for PB
	//if (System_GetEnableDispCount() == 2) {
	//	PB_SetParam(PBPRMID_THUMB_LAYOUT_ARRAY2, (UINT32)pThumbRect);
	//}
//#NT#2012/11/27#Scottie -end
	NumsPerPage = VerNums * VerNums;
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &FileNumsInDir);
	FlowPBBrowserObj.BrowserCommand = PB_BROWSER_CURR;
	FlowPBBrowserObj.HorNums        = HorNums;
	FlowPBBrowserObj.VerNums        = VerNums;
	FlowPBBrowserObj.slideEffectFunc = PBX_SLIDE_EFFECT_NONE;
	if (FileNumsInDir <= NumsPerPage) { // means only one page
		FlowPBBrowserObj.bReDecodeImages = FALSE;
	} else {
		FlowPBBrowserObj.bReDecodeImages = TRUE;
	}

	PB_PlayBrowserMode(&FlowPBBrowserObj);
	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
	DBG_DUMP("UIFlowWndPlayThumb_OnOpen: uiStatus 0x%X\r\n", uiStatus);


	#if PLAY_THUMB_AND_MOVIE // play thumbnail and movie together
	UINT32 idx;
	PB_GetParam(PBPRMID_THUMB_CURR_IDX, &idx);
	//DBG_DUMP("UIFlowWndPlayThumb_NaviKey: PBPRMID_THUMB_CURR_IDX %d\r\n", idx);
	PBView_DrawThumbFrame(idx-1, THUMB_DRAW_TMP_BUFFER);
	#endif

    UIFlowWndPlayThumb_IconDrawDCFFileID(TRUE);
	FlowPB_ShowAllThumbIcon();
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
        g_FileNumIndex--;
        if (g_FileNumIndex < 0) {
            g_FileNumIndex = g_FileTotalNum - 1;
        }
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_LEFT);
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
        g_FileNumIndex++;
        if (g_FileNumIndex >= g_FileTotalNum) {
            g_FileNumIndex = 0;
        }
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_RIGHT);
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

    case NVTEVT_KEY_RELEASE:
		DBG_DUMP("call UIFlowWndPlayThumb_OnKeyLeft1\n");
        FlowPB_ClearAllThumbIcon();
        //Ux_Redraw();
        Ux_CloseWindowClear((VControl *)(&UIFlowWndPlayThumbCtrl), 1, 0);
        UIFlowPlayShowFileTypeEnable(TRUE);
        #if 1
        Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_PLAYBACK_MODE, 0);
		DBG_DUMP("call UIFlowWndPlayThumb_OnKeyLeft2\n");
        #else
        Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_MOVIE_MODE, 0);
        #endif
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_RIGHT);
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 uiActKey;
    uiActKey = paramArray[0];
    switch (uiActKey) {
    case NVTEVT_KEY_PRESS:
	FlowPB_ClearAllThumbIcon();
	Ux_Redraw();
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
        break;
    }
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FlowPB_ClearAllThumbIcon();
	Ux_Redraw();
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];

	switch (uiActKey) {
	case NVTEVT_KEY_PRESS:
	FlowPB_ClearAllThumbIcon();
	Ux_Redraw();
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	//Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
	    break;
	}
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_LEFT);
		break;

	}

	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlayThumb_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_RIGHT);
		break;

	}

	return NVTEVT_CONSUME;
}

#if PLAY_THUMB_AND_MOVIE // play thumbnail and movie together
#include "UIApp/Play/UIAppMoviePlay.h"
#define FULL_FILE_PATH_LEN      64
extern FST_FILE       gphUIFlowMovPlay_Filehdl;
INT32 UIFlowWndPlayThumb_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//INT32  uiActKey;
	char   pFilePath[FULL_FILE_PATH_LEN] = {0};
	UINT32 uiPBFileFmt = PBFMT_MP4;
	UINT32 uiPBFileSize = 0;

	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}

	//uiActKey = paramArray[0];

	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		PB_SeekCurrent(); // seek current file after leaving thumbnail mode

		PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
		if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
			UINT32 u32CurrPbStatus = 0;

			PB_GetParam(PBPRMID_PLAYBACK_STATUS, &u32CurrPbStatus);
			if (u32CurrPbStatus != PB_STA_DONE){
				return NVTEVT_CONSUME;
			}

			// Open Video File
			if (gphUIFlowMovPlay_Filehdl) {
				FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
				gphUIFlowMovPlay_Filehdl = NULL;
			}
			if (uiPBFileFmt & PBFMT_TS) {
				PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
				if (uiPBFileSize <= 0x10000) {
					DBG_DUMP("Wrong video file format!! \r\n");
					break;
				}
			}
			// Get Current index
			PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
			DBG_DUMP("play file path: %s\r\n", pFilePath);

			// Open Test Media File
			gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

			if (!gphUIFlowMovPlay_Filehdl) {
				DBG_DUMP("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
				break;
			}
			#if 0
			KeyScan_EnableMisc(FALSE);
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
			#endif
			Ux_SendEvent(0, NVTEVT_EXE_CLOSE, 0); //CustomPlayObjCmdMap

			//flush event first
			Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

			//stop scan
			#if 0
			//SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
			SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);
			#endif

			Ux_SetActiveApp(&CustomMoviePlayObjCtrl);
			Ux_SendEvent(0, NVTEVT_EXE_OPENPLAY, 1, (UINT32)gphUIFlowMovPlay_Filehdl);
			Ux_SendEvent(0, NVTEVT_EXE_STARTPLAY, 0);

			//set movie volumn
			Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
			FlowPB_UpdateIcons(0);
			g_PlbData.State = PLB_ST_PLAY_MOV;
			//FlowPB_IconDrawLeftBtn(TRUE);
			//FlowPB_IconDrawRightBtn(TRUE);
			FlowPB_IconDrawMovPlayTime(TRUE);
		}
		break;

	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
		g_PlbData.State 	   = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		#if 0
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
		#endif

		// Close MoviePlay module.
		Ux_SendEvent(0, NVTEVT_EXE_CLOSEPLAY, 0);
		Ux_SetActiveApp(&CustomPlayObjCtrl);

		#if 0
		if (gMovie_Play_Info.event_cb) {
			gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
		}
		if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
			return NVTEVT_CONSUME;
		}
		#endif

		// Wakeup playback task and ImageApp_Play module.
		Ux_SendEvent(0, NVTEVT_EXE_OPEN, 0);

		#if 0
		KeyScan_EnableMisc(TRUE);

		if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
			SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
		}
		#endif

		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}

		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_ENTER); // recall current thumbnail
		break;

	}

	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlayThumb_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	g_PlbData.State 	   = PLB_ST_FULL;
	g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;

#if 0
	UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
	g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
#endif

	Ux_SendEvent(0, NVTEVT_EXE_CLOSEPLAY, 0);
	Ux_SetActiveApp(&CustomPlayObjCtrl);

	// Wakeup playback task and ImageApp_Play module.
	Ux_SendEvent(0, NVTEVT_EXE_OPEN, 0);

	#if 0
	KeyScan_EnableMisc(TRUE);

	if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
		SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
	}
	#endif

	if (gphUIFlowMovPlay_Filehdl) {
		FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
		gphUIFlowMovPlay_Filehdl = NULL;
	}

	UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_ENTER); // recall current thumbnail

	return NVTEVT_CONSUME;
}
#endif

//---------------------UIFlowWndPlayThumb_Panel0Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel0)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel0)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel1Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel1)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel1)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel2Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel2)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel2)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel3)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel3)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel4Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel4)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel4)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel5Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel5)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel5)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel6Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel6)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel6)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel7Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel7)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel7Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel7)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel8Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel8)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel8Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel8)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect0)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect1)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect2)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect3)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect4)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect5)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect6)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect7Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect7)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_Protect8Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect8)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm0)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm1Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm1)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm2)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm3)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm4)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm5)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm6)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm7Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm7)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticICN_FileFilm8Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm8)
EVENT_END

//----------------------UIFlowWndPlayThumb_ThumbIDCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_ThumbID)
EVENT_END

//----------------------UIFlowWndPlayThumb_StaticFileListCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_StaticFileList)
EVENT_END

//----------------------UIFlowWndPlayThumb_ThumbFileDateTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_ThumbFileDateTime)
EVENT_END

//---------------------UIFlowWndPlayThumb_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_TipsBar)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_TipsIconReturn)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_TipsIconUp)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_TipsIconDown)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_TipsIconOK)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_TipsBar)
EVENT_END

//----------------------UIFlowWndPlayThumb_TipsIconReturnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_TipsIconReturn)
EVENT_END

//----------------------UIFlowWndPlayThumb_TipsIconUpCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_TipsIconUp)
EVENT_END

//----------------------UIFlowWndPlayThumb_TipsIconDownCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_TipsIconDown)
EVENT_END

//----------------------UIFlowWndPlayThumb_TipsIconOKCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_TipsIconOK)
EVENT_END

