//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAY_H
#define UIFLOWWNDPLAY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayCtrl;//Panel type 

extern VControl UIFlowWndPlay_StaticICN_DSCModeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_SizeCtrl;//Static type 

extern VControl UIFlowWndPlay_StatusICN_BatteryCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_FULL,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_MED,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_LOW,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_EMPTY,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_ZERO,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_CHARGE,
UIFlowWndPlay_StatusICN_Battery_MAX
}UIFlowWndPlay_StatusICN_Battery_Setting;

extern VControl UIFlowWndPlay_StaticTXT_FilenameCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticICN_ProtectCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_DateCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_TimeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_VideoTotalTimeCtrl;//Static type 

extern VControl UIFlowWndPlay_Static_SpeedCtrl;//Static type 

extern VControl UIFlowWndPlay_TipsBarCtrl;//Panel type 

extern VControl UIFlowWndPlay_TipsIconReturnCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_TipsIconReturn_ICON_BACK,
UIFlowWndPlay_TipsIconReturn_MAX
}UIFlowWndPlay_TipsIconReturn_Setting;

extern VControl UIFlowWndPlay_TipsIconDelCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_TipsIconDel_ICON_DELETE,
UIFlowWndPlay_TipsIconDel_ICON_PLAY_FF_B,
UIFlowWndPlay_TipsIconDel_MAX
}UIFlowWndPlay_TipsIconDel_Setting;

extern VControl UIFlowWndPlay_TipsIconLockCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_TipsIconLock_ICON_FILE_LOCK,
UIFlowWndPlay_TipsIconLock_ICON_PLAY_FF_F,
UIFlowWndPlay_TipsIconLock_ICON_SET_LOCK,
UIFlowWndPlay_TipsIconLock_MAX
}UIFlowWndPlay_TipsIconLock_Setting;

extern VControl UIFlowWndPlay_TipsIconPlayCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_TipsIconPlay_ICON_DIR_R,
UIFlowWndPlay_TipsIconPlay_ICON_PAUSE,
UIFlowWndPlay_TipsIconPlay_MAX
}UIFlowWndPlay_TipsIconPlay_Setting;

//---------------------UIFlowWndPlayCtrl User Export---------------------------
#endif
