//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAY_H
#define UIFLOWWNDPLAY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayCtrl;//Panel type 

extern VControl UIFlowWndPlay_StaticICN_DSCModeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_SizeCtrl;//Static type 

extern VControl UIFlowWndPlay_StatusICN_BatteryCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_FULL,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_MED,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_LOW,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_EMPTY,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_ZERO,
UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_CHARGE,
UIFlowWndPlay_StatusICN_Battery_MAX
}UIFlowWndPlay_StatusICN_Battery_Setting;

extern VControl UIFlowWndPlay_StaticTXT_FilenameCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticICN_ProtectCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_DateCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_TimeCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionPanelCtrl;//Panel type 

extern VControl UIFlowWndPlay_StaticTXT_VideoTotalTimeCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticICN_UnProtectCtrl;//Static type 

extern VControl UIFlowWndPlay_Static_SpeedCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_ReturnCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_PLAY_FF_BCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_COLN0Ctrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_DELCtrl;//Static type 

extern VControl UIFlowWndPlay_StatusIcon_PlayCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_StatusIcon_Play_ICON_DIR_R,
UIFlowWndPlay_StatusIcon_Play_ICON_PAUSE,
UIFlowWndPlay_StatusIcon_Play_MAX
}UIFlowWndPlay_StatusIcon_Play_Setting;

extern VControl UIFlowWndPlay_OptionStaticIcon_ProtectCtrl;//Static type 

extern VControl UIFlowWndPlay_Option_StaticOKCtrl;//Static type 

extern VControl UIFlowWndPlay_Option_StaticReturnCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_UPCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_DownCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_COLN1Ctrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_LockStdCtrl;//Static type 

extern VControl UIFlowWndPlay_OptionStaticIcon_PLAY_FF_FCtrl;//Static type 

extern VControl UIFlowWndPlay_StatusIcon_PowerKeyCtrl;//Status type 

typedef enum
{
UIFlowWndPlay_StatusIcon_PowerKey_ICON_POWER_OFF,
UIFlowWndPlay_StatusIcon_PowerKey_MAX
}UIFlowWndPlay_StatusIcon_PowerKey_Setting;

#endif
