//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupOption_LV3Res.c"
#include "UIMenuWndSetupOption_LV3.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupOption_LV3Ctrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPOPTION_LV3_ERROR_MSG        1
#define _UIMENUWNDSETUPOPTION_LV3_TRACE_MSG        0

#if (_UIMENUWNDSETUPOPTION_LV3_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupOption_LV3ErrMsg(...)            debug_msg ("^R UIMenuWndSetupOption_LV3: "__VA_ARGS__)
#else
#define UIMenuWndSetupOption_LV3ErrMsg(...)
#endif

#if (_UIMENUWNDSETUPOPTION_LV3_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupOption_LV3TraceMsg(...)          debug_msg ("^B UIMenuWndSetupOption_LV3: "__VA_ARGS__)
#else
#define UIMenuWndSetupOption_LV3TraceMsg(...)
#endif

//---------------------UIMenuWndSetupOption_LV3Ctrl Global Variables -----------------------------

//---------------------UIMenuWndSetupOption_LV3Ctrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupOption_LV3Ctrl Public API  ----------------------------------

//---------------------UIMenuWndSetupOption_LV3Ctrl Private API  ---------------------------------
//---------------------UIMenuWndSetupOption_LV3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupOption_LV3)
CTRL_LIST_ITEM(UIMenuWndSetupOption_LV3_Title)
CTRL_LIST_ITEM(UIMenuWndSetupOption_LV3_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupOption_LV3_PageNum)
CTRL_LIST_END

//----------------------UIMenuWndSetupOption_LV3Ctrl Event---------------------------
INT32 UIMenuWndSetupOption_LV3_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupOption_LV3_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupOption_LV3_OnKeyLeft(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupOption_LV3)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupOption_LV3_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupOption_LV3_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupOption_LV3_OnKeyLeft)
EVENT_END

UINT32 FunctionSwitch_StrTab[]=
{
    STRID_OFF,
    STRID_ON,
};

static UINT8 g_Option_Sel = 0;
static UINT8 g_PageNumBuf[8];

void UIMenuWndSetupOption_LV3_Tex_ShowInit(UINT32 ItemId,UINT32 SelOption)
{
    INT32   i;

    UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, FALSE);

    switch (ItemId)
    {
    case IDM_MOVIE_ADAS:
        switch (SelOption)
        {
        case MOVIE_LDWS:
            //DBG_DUMP("\r\ncase MOVIE_LDWS !!!!, SysGetFlag(FL_MOVIE_LDWS) = %d\r\n", SysGetFlag(FL_MOVIE_LDWS));
            g_Option_Sel = SysGetFlag(FL_MOVIE_LDWS);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_MOVIE_LDWS));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_LDWS);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < MOVIE_LDWS_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = MOVIE_LDWS_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

        case MOVIE_FCW:
            //DBG_DUMP("\r\ncase MOVIE_FCW !!!!, SysGetFlag(FL_MOVIE_FCW) = %d\r\n", SysGetFlag(FL_MOVIE_FCW));
            g_Option_Sel = SysGetFlag(FL_MOVIE_FCW);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_MOVIE_FCW));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_FCW);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < MOVIE_FCW_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = MOVIE_FCW_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

        case MOVIE_SNG:
            //DBG_DUMP("\r\ncase MOVIE_SNG !!!!, SysGetFlag(FL_SNG) = %d\r\n", SysGetFlag(FL_SNG));
            g_Option_Sel = SysGetFlag(FL_SNG);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_SNG));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_SNG);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < FUNCTION_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = FUNCTION_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

        case MOVIE_PCW:
            //DBG_DUMP("\r\ncase MOVIE_PCW !!!!, SysGetFlag(FL_PCW) = %d\r\n", SysGetFlag(FL_PCW));
            g_Option_Sel = SysGetFlag(FL_PCW);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_PCW));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_PCW);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < FUNCTION_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = FUNCTION_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

        case MOVIE_RCW:
            //DBG_DUMP("\r\ncase MOVIE_RCW !!!!, SysGetFlag(FL_RCW) = %d\r\n", SysGetFlag(FL_RCW));
            g_Option_Sel = SysGetFlag(FL_RCW);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_RCW));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_RCW);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < FUNCTION_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = FUNCTION_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

        case MOVIE_LCAWS:
            //DBG_DUMP("\r\ncase MOVIE_RCW !!!!, SysGetFlag(FL_RCW) = %d\r\n", SysGetFlag(FL_RCW));
            g_Option_Sel = SysGetFlag(FL_ADAS_LCAWS);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_ADAS_LCAWS));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_LCWS);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < FUNCTION_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = FUNCTION_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

		case MOVIE_VIRTUAL_BUMPER:
            //DBG_DUMP("\r\ncase MOVIE_VIRTUAL_BUMPER !!!!, SysGetFlag(FL_ADAS_VIRTUAL_BUMPER) = %d\r\n", SysGetFlag(FL_ADAS_VIRTUAL_BUMPER));
            g_Option_Sel = SysGetFlag(FL_ADAS_VIRTUAL_BUMPER);
            UxMenu_SetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM, SysGetFlag(FL_ADAS_VIRTUAL_BUMPER));
            UxStatic_SetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE, STRID_VIRTUAL_BUMPER);
            UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_TitleCtrl, TRUE);
            for (i = 0; i < FUNCTION_ID_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  FunctionSwitch_StrTab[i]);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
            }
            for (i = FUNCTION_ID_MAX; i < UIMenuWndSetupOption_LV3_Menu_MAX; i ++)
            {
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STRID,  0);
                UxMenu_SetItemData(&UIMenuWndSetupOption_LV3_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
            }
            break;

        default:
            break;
        }
        break;
    
    }
    UxCtrl_SetDirty(&UIMenuWndSetupOption_LV3Ctrl, TRUE);
}

void UIMenuWndSetupOption_LV3_CalcPageInfo(VControl *pCtrl,UINT32 Sel)
{
    UINT32  i, uiItem, uiCurrItem, uiTotalItem, uiTotalItemOri;
    UINT32  uiItemPerPage, uiCurrPage, uiTotalPage;

    uiItem = UxMenu_GetData(pCtrl, MNU_CURITM);          // current item number in menu (include disabled items)
    uiItemPerPage = UxMenu_GetData(pCtrl, MNU_PAGEITEM); // items per page
    uiTotalItemOri = UxMenu_GetData(pCtrl, MNU_TOTITM);  // total item number

    // check total item number and current item number (skip disabled items)
    uiCurrItem = 0;
    uiTotalItem = 0;
    for (i = 0; i < uiTotalItemOri; i++) {
        if (UxMenu_GetItemData(pCtrl, i, MNUITM_STATUS) == STATUS_ENABLE) {
            uiTotalItem++;
            if (i < uiItem)
                uiCurrItem++;
        }
    }

    uiCurrPage = (uiCurrItem / uiItemPerPage) + 1;
    uiTotalPage = ((uiTotalItem % uiItemPerPage) == 0) ? (uiTotalItem / uiItemPerPage) : (uiTotalItem / uiItemPerPage + 1);

    sprintf((char *)g_PageNumBuf, "%02d/%02d", uiCurrPage, uiTotalPage);
    UxStatic_SetData(&UIMenuWndSetupOption_LV3_PageNumCtrl, STATIC_VALUE, Txt_Pointer(g_PageNumBuf));
    UxCtrl_SetShow(&UIMenuWndSetupOption_LV3_PageNumCtrl, TRUE);
    UxCtrl_SetDirty(&UIMenuWndSetupOption_LV3_PageNumCtrl, TRUE);
}

INT32 UIMenuWndSetupOption_LV3_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UIMenuWndSetupOption_LV3_Tex_ShowInit(paramArray[0],paramArray[1]);
    UIMenuWndSetupOption_LV3_CalcPageInfo(&UIMenuWndSetupOption_LV3_MenuCtrl, g_Option_Sel);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupOption_LV3_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupOption_LV3_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupOption_LV3Ctrl,0);
        break;
    }
    return NVTEVT_CONSUME;
}


//----------------------UIMenuWndSetupOption_LV3_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupOption_LV3_Title)
EVENT_END

//---------------------UIMenuWndSetupOption_LV3_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupOption_LV3_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupOption_LV3_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupOption_LV3_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupOption_LV3_Panel)
EVENT_END

//----------------------UIMenuWndSetupOption_LV3_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupOption_LV3_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupOption_LV3_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupOption_LV3_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupOption_LV3_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupOption_LV3_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupOption_LV3_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupOption_LV3_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupOption_LV3_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        UIMenuWndSetupOption_LV3_CalcPageInfo(&MenuCommonOption_MenuCtrl, g_Option_Sel);
        break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupOption_LV3_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        UIMenuWndSetupOption_LV3_CalcPageInfo(&MenuCommonOption_MenuCtrl, g_Option_Sel);
        break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupOption_LV3_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;
    //UINT32  uiSelOption = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        g_Option_Sel = UxMenu_GetData(&UIMenuWndSetupOption_LV3_MenuCtrl, MNU_CURITM); // selected option
        UINT32 titleid = UxStatic_GetData(&UIMenuWndSetupOption_LV3_TitleCtrl, STATIC_VALUE);
        switch(titleid)
        {
        case STRID_LDWS:
            SysSetFlag(FL_MOVIE_LDWS, g_Option_Sel);
            break;
        case STRID_FCW:
            SysSetFlag(FL_MOVIE_FCW, g_Option_Sel);
            break;
		case STRID_SNG:
			SysSetFlag(FL_SNG, g_Option_Sel);
			break;
		case STRID_PCW:
			SysSetFlag(FL_PCW, g_Option_Sel);
			break;
		case STRID_RCW:
			SysSetFlag(FL_RCW, g_Option_Sel);
			break;
		case STRID_LCWS:
			SysSetFlag(FL_ADAS_LCAWS, g_Option_Sel);
			break;
		case STRID_VIRTUAL_BUMPER:
			SysSetFlag(FL_ADAS_VIRTUAL_BUMPER, g_Option_Sel);
			break;
        }
		UIMenuWndSetupOption_LV3_CalcPageInfo(&MenuCommonOption_MenuCtrl, g_Option_Sel);
        UxCtrl_SetDirty(&UIMenuWndSetupOption_LV3Ctrl, TRUE);
        Ux_CloseWindow(&UIMenuWndSetupOption_LV3Ctrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupOption_LV3_PageNumCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupOption_LV3_PageNum)
EVENT_END

