//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupHDRTimeRes.c"
#include "UIWnd/UIFlow.h"
#include "UIWnd/SPORTCAM/UIInfo/UICfgDefault.h"
typedef enum {
    UI_HDRTIME_IDX_HR0,
    UI_HDRTIME_IDX_MIN0,
    UI_HDRTIME_IDX_HR1,
    UI_HDRTIME_IDX_MIN1,
} _UI_HDRTIME_IDX_;

//---------------------UIMenuWndSetupHDRTimeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupHDRTime)
CTRL_LIST_ITEM(UIMenuWndSetupHDRTime_Tab)
CTRL_LIST_END

//----------------------UIMenuWndSetupHDRTimeCtrl Event---------------------------
INT32 UIMenuWndSetupHDRTime_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupHDRTime)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupHDRTime_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupHDRTime_OnClose)
//EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupHDRTime_OnKeyEnter)
//EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupHDRTime_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupHDRTime_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupHDRTime_OnKeyShutter2)
EVENT_END

static UINT32 g_hour0 = 0;
static UINT32 g_min0 = 0;
static UINT32 g_hour1 = 0;
static UINT32 g_min1 = 0;
static char   itemHR0_Buf[32] = "00";
static char   itemMIN0_Buf[32] = "00";
static char   itemHR1_Buf[32] = "00";
static char   itemMIN1_Buf[32] = "00";
static char   itemOther0_Buf[32] = ":";
static UINT32 g_time_start = DEFAULT_TIME_START;
static UINT32 g_time_stop = DEFAULT_TIME_STOP;

static void UIMenuWndSetupHDRTime_UpdateInfo(void)
{
    snprintf(itemHR0_Buf, 32, "%02ld", g_hour0);
    snprintf(itemMIN0_Buf, 32, "%02ld", g_min0);
    snprintf(itemHR1_Buf, 32, "%02ld", g_hour1);
    snprintf(itemMIN1_Buf, 32, "%02ld", g_min1);

    UxButton_SetItemData(&UIMenuWndSetupHDRTime_HR0Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemHR0_Buf));
    UxButton_SetItemData(&UIMenuWndSetupHDRTime_MIN0Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemMIN0_Buf));
    UxButton_SetItemData(&UIMenuWndSetupHDRTime_HR1Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemHR1_Buf));
    UxButton_SetItemData(&UIMenuWndSetupHDRTime_MIN1Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemMIN1_Buf));
    UxStatic_SetData(&UIMenuWndSetupHDRTime_VALUE_Other0Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndSetupHDRTime_VALUE_Other1Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
}

INT32 UIMenuWndSetupHDRTime_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_time_start = SysGetFlag(FL_TIME_START);
    g_time_stop = SysGetFlag(FL_TIME_STOP);

    g_hour0 = g_time_start/100;
    g_min0 = g_time_start%100;
    g_hour1 = g_time_stop/100;
    g_min1 = g_time_stop%100;
    //debug_msg("*** g_hour0= %d, g_min0= %d, g_hour1= %d, g_min1= %d ***\r\n", g_hour0, g_min0, g_hour1, g_min1)

    UxTab_SetData(&UIMenuWndSetupHDRTime_TabCtrl, TAB_FOCUS, 0);

    UIMenuWndSetupHDRTime_UpdateInfo();
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_time_start = g_hour0*100 + g_min0;
    g_time_stop = g_hour1*100 + g_min1;
    SysSetFlag(FL_TIME_START, g_time_start);
    SysSetFlag(FL_TIME_STOP, g_time_stop);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupHDRTime_TabCtrl Event---------------------------
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupHDRTime_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupHDRTime_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupHDRTime_Tab_OnKeyDown)
//EVENT_ITEM(NVTEVT_KEY_SELECT,UIMenuWndSetupHDRTime_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupHDRTime_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupHDRTime_Tab_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupHDRTime_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        switch (UxTab_GetData(&UIMenuWndSetupHDRTime_TabCtrl, TAB_FOCUS)) {
        case UI_HDRTIME_IDX_HR0:
            if (g_hour0 == 11) {
                g_hour0 = 0;
            } else {
                g_hour0++;
            }
            break;
        case UI_HDRTIME_IDX_MIN0:
            if (g_min0 == 59) {
                g_min0 = 0;
            } else {
                g_min0++;
            }
            break;
        case UI_HDRTIME_IDX_HR1:
            if (g_hour1 == 23) {
                g_hour1 = 12;
            } else {
                g_hour1++;
            }
            break;
        case UI_HDRTIME_IDX_MIN1:
            if (g_min1 == 59) {
                g_min1 = 0;
            } else {
                g_min1++;
            }
            break;
        }

        UIMenuWndSetupHDRTime_UpdateInfo();
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        switch (UxTab_GetData(&UIMenuWndSetupHDRTime_TabCtrl, TAB_FOCUS)) {
        case UI_HDRTIME_IDX_HR0:
            if (g_hour0 == 0) {
                g_hour0 = 11;
            } else {
                g_hour0--;
            }
            break;
        case UI_HDRTIME_IDX_MIN0:
            if (g_min0 == 0) {
                g_min0 = 59;
            } else {
                g_min0--;
            }
            break;
        case UI_HDRTIME_IDX_HR1:
            if (g_hour1 == 12) {
                g_hour1 = 23;
            } else {
                g_hour1--;
            }
            break;
        case UI_HDRTIME_IDX_MIN1:
            if (g_min1 == 0) {
                g_min1 = 59;
            } else {
                g_min1--;
            }
            break;
        }

        UIMenuWndSetupHDRTime_UpdateInfo();
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        /*
        g_time_start = g_hour0*100 + g_min0;
        g_time_stop = g_hour1*100 + g_min1;
        SysSetFlag(FL_TIME_START, g_time_start);
        SysSetFlag(FL_TIME_STOP, g_time_stop);
        */
        Ux_CloseWindow(&UIMenuWndSetupHDRTimeCtrl,0); // close whole tab menu
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        switch (UxTab_GetData(&UIMenuWndSetupHDRTime_TabCtrl, TAB_FOCUS)) {
        case UI_HDRTIME_IDX_MIN1:
            UxTab_SetData(&UIMenuWndSetupHDRTime_TabCtrl, TAB_FOCUS, 0);
            break;
        default:
            Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
            break;
        }

        UIMenuWndSetupHDRTime_UpdateInfo();
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupHDRTime_Tab_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIMenuWndSetupHDRTime_Tab_OnKeyRight(pCtrl,paramNum,paramArray);
}
//----------------------UIMenuWndSetupHDRTime_HR0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_HR0)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_MIN0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_MIN0)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_HR1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_HR1)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_MIN1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_MIN1)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_Tab_VALUECtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_Tab_VALUE)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_VALUE_Other0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_VALUE_Other0)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_VALUE_Other1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_VALUE_Other1)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_VALUE_Other2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_VALUE_Other2)
EVENT_END

//----------------------UIMenuWndSetupHDRTime_VALUE_Other3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupHDRTime_VALUE_Other3)
EVENT_END

