//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFORMATQUICKCONFIRM_H
#define UIMENUWNDSETUPFORMATQUICKCONFIRM_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFormatQuickConfirmCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndSetupFormatQuickConfirm_List_Text_STRID_CANCEL,
UIMenuWndSetupFormatQuickConfirm_List_Text_STRID_OK,
UIMenuWndSetupFormatQuickConfirm_List_Text_MAX
}UIMenuWndSetupFormatQuickConfirm_List_Text_Setting;

extern VControl UIMenuWndSetupFormatQuickConfirm_Static_TextCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TitleBarCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TitleTextCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconReturnCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconUpCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconDownCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconLUDOKCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconPowerCtrl;//Panel type 

//---------------------UIMenuWndSetupFormatQuickConfirmCtrl User Export---------------------------
#endif
