//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRESETDATETIME_H
#define UIMENUWNDPRESETDATETIME_H

#include "UIFramework.h"

extern VControl UIMenuWndPreSetDateTimeCtrl;//Panel type 

extern VControl UIMenuWndPreSetDateTime_TabCtrl;//Tab type 

typedef enum
{
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_Y,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_M,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_D,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_HR,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_MIN,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_SEC,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_Switch,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_AMPM,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_VALUE_Other0,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_VALUE_Other1,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_VALUE_Other2,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_VALUE_Other3,
UIMenuWndPreSetDateTime_Tab_UIMenuWndPreSetDateTime_YMD_VALUE_Other4,
UIMenuWndPreSetDateTime_Tab_MAX
}UIMenuWndPreSetDateTime_Tab_Setting;

extern VControl UIMenuWndPreSetDateTime_YMD_YCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_MCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_DCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_HRCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_MINCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_SECCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_SwitchCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_AMPMCtrl;//Button type 

extern VControl UIMenuWndPreSetDateTime_YMD_VALUE_Other0Ctrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_YMD_VALUE_Other1Ctrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_YMD_VALUE_Other2Ctrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_YMD_VALUE_Other3Ctrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_YMD_VALUE_Other4Ctrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_Static_TitleCtrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndPreSetDateTime_TipsIconReturnCtrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_TipsIconUpCtrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_TipsIconDownCtrl;//Static type 

extern VControl UIMenuWndPreSetDateTime_TipsIconOKCtrl;//Static type 

//---------------------UIMenuWndPreSetDateTimeCtrl User Export---------------------------
#endif
