//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupVersionRes.c"
#include "UIWnd/UIFlow.h"
#include "PrjInc.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion)
CTRL_LIST_ITEM(UIMenuSetupVersionText)
CTRL_LIST_ITEM(UIMenuSetupVersionText2)
CTRL_LIST_ITEM(UIMenuSetupVersionText3)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersionCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupVersion_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupVersion_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupVersion_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupVersion_OnKeyEnter)
//EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupVersion_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupVersion_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupVersion_OnKeyShutter2)
EVENT_END


INT32 UIMenuWndSetupVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxStatic_SetData(&UIMenuSetupVersionTextCtrl, STATIC_VALUE, Txt_Pointer(Prj_GetVersionString()));
#if defined(_NVT_ETHREARCAM_RX_)
	if(FlowMovie_IsEthCamConnectOK())
	{
    	UxStatic_SetData(&UIMenuSetupVersionText2Ctrl, STATIC_VALUE, Txt_Pointer(Prj_GetEthCamVersionString()));
	}
	else
	{
		UxCtrl_SetShow(&UIMenuSetupVersionText2Ctrl,FALSE);
	}
#else 
	UxCtrl_SetShow(&UIMenuSetupVersionText2Ctrl,FALSE);
#endif
#if defined(_GPS_EDOG_UNIQUE_SKY_)
	UxStatic_SetData(&UIMenuSetupVersionText3Ctrl, STATIC_VALUE, Txt_Pointer(GPSRec_GetEdogVersion()));
	UxCtrl_SetShow(&UIMenuSetupVersionText3Ctrl,FALSE);
#else
	UxCtrl_SetShow(&UIMenuSetupVersionText3Ctrl,FALSE);
#endif
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuSetupVersionTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText)
EVENT_END

//----------------------UIMenuSetupVersionText2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText2)
EVENT_END

//----------------------UIMenuSetupVersionText3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText3)
EVENT_END

