//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupDefaultSettingRes.c"
#include "UIWnd/UIFlow.h"

//---------------------UIMenuWndSetupDefaultSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDefaultSetting)
CTRL_LIST_ITEM(UIMenuWndSetupDefaultSetting_Static_Text)
CTRL_LIST_ITEM(UIMenuWndSetupDefaultSetting_Static_Title)
CTRL_LIST_ITEM(UIMenuWndSetupDefaultSetting_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupDefaultSettingCtrl Event---------------------------
INT32 UIMenuWndSetupDefaultSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDefaultSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupDefaultSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupDefaultSetting_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupDefaultSetting_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupDefaultSetting_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupDefaultSetting_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupDefaultSetting_OnKeyShutter2)
EVENT_END
extern void GxSystem_SWResetNOW(void);

INT32 UIMenuWndSetupDefaultSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndSetupDefaultSetting_MenuCtrl, MNU_CURITM, 1);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0)
        state = paramArray[0];

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupDefaultSettingCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupDefaultSetting_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDefaultSetting_Static_Text)
EVENT_END

//----------------------UIMenuWndSetupDefaultSetting_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDefaultSetting_Static_Title)
EVENT_END

//----------------------UIMenuWndSetupDefaultSetting_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupDefaultSetting_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDefaultSetting_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDefaultSetting_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupDefaultSetting_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupDefaultSetting_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupDefaultSetting_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupDefaultSetting_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0)
        state = paramArray[0];

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0)
        state = paramArray[0];

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDefaultSetting_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;
    INT32   ui32CurrItem = 0;

    if (paramNum > 0)
        state = paramArray[0];

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        ui32CurrItem = UxMenu_GetData(pCtrl, MNU_CURITM);
        switch (ui32CurrItem)
        {
        case UIMenuWndSetupDefaultSetting_Menu_STRID_CANCEL:  //cancel
            break;
        case UIMenuWndSetupDefaultSetting_Menu_STRID_OK:  //OK
            //debug_err(("Reser default setting\n\r"));
            UI_ResetSSIDPASSPHRASE(); //reset Wi-Fi SSID and PASSPHRASE
            Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_SYSRESET, 0);
            SysSetFlag(FL_FIRSTPOWERON, FIRSTPOWERON_TRUE);  //@Ken 140620 for first power on
            Save_MenuInfo();
            //SysExeMenuSettingFuncs();   // execute menu setting related functions
            //Ux_CloseWindow(&UIMenuWndSetupDefaultSettingCtrl, 0);
            //rtc_reset();  //reset and reset time

            Delay_DelayMs(100);
            GxSystem_SWResetNOW();//GxSystem_Reboot();
            break;
        default:
            //debug_err(("No any is selected for default setting\n\r"));
            break;
        }
        Ux_CloseWindow(&UIMenuWndSetupDefaultSettingCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}

