//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPCARNO_H
#define UIMENUWNDSETUPCARNO_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupCarNoCtrl;//Panel type 

extern VControl UIMenuWndSetupCarNo_TabCtrl;//Tab type 

typedef enum
{
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A1,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A2,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A3,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A4,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A5,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A6,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A7,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A8,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A9,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A10,
UIMenuWndSetupCarNo_Tab_UIMenuWndSetupCarNo_A11,
UIMenuWndSetupCarNo_Tab_MAX
}UIMenuWndSetupCarNo_Tab_Setting;

extern VControl UIMenuWndSetupCarNo_A1Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A2Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A3Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A4Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A5Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A6Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A7Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A8Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A9Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A10Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNo_A11Ctrl;//Button type 

#endif
