//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPADASCORDONRES_H
#define UIMENUWNDSETUPADASCORDONRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,619,239)

SHOW_ITEM_RECT(CMD_Rectangle,Rect4,0,0,619,239,16,2,0,0,0,0,0)
SHOW_MAP_BEGIN(Skin2)
SHOW_MAP_BODY(Rect4)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin2,0,0,619,239)

SHOW_ITEM_RECT(CMD_Rectangle,Rect8,0,45,460,47,16,2,3,3,0,0,0)
SHOW_ITEM_RECT(CMD_Rectangle,Rect10,228,45,232,94,16,2,3,3,0,0,0)
SHOW_MAP_BEGIN(Skin6)
SHOW_MAP_BODY(Rect8)
SHOW_MAP_BODY(Rect10)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin6,0,0,460,99)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text12,0,2,460,42,STRID_NULL,0,0,0,0,2,0,0,256,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal5)
SHOW_MAP_BODY(Skin6)
SHOW_MAP_BODY(Text12)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal5,80,65,540,164)

SHOW_MAP_BEGIN(UIMenuWdnSetupADASCheck)
SHOW_MAP_BODY(Normal5)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWdnSetupADASCheck)
CREATE_STATIC_DATA(UIMenuWdnSetupADASCheck,STRID_ADAS_CORDON_LINE)
CREATE_STATIC_CTRL(UIMenuWdnSetupADASCheck,0,80,65,540,164)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIMenuWndSetupADASCordon_Panel)
SHOW_MAP_BODY(Skin2)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndSetupADASCordon_Panel)
DECLARE_CTRL_LIST(UIMenuWndSetupADASCordon_Panel)
CREATE_CTRL(UIMenuWndSetupADASCordon_Panel,UIMenuWndSetupADASCordon_Panel,CTRL_WND,NULL,0 ,0,0,619,239)
SHOW_MAP_BEGIN(UIMenuWndSetupADASCordon)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndSetupADASCordon)
DECLARE_CTRL_LIST(UIMenuWndSetupADASCordon)
CREATE_CTRL(UIMenuWndSetupADASCordon,UIMenuWndSetupADASCordon,CTRL_WND,NULL,0 ,0,0,619,239)
#endif
