//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPGPS_H
#define UIMENUWNDSETUPGPS_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupGPSCtrl;//Panel type 

extern VControl UIMenuWndSetupGPS_PanelCtrl;//Panel type 

extern VControl GPS_Signal_1_NUMCtrl;//Static type 

extern VControl GPS_Signal_2_NUMCtrl;//Static type 

extern VControl GPS_Signal_3_NUMCtrl;//Static type 

extern VControl GPS_Signal_4_NUMCtrl;//Static type 

extern VControl GPS_Signal_5_NUMCtrl;//Static type 

extern VControl GPS_Signal_6_NUMCtrl;//Static type 

extern VControl GPS_Signal_7_NUMCtrl;//Static type 

extern VControl GPS_Signal_8_NUMCtrl;//Static type 

extern VControl GPS_Signal_9_NUMCtrl;//Static type 

extern VControl GPS_Signal_10_NUMCtrl;//Static type 

extern VControl GPS_Signal_11_NUMCtrl;//Static type 

extern VControl GPS_Signal_12_NUMCtrl;//Static type 

extern VControl GPS_Signal_1_ValCtrl;//Static type 

extern VControl GPS_Signal_2_ValCtrl;//Static type 

extern VControl GPS_Signal_3_ValCtrl;//Static type 

extern VControl GPS_Signal_4_ValCtrl;//Static type 

extern VControl GPS_Signal_5_ValCtrl;//Static type 

extern VControl GPS_Signal_6_ValCtrl;//Static type 

extern VControl GPS_Signal_7_ValCtrl;//Static type 

extern VControl GPS_Signal_8_ValCtrl;//Static type 

extern VControl GPS_Signal_9_ValCtrl;//Static type 

extern VControl GPS_Signal_10_ValCtrl;//Static type 

extern VControl GPS_Signal_11_ValCtrl;//Static type 

extern VControl GPS_Signal_12_ValCtrl;//Static type 

extern VControl GPS_Signal_Red_1Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_2Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_3Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_4Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_5Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_6Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_7Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_8Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_9Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_10Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_11Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Red_12Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_1Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_2Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_3Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_4Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_5Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_6Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_7Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_8Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_9Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_10Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_11Ctrl;//ProgressBar type 

extern VControl GPS_Signal_Green_12Ctrl;//ProgressBar type 

extern VControl GPS_Status_ICONCtrl;//Status type 

typedef enum
{
GPS_Status_ICON_ICONID_NULL,
GPS_Status_ICON_MAX
}GPS_Status_ICON_Setting;

extern VControl GPS_Status_NameCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_TipsIconPowerCtrl;//Static type 

extern VControl UIMenuWndSetupGPS_TipsIconLUDOKCtrl;//Panel type 

extern VControl UIMenuWndSetupGPS_TipsIconReturnCtrl;//Static type 

//---------------------UIMenuWndSetupGPSCtrl User Export---------------------------
#endif
