//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFORMATQUICKCONFIRM_H
#define UIMENUWNDSETUPFORMATQUICKCONFIRM_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFormatQuickConfirmCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_Static_TextCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_Static_TitleCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupFormatQuickConfirm_Menu_STRID_OK,
UIMenuWndSetupFormatQuickConfirm_Menu_STRID_CANCEL,
UIMenuWndSetupFormatQuickConfirm_Menu_MAX
}UIMenuWndSetupFormatQuickConfirm_Menu_Setting;

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconReturnCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconUpCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconDownCtrl;//Static type 

extern VControl UIMenuWndSetupFormatQuickConfirm_TipsIconOKCtrl;//Static type 

//---------------------UIMenuWndSetupFormatQuickConfirmCtrl User Export---------------------------
#endif
