//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPVERSIONRES_H
#define UIMENUWNDSETUPVERSIONRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
//#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Rect3,0,30,289,239,272,2,1,1,0,0,0)
SHOW_ITEM_RECT(CMD_Rectangle,Rect5,10,31,289,32,16,0,2,2,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Rect3)
SHOW_MAP_BODY(Rect5)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin7Rect,0,0,259,39,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin7)
SHOW_MAP_BODY(Skin7Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin7,0,0,259,39)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text9,0,0,259,39,STRID_NULL,0,0,0,0,2,1,1,0,0,16,0,0,0,0)
SHOW_MAP_BEGIN(Normal6)
SHOW_MAP_BODY(Skin7)
SHOW_MAP_BODY(Text9)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal6,30,65,289,104)

SHOW_MAP_BEGIN(UIMenuSetupVersionText)
SHOW_MAP_BODY(Normal6)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText)
CREATE_STATIC_DATA(UIMenuSetupVersionText,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText,0,30,65,289,104)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin12Rect,0,0,259,39,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin12)
SHOW_MAP_BODY(Skin12Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin12,0,0,259,39)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text14,0,0,259,39,STRID_NULL,0,0,0,0,2,1,1,0,0,16,0,0,0,0)
SHOW_MAP_BEGIN(Normal11)
SHOW_MAP_BODY(Skin12)
SHOW_MAP_BODY(Text14)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal11,30,106,289,145)

SHOW_MAP_BEGIN(UIMenuSetupVersionText2)
SHOW_MAP_BODY(Normal11)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText2)
CREATE_STATIC_DATA(UIMenuSetupVersionText2,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText2,0,30,106,289,145)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin17Rect,0,0,259,39,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin17)
SHOW_MAP_BODY(Skin17Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin17,0,0,259,39)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text19,0,0,259,39,STRID_NULL,0,0,0,0,2,1,1,0,0,16,0,0,0,0)
SHOW_MAP_BEGIN(Normal16)
SHOW_MAP_BODY(Skin17)
SHOW_MAP_BODY(Text19)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal16,30,147,289,186)

SHOW_MAP_BEGIN(UIMenuSetupVersionText3)
SHOW_MAP_BODY(Normal16)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText3)
CREATE_STATIC_DATA(UIMenuSetupVersionText3,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText3,0,30,147,289,186)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin22Rect,0,0,259,39,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin22)
SHOW_MAP_BODY(Skin22Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin22,0,0,259,39)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text24,0,0,259,39,STRID_NULL,0,0,0,0,2,1,1,0,0,16,0,0,0,0)
SHOW_MAP_BEGIN(Normal21)
SHOW_MAP_BODY(Skin22)
SHOW_MAP_BODY(Text24)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal21,30,188,289,227)

SHOW_MAP_BEGIN(UIMenuSetupVersionText4)
SHOW_MAP_BODY(Normal21)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText4)
CREATE_STATIC_DATA(UIMenuSetupVersionText4,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText4,0,30,188,289,227)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIMenuWndSetupVersion)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndSetupVersion)
DECLARE_CTRL_LIST(UIMenuWndSetupVersion)
CREATE_CTRL(UIMenuWndSetupVersion,UIMenuWndSetupVersion,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
