//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPHDRTIME_H
#define UIMENUWNDSETUPHDRTIME_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupHDRTimeCtrl;//Panel type 

extern VControl UIMenuWndSetupHDRTime_TabCtrl;//Tab type 

typedef enum
{
UIMenuWndSetupHDRTime_Tab_UIMenuWndSetupHDRTime_HR0,
UIMenuWndSetupHDRTime_Tab_UIMenuWndSetupHDRTime_MIN0,
UIMenuWndSetupHDRTime_Tab_UIMenuWndSetupHDRTime_HR1,
UIMenuWndSetupHDRTime_Tab_UIMenuWndSetupHDRTime_MIN1,
UIMenuWndSetupHDRTime_Tab_UIMenuWndSetupHDRTime_Tab_VALUE,
UIMenuWndSetupHDRTime_Tab_MAX
}UIMenuWndSetupHDRTime_Tab_Setting;

extern VControl UIMenuWndSetupHDRTime_HR0Ctrl;//Button type 

extern VControl UIMenuWndSetupHDRTime_MIN0Ctrl;//Button type 

extern VControl UIMenuWndSetupHDRTime_HR1Ctrl;//Button type 

extern VControl UIMenuWndSetupHDRTime_MIN1Ctrl;//Button type 

extern VControl UIMenuWndSetupHDRTime_Tab_VALUECtrl;//Tab type 

typedef enum
{
UIMenuWndSetupHDRTime_Tab_VALUE_UIMenuWndSetupHDRTime_VALUE_Other0,
UIMenuWndSetupHDRTime_Tab_VALUE_UIMenuWndSetupHDRTime_VALUE_Other1,
UIMenuWndSetupHDRTime_Tab_VALUE_UIMenuWndSetupHDRTime_VALUE_Other2,
UIMenuWndSetupHDRTime_Tab_VALUE_UIMenuWndSetupHDRTime_VALUE_Other3,
UIMenuWndSetupHDRTime_Tab_VALUE_MAX
}UIMenuWndSetupHDRTime_Tab_VALUE_Setting;

extern VControl UIMenuWndSetupHDRTime_VALUE_Other0Ctrl;//Static type 

extern VControl UIMenuWndSetupHDRTime_VALUE_Other1Ctrl;//Static type 

extern VControl UIMenuWndSetupHDRTime_VALUE_Other2Ctrl;//Static type 

extern VControl UIMenuWndSetupHDRTime_VALUE_Other3Ctrl;//Static type 

#endif
