//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "PrjCfg.h"
#include "UIMenuWndSetupADASCordonRes.c"
#include "UIMenuWndSetupADASCordon.h"

#define __MODULE__          UIMenuWndSetupADASCordon
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include <kwrap/debug.h>



UINT32 Curr_Cordon = 0;

Ux_RECT Rect_LOW  = {80, 100+15, 540, 189+15};
Ux_RECT Rect_MED  = {80, 100, 540, 189};
Ux_RECT Rect_HIGH = {80, 100-15, 540, 189-15};

//---------------------UIMenuWndSetupADASCordonCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupADASCordon)
CTRL_LIST_ITEM(UIMenuWndSetupADASCordon_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetupADASCordonCtrl Event---------------------------
INT32 UIMenuWndSetupADASCordon_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupADASCordon_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupADASCordon)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupADASCordon_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupADASCordon_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupADASCordon_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupADASCordon_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupADASCordon_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupADASCordon_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_UP, UIMenuWndSetupADASCordon_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupADASCordon_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupADASCordon_OnKeyEnter)
EVENT_END

///----------------------------------
void UIMenuWndSetupADASCordonIcons(UINT32 Value)
{
	UxCtrl_SetShow(&UIMenuWdnSetupADASCheckCtrl, FALSE);
	//DBG_WRN("6666666666666 %d \r\n",Value);

	switch (Value) {
	case MOVIE_CORDON_LOW:
		UxCtrl_SetPos(&UIMenuWdnSetupADASCheckCtrl, Rect_LOW);
		break;
	case MOVIE_CORDON_MED:
		UxCtrl_SetPos(&UIMenuWdnSetupADASCheckCtrl, Rect_MED);
		break;
	case MOVIE_CORDON_HIGH:
		UxCtrl_SetPos(&UIMenuWdnSetupADASCheckCtrl, Rect_HIGH);
		break;
    }
	UxCtrl_SetShow(&UIMenuWdnSetupADASCheckCtrl, TRUE);
}

INT32 UIMenuWndSetupADASCordon_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	Curr_Cordon = SysGetFlag(FL_MOVIE_ADAS_CORDON);
	UIMenuWndSetupADASCordonIcons(Curr_Cordon);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupADASCordon_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupADASCordon_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupADASCordon_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
		Ux_CloseWindow(&UIMenuWndSetupADASCordonCtrl,0); // close whole tab menu
		break;
    }

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupADASCordon_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
		SysSetFlag(FL_MOVIE_ADAS_CORDON, Curr_Cordon);
		//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_VOLUME, 1, SysGetFlag(FL_MOVIE_ADAS_CORDON));
		Save_MenuInfo(); //for no super capacitor
		Ux_CloseWindow(&UIMenuWndSetupADASCordonCtrl,0); // close whole tab menu
		break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupADASCordon_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
		Curr_Cordon++;
		if (Curr_Cordon > 2){
			Curr_Cordon = 2;
		}
		UIMenuWndSetupADASCordonIcons(Curr_Cordon);
		break;
    }

    return NVTEVT_CONSUME;

}
INT32 UIMenuWndSetupADASCordon_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
		
		if (Curr_Cordon > 0){
			Curr_Cordon--;
			//Curr_Cordon = 0;
		}
		UIMenuWndSetupADASCordonIcons(Curr_Cordon);
		break;
    }

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupADASCordon_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupADASCordon_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupADASCordon_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupADASCordon_Panel)
CTRL_LIST_ITEM(UIMenuWdnSetupADASCheck)
CTRL_LIST_END

//----------------------UIMenuWndSetupADASCordon_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupADASCordon_Panel)
EVENT_END

//----------------------UIMenuWdnSetupADASCheckCtrl Event---------------------------
EVENT_BEGIN(UIMenuWdnSetupADASCheck)
EVENT_END

