//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPVERSIONRES_H
#define UIMENUWNDSETUPVERSIONRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
//#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Rect3,53,52,602,206,272,0,5,15,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Rect3)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,619,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin5Rect,0,0,497,27,0,0,15,15,0,0,0)
SHOW_MAP_BEGIN(Skin5)
SHOW_MAP_BODY(Skin5Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin5,0,0,497,27)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text7,0,0,497,27,STRID_NULL,0,0,0,0,2,0,0,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal4)
SHOW_MAP_BODY(Skin5)
SHOW_MAP_BODY(Text7)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal4,82,82,579,109)

SHOW_MAP_BEGIN(UIMenuSetupVersionText)
SHOW_MAP_BODY(Normal4)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText)
CREATE_STATIC_DATA(UIMenuSetupVersionText,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText,0,82,82,579,109)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin10Rect,0,0,497,27,0,0,15,15,0,0,0)
SHOW_MAP_BEGIN(Skin10)
SHOW_MAP_BODY(Skin10Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin10,0,0,497,27)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text12,0,0,497,27,STRID_NULL,0,0,0,0,2,0,0,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal9)
SHOW_MAP_BODY(Skin10)
SHOW_MAP_BODY(Text12)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal9,82,112,579,139)

SHOW_MAP_BEGIN(UIMenuSetupVersionText2)
SHOW_MAP_BODY(Normal9)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText2)
CREATE_STATIC_DATA(UIMenuSetupVersionText2,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText2,0,82,112,579,139)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin15Rect,0,0,497,27,0,0,15,15,0,0,0)
SHOW_MAP_BEGIN(Skin15)
SHOW_MAP_BODY(Skin15Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin15,0,0,497,27)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text17,0,0,497,27,STRID_NULL,0,0,0,0,2,0,0,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal14)
SHOW_MAP_BODY(Skin15)
SHOW_MAP_BODY(Text17)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal14,82,142,579,169)

SHOW_MAP_BEGIN(UIMenuSetupVersionText3)
SHOW_MAP_BODY(Normal14)
SHOW_MAP_END

DECLARE_EVENT(UIMenuSetupVersionText3)
CREATE_STATIC_DATA(UIMenuSetupVersionText3,STRID_MODE)
CREATE_STATIC_CTRL(UIMenuSetupVersionText3,0,82,142,579,169)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIMenuWndSetupVersion)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndSetupVersion)
DECLARE_CTRL_LIST(UIMenuWndSetupVersion)
CREATE_CTRL(UIMenuWndSetupVersion,UIMenuWndSetupVersion,CTRL_WND,NULL,0 ,0,0,619,239)
#endif
