//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupVersionRes.c"
#include "UIWnd/UIFlow.h"
#include "PrjInc.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion)
CTRL_LIST_ITEM(UIMenuSetupVersionText)
CTRL_LIST_ITEM(UIMenuSetupVersionText2)
CTRL_LIST_ITEM(UIMenuSetupVersionText3)
CTRL_LIST_ITEM(UIMenuSetupVersionText4)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersionCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupVersion_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupVersion_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupVersion_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupVersion_OnKeyEnter)
//EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupVersion_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupVersion_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupVersion_OnKeyShutter2)
EVENT_END


INT32 UIMenuWndSetupVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    static CHAR FwVersion[32] = {0};
    static CHAR FwVersion_2[32] = {0};
    static CHAR FwBuild[32] = {0};
	#if (defined(COUNTRY_JP))	
    sprintf((char*)FwVersion, "%s_JP: %s", FW_CUSTOMER_MODEL, FW_CUSTOMER_VERSION_NUM);
	#else
    sprintf((char*)FwVersion, "%s: %s", FW_CUSTOMER_MODEL, FW_CUSTOMER_VERSION_NUM);
	#endif
    sprintf((char*)FwBuild, "Build: %04d%02d%02d", Prj_GetBuildYear(), Prj_GetBuildMonth(), Prj_GetBuildDay());
    //sprintf((char*)FwBuild, "Build: %s",Prj_GetVersionString());
    sprintf((char*)FwVersion_2, "%s", Prj_GetEthCam1VersionString());

    UxStatic_SetData(&UIMenuSetupVersionTextCtrl, STATIC_VALUE, Txt_Pointer(FwVersion));
    UxStatic_SetData(&UIMenuSetupVersionText2Ctrl, STATIC_VALUE, Txt_Pointer(FwBuild));
    UxStatic_SetData(&UIMenuSetupVersionText3Ctrl, STATIC_VALUE, Txt_Pointer(FwVersion_2));

#if (defined(_NVT_ETHREARCAM_RX_))
    if (FlowMovie_IsEthCamConnectOK()) {
        UxCtrl_SetShow(&UIMenuSetupVersionTextCtrl, TRUE);
        UxCtrl_SetShow(&UIMenuSetupVersionText2Ctrl, TRUE);
        UxCtrl_SetShow(&UIMenuSetupVersionText3Ctrl, TRUE);
    } else
#endif
    {
        UxCtrl_SetShow(&UIMenuSetupVersionTextCtrl, TRUE);
        UxCtrl_SetShow(&UIMenuSetupVersionText2Ctrl, TRUE);
        UxCtrl_SetShow(&UIMenuSetupVersionText3Ctrl, FALSE);
    }
#if (defined(COUNTRY_JP))	
	UxCtrl_SetShow(&UIMenuSetupVersionText4Ctrl, FALSE);
#else
	UxStatic_SetData(&UIMenuSetupVersionText4Ctrl, STATIC_VALUE, Txt_Pointer(GPSRec_GetEdogVersion()));
#endif
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuSetupVersionTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText)
EVENT_END

//----------------------UIMenuSetupVersionText2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText2)
EVENT_END

//----------------------UIMenuSetupVersionText3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText3)
EVENT_END

//----------------------UIMenuSetupVersionText4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText4)
EVENT_END

