//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPCUSTOMIZE_H
#define UIMENUWNDSETUPCUSTOMIZE_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupCustomizeCtrl;//Panel type 

extern VControl UIMenuWndSetupCustomize_TabCtrl;//Tab type 

typedef enum
{
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A1,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A2,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A3,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A4,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A5,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A6,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A7,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A8,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A9,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A10,
UIMenuWndSetupCustomize_Tab_UIMenuWndSetupCustomize_A11,
UIMenuWndSetupCustomize_Tab_MAX
}UIMenuWndSetupCustomize_Tab_Setting;

extern VControl UIMenuWndSetupCustomize_A1Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A2Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A3Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A4Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A5Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A6Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A7Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A8Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A9Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A10Ctrl;//Button type 

extern VControl UIMenuWndSetupCustomize_A11Ctrl;//Button type 

#endif
