//This source code is generated by UI Designer Studio.

#include <stdio.h>
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPreSetDateTimeRes.c"
#include "UIWnd/UIFlow.h"
#include "GxTime.h"
#include "comm/hwclock.h"
#if (defined(_NVT_ETHREARCAM_RX_))
#include "UIApp/Network/EthCamAppSocket.h"
#include "UIApp/Network/EthCamAppCmd.h"
#include "UIApp/Network/EthCamAppNetwork.h"
#endif
#if defined(_CPU2_LINUX_)
#include "NvtIpcAPI.h"
#endif

#define DATETIME_AMPM_ENABLE    DISABLE

#define DATETIME_MAX_YEAR          MAX_YEAR
#define DATETIME_DEFAULT_YEAR      DEF_YEAR
#define DATETIME_DEFAULT_MONTH     DEF_MONTH
#define DATETIME_DEFAULT_DAY       DEF_DAY
#define DATETIME_DEFAULT_HOUR      0
#define DATETIME_DEFAULT_MINUTE    0
#define DATETIME_DEFAULT_SECOND    0

/* (57, 53) is the parent's start (x,y). */
#define DATETIME_START_X        57
#define DATETIME_START_Y        53

#define DATETIME_SHIFT_X        20

typedef enum {
    UI_DATETIME_IDX_Y,
    UI_DATETIME_IDX_M,
    UI_DATETIME_IDX_D,
    UI_DATETIME_IDX_HR,
    UI_DATETIME_IDX_MIN,
    UI_DATETIME_IDX_SEC,
    UI_DATETIME_IDX_SWITCH
} _UI_DATETIME_IDX_;
//#NT#2010/06/01#Chris Chung -end
#if 0//(BOOT_RECOVERY_FILE==ENABLE)
extern UINT8 g_FileRecoveryFlag;
#endif
//---------------------UIMenuWndPreSetDateTimeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPreSetDateTime)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_Tab)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_Static_Title)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_TipsBar)
CTRL_LIST_END

//----------------------UIMenuWndPreSetDateTimeCtrl Event---------------------------
INT32 UIMenuWndPreSetDateTime_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_OnBatteryLow(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(UIMenuWndPreSetDateTime)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPreSetDateTime_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPreSetDateTime_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPreSetDateTime_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPreSetDateTime_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPreSetDateTime_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPreSetDateTime_OnKeyLeft)
//EVENT_ITEM(NVTEVT_BATTERY_LOW,UIMenuWndPreSetDateTime_OnBatteryLow)
EVENT_END

//#NT#2010/06/01#Chris Chung -begin
static UINT32 g_year = DATETIME_DEFAULT_YEAR, g_month = DATETIME_DEFAULT_MONTH, g_day = DATETIME_DEFAULT_DAY;
static UINT32 g_hour = DATETIME_DEFAULT_HOUR, g_min = DATETIME_DEFAULT_MINUTE, g_second = DATETIME_DEFAULT_SECOND;
static char   itemY_Buf[32] = "0000";
static char   itemM_Buf[32] = "00";
static char   itemD_Buf[32] = "00";
static char   itemHR_Buf[32] = "00";
static char   itemMIN_Buf[32] = "00";
static char   itemSEC_Buf[32] = "00";
static char   itemAMPM_Buf[32] = "AM";
static char   itemSwitch_Buf[32] = "YY";
static char   itemOther0_Buf[32] = "/";
static char   itemOther2_Buf[32] = ":";
static char   itemOther4_Buf[32] = "/MM/DD";

_ALIGNED(4) static const UINT8 DayOfMonth[2][12] = {
    // Not leap year
    {31,28,31,30,31,30,31,31,30,31,30,31},
    // Leap year
    {31,29,31,30,31,30,31,31,30,31,30,31}
};


static void UIMenuWndPreSetDateTime_UpdateInfo(void)
{
    /* rect1_x: YYYY MM DD position */
    Ux_RECT rect1_1_1 = { 96-DATETIME_START_X,  61-DATETIME_START_Y, 163-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_1_2 = {116-DATETIME_START_X,  61-DATETIME_START_Y, 163-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_2   = {173-DATETIME_START_X,  61-DATETIME_START_Y, 212-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_3   = {229-DATETIME_START_X,  61-DATETIME_START_Y, 268-DATETIME_START_X, 117-DATETIME_START_Y};
    #if (DATETIME_AMPM_ENABLE == ENABLE)
    /* rect2_x: HH:MI:SEC AM position */
    Ux_RECT rect2_1   = {116-DATETIME_START_X-DATETIME_SHIFT_X, 104-DATETIME_START_Y, 155-DATETIME_START_X-DATETIME_SHIFT_X, 160-DATETIME_START_Y};
    Ux_RECT rect2_2   = {152-DATETIME_START_X-DATETIME_SHIFT_X, 117-DATETIME_START_Y, 172-DATETIME_START_X-DATETIME_SHIFT_X, 146-DATETIME_START_Y};
    Ux_RECT rect2_3   = {173-DATETIME_START_X-DATETIME_SHIFT_X, 104-DATETIME_START_Y, 212-DATETIME_START_X-DATETIME_SHIFT_X, 160-DATETIME_START_Y};
    Ux_RECT rect2_4   = {208-DATETIME_START_X-DATETIME_SHIFT_X, 117-DATETIME_START_Y, 228-DATETIME_START_X-DATETIME_SHIFT_X, 146-DATETIME_START_Y};
    Ux_RECT rect2_5   = {229-DATETIME_START_X-DATETIME_SHIFT_X, 104-DATETIME_START_Y, 268-DATETIME_START_X-DATETIME_SHIFT_X, 160-DATETIME_START_Y};
    Ux_RECT rect2_6   = {268-DATETIME_START_X-DATETIME_SHIFT_X, 104-DATETIME_START_Y, 307-DATETIME_START_X-DATETIME_SHIFT_X, 160-DATETIME_START_Y};
    #endif

    if (g_day > DayOfMonth[timeutil_is_leap_year(g_year)][g_month - 1]) {
        g_day = DayOfMonth[timeutil_is_leap_year(g_year)][g_month - 1];
    }

    snprintf(itemY_Buf, 32, "%4ld", g_year);
    snprintf(itemM_Buf, 32, "%02ld", g_month);
    snprintf(itemD_Buf, 32, "%02ld", g_day);
    #if (DATETIME_AMPM_ENABLE == ENABLE)
    {
        if (g_hour <= 12) {
            snprintf(itemHR_Buf, 32, "%02ld", g_hour);
        } else {
            snprintf(itemHR_Buf, 32, "%02ld", g_hour-12);
        }

        if (g_hour <= 11) {
            snprintf(itemAMPM_Buf, 32, "AM");
        } else {
            snprintf(itemAMPM_Buf, 32, "PM");
        }
    }
    #else
    snprintf(itemHR_Buf, 32, "%02ld", g_hour);
    #endif
    snprintf(itemMIN_Buf, 32, "%02ld", g_min);
    snprintf(itemSEC_Buf, 32, "%02ld", g_second);

    switch (SysGetFlag(FL_DATE_FORMAT)) {
    case DATE_FORMAT_DMY:
        snprintf(itemSwitch_Buf, 32, "DD");
        snprintf(itemOther4_Buf, 32, "/MM/YY");
        {
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_DCtrl, rect1_1_2);
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_MCtrl, rect1_2);
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_YCtrl, rect1_3);
        }
        break;
    case DATE_FORMAT_MDY:
        snprintf(itemSwitch_Buf, 32, "MM");
        snprintf(itemOther4_Buf, 32, "/DD/YY");
        {
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_MCtrl, rect1_1_2);
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_DCtrl, rect1_2);
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_YCtrl, rect1_3);
        }
        break;
    case DATE_FORMAT_YMD:
        snprintf(itemSwitch_Buf, 32, "YY");
        snprintf(itemOther4_Buf, 32, "/MM/DD");
        {
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_YCtrl, rect1_1_1);
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_MCtrl, rect1_2);
            UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_DCtrl, rect1_3);
        }
        break;
    }

    #if (DATETIME_AMPM_ENABLE == ENABLE)
    UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_HRCtrl,           rect2_1);
    UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_VALUE_Other2Ctrl, rect2_2);
    UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_MINCtrl,          rect2_3);
    UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_VALUE_Other3Ctrl, rect2_4);
    UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_SECCtrl,          rect2_5);
    UxCtrl_SetPos(&UIMenuWndPreSetDateTime_YMD_AMPMCtrl,         rect2_6);
    #endif

    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_YCtrl, 0, BTNITM_STRID, Txt_Pointer(itemY_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_MCtrl, 0, BTNITM_STRID, Txt_Pointer(itemM_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_DCtrl, 0, BTNITM_STRID, Txt_Pointer(itemD_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_HRCtrl, 0, BTNITM_STRID, Txt_Pointer(itemHR_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_MINCtrl, 0, BTNITM_STRID, Txt_Pointer(itemMIN_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_SECCtrl, 0, BTNITM_STRID, Txt_Pointer(itemSEC_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_AMPMCtrl, 0, BTNITM_STRID, Txt_Pointer(itemAMPM_Buf));
    UxButton_SetItemData(&UIMenuWndPreSetDateTime_YMD_SwitchCtrl, 0, BTNITM_STRID, Txt_Pointer(itemSwitch_Buf));

    UxStatic_SetData(&UIMenuWndPreSetDateTime_YMD_VALUE_Other0Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndPreSetDateTime_YMD_VALUE_Other1Ctrl, STATIC_VALUE, Txt_Pointer(itemOther0_Buf));
    UxStatic_SetData(&UIMenuWndPreSetDateTime_YMD_VALUE_Other2Ctrl, STATIC_VALUE, Txt_Pointer(itemOther2_Buf));
    UxStatic_SetData(&UIMenuWndPreSetDateTime_YMD_VALUE_Other3Ctrl, STATIC_VALUE, Txt_Pointer(itemOther2_Buf));
    UxStatic_SetData(&UIMenuWndPreSetDateTime_YMD_VALUE_Other4Ctrl, STATIC_VALUE, Txt_Pointer(itemOther4_Buf));
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_DATEFORMAT,    1,  SysGetFlag(FL_DATE_FORMAT));
}
//#NT#2010/06/01#Chris Chung -end

static void UIMenuWndPreSetDateTime_Confirm(void)
{
    struct tm Curr_DateTime = {0};

    Curr_DateTime.tm_year = g_year;
    Curr_DateTime.tm_mon = g_month;
    Curr_DateTime.tm_mday = g_day;
    Curr_DateTime.tm_hour = g_hour;
    Curr_DateTime.tm_min = g_min;
    Curr_DateTime.tm_sec = g_second;

    GxTime_SetTime(Curr_DateTime);
    FlowMovie_BaseDaySet(g_year, g_month, g_day);
#if(defined(_NVT_ETHREARCAM_RX_))
	UINT32 i;
	for (i=0; i<ETH_REARCAM_CAPS_COUNT; i++){
		if(EthCamNet_GetEthLinkStatus(i)==ETHCAM_LINK_UP){
			//sync time
			EthCam_SendXMLCmd(i, ETHCAM_PORT_DEFAULT ,ETHCAM_CMD_SYNC_TIME, 0);
			EthCam_SendXMLData(i, (UINT8 *)&Curr_DateTime, sizeof(struct tm));
		}
	}
#endif
#if defined(_CPU2_LINUX_)//sync date to linux, jira id :CARDV_680-237
    NVTIPC_SYS_MSG  sysMsg;
    char cmd[40]={0};
    sprintf(cmd,"date -s \"%d-%d-%d %d:%d:%d\" &",g_year,g_month,g_day,g_hour,g_min,g_second);
    //debug_msg("cmd=%s\r\n",cmd);
    sysMsg.sysCmdID = NVTIPC_SYSCMD_SYSCALL_REQ;

    sysMsg.DataAddr = (UINT32)cmd;
    sysMsg.DataSize = strlen(cmd) + 1;

    if (NvtIPC_MsgSnd(NVTIPC_SYS_QUEUE_ID, NVTIPC_SENDTO_CORE2, &sysMsg, sizeof(sysMsg)) < 0) {
        debug_msg("Failed to NVTIPC_SYS_QUEUE_ID\r\n");
    }
#endif

    SysSetFlag(FL_FIRSTPOWERON, FIRSTPOWERON_FALSE);  //@Ken 140620 for first power on
    Ux_CloseWindow(&UIMenuWndPreSetDateTimeCtrl,0); // close whole tab menu
    Save_MenuInfo();
#if 0//(BOOT_RECOVERY_FILE==ENABLE)
    if(TRUE==g_FileRecoveryFlag)
    {
        GxDisplay_Set(LAYER_OSD1, LAYER_STATE_ENABLE, 0);
//        GxDisplay_Set(LAYER_OSD2, LAYER_STATE_ENABLE, 0);
        GxDisplay_Flush(LAYER_OSD1);
//        GxDisplay_Flush(LAYER_OSD2);
        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
    }
    else
#endif
    {
    	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
		Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_NULL);
		Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_MOVIE_MODE, 0);
        //Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_MOVIE_MODE, 1, DSCMODE_CHGTO_CURR);
    }
}

INT32 UIMenuWndPreSetDateTime_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2010/06/01#Chris Chung -begin
    struct tm Curr_DateTime = {0};

    Curr_DateTime.tm_year = DEF_YEAR;
    Curr_DateTime.tm_mon = DEF_MONTH;
    Curr_DateTime.tm_mday = DEF_DAY;
    Curr_DateTime.tm_hour = 0;
    Curr_DateTime.tm_min = 0;
    Curr_DateTime.tm_sec = 0;

    GxTime_SetTime(Curr_DateTime);
    FlowMovie_BaseDaySet(DEF_YEAR, DEF_MONTH, DEF_DAY);
    g_year = Curr_DateTime.tm_year;
    g_month = Curr_DateTime.tm_mon;
    g_day = Curr_DateTime.tm_mday;
    g_hour = Curr_DateTime.tm_hour;
    g_min = Curr_DateTime.tm_min;
    g_second = Curr_DateTime.tm_sec;

    switch(SysGetFlag(FL_DATE_FORMAT))
    {
    case DATE_FORMAT_DMY:
        UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, 2);
        break;
    case DATE_FORMAT_MDY:
        UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, 1);
        break;
    case DATE_FORMAT_YMD:
        UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, 0);
        break;
    }

    #if (DATETIME_AMPM_ENABLE == ENABLE)
    UxCtrl_SetShow(&UIMenuWndPreSetDateTime_YMD_AMPMCtrl, TRUE);
    #else
    UxCtrl_SetShow(&UIMenuWndPreSetDateTime_YMD_AMPMCtrl, FALSE);
    #endif

    UIMenuWndPreSetDateTime_UpdateInfo();
    //#NT#2010/06/01#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    struct tm Curr_DateTime = {0};

	Curr_DateTime.tm_year = g_year ;
	Curr_DateTime.tm_mon = g_month ;
	Curr_DateTime.tm_mday = g_day ;
	Curr_DateTime.tm_hour = g_hour ;
	Curr_DateTime.tm_min = g_min ;
	Curr_DateTime.tm_sec = g_second ;

    GxTime_SetTime(Curr_DateTime);
#if(defined(_NVT_ETHREARCAM_RX_))
	UINT32 i;
	for (i=0; i<ETH_REARCAM_CAPS_COUNT; i++){
		if(EthCamNet_GetEthLinkStatus(i)==ETHCAM_LINK_UP){
			//sync time
			EthCam_SendXMLCmd(i, ETHCAM_PORT_DEFAULT ,ETHCAM_CMD_SYNC_TIME, 0);
			EthCam_SendXMLData(i, (UINT8 *)&Curr_DateTime, sizeof(struct tm));
		}
	}
#endif
	//Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    struct tm Curr_DateTime = {0};

	Curr_DateTime.tm_year = g_year ;
	Curr_DateTime.tm_mon = g_month ;
	Curr_DateTime.tm_mday = g_day ;
	Curr_DateTime.tm_hour = g_hour ;
	Curr_DateTime.tm_min = g_min ;
	Curr_DateTime.tm_sec = g_second ;

    GxTime_SetTime(Curr_DateTime);
#if(defined(_NVT_ETHREARCAM_RX_))
	UINT32 i;
	for (i=0; i<ETH_REARCAM_CAPS_COUNT; i++){
		if(EthCamNet_GetEthLinkStatus(i)==ETHCAM_LINK_UP){
			//sync time
			EthCam_SendXMLCmd(i, ETHCAM_PORT_DEFAULT ,ETHCAM_CMD_SYNC_TIME, 0);
			EthCam_SendXMLData(i, (UINT8 *)&Curr_DateTime, sizeof(struct tm));
		}
	}

#endif

	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndPreSetDateTimeCtrl,0);
        Ux_OpenWindow(&UIMenuWndPreSetLanguageCtrl,0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_1SEC);
    return NVTEVT_CONSUME;
}

//----------------------UIMenuWndPreSetDateTime_TabCtrl Event---------------------------
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPreSetDateTime_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPreSetDateTime_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPreSetDateTime_Tab_OnKeyDown)
//EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPreSetDateTime_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPreSetDateTime_Tab_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPreSetDateTime_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        //#NT#2010/05/19#Chris Chung -begin
        switch (UxTab_GetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS)) {
        case UI_DATETIME_IDX_Y:
            if (g_year == DATETIME_MAX_YEAR) {
                g_year = DATETIME_DEFAULT_YEAR;
            } else {
                g_year++;
            }
            break;
        case UI_DATETIME_IDX_M:
            if (g_month == 12) {
                g_month = 1;
            } else {
                g_month++;
            }
            break;
        case UI_DATETIME_IDX_D:
            if(g_day == DayOfMonth[timeutil_is_leap_year(g_year)][g_month - 1]) {
                g_day = 1;
            } else {
                g_day++;
            }
            break;
        case UI_DATETIME_IDX_HR:
            if (g_hour == 23) {
                g_hour = 0;
            } else {
                g_hour++;
            }
            break;
        case UI_DATETIME_IDX_MIN:
            if (g_min == 59) {
                g_min = 0;
            } else {
                g_min++;
            }
            break;
        case UI_DATETIME_IDX_SEC:
            if (g_second == 59) {
                g_second = 0;
            } else {
                g_second++;
            }
            break;
        case UI_DATETIME_IDX_SWITCH:
            switch (SysGetFlag(FL_DATE_FORMAT)) {
            case DATE_FORMAT_DMY:
                SysSetFlag(FL_DATE_FORMAT, DATE_FORMAT_MDY);
                break;
            case DATE_FORMAT_MDY:
                SysSetFlag(FL_DATE_FORMAT, DATE_FORMAT_YMD);
                break;
            case DATE_FORMAT_YMD:
            default:
                SysSetFlag(FL_DATE_FORMAT, DATE_FORMAT_DMY);
                break;
            }
            break;
        }

        UIMenuWndPreSetDateTime_UpdateInfo();
        break;
    }
    //#NT#2010/05/19#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        //#NT#2010/05/19#Chris Chung -begin
        switch (UxTab_GetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS)) {
        case UI_DATETIME_IDX_Y:
            if(g_year == DATETIME_DEFAULT_YEAR) {
                g_year = DATETIME_MAX_YEAR;
            } else {
                g_year--;
            }
            break;
        case UI_DATETIME_IDX_M:
            if (g_month == 1) {
                g_month = 12;
            } else {
                g_month--;
            }
            break;
        case UI_DATETIME_IDX_D:
            if (g_day == 1) {
                g_day = DayOfMonth[timeutil_is_leap_year(g_year)][g_month - 1];
            } else {
                g_day--;
            }
            break;
        case UI_DATETIME_IDX_HR:
            if (g_hour == 0) {
                g_hour = 23;
            } else {
                g_hour--;
            }
            break;
        case UI_DATETIME_IDX_MIN:
            if (g_min == 0) {
                g_min = 59;
            } else {
                g_min--;
            }
            break;
        case UI_DATETIME_IDX_SEC:
            if (g_second == 0) {
                g_second = 59;
            } else {
                g_second--;
            }
            break;
        case UI_DATETIME_IDX_SWITCH:
            switch (SysGetFlag(FL_DATE_FORMAT)) {
            case DATE_FORMAT_DMY:
                SysSetFlag(FL_DATE_FORMAT, DATE_FORMAT_YMD);
                break;
            case DATE_FORMAT_MDY:
                SysSetFlag(FL_DATE_FORMAT, DATE_FORMAT_DMY);
                break;
            case DATE_FORMAT_YMD:
            default:
                SysSetFlag(FL_DATE_FORMAT, DATE_FORMAT_MDY);
                break;
            }
            break;
        }

        UIMenuWndPreSetDateTime_UpdateInfo();
        //#NT#2010/05/19#Chris Chung -end
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:

        //#NT#2010/05/19#Chris Chung -begin
        switch (SysGetFlag(FL_DATE_FORMAT)) {
        case DATE_FORMAT_DMY:
            switch (UxTab_GetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS)) {
            case UI_DATETIME_IDX_Y:
                UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_HR);
                break;
            case UI_DATETIME_IDX_M:
                UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_Y);
                break;
            case UI_DATETIME_IDX_D:
                UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_M);
                break;
            case UI_DATETIME_IDX_SWITCH:
                // UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_D);
                UIMenuWndPreSetDateTime_Confirm();
                break;
            default:
                Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
            }
            break;
        case DATE_FORMAT_MDY:
            switch (UxTab_GetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS)) {
            case UI_DATETIME_IDX_Y:
                UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_HR);
                break;
            case UI_DATETIME_IDX_M:
                UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_D);
                break;
            case UI_DATETIME_IDX_D:
                UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_Y);
                break;
            case UI_DATETIME_IDX_SWITCH:
                // UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_M);
                UIMenuWndPreSetDateTime_Confirm();
                break;
            default:
                Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
            }
            break;
        case DATE_FORMAT_YMD:
            switch(UxTab_GetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS))
            {
            case UI_DATETIME_IDX_SWITCH:
                //UxTab_SetData(&UIMenuWndPreSetDateTime_TabCtrl, TAB_FOCUS, UI_DATETIME_IDX_Y);	rtc_setDate(g_year, g_month, g_day);
                UIMenuWndPreSetDateTime_Confirm();
                break;
            default:
                Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
            }
        }
        UIMenuWndPreSetDateTime_UpdateInfo();
        break;
    }
    //#NT#2010/05/19#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0)
        state = paramArray[0];

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        return UIMenuWndPreSetDateTime_Tab_OnKeyRight(pCtrl,paramNum,paramArray);
        break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndPreSetDateTime_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0)
        state = paramArray[0];

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        UIMenuWndPreSetDateTime_Confirm();
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetDateTime_Tab_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    // the same behavior as RIGHT key!
    return UIMenuWndPreSetDateTime_Tab_OnKeyRight(pCtrl,paramNum,paramArray);
}

//----------------------UIMenuWndPreSetDateTime_YMD_YCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_Y)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_MCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_M)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_DCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_D)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_HRCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_HR)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_MINCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_MIN)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_SECCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_SEC)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_SwitchCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_Switch)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_AMPMCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_AMPM)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_VALUE_Other0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_VALUE_Other0)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_VALUE_Other1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_VALUE_Other1)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_VALUE_Other2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_VALUE_Other2)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_VALUE_Other3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_VALUE_Other3)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_YMD_VALUE_Other4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_YMD_VALUE_Other4)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_Static_Title)
EVENT_END

//---------------------UIMenuWndPreSetDateTime_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPreSetDateTime_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_TipsIconReturn)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_TipsIconUp)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_TipsIconDown)
CTRL_LIST_ITEM(UIMenuWndPreSetDateTime_TipsIconOK)
CTRL_LIST_END

//----------------------UIMenuWndPreSetDateTime_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_TipsBar)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_TipsIconReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_TipsIconReturn)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_TipsIconUpCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_TipsIconUp)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_TipsIconDownCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_TipsIconDown)
EVENT_END

//----------------------UIMenuWndPreSetDateTime_TipsIconOKCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetDateTime_TipsIconOK)
EVENT_END

