//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPADASCORDON_H
#define UIMENUWNDSETUPADASCORDON_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupADASCordonCtrl;//Panel type 

extern VControl UIMenuWndSetupADASCordon_PanelCtrl;//Panel type 

extern VControl UIMenuWdnSetupADASCheckCtrl;//Static type 

//---------------------UIMenuWndSetupADASCordonCtrl User Export---------------------------
#endif
