//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRESETLANGUAGE_H
#define UIMENUWNDPRESETLANGUAGE_H

#include "UIFramework.h"

extern VControl UIMenuWndPreSetLanguageCtrl;//Panel type 

extern VControl UIMenuWndPreSetLanguage_Static_TitleCtrl;//Static type 

extern VControl UIMenuWndPreSetLangeage_Static_PageNumCtrl;//Static type 

extern VControl UIMenuWndPreSetLanguage_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPreSetLanguage_Menu_STRID_A0,
UIMenuWndPreSetLanguage_Menu_STRID_A1,
UIMenuWndPreSetLanguage_Menu_STRID_A2,
UIMenuWndPreSetLanguage_Menu_STRID_A3,
UIMenuWndPreSetLanguage_Menu_STRID_A4,
UIMenuWndPreSetLanguage_Menu_STRID_A5,
UIMenuWndPreSetLanguage_Menu_STRID_A6,
UIMenuWndPreSetLanguage_Menu_STRID_A7,
UIMenuWndPreSetLanguage_Menu_STRID_A8,
UIMenuWndPreSetLanguage_Menu_STRID_A9,
UIMenuWndPreSetLanguage_Menu_STRID_B0,
UIMenuWndPreSetLanguage_Menu_STRID_B1,
UIMenuWndPreSetLanguage_Menu_STRID_B2,
UIMenuWndPreSetLanguage_Menu_STRID_B3,
UIMenuWndPreSetLanguage_Menu_MAX
}UIMenuWndPreSetLanguage_Menu_Setting;

extern VControl UIMenuWndPreSetLanguage_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndPreSetLanguage_TipsIconReturnCtrl;//Static type 

extern VControl UIMenuWndPreSetLanguage_TipsIconUpCtrl;//Panel type 

extern VControl UIMenuWndPreSetLanguage_TipsIconDownCtrl;//Panel type 

extern VControl UIMenuWndPreSetLanguage_TipsIconOKCtrl;//Panel type 

extern VControl UIMenuWndPreSetLanguage_TipsIconPowerCtrl;//Static type 

//---------------------UIMenuWndPreSetLanguageCtrl User Export---------------------------
#endif
