//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupCarNoRes.c"
#include "UIMenuWndSetupCarNo.h"
#include "UIWnd/SPORTCAM/UIMenu/UIMenuCommon/MenuCommonItem.h"
#include "UIWnd/UIFlow.h"
//#include "Utility.h"
#include <kwrap/debug.h>

typedef enum {
    UI_CARNO_IDX_A1,
    UI_CARNO_IDX_A2,
    UI_CARNO_IDX_A3,
    UI_CARNO_IDX_A4,
    UI_CARNO_IDX_A5,
    UI_CARNO_IDX_A6,
    UI_CARNO_IDX_A7,
    UI_CARNO_IDX_A8,
    UI_CARNO_IDX_A9,
    UI_CARNO_IDX_A10,
    UI_CARNO_IDX_A11,
} _UI_CARNO_IDX_;

static UINT32 g_A1=0,g_A2=0,g_A3=0,g_A4=0,g_A5=0,g_A6=0,g_A7=0,g_A8=0,g_A9=0,g_A10=0,g_A11=0;
static char   itemA1_Buf[2] = "0";
static char   itemA2_Buf[2] = "0";
static char   itemA3_Buf[2] = "0";
static char   itemA4_Buf[2] = "0";
static char   itemA5_Buf[2] = "0";
static char   itemA6_Buf[2] = "0";
static char   itemA7_Buf[2] = "0";
static char   itemA8_Buf[2] = "0";
static char   itemA9_Buf[2] = "0";
static char   itemA10_Buf[2] = "0";
static char   itemA11_Buf[2] = "0";

char  CarNo_Buf[13] = "           ";

#define CARNO_MAX       	38//35
#define CARNO_MIN   		0

void UIMenuWndSetupCarNo_DeCodeNum(void);
static void UIMenuWndSetupCarNo_UpdateInfo(void);

//---------------------UIMenuWndSetupCarNoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCarNo)
CTRL_LIST_ITEM(UIMenuWndSetupCarNo_Tab)
CTRL_LIST_END

//----------------------UIMenuWndSetupCarNoCtrl Event---------------------------
INT32 UIMenuWndSetupCarNo_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCarNo)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupCarNo_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupCarNo_OnClose)
//EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupCarNo_OnKeyEnter)
//EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupCarNo_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupCarNo_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupCarNo_OnKeyShutter2)
EVENT_END


INT32 UIMenuWndSetupCarNo_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, 0);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    UIMenuWndSetupCarNo_DeCodeNum();

    UIMenuWndSetupCarNo_UpdateInfo();

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNo_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNo_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNo_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupCarNoCtrl,0); // close whole tab menu
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNo_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNo_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
UINT32 UIMenuWndSetupCarNo_DeCodeDataUpdate(UINT32 Data)
{
    UINT32 temp;

    if(Data == ' ')
        temp = 36;//36;//' '
    //else if(Data == '&')
        //temp = CARNO_MAX-2;//'&'
    else if(Data == '-')
        temp = CARNO_MAX - 1;//'-'
    else if(Data == '.')
        temp = CARNO_MAX;//'.'
    else if((Data < 0x41) /*&& (Data > 0x2F)*/)
        temp = Data - 0x30;//'0';
    else
        temp = Data - 0x41 + 10;//'A';

    //debug_err(("UIMenuWndSetupCarNo_DeCodeData=%d %d \r\n",Data,temp));

    return  temp;
}
void UIMenuWndSetupCarNo_DeCodeNum(void)
{
    g_A1  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[0]);
    g_A2  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[1]);
    g_A3  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[2]);
    g_A4  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[3]);
    g_A5  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[4]);
    g_A6  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[5]);
    g_A7  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[6]);
    g_A8  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[7]);
    g_A9  = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[8]);
    g_A10 = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[9]);
    g_A11 = UIMenuWndSetupCarNo_DeCodeDataUpdate(CarNo_Buf[10]);
}

UINT32 UIMenuWndSetupCarNo_DataUpdate(UINT32 Data)
{
    UINT32 temp = 36;//' ';

    if(Data < 10)
    {
        temp = Data + 0x30;//'0';
    }
    else if(Data <= 35)
    {
        temp = (Data-10) + 0x41;//'A';
    }
    else if(Data == 36)
    {
        temp = ' ';//0;//' ';
    }
    /*else if(Data == CARNO_MAX-2)
    {
        temp = '&';//'&';
    }*/
    else if(Data == CARNO_MAX-1)
    {
        temp = '-';//'-';
    }
    else if(Data == CARNO_MAX)
    {
        temp = '.';//'.';
    }

    //debug_err(("UIMenuWndSetupCarNo_DataUpdate =%d %d \r\n",Data,temp));

    return  temp;
}

static void UIMenuWndSetupCarNo_UpdateInfo(void)
{
/*
    Ux_RECT rect1_1_1 = { 96-DATETIME_START_X,  61-DATETIME_START_Y, 163-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_1_2 = {116-DATETIME_START_X,  61-DATETIME_START_Y, 163-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_1_3   = {173-DATETIME_START_X,  61-DATETIME_START_Y, 212-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_1_4   = {229-DATETIME_START_X,  61-DATETIME_START_Y, 268-DATETIME_START_X, 117-DATETIME_START_Y};
    Ux_RECT rect1_1_5   = {229-DATETIME_START_X,  61-DATETIME_START_Y, 268-DATETIME_START_X, 117-DATETIME_START_Y};
*/
    snprintf(itemA1_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A1));
    snprintf(itemA2_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A2));
    snprintf(itemA3_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A3));
    snprintf(itemA4_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A4));
    snprintf(itemA5_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A5));
    snprintf(itemA6_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A6));
    snprintf(itemA7_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A7));
    snprintf(itemA8_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A8));
    snprintf(itemA9_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A9));
    snprintf(itemA10_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A10));
    snprintf(itemA11_Buf, 2, "%c",(char)UIMenuWndSetupCarNo_DataUpdate(g_A11));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A1Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA1_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A2Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA2_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A3Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA3_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A4Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA4_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A5Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA5_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A6Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA6_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A7Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA7_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A8Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA8_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A9Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA9_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A10Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA10_Buf));
    UxButton_SetItemData(&UIMenuWndSetupCarNo_A11Ctrl, 0, BTNITM_STRID, Txt_Pointer(itemA11_Buf));
}

//----------------------UIMenuWndSetupCarNo_TabCtrl Event---------------------------
INT32 UIMenuWndSetupCarNo_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNo_Tab_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCarNo_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupCarNo_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupCarNo_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupCarNo_Tab_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupCarNo_Tab_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupCarNo_Tab_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupCarNo_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        switch(UxTab_GetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS))
        {
        case UI_CARNO_IDX_A1:
            if(g_A1 == CARNO_MAX)
                g_A1 = CARNO_MIN;
            else
                g_A1++;
            break;

        case UI_CARNO_IDX_A2:
            if(g_A2 == CARNO_MAX)
                g_A2 = CARNO_MIN;
            else
                g_A2++;
            break;

        case UI_CARNO_IDX_A3:
            if(g_A3 == CARNO_MAX)
                g_A3 = CARNO_MIN;
            else
                g_A3++;
            break;

        case UI_CARNO_IDX_A4:
            if(g_A4 == CARNO_MAX)
                g_A4 = CARNO_MIN;
            else
                g_A4++;
            break;

        case UI_CARNO_IDX_A5:
            if(g_A5 == CARNO_MAX)
                g_A5 = CARNO_MIN;
            else
                g_A5++;
            break;

        case UI_CARNO_IDX_A6:
            if(g_A6 == CARNO_MAX)
                g_A6 = CARNO_MIN;
            else
                g_A6++;
            break;

        case UI_CARNO_IDX_A7:
            if(g_A7 == CARNO_MAX)
                g_A7 = CARNO_MIN;
            else
                g_A7++;
            break;

        case UI_CARNO_IDX_A8:
            if(g_A8 == CARNO_MAX)
                g_A8 = CARNO_MIN;
            else
                g_A8++;
            break;

        case UI_CARNO_IDX_A9:
            if(g_A9 == CARNO_MAX)
                g_A9 = CARNO_MIN;
            else
                g_A9++;
            break;

        case UI_CARNO_IDX_A10:
            if(g_A10 == CARNO_MAX)
                g_A10 = CARNO_MIN;
            else
                g_A10++;
            break;

        case UI_CARNO_IDX_A11:
            if(g_A11 == CARNO_MAX)
                g_A11 = CARNO_MIN;
            else
                g_A11++;
            break;
        }

        UIMenuWndSetupCarNo_UpdateInfo();
        break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupCarNo_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        switch(UxTab_GetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS))
        {
        case UI_CARNO_IDX_A1:
            if(g_A1 == CARNO_MIN)
                g_A1 = CARNO_MAX;
            else
                g_A1--;
            break;

        case UI_CARNO_IDX_A2:
            if(g_A2 == CARNO_MIN)
                g_A2 = CARNO_MAX;
            else
                g_A2--;
            break;

        case UI_CARNO_IDX_A3:
            if(g_A3 == CARNO_MIN)
                g_A3 = CARNO_MAX;
            else
                g_A3--;
            break;

        case UI_CARNO_IDX_A4:
            if(g_A4 == CARNO_MIN)
                g_A4 = CARNO_MAX;
            else
                g_A4--;
            break;

        case UI_CARNO_IDX_A5:
            if(g_A5 == CARNO_MIN)
                g_A5 = CARNO_MAX;
            else
                g_A5--;
            break;

        case UI_CARNO_IDX_A6:
            if(g_A6 == CARNO_MIN)
                g_A6 = CARNO_MAX;
            else
                g_A6--;
            break;

        case UI_CARNO_IDX_A7:
            if(g_A7 == CARNO_MIN)
                g_A7 = CARNO_MAX;
            else
                g_A7--;
            break;

        case UI_CARNO_IDX_A8:
            if(g_A8 == CARNO_MIN)
                g_A8 = CARNO_MAX;
            else
                g_A8--;
            break;

        case UI_CARNO_IDX_A9:
            if(g_A9 == CARNO_MIN)
                g_A9 = CARNO_MAX;
            else
                g_A9--;
            break;

        case UI_CARNO_IDX_A10:
            if(g_A10 == CARNO_MIN)
                g_A10 = CARNO_MAX;
            else
                g_A10--;
            break;

        case UI_CARNO_IDX_A11:
            if(g_A11 == CARNO_MIN)
                g_A11 = CARNO_MAX;
            else
                g_A11--;
            break;
        }

        UIMenuWndSetupCarNo_UpdateInfo();
        break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupCarNo_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNo_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        switch (UxTab_GetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS))
        {
        case UI_CARNO_IDX_A1:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A2);
            break;
        case UI_CARNO_IDX_A2:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A3);
            break;
        case UI_CARNO_IDX_A3:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A4);
            break;
        case UI_CARNO_IDX_A4:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A5);
            break;
        case UI_CARNO_IDX_A5:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A6);
            break;
        case UI_CARNO_IDX_A6:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A7);
            break;
        case UI_CARNO_IDX_A7:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A8);
            break;
        case UI_CARNO_IDX_A8:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A9);
            break;
        case UI_CARNO_IDX_A9:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A10);
            break;
        case UI_CARNO_IDX_A10:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A11);
            break;
        case UI_CARNO_IDX_A11:
            UxTab_SetData(&UIMenuWndSetupCarNo_TabCtrl, TAB_FOCUS, UI_CARNO_IDX_A1);
            break;
        default:
            Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        }
        UIMenuWndSetupCarNo_UpdateInfo();
        break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupCarNo_Tab_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        CarNo_Buf[0]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A1);
        CarNo_Buf[1]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A2);
        CarNo_Buf[2]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A3);
        CarNo_Buf[3]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A4);
        CarNo_Buf[4]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A5);
        CarNo_Buf[5]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A6);
        CarNo_Buf[6]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A7);
        CarNo_Buf[7]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A8);
        CarNo_Buf[8]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A9);
        CarNo_Buf[9]  = (char)UIMenuWndSetupCarNo_DataUpdate(g_A10);
        CarNo_Buf[10] = (char)UIMenuWndSetupCarNo_DataUpdate(g_A11);
        CarNo_Buf[11] = '\0';

        //write CarNo to txt file
        UI_WriteCarNoToFile();

        Ux_CloseWindow(&UIMenuWndSetupCarNoCtrl,0); // close whole tab menu
        break;
    }
    return NVTEVT_CONSUME;
}

//----------------------UIMenuWndSetupCarNo_A1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A1)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A2)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A3)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A4)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A5Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A5)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A6Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A6)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A7Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A7)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A8Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A8)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A9Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A9)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A10Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A10)
EVENT_END

//----------------------UIMenuWndSetupCarNo_A11Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNo_A11)
EVENT_END

