//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupGPSRes.c"
#include "UIMenuWndSetupGPS.h"
#include "NVTToolCommand.h"
#include "UIWnd/SPORTCAM/UIInfo/UICfgDefault.h"
#include <kwrap/debug.h>

//---------------------UIMenuWndSetupGPSCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupGPS)
CTRL_LIST_ITEM(GPS_Signal_2_NUM)
CTRL_LIST_ITEM(GPS_Status_Name)
CTRL_LIST_ITEM(GPS_Status_ICON)
CTRL_LIST_ITEM(GPS_Signal_3_NUM)
CTRL_LIST_ITEM(GPS_Signal_4_NUM)
CTRL_LIST_ITEM(GPS_Signal_5_NUM)
CTRL_LIST_ITEM(GPS_Signal_6_NUM)
CTRL_LIST_ITEM(GPS_Signal_7_NUM)
CTRL_LIST_ITEM(GPS_Signal_8_NUM)
CTRL_LIST_ITEM(GPS_Signal_9_NUM)
CTRL_LIST_ITEM(GPS_Signal_10_NUM)
CTRL_LIST_ITEM(GPS_Signal_11_NUM)
CTRL_LIST_ITEM(GPS_Signal_2_Val)
CTRL_LIST_ITEM(GPS_Signal_3_Val)
CTRL_LIST_ITEM(GPS_Signal_4_Val)
CTRL_LIST_ITEM(GPS_Signal_5_Val)
CTRL_LIST_ITEM(GPS_Signal_6_Val)
CTRL_LIST_ITEM(GPS_Signal_7_Val)
CTRL_LIST_ITEM(GPS_Signal_8_Val)
CTRL_LIST_ITEM(GPS_Signal_9_Val)
CTRL_LIST_ITEM(GPS_Signal_10_Val)
CTRL_LIST_ITEM(GPS_Signal_11_Val)
CTRL_LIST_ITEM(GPS_Signal_Green_2)
CTRL_LIST_ITEM(GPS_Signal_Green_3)
CTRL_LIST_ITEM(GPS_Signal_Green_4)
CTRL_LIST_ITEM(GPS_Signal_Green_5)
CTRL_LIST_ITEM(GPS_Signal_Green_6)
CTRL_LIST_ITEM(GPS_Signal_Green_7)
CTRL_LIST_ITEM(GPS_Signal_Green_8)
CTRL_LIST_ITEM(GPS_Signal_Green_9)
CTRL_LIST_ITEM(GPS_Signal_Green_10)
CTRL_LIST_ITEM(GPS_Signal_Green_11)
CTRL_LIST_ITEM(GPS_Signal_Red_2)
CTRL_LIST_ITEM(GPS_Signal_Red_3)
CTRL_LIST_ITEM(GPS_Signal_Red_4)
CTRL_LIST_ITEM(GPS_Signal_Red_5)
CTRL_LIST_ITEM(GPS_Signal_Red_6)
CTRL_LIST_ITEM(GPS_Signal_Red_7)
CTRL_LIST_ITEM(GPS_Signal_Red_8)
CTRL_LIST_ITEM(GPS_Signal_Red_9)
CTRL_LIST_ITEM(GPS_Signal_Red_10)
CTRL_LIST_ITEM(GPS_Signal_Red_11)
CTRL_LIST_ITEM(GPS_Signal_Red_1)
CTRL_LIST_ITEM(GPS_Signal_Red_12)
CTRL_LIST_ITEM(GPS_Signal_Green_1)
CTRL_LIST_ITEM(GPS_Signal_Green_12)
CTRL_LIST_ITEM(GPS_Signal_12_NUM)
CTRL_LIST_ITEM(GPS_Signal_1_NUM)
CTRL_LIST_ITEM(GPS_Signal_1_Val)
CTRL_LIST_ITEM(GPS_Signal_12_Val)
CTRL_LIST_END

//----------------------UIMenuWndSetupGPSCtrl Event---------------------------
INT32 UIMenuWndSetupGPS_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupGPS_OnSatelliteDBVal(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndSetupGPS_OnTimer(VControl *, UINT32 , UINT32 *);
//INT32 UIMenuWndSetupGPS_OnUpdate_GpsMsg(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(UIMenuWndSetupGPS)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupGPS_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupGPS_OnClose)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupGPS_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupGPS_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_EDOGGPSMSG,UIMenuWndSetupGPS_OnSatelliteDBVal)
//EVENT_ITEM(NVTEVT_KEY_EDOGGPSMSG,UIMenuWndSetupGPS_OnUpdate_GpsMsg)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndSetupGPS_OnTimer)
EVENT_END

static char sGPSName[20] = {0};
static UINT32  g_uiGPSDetTimerID = NULL_TIMER;

#define GPS_DB_VAL   65

static void UIMenuWndSetupGPS_OnUpdateGpsNameStr(void)
{
    sprintf(sGPSName, "GPS");
    UxStatic_SetData(&GPS_Status_NameCtrl, STATIC_VALUE, Txt_Pointer(sGPSName));
    UxCtrl_SetShow(&GPS_Status_NameCtrl, TRUE);
}

static void UIMenuWndSetupGPS_OnUpdateGpsNum(void)
{
    static char sGPSNum1[2] = {'0','1'};
    static char sGPSNum2[2] = {'0','2'};
    static char sGPSNum3[2] = {'0','3'};
    static char sGPSNum4[2] = {'0','4'};
    static char sGPSNum5[2] = {'0','5'};
    static char sGPSNum6[2] = {'0','6'};
    static char sGPSNum7[2] = {'0','7'};
    static char sGPSNum8[2] = {'0','8'};
    static char sGPSNum9[2] = {'0','9'};
    static char sGPSNum10[2] = {'1','0'};
    static char sGPSNum11[2] = {'1','1'};
    static char sGPSNum12[2] = {'1','2'};

    UxStatic_SetData(&GPS_Signal_1_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum1));
    UxCtrl_SetShow(&GPS_Signal_1_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_2_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum2));
    UxCtrl_SetShow(&GPS_Signal_2_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_3_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum3));
    UxCtrl_SetShow(&GPS_Signal_3_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_4_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum4));
    UxCtrl_SetShow(&GPS_Signal_4_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_5_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum5));
    UxCtrl_SetShow(&GPS_Signal_5_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_6_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum6));
    UxCtrl_SetShow(&GPS_Signal_6_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_7_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum7));
    UxCtrl_SetShow(&GPS_Signal_7_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_8_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum8));
    UxCtrl_SetShow(&GPS_Signal_8_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_9_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum9));
    UxCtrl_SetShow(&GPS_Signal_9_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_10_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum10));
    UxCtrl_SetShow(&GPS_Signal_10_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_11_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum11));
    UxCtrl_SetShow(&GPS_Signal_11_NUMCtrl, TRUE);

    UxStatic_SetData(&GPS_Signal_12_NUMCtrl, STATIC_VALUE, Txt_Pointer(sGPSNum12));
    UxCtrl_SetShow(&GPS_Signal_12_NUMCtrl, TRUE);
}


static void UIMenuWndSetupGPS_HideAllGpsVal(void)
{
    UxCtrl_SetShow(&GPS_Signal_1_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_2_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_3_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_4_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_5_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_6_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_7_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_8_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_9_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_10_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_11_ValCtrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_12_ValCtrl, FALSE);
}


static void UIMenuWndSetupGPS_OnUpdateGpsVal(void)
{
    static char sGPSVal1[2] = {0};
    static char sGPSVal2[2] = {0};
    static char sGPSVal3[2] = {0};
    static char sGPSVal4[2] = {0};
    static char sGPSVal5[2] = {0};
    static char sGPSVal6[2] = {0};
    static char sGPSVal7[2] = {0};
    static char sGPSVal8[2] = {0};
    static char sGPSVal9[2] = {0};
    static char sGPSVal10[2] = {0};
    static char sGPSVal11[2] = {0};
    static char sGPSVal12[2] = {0};

    UIMenuWndSetupGPS_HideAllGpsVal();

    {
        sprintf(sGPSVal1,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_1);
        UxStatic_SetData(&GPS_Signal_1_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal1));
        UxCtrl_SetShow(&GPS_Signal_1_ValCtrl, TRUE);

        sprintf(sGPSVal2,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_2);
        UxStatic_SetData(&GPS_Signal_2_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal2));
        UxCtrl_SetShow(&GPS_Signal_2_ValCtrl, TRUE);

        sprintf(sGPSVal3,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_3);
        UxStatic_SetData(&GPS_Signal_3_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal3));
        UxCtrl_SetShow(&GPS_Signal_3_ValCtrl, TRUE);

        sprintf(sGPSVal4,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_4);
        UxStatic_SetData(&GPS_Signal_4_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal4));
        UxCtrl_SetShow(&GPS_Signal_4_ValCtrl, TRUE);

        sprintf(sGPSVal5,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_5);
        UxStatic_SetData(&GPS_Signal_5_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal5));
        UxCtrl_SetShow(&GPS_Signal_5_ValCtrl, TRUE);

        sprintf(sGPSVal6,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_6);
        UxStatic_SetData(&GPS_Signal_6_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal6));
        UxCtrl_SetShow(&GPS_Signal_6_ValCtrl, TRUE);

        sprintf(sGPSVal7,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_7);
        UxStatic_SetData(&GPS_Signal_7_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal7));
        UxCtrl_SetShow(&GPS_Signal_7_ValCtrl, TRUE);

        sprintf(sGPSVal8,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_8);
        UxStatic_SetData(&GPS_Signal_8_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal8));
        UxCtrl_SetShow(&GPS_Signal_8_ValCtrl, TRUE);

        sprintf(sGPSVal9,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_9);
        UxStatic_SetData(&GPS_Signal_9_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal9));
        UxCtrl_SetShow(&GPS_Signal_9_ValCtrl, TRUE);

        sprintf(sGPSVal10,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_10);
        UxStatic_SetData(&GPS_Signal_10_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal10));
        UxCtrl_SetShow(&GPS_Signal_10_ValCtrl, TRUE);

        sprintf(sGPSVal11,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_11);
        UxStatic_SetData(&GPS_Signal_11_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal11));
        UxCtrl_SetShow(&GPS_Signal_11_ValCtrl, TRUE);

        sprintf(sGPSVal12,"%02d",g_Edog_satellie_DB.satellie_DB_GSM_12);
        UxStatic_SetData(&GPS_Signal_12_ValCtrl, STATIC_VALUE, Txt_Pointer(sGPSVal12));
        UxCtrl_SetShow(&GPS_Signal_12_ValCtrl, TRUE);
    }
}

static void UIMenuWndSetupGPS_HideAllGpsVa_ICON(void)
{
    UxCtrl_SetShow(&GPS_Signal_Red_1Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_2Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_3Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_4Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_5Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_6Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_7Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_8Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_9Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_10Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_11Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Red_12Ctrl, FALSE);



    UxCtrl_SetShow(&GPS_Signal_Green_1Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_2Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_3Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_4Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_5Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_6Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_7Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_8Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_9Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_10Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_11Ctrl, FALSE);
    UxCtrl_SetShow(&GPS_Signal_Green_12Ctrl, FALSE);
}


static void UIMenuWndSetupGPS_OnUpdateGpsVa_ICON(void)
{
    UINT32  uiTotalStep = GPS_DB_VAL;

    UIMenuWndSetupGPS_HideAllGpsVa_ICON();
    if (RMCInfo.Status != 'A') {
        UxProgressBar_SetData(&GPS_Signal_Red_1Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_1Ctrl, TRUE);

        if(g_Edog_satellie_DB.satellie_DB_GSM_1 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_1Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_1Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_1);

        UxProgressBar_SetData(&GPS_Signal_Red_2Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_2Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_2 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_2Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_2Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_2);

        UxProgressBar_SetData(&GPS_Signal_Red_3Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_3Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_3 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_3Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_3Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_3);

        UxProgressBar_SetData(&GPS_Signal_Red_4Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_4Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_4 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_4Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_4Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_4);

        UxProgressBar_SetData(&GPS_Signal_Red_5Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_5Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_5 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_5Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_5Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_5);

        UxProgressBar_SetData(&GPS_Signal_Red_6Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_6Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_6 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_6Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_6Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_6);

        UxProgressBar_SetData(&GPS_Signal_Red_7Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_7Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_7 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_7Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_7Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_7);

        UxProgressBar_SetData(&GPS_Signal_Red_8Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_8Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_8 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_8Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_8Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_8);

        UxProgressBar_SetData(&GPS_Signal_Red_9Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_9Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_9 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_9Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_9Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_9);

        UxProgressBar_SetData(&GPS_Signal_Red_10Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_10Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_10 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_10Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_10Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_10);

        UxProgressBar_SetData(&GPS_Signal_Red_11Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_11Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_11 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_11Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_11Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_11);

        UxProgressBar_SetData(&GPS_Signal_Red_12Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Red_12Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_12 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Red_12Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Red_12Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_12);

    } else {
        UxProgressBar_SetData(&GPS_Signal_Green_1Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_1Ctrl, TRUE);

        if(g_Edog_satellie_DB.satellie_DB_GSM_1 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_1Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_1Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_1);

        UxProgressBar_SetData(&GPS_Signal_Green_2Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_2Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_2 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_2Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_2Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_2);

        UxProgressBar_SetData(&GPS_Signal_Green_3Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_3Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_3 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_3Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_3Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_3);

        UxProgressBar_SetData(&GPS_Signal_Green_4Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_4Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_4 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_4Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_4Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_4);

        UxProgressBar_SetData(&GPS_Signal_Green_5Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_5Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_5 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_5Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_5Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_5);

        UxProgressBar_SetData(&GPS_Signal_Green_6Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_6Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_6 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_6Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_6Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_6);

        UxProgressBar_SetData(&GPS_Signal_Green_7Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_7Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_7 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_7Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_7Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_7);

        UxProgressBar_SetData(&GPS_Signal_Green_8Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_8Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_8 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_8Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_8Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_8);

        UxProgressBar_SetData(&GPS_Signal_Green_9Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_9Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_9 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_9Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_9Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_9);

        UxProgressBar_SetData(&GPS_Signal_Green_10Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_10Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_10 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_10Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_10Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_10);

        UxProgressBar_SetData(&GPS_Signal_Green_11Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_11Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_11 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_11Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_11Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_11);

        UxProgressBar_SetData(&GPS_Signal_Green_12Ctrl,PROBAR_TOTSTP,uiTotalStep);
        UxCtrl_SetShow(&GPS_Signal_Green_12Ctrl, TRUE);
        if(g_Edog_satellie_DB.satellie_DB_GSM_12 > GPS_DB_VAL)
            UxProgressBar_SetData(&GPS_Signal_Green_12Ctrl,PROBAR_CURSTP,uiTotalStep);
        else
            UxProgressBar_SetData(&GPS_Signal_Green_12Ctrl,PROBAR_CURSTP,uiTotalStep - g_Edog_satellie_DB.satellie_DB_GSM_12);

    }

    Ux_Redraw();
}
INT32 UIMenuWndSetupGPS_OnSatelliteDBVal(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DBG_DUMP("====UIMenuWndSetupGPS_OnSatelliteDBVal   %c \r\n",RMCInfo.Status);
    UIMenuWndSetupGPS_OnUpdateGpsVa_ICON();
    UIMenuWndSetupGPS_OnUpdateGpsVal();
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupGPS_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndSetupGPS_OnUpdateGpsNameStr();
    UIMenuWndSetupGPS_OnUpdateGpsNum();
    {
        UIMenuWndSetupGPS_OnUpdateGpsVal();
        UIMenuWndSetupGPS_OnUpdateGpsVa_ICON();
    }

    if (g_uiGPSDetTimerID == NULL_TIMER) {
        g_uiGPSDetTimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_uiGPSDetTimerID != NULL_TIMER) {
        GxTimer_StopTimer(&g_uiGPSDetTimerID);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct = 0;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupGPSCtrl,0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupGPS_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct = 0;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(&UIMenuWndSetupGPSCtrl,0);
        break;
    }
    return NVTEVT_CONSUME;
}

extern BOOL g_bEdogSatelliteDBMSG;
INT32 UIMenuWndSetupGPS_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;
    static UINT32  GPS_std = 0;

    uiEvent = paramNum ? paramArray[0] : 0;

    switch (uiEvent) {
    case NVTEVT_1SEC_TIMER:
		//DBG_DUMP("====UIMenuWndSetupGPS_OnTimer   \r\n");
        if ((g_bEdogSatelliteDBMSG == TRUE) && (GPS_std == 0)) {
            UIMenuWndSetupGPS_OnUpdateGpsVa_ICON();
            UIMenuWndSetupGPS_OnUpdateGpsVal();
        }
        break;
    }
    return NVTEVT_CONSUME;
}

//----------------------GPS_Signal_2_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_2_NUM)
EVENT_END

//----------------------GPS_Status_NameCtrl Event---------------------------
EVENT_BEGIN(GPS_Status_Name)
EVENT_END

//----------------------GPS_Status_ICONCtrl Event---------------------------
EVENT_BEGIN(GPS_Status_ICON)
EVENT_END

//----------------------GPS_Signal_3_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_3_NUM)
EVENT_END

//----------------------GPS_Signal_4_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_4_NUM)
EVENT_END

//----------------------GPS_Signal_5_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_5_NUM)
EVENT_END

//----------------------GPS_Signal_6_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_6_NUM)
EVENT_END

//----------------------GPS_Signal_7_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_7_NUM)
EVENT_END

//----------------------GPS_Signal_8_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_8_NUM)
EVENT_END

//----------------------GPS_Signal_9_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_9_NUM)
EVENT_END

//----------------------GPS_Signal_10_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_10_NUM)
EVENT_END

//----------------------GPS_Signal_11_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_11_NUM)
EVENT_END

//----------------------GPS_Signal_2_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_2_Val)
EVENT_END

//----------------------GPS_Signal_3_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_3_Val)
EVENT_END

//----------------------GPS_Signal_4_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_4_Val)
EVENT_END

//----------------------GPS_Signal_5_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_5_Val)
EVENT_END

//----------------------GPS_Signal_6_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_6_Val)
EVENT_END

//----------------------GPS_Signal_7_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_7_Val)
EVENT_END

//----------------------GPS_Signal_8_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_8_Val)
EVENT_END

//----------------------GPS_Signal_9_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_9_Val)
EVENT_END

//----------------------GPS_Signal_10_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_10_Val)
EVENT_END

//----------------------GPS_Signal_11_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_11_Val)
EVENT_END

//----------------------GPS_Signal_Green_2Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_2)
EVENT_END

//----------------------GPS_Signal_Green_3Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_3)
EVENT_END

//----------------------GPS_Signal_Green_4Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_4)
EVENT_END

//----------------------GPS_Signal_Green_5Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_5)
EVENT_END

//----------------------GPS_Signal_Green_6Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_6)
EVENT_END

//----------------------GPS_Signal_Green_7Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_7)
EVENT_END

//----------------------GPS_Signal_Green_8Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_8)
EVENT_END

//----------------------GPS_Signal_Green_9Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_9)
EVENT_END

//----------------------GPS_Signal_Green_10Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_10)
EVENT_END

//----------------------GPS_Signal_Green_11Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_11)
EVENT_END

//----------------------GPS_Signal_Red_2Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_2)
EVENT_END

//----------------------GPS_Signal_Red_3Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_3)
EVENT_END

//----------------------GPS_Signal_Red_4Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_4)
EVENT_END

//----------------------GPS_Signal_Red_5Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_5)
EVENT_END

//----------------------GPS_Signal_Red_6Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_6)
EVENT_END

//----------------------GPS_Signal_Red_7Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_7)
EVENT_END

//----------------------GPS_Signal_Red_8Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_8)
EVENT_END

//----------------------GPS_Signal_Red_9Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_9)
EVENT_END

//----------------------GPS_Signal_Red_10Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_10)
EVENT_END

//----------------------GPS_Signal_Red_11Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_11)
EVENT_END

//----------------------GPS_Signal_Red_1Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_1)
EVENT_END

//----------------------GPS_Signal_Red_12Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Red_12)
EVENT_END

//----------------------GPS_Signal_Green_1Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_1)
EVENT_END

//----------------------GPS_Signal_Green_12Ctrl Event---------------------------
EVENT_BEGIN(GPS_Signal_Green_12)
EVENT_END

//----------------------GPS_Signal_12_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_12_NUM)
EVENT_END

//----------------------GPS_Signal_1_NUMCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_1_NUM)
EVENT_END

//----------------------GPS_Signal_1_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_1_Val)
EVENT_END

//----------------------GPS_Signal_12_ValCtrl Event---------------------------
EVENT_BEGIN(GPS_Signal_12_Val)
EVENT_END

