//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupFormatQuickConfirmRes.c"
#include "UIMenuWndSetupFormatQuickConfirm.h"
#include "UIWnd/UIFlow.h"
#include <kwrap/debug.h>
extern void SysInit_CarNoBackup_setstd(BOOL std);

BOOL g_WndWarningFormat = FALSE;
BOOL g_FmtCardBeep = FALSE;

//---------------------UIMenuWndSetupFormatQuickConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFormatQuickConfirm)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_Static_Text)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_Static_Title)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_Menu)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_TipsBar)
CTRL_LIST_END

//----------------------UIMenuWndSetupFormatQuickConfirmCtrl Event---------------------------
INT32 UIMenuWndSetupFormatQuickConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupFormatQuickConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupFormatQuickConfirm_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndSetupFormatQuickConfirm_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupFormatQuickConfirm_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupFormatQuickConfirm_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupFormatQuickConfirm_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupFormatQuickConfirm_OnKeyShutter2)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndSetupFormatQuickConfirm_OnTimer)
EVENT_END

INT32 UIMenuWndSetupFormatQuickConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_FmtCardBeep = TRUE;
    UxMenu_SetData(&UIMenuWndSetupFormatQuickConfirmCtrl, MNU_CURITM, 1);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_WndWarningFormat = TRUE;
    g_FmtCardBeep = FALSE;
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupFormatQuickConfirmCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        //if (FlowMovie_WakeUpLCDBacklight()) {
        //    return NVTEVT_CONSUME;
        //}
        Ux_CloseWindow(&UIMenuWndSetupFormatQuickConfirmCtrl, 0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
       // if (FlowMovie_WakeUpLCDBacklight()) {
       //     return NVTEVT_CONSUME;
       //  }
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvent;
    static UINT32 g_sound_Cnt = 0;

    uiEvent = paramNum ? paramArray[0] : 0;

    switch (uiEvent) {
    case NVTEVT_01SEC_TIMER:
        if (g_FmtCardBeep) {
            g_sound_Cnt++;
            if ((g_sound_Cnt == 1) || (g_sound_Cnt == 3) || (g_sound_Cnt == 5)) {
                UISound_Play(DEMOSOUND_SOUND_KEY_TONE);
            }

            if (g_sound_Cnt%30 == 0) {
                g_sound_Cnt = 0;
            }
        } else {
            g_sound_Cnt = 0;
        }
        break;
    }
    //Ux_DefaultEvent(pCtrl, NVTEVT_TIMER, paramNum, paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupFormatQuickConfirm_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_Static_Text)
EVENT_END

//----------------------UIMenuWndSetupFormatQuickConfirm_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_Static_Title)
EVENT_END

//----------------------UIMenuWndSetupFormatQuickConfirm_MenuCtrl Event---------------------------
INT32 UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        //if (FlowMovie_WakeUpLCDBacklight()) {
        //    return NVTEVT_CONSUME;
        //}
        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        //if (FlowMovie_WakeUpLCDBacklight()) {
        //    return NVTEVT_CONSUME;
       // }
        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatQuickConfirm_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_RELEASE:
        //if (FlowMovie_WakeUpLCDBacklight()) {
        //    return NVTEVT_CONSUME;
        //}

        if (UxMenu_GetData(pCtrl,MNU_CURITM) == UIMenuWndSetupFormatQuickConfirm_Menu_STRID_OK) {
            if (System_GetState(SYS_STATE_CARD) == CARD_REMOVED) {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_CARD, FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            } else {
                if (UIStorageCheck(STORAGE_CHECK_LOCKED, NULL) == TRUE) {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_CARD_LOCKED, FLOWWRNMSG_TIMER_2SEC);
                    return NVTEVT_CONSUME;
                }
            }

            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT);
            BKG_PostEvent(NVTEVT_BKW_FORMAT_CARD);
            //SysInit_CarNoBackup_setstd(FALSE);
            // reset file ID
            #if USE_FILEDB
            if (UI_GetData(FL_IsUseFileDB)) {
                Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FILEID_RESET, 0);
            }
            #endif
        } else {
            Ux_CloseWindow(&UIMenuWndSetupFormatQuickConfirmCtrl, 0);
        }
        break;
    }
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupFormatQuickConfirm_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFormatQuickConfirm_TipsBar)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_TipsIconReturn)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_TipsIconUp)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_TipsIconDown)
CTRL_LIST_ITEM(UIMenuWndSetupFormatQuickConfirm_TipsIconOK)
CTRL_LIST_END

//----------------------UIMenuWndSetupFormatQuickConfirm_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_TipsBar)
EVENT_END

//----------------------UIMenuWndSetupFormatQuickConfirm_TipsIconReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_TipsIconReturn)
EVENT_END

//----------------------UIMenuWndSetupFormatQuickConfirm_TipsIconUpCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_TipsIconUp)
EVENT_END

//----------------------UIMenuWndSetupFormatQuickConfirm_TipsIconDownCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_TipsIconDown)
EVENT_END

//----------------------UIMenuWndSetupFormatQuickConfirm_TipsIconOKCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatQuickConfirm_TipsIconOK)
EVENT_END

