//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPreSetLanguageRes.c"
#include "UIWnd/UIFlow.h"
#include "GxTime.h"
#include "comm/hwclock.h"

///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIMenuWndPreSetLanguage
#define __DBGLVL__          1 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include <kwrap/debug.h>

extern void GPIOMap_TurnOnLCDBacklight(void);
extern BOOL GPIOMap_IsLCDBacklightOn(void);
static UINT8 g_PageNumBuf[8];

//---------------------UIMenuWndPreSetLanguageCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPreSetLanguage)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_Static_Title)
CTRL_LIST_ITEM(UIMenuWndPreSetLangeage_Static_PageNum)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_Menu)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_TipsBar)
CTRL_LIST_END

//----------------------UIMenuWndPreSetLanguageCtrl Event---------------------------
INT32 UIMenuWndPreSetLanguage_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetLanguage_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetLanguage_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetLanguage_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetLanguage_OnKeyLeft(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPreSetLanguage)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPreSetLanguage_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPreSetLanguage_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPreSetLanguage_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPreSetLanguage_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPreSetLanguage_OnKeyLeft)
EVENT_END

void UIMenuWndPreSetLanguage_CalcPageInfo(VControl *pCtrl)
{
    UINT32  i, uiItem, uiCurrItem, uiTotalItem, uiTotalItemOri;
    UINT32  uiItemPerPage, uiCurrPage, uiTotalPage;

    uiItem = UxMenu_GetData(pCtrl, MNU_CURITM);          // current item number in menu (include disabled items)
    uiItemPerPage = UxMenu_GetData(pCtrl, MNU_PAGEITEM); // items per page
    uiTotalItemOri = UxMenu_GetData(pCtrl, MNU_TOTITM);  // total item number

    // check total item number and current item number (skip disabled items)
    uiCurrItem = 0;
    uiTotalItem = 0;
    for (i = 0; i < uiTotalItemOri; i++)
    {
        if (UxMenu_GetItemData(pCtrl, i, MNUITM_STATUS) == STATUS_ENABLE)
        {
            uiTotalItem++;
            if (i < uiItem)
                uiCurrItem++;
        }
    }

    uiCurrPage = (uiCurrItem / uiItemPerPage) + 1;
    uiTotalPage = ((uiTotalItem % uiItemPerPage) == 0) ? (uiTotalItem / uiItemPerPage) : (uiTotalItem / uiItemPerPage + 1);

    if (uiTotalPage > 1) {
        sprintf((char *)g_PageNumBuf, "%02d/%02d", uiCurrPage, uiTotalPage);
        UxStatic_SetData(&UIMenuWndPreSetLangeage_Static_PageNumCtrl, STATIC_VALUE, Txt_Pointer(g_PageNumBuf));
        UxCtrl_SetShow(&UIMenuWndPreSetLangeage_Static_PageNumCtrl, TRUE);
        UxCtrl_SetDirty(&UIMenuWndPreSetLangeage_Static_PageNumCtrl, TRUE);
    } else {
        UxCtrl_SetShow(&UIMenuWndPreSetLangeage_Static_PageNumCtrl, FALSE);
    }
}

void UIMenuWndPreSetLanguage_UpdateContent(void)
{
    UINT32      i;

    UxMenu_SetData(&UIMenuWndPreSetLanguage_MenuCtrl, MNU_TOTITM, LANG_ID_MAX);
    for (i = 0; i < LANG_ID_MAX; i++)
    {
        UxMenu_SetItemData(&UIMenuWndPreSetLanguage_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);

        UxMenu_SetItemData(&UIMenuWndPreSetLanguage_MenuCtrl, i, MNUITM_STRID,  gTM_OPTIONS_LANGUAGE[i].TextId);
        UxMenu_SetItemData(&UIMenuWndPreSetLanguage_MenuCtrl, i, MNUITM_ICONID, ICON_CORRECT);        
    }

    UxMenu_SetItemData(&UIMenuWndPreSetLanguage_MenuCtrl, SysGetFlag(FL_LANGUAGE), MNUITM_ICONID, ICON_SEL_FOCUS);
}

INT32 UIMenuWndPreSetLanguage_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    struct tm Curr_DateTime = {0};

    Curr_DateTime.tm_year = DEF_YEAR;
    Curr_DateTime.tm_mon = DEF_MONTH;
    Curr_DateTime.tm_mday = DEF_DAY;
    Curr_DateTime.tm_hour = 0;
    Curr_DateTime.tm_min = 0;
    Curr_DateTime.tm_sec = 0;

    GxTime_SetTime(Curr_DateTime);

    if (GPIOMap_IsLCDBacklightOn() == FALSE)
    {
        if ((KeyScan_GetPlugDev() == PLUG_TV)||(KeyScan_GetPlugDev() == PLUG_HDMI))
        {
            ;
        }
        else
        {
            GPIOMap_TurnOnLCDBacklight();
        }
    }

    FlowMovie_BaseDaySet(DEF_YEAR,DEF_MONTH,DEF_DAY);
    DBG_DUMP("UIMenuWndPreSetLanguage_OnOpen %d \r\n",  SysGetFlag(FL_LANGUAGE));
	UxMenu_SetData(&UIMenuWndPreSetLanguage_MenuCtrl, MNU_CURITM, SysGetFlag(FL_LANGUAGE));//set focus
    UIMenuWndPreSetLanguage_UpdateContent();
    UIMenuWndPreSetLanguage_CalcPageInfo(&UIMenuWndPreSetLanguage_MenuCtrl);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetLanguage_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetLanguage_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPreSetLanguage_UpdateContent();
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetLanguage_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetLanguage_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        SysSetFlag(FL_FIRSTPOWERON, FIRSTPOWERON_FALSE);
        Ux_CloseWindow(&UIMenuWndPreSetLanguageCtrl,0);
        Save_MenuInfo();
#if 0//(BOOT_RECOVERY_FILE==ENABLE)
        if(TRUE==g_FileRecoveryFlag)
        {
            GxDisplay_Set(LAYER_OSD1, LAYER_STATE_ENABLE, 0);
	        //GxDisplay_Set(LAYER_OSD2, LAYER_STATE_ENABLE, 0);
            GxDisplay_Flush(LAYER_OSD1);
            //GxDisplay_Flush(LAYER_OSD2);
            Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
        }
        else
#endif
        {
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_MOVIE_MODE,0);
        }
        break;
    }
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPreSetLanguage_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLanguage_Static_Title)
EVENT_END

//----------------------UIMenuWndPreSetLangeage_Static_PageNumCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLangeage_Static_PageNum)
EVENT_END

//----------------------UIMenuWndPreSetLanguage_MenuCtrl Event---------------------------
INT32 UIMenuWndPreSetLanguage_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetLanguage_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPreSetLanguage_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPreSetLanguage_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPreSetLanguage_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPreSetLanguage_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPreSetLanguage_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPreSetLanguage_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        UIMenuWndPreSetLanguage_CalcPageInfo(&UIMenuWndPreSetLanguage_MenuCtrl);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetLanguage_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        UIMenuWndPreSetLanguage_CalcPageInfo(&UIMenuWndPreSetLanguage_MenuCtrl);
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPreSetLanguage_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;
    UINT32  value = 0;

    uiKeyAct = paramArray[0];

    switch (uiKeyAct) {
    case NVTEVT_KEY_PRESS:
        value = UxMenu_GetData(pCtrl,MNU_CURITM);
        Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LANGUAGE, 1, value);
        Ux_CloseWindow((VControl *)(&UIMenuWndPreSetLanguageCtrl), 0);
        Ux_OpenWindow((VControl *)(&UIMenuWndPreSetDateTimeCtrl), 0);
        break;
    }
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPreSetLanguage_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPreSetLanguage_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_TipsIconReturn)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_TipsIconUp)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_TipsIconDown)
CTRL_LIST_ITEM(UIMenuWndPreSetLanguage_TipsIconOK)
CTRL_LIST_END

//----------------------UIMenuWndPreSetLanguage_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLanguage_TipsBar)
EVENT_END

//----------------------UIMenuWndPreSetLanguage_TipsIconReturnCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLanguage_TipsIconReturn)
EVENT_END

//----------------------UIMenuWndPreSetLanguage_TipsIconUpCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLanguage_TipsIconUp)
EVENT_END

//----------------------UIMenuWndPreSetLanguage_TipsIconDownCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLanguage_TipsIconDown)
EVENT_END

//----------------------UIMenuWndPreSetLanguage_TipsIconOKCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPreSetLanguage_TipsIconOK)
EVENT_END

