//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPOPTION_LV3_H
#define UIMENUWNDSETUPOPTION_LV3_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupOption_LV3Ctrl;//Panel type 

extern VControl UIMenuWndSetupOption_LV3_TitleCtrl;//Static type 

extern VControl UIMenuWndSetupOption_LV3_PanelCtrl;//Panel type 

extern VControl UIMenuWndSetupOption_LV3_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndSetupOption_LV3_Menu_STRID_A0,
UIMenuWndSetupOption_LV3_Menu_STRID_A1,
UIMenuWndSetupOption_LV3_Menu_STRID_A2,
UIMenuWndSetupOption_LV3_Menu_STRID_A3,
UIMenuWndSetupOption_LV3_Menu_STRID_A4,
UIMenuWndSetupOption_LV3_Menu_STRID_A5,
UIMenuWndSetupOption_LV3_Menu_STRID_A6,
UIMenuWndSetupOption_LV3_Menu_STRID_A7,
UIMenuWndSetupOption_LV3_Menu_STRID_A8,
UIMenuWndSetupOption_LV3_Menu_STRID_A9,
UIMenuWndSetupOption_LV3_Menu_STRID_B0,
UIMenuWndSetupOption_LV3_Menu_STRID_B1,
UIMenuWndSetupOption_LV3_Menu_STRID_B2,
UIMenuWndSetupOption_LV3_Menu_STRID_B3,
UIMenuWndSetupOption_LV3_Menu_STRID_B4,
UIMenuWndSetupOption_LV3_Menu_STRID_B5,
UIMenuWndSetupOption_LV3_Menu_STRID_B6,
UIMenuWndSetupOption_LV3_Menu_STRID_B7,
UIMenuWndSetupOption_LV3_Menu_STRID_B8,
UIMenuWndSetupOption_LV3_Menu_STRID_B9,
UIMenuWndSetupOption_LV3_Menu_STRID_C0,
UIMenuWndSetupOption_LV3_Menu_STRID_C1,
UIMenuWndSetupOption_LV3_Menu_STRID_C2,
UIMenuWndSetupOption_LV3_Menu_STRID_C3,
UIMenuWndSetupOption_LV3_Menu_STRID_C4,
UIMenuWndSetupOption_LV3_Menu_STRID_C5,
UIMenuWndSetupOption_LV3_Menu_STRID_C6,
UIMenuWndSetupOption_LV3_Menu_STRID_C7,
UIMenuWndSetupOption_LV3_Menu_STRID_C8,
UIMenuWndSetupOption_LV3_Menu_STRID_C9,
UIMenuWndSetupOption_LV3_Menu_STRID_1UP,
UIMenuWndSetupOption_LV3_Menu_STRID_2UP,
UIMenuWndSetupOption_LV3_Menu_STRID_3UP,
UIMenuWndSetupOption_LV3_Menu_STRID_4UP,
UIMenuWndSetupOption_LV3_Menu_STRID_5UP,
UIMenuWndSetupOption_LV3_Menu_STRID_6UP,
UIMenuWndSetupOption_LV3_Menu_MAX
}UIMenuWndSetupOption_LV3_Menu_Setting;

extern VControl UIMenuWndSetupOption_LV3_PageNumCtrl;//Static type 

//---------------------UIMenuWndSetupOption_LV3Ctrl User Export---------------------------
#endif
