//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWIFIMOVIE_H
#define UIFLOWWNDWIFIMOVIE_H

#include "UIFramework.h"

extern VControl UIFlowWndWiFiMovieCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_Panel_Normal_DisplayCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_Status_MotionDetCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_MotionDet_ICONID_NULL,
UIFlowWndWiFiMovie_Status_MotionDet_ICON_FLASH_REC,
UIFlowWndWiFiMovie_Status_MotionDet_MAX
}UIFlowWndWiFiMovie_Status_MotionDet_Setting;

extern VControl UIFlowWndWiFiMovie_YMD_StaticCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_HMS_StaticCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_PanelCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_Static_timeCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_maxtimeCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_resolutionCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Status_AudioCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_Audio_ICON_SOUND_REC_OFF,
UIFlowWndWiFiMovie_Status_Audio_ICON_SOUND_REC_ON,
UIFlowWndWiFiMovie_Status_Audio_MAX
}UIFlowWndWiFiMovie_Status_Audio_Setting;

extern VControl UIFlowWndWiFiMovie_StaticIcon_PIMCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Status_WiFi_ConnectedCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_WiFi_Connected_ICON_WIFI,
UIFlowWndWiFiMovie_Status_WiFi_Connected_ICON_WIFI_CONNECTED_SMALL,
UIFlowWndWiFiMovie_Status_WiFi_Connected_MAX
}UIFlowWndWiFiMovie_Status_WiFi_Connected_Setting;

extern VControl UIFlowWndWiFiMovie_Panel_SSID_KEYCtrl;//Panel type 

extern VControl UIFlowWiFiMoive_static_SSIDCtrl;//Static type 

extern VControl UIFlowWiFiMoive_static_KeyCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_WiFi_DisconnectedCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSSignalCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSSignalCCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSSignalCCCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_MotionDet1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_MotionDet2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TimeLapse1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TimeLapse2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSN_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPS_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_SOSCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_SOS1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_SNG1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_SNG2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSRCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSR1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSR2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSR3Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RLCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RL1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RL2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RL3Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_SOSCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_SSIDCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_CAPCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_CLOSELCDCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_PowerKeyCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_FolderCheck_StatusTxtCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_FolderCheck_StatusTxt_STRID_FORMAT_WARNING1,
UIFlowWndWiFiMovie_FolderCheck_StatusTxt_MAX
}UIFlowWndWiFiMovie_FolderCheck_StatusTxt_Setting;

extern VControl UIFlowWndWiFiMovie_Static_SNGCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Panel_PlayModeCtrl;//Panel type 

extern VControl UIFlowWiFiMoive_static_AppConnecttingCtrl;//Static type 

//---------------------UIFlowWndWiFiMovieCtrl User Export---------------------------
extern INT32 UIFlowWndWiFiMovie_OnCustom2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
#endif
