//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWIFIMOVIE_H
#define UIFLOWWNDWIFIMOVIE_H

#include "UIFramework.h"

extern VControl UIFlowWndWiFiMovieCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_Panel_Normal_DisplayCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_Status_MotionDetCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_MotionDet_ICONID_NULL,
UIFlowWndWiFiMovie_Status_MotionDet_ICON_FLASH_REC,
UIFlowWndWiFiMovie_Status_MotionDet_MAX
}UIFlowWndWiFiMovie_Status_MotionDet_Setting;

extern VControl UIFlowWndWiFiMovie_YMD_StaticCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_HMS_StaticCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_PanelCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_Static_timeCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_maxtimeCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_resolutionCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Status_AudioCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_Audio_ICON_SOUND_REC_OFF,
UIFlowWndWiFiMovie_Status_Audio_ICON_SOUND_REC_ON,
UIFlowWndWiFiMovie_Status_Audio_MAX
}UIFlowWndWiFiMovie_Status_Audio_Setting;

extern VControl UIFlowWndWiFiMovie_StaticIcon_PIMCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Status_WiFi_ConnectedCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_WiFi_Connected_ICON_WIFI,
UIFlowWndWiFiMovie_Status_WiFi_Connected_ICON_WIFI_CONNECTED_SMALL,
UIFlowWndWiFiMovie_Status_WiFi_Connected_MAX
}UIFlowWndWiFiMovie_Status_WiFi_Connected_Setting;

extern VControl UIFlowWndWiFiMovie_Panel_SSID_KEYCtrl;//Panel type 

extern VControl UIFlowWiFiMoive_static_SSIDCtrl;//Static type 

extern VControl UIFlowWiFiMoive_static_KeyCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_WiFi_DisconnectedCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSSignalCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSSignalCCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSSignalCCCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_MotionDet1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_MotionDet2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TimeLapse1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TimeLapse2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPSN_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_GPS_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_SOSCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_SOS1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_SNG1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_SNG2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSRCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSR1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSR2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_TSR3Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RLCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RL1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RL2Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Static_RL3Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_SOSCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_SSIDCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_CAPCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_CLOSELCDCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_MENU_PowerKeyCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_FolderCheck_StatusTxtCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_FolderCheck_StatusTxt_STRID_FORMAT_WARNING1,
UIFlowWndWiFiMovie_FolderCheck_StatusTxt_MAX
}UIFlowWndWiFiMovie_FolderCheck_StatusTxt_Setting;

extern VControl UIFlowWndWiFiMovie_Static_SNGCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Panel_PlayModeCtrl;//Panel type 

extern VControl UIFlowWiFiMoive_static_AppConnecttingCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_Status_HDRCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_Status_HDR_ICONID_NULL,
UIFlowWndWiFiMovie_Status_HDR_ICON_HDR,
UIFlowWndWiFiMovie_Status_HDR_MAX
}UIFlowWndWiFiMovie_Status_HDR_Setting;

extern VControl UIFlowWndWiFiMovie_ADAS_Alert_DisplayCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_StatusICN_LDWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_LDWS_Alert_ICON_ADAS_LANE_LEFT,
UIFlowWndWiFiMovie_StatusICN_LDWS_Alert_ICON_ADAS_LANE_RIGHT,
UIFlowWndWiFiMovie_StatusICN_LDWS_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_LDWS_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_StatusICN_FCWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_FCWS_Alert_ICON_ADAS_FRONT_ALERT,
UIFlowWndWiFiMovie_StatusICN_FCWS_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_FCWS_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_StatusICN_SNG_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_SNG_Alert_ICON_ADAS_GO_ALERT,
UIFlowWndWiFiMovie_StatusICN_SNG_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_SNG_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_StatusICN_PDWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_PDWS_Alert_ICON_ADAS_PEOPLE_ALERT,
UIFlowWndWiFiMovie_StatusICN_PDWS_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_PDWS_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_StatusICN_RCWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_RCWS_Alert_ICON_ADAS_REAR_ALERT,
UIFlowWndWiFiMovie_StatusICN_RCWS_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_RCWS_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_StatusICN_VBWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_VBWS_Alert_ICON_ADAS_VIRTUAL_BUMPER,
UIFlowWndWiFiMovie_StatusICN_VBWS_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_VBWS_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_StatusICN_LCWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndWiFiMovie_StatusICN_LCWS_Alert_ICON_ADAS_CHANGE_LANE_LEFT,
UIFlowWndWiFiMovie_StatusICN_LCWS_Alert_ICON_ADAS_CHANGE_LANE_RIGHT,
UIFlowWndWiFiMovie_StatusICN_LCWS_Alert_MAX
}UIFlowWndWiFiMovie_StatusICN_LCWS_Alert_Setting;

extern VControl UIFlowWndWiFiMovie_ADAS_Alert_PanelCtrl;//Panel type 

extern VControl UIFlowWndWiFiMovie_ADAS_Road_Static_IconCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Distance_BGCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Distance_SeperateCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Distance_Num0Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Distance_Num1Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Distance_UnitCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_WhiteCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_AnimationCtrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_00Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_01Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_02Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_03Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_04Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_05Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Blue_06Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Red_00Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_Car_Red_01Ctrl;//Static type 

extern VControl UIFlowWndWiFiMovie_ADAS_TypeCtrl;//Static type 

//---------------------UIFlowWndWiFiMovieCtrl User Export---------------------------
extern INT32 UIFlowWndWiFiMovie_OnCustom2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
#endif
