//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIWAITRES_H
#define UIMENUWNDWIFIWAITRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UI/UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,619,239,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,619,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin3Rect,0,0,126,99,0,0,1,1,0,0,0)
SHOW_MAP_BEGIN(Skin3)
SHOW_MAP_BODY(Skin3Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin3,0,0,126,99)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon4, 0, 0, 126,99, ICONID_NULL,83886080,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Normal2)
SHOW_MAP_BODY(Skin3)
SHOW_MAP_BODY(Icon4)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal2,246,70,372,169)

CREATE_STATE_ITEM_DATA(ICON_WIFI_CONNECT5,STRID_NULL,ICON_WIFI_CONNECT,NULL) 
SHOW_MAP_BEGIN(UIMenuWndWiFiWait_Connect_Icon_Status)
SHOW_MAP_BODY(Normal2)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndWiFiWait_Connect_Icon_Status)
STATE_LIST_BEGIN(UIMenuWndWiFiWait_Connect_Icon_Status)
STATE_LIST_ITEM(ICON_WIFI_CONNECT5)
STATE_LIST_END

CREATE_STATE_DATA(UIMenuWndWiFiWait_Connect_Icon_Status,0)
CREATE_STATE_CTRL(UIMenuWndWiFiWait_Connect_Icon_Status,0,246,70,372,169)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIMenuWndWiFiWait)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndWiFiWait)
DECLARE_CTRL_LIST(UIMenuWndWiFiWait)
CREATE_CTRL(UIMenuWndWiFiWait,UIMenuWndWiFiWait,CTRL_WND,NULL,0 ,0,0,619,239)
#endif
