/*//////////////////////////////////////////////////////////////////////////////

 ---------- Document Info ---------------

        Author : Anonymous
       Created : 20:42:59, May 19 2009
 Last modified : 15:18:17, Mar 22 2013
   Making tool : UI Designer Studio
   File format : C language header file

 ----------- Object Info ----------------

         Class : IMAGE_TABLE
          Name : DemoKit_Image

*///////////////////////////////////////////////////////////////////////////////

#ifndef _DEMOKIT_IMAGE_H_
#define _DEMOKIT_IMAGE_H_

// IMAGE_TABLE
extern const
unsigned char gDemoKit_Image[];

// IMAGE ID
#define BYE_SC                                   0x0000
#define BYE_TC                                   0x0001
#define ICON_AM                                  0x0002
#define ICON_AUTO_1FPS                           0x0003
#define ICON_BACK                                0x0004
#define ICON_BAR                                 0x0005
#define ICON_BATTERY_CHARGE                      0x0006
#define ICON_BATTERY_EMPTY                       0x0007
#define ICON_BATTERY_FULL                        0x0008
#define ICON_BATTERY_LOW                         0x0009
#define ICON_BATTERY_MED                         0x000A
#define ICON_BATTERY_TPMS                        0x000B
#define ICON_BATTERY_ZERO                        0x000C
#define ICON_C                                   0x000D
#define ICON_CAMERA_MODE                         0x000E
#define ICON_CAR_CAMERA                          0x000F
#define ICON_CAR_NO                              0x0010
#define ICON_CLOSE                               0x0011
#define ICON_COLN                                0x0012
#define ICON_COLOR                               0x0013
#define ICON_COMPASS_E                           0x0014
#define ICON_COMPASS_N                           0x0015
#define ICON_COMPASS_NE                          0x0016
#define ICON_COMPASS_NW                          0x0017
#define ICON_COMPASS_S                           0x0018
#define ICON_COMPASS_SE                          0x0019
#define ICON_COMPASS_SW                          0x001A
#define ICON_COMPASS_W                           0x001B
#define ICON_COPY_FROM_CARD                      0x001C
#define ICON_CORRECT                             0x001D
#define ICON_CYCLIC_REC                          0x001E
#define ICON_CYCLIC_REC_1MIN                     0x001F
#define ICON_CYCLIC_REC_2MIN                     0x0020
#define ICON_CYCLIC_REC_3MIN                     0x0021
#define ICON_CYCLIC_REC_5MIN                     0x0022
#define ICON_CYCLIC_REC_10MIN                    0x0023
#define ICON_CYCLIC_REC_15MIN                    0x0024
#define ICON_DATE_0                              0x0025
#define ICON_DATE_1                              0x0026
#define ICON_DATE_2                              0x0027
#define ICON_DATE_3                              0x0028
#define ICON_DATE_4                              0x0029
#define ICON_DATE_5                              0x002A
#define ICON_DATE_6                              0x002B
#define ICON_DATE_7                              0x002C
#define ICON_DATE_8                              0x002D
#define ICON_DATE_9                              0x002E
#define ICON_DATE_PRINT                          0x002F
#define ICON_DATE_STAMPING                       0x0030
#define ICON_DATE_TIME                           0x0031
#define ICON_DEFAULT                             0x0032
#define ICON_DELETE                              0x0033
#define ICON_DIR_D                               0x0034
#define ICON_DIR_DOWN                            0x0035
#define ICON_DIR_LEFT                            0x0036
#define ICON_DIR_R                               0x0037
#define ICON_DIR_RIGHT                           0x0038
#define ICON_DIR_U                               0x0039
#define ICON_DIR_UP                              0x003A
#define ICON_EAST                                0x003B
#define ICON_EDOG_00KM                           0x003C
#define ICON_EDOG_20KM                           0x003D
#define ICON_EDOG_30KM                           0x003E
#define ICON_EDOG_40KM                           0x003F
#define ICON_EDOG_50KM                           0x0040
#define ICON_EDOG_60KM                           0x0041
#define ICON_EDOG_70KM                           0x0042
#define ICON_EDOG_80KM                           0x0043
#define ICON_EDOG_90KM                           0x0044
#define ICON_EDOG_100KM                          0x0045
#define ICON_EDOG_110KM                          0x0046
#define ICON_EDOG_120KM                          0x0047
#define ICON_EDOG_AVERAGE_SPEED                  0x0048
#define ICON_EDOG_BG                             0x0049
#define ICON_EDOG_BG_RECT                        0x004A
#define ICON_EDOG_CAPTUR                         0x004B
#define ICON_EDOG_DIS                            0x004C
#define ICON_EDOG_DIS_BIG                        0x004D
#define ICON_EDOG_DISTANCE                       0x004E
#define ICON_EDOG_KM                             0x004F
#define ICON_EDOG_KM_SMALL                       0x0050
#define ICON_EDOG_KMH_BIG                        0x0051
#define ICON_EDOG_KMH_RED                        0x0052
#define ICON_EDOG_KMH_SMALL                      0x0053
#define ICON_EDOG_M                              0x0054
#define ICON_EDOG_M_BIG                          0x0055
#define ICON_EDOG_M_SMALL                        0x0056
#define ICON_EDOG_MIN_SMALL                      0x0057
#define ICON_EDOG_NUM_RED_0                      0x0058
#define ICON_EDOG_NUM_RED_1                      0x0059
#define ICON_EDOG_NUM_RED_2                      0x005A
#define ICON_EDOG_NUM_RED_3                      0x005B
#define ICON_EDOG_NUM_RED_4                      0x005C
#define ICON_EDOG_NUM_RED_5                      0x005D
#define ICON_EDOG_NUM_RED_6                      0x005E
#define ICON_EDOG_NUM_RED_7                      0x005F
#define ICON_EDOG_NUM_RED_8                      0x0060
#define ICON_EDOG_NUM_RED_9                      0x0061
#define ICON_EDOG_NUM_RED_MID_0                  0x0062
#define ICON_EDOG_NUM_RED_MID_1                  0x0063
#define ICON_EDOG_NUM_RED_MID_2                  0x0064
#define ICON_EDOG_NUM_RED_MID_3                  0x0065
#define ICON_EDOG_NUM_RED_MID_4                  0x0066
#define ICON_EDOG_NUM_RED_MID_5                  0x0067
#define ICON_EDOG_NUM_RED_MID_6                  0x0068
#define ICON_EDOG_NUM_RED_MID_7                  0x0069
#define ICON_EDOG_NUM_RED_MID_8                  0x006A
#define ICON_EDOG_NUM_RED_MID_9                  0x006B
#define ICON_EDOG_NUM_RED_SMALL_0                0x006C
#define ICON_EDOG_NUM_RED_SMALL_1                0x006D
#define ICON_EDOG_NUM_RED_SMALL_2                0x006E
#define ICON_EDOG_NUM_RED_SMALL_3                0x006F
#define ICON_EDOG_NUM_RED_SMALL_4                0x0070
#define ICON_EDOG_NUM_RED_SMALL_5                0x0071
#define ICON_EDOG_NUM_RED_SMALL_6                0x0072
#define ICON_EDOG_NUM_RED_SMALL_7                0x0073
#define ICON_EDOG_NUM_RED_SMALL_8                0x0074
#define ICON_EDOG_NUM_RED_SMALL_9                0x0075
#define ICON_EDOG_NUM_YELLOW_0                   0x0076
#define ICON_EDOG_NUM_YELLOW_1                   0x0077
#define ICON_EDOG_NUM_YELLOW_2                   0x0078
#define ICON_EDOG_NUM_YELLOW_3                   0x0079
#define ICON_EDOG_NUM_YELLOW_4                   0x007A
#define ICON_EDOG_NUM_YELLOW_5                   0x007B
#define ICON_EDOG_NUM_YELLOW_6                   0x007C
#define ICON_EDOG_NUM_YELLOW_7                   0x007D
#define ICON_EDOG_NUM_YELLOW_8                   0x007E
#define ICON_EDOG_NUM_YELLOW_9                   0x007F
#define ICON_EDOG_NUM_YELLOW_MID_0               0x0080
#define ICON_EDOG_NUM_YELLOW_MID_1               0x0081
#define ICON_EDOG_NUM_YELLOW_MID_2               0x0082
#define ICON_EDOG_NUM_YELLOW_MID_3               0x0083
#define ICON_EDOG_NUM_YELLOW_MID_4               0x0084
#define ICON_EDOG_NUM_YELLOW_MID_5               0x0085
#define ICON_EDOG_NUM_YELLOW_MID_6               0x0086
#define ICON_EDOG_NUM_YELLOW_MID_7               0x0087
#define ICON_EDOG_NUM_YELLOW_MID_8               0x0088
#define ICON_EDOG_NUM_YELLOW_MID_9               0x0089
#define ICON_EDOG_NUM_YELLOW_SMALL_0             0x008A
#define ICON_EDOG_NUM_YELLOW_SMALL_1             0x008B
#define ICON_EDOG_NUM_YELLOW_SMALL_2             0x008C
#define ICON_EDOG_NUM_YELLOW_SMALL_3             0x008D
#define ICON_EDOG_NUM_YELLOW_SMALL_4             0x008E
#define ICON_EDOG_NUM_YELLOW_SMALL_5             0x008F
#define ICON_EDOG_NUM_YELLOW_SMALL_6             0x0090
#define ICON_EDOG_NUM_YELLOW_SMALL_7             0x0091
#define ICON_EDOG_NUM_YELLOW_SMALL_8             0x0092
#define ICON_EDOG_NUM_YELLOW_SMALL_9             0x0093
#define ICON_EDOG_REDGREEN                       0x0094
#define ICON_EDOG_SEC_SMALL                      0x0095
#define ICON_EDOG_TIME                           0x0096
#define ICON_EDOG_TYPE_ACCIDENT                  0x0097
#define ICON_EDOG_TYPE_BUS                       0x0098
#define ICON_EDOG_TYPE_DAWANDAO                  0x0099
#define ICON_EDOG_TYPE_DOWN_HILL                 0x009A
#define ICON_EDOG_TYPE_ENTRY                     0x009B
#define ICON_EDOG_TYPE_EXIT                      0x009C
#define ICON_EDOG_TYPE_JIAOLIUDAO                0x009D
#define ICON_EDOG_TYPE_MONITOR                   0x009E
#define ICON_EDOG_TYPE_NO_DRINKING               0x009F
#define ICON_EDOG_TYPE_NO_LEFT_TURN              0x00A0
#define ICON_EDOG_TYPE_NO_PARKING                0x00A1
#define ICON_EDOG_TYPE_OIL_STATION               0x00A2
#define ICON_EDOG_TYPE_POLICE                    0x00A3
#define ICON_EDOG_TYPE_SCHOOL                    0x00A4
#define ICON_EDOG_TYPE_SERVICE_CENTER            0x00A5
#define ICON_EDOG_TYPE_STRAIGHT_LINE             0x00A6
#define ICON_EDOG_TYPE_TRAIN_WAY                 0x00A7
#define ICON_EDOG_TYPE_TUNNEL                    0x00A8
#define ICON_EDOG_WARN_BG                        0x00A9
#define ICON_EV                                  0x00AA
#define ICON_EV_M0P3                             0x00AB
#define ICON_EV_M0P6                             0x00AC
#define ICON_EV_M1P0                             0x00AD
#define ICON_EV_M1P3                             0x00AE
#define ICON_EV_M1P6                             0x00AF
#define ICON_EV_M2P0                             0x00B0
#define ICON_EV_P0P0                             0x00B1
#define ICON_EV_P0P3                             0x00B2
#define ICON_EV_P0P6                             0x00B3
#define ICON_EV_P1P0                             0x00B4
#define ICON_EV_P1P3                             0x00B5
#define ICON_EV_P1P6                             0x00B6
#define ICON_EV_P2P0                             0x00B7
#define ICON_F                                   0x00B8
#define ICON_FACE_ON                             0x00B9
#define ICON_FB_LEFT                             0x00BA
#define ICON_FB_LEFT_ORI                         0x00BB
#define ICON_FF_RIGHT                            0x00BC
#define ICON_FF_RIGHT_ORI                        0x00BD
#define ICON_FILE_LOCK                           0x00BE
#define ICON_FILE_VIDEO                          0x00BF
#define ICON_FLASH_REC                           0x00C0
#define ICON_FORMAT                              0x00C1
#define ICON_GOLF_REC                            0x00C2
#define ICON_GPS                                 0x00C3
#define ICON_GPS_INFO_NULL                       0x00C4
#define ICON_GPS_OFF                             0x00C5
#define ICON_GPS_ON                              0x00C6
#define ICON_GPS_ON_M                            0x00C7
#define ICON_GPS_S_OFF                           0x00C8
#define ICON_GPS_S_ON                            0x00C9
#define ICON_GSENSOR                             0x00CA
#define ICON_HDR                                 0x00CB
#define ICON_HINT_BAR                            0x00CC
#define ICON_HZ                                  0x00CD
#define ICON_INTERNAL_FLASH                      0x00CE
#define ICON_ISO                                 0x00CF
#define ICON_ISO_100                             0x00D0
#define ICON_ISO_200                             0x00D1
#define ICON_ISO_400                             0x00D2
#define ICON_ISO_AUTO                            0x00D3
#define ICON_KMH                                 0x00D4
#define ICON_LANDSCAPE                           0x00D5
#define ICON_LANGUAGE                            0x00D6
#define ICON_LOCK                                0x00D7
#define ICON_MENU_FLASH_REC                      0x00D8
#define ICON_MENU_HDR                            0x00D9
#define ICON_MENU_PLAYBACK_OFF                   0x00DA
#define ICON_MENU_PLAYBACK_ON                    0x00DB
#define ICON_MENU_RETURN                         0x00DC
#define ICON_MENU_SETUP_OFF                      0x00DD
#define ICON_MENU_SETUP_ON                       0x00DE
#define ICON_MENU_STILL_OFF                      0x00DF
#define ICON_MENU_STILL_ON                       0x00E0
#define ICON_MENU_VIDEO_OFF                      0x00E1
#define ICON_MENU_VIDEO_ON                       0x00E2
#define ICON_MENU_WDR                            0x00E3
#define ICON_METERING                            0x00E4
#define ICON_MODE_CAPTURE                        0x00E5
#define ICON_MODE_PLAYBACK                       0x00E6
#define ICON_MODE_VIDEO                          0x00E7
#define ICON_MOVIE_MENU_WARING                   0x00E8
#define ICON_MPH                                 0x00E9
#define ICON_NORTH                               0x00EA
#define ICON_NORTH_EAST                          0x00EB
#define ICON_NORTH_WEST                          0x00EC
#define ICON_OK                                  0x00ED
#define ICON_OK_PAUSE                            0x00EE
#define ICON_OK_PLAY                             0x00EF
#define ICON_PANEL_SPPED_0                       0x00F0
#define ICON_PANEL_SPPED_10                      0x00F1
#define ICON_PANEL_SPPED_20                      0x00F2
#define ICON_PANEL_SPPED_30                      0x00F3
#define ICON_PANEL_SPPED_40                      0x00F4
#define ICON_PANEL_SPPED_50                      0x00F5
#define ICON_PANEL_SPPED_60                      0x00F6
#define ICON_PANEL_SPPED_70                      0x00F7
#define ICON_PANEL_SPPED_80                      0x00F8
#define ICON_PANEL_SPPED_90                      0x00F9
#define ICON_PANEL_SPPED_100                     0x00FA
#define ICON_PANEL_SPPED_110                     0x00FB
#define ICON_PANEL_SPPED_120                     0x00FC
#define ICON_PANEL_SPPED_130                     0x00FD
#define ICON_PANEL_SPPED_140                     0x00FE
#define ICON_PANEL_SPPED_150                     0x00FF
#define ICON_PANEL_SPPED_160                     0x0100
#define ICON_PAUSE                               0x0101
#define ICON_PLAY                                0x0102
#define ICON_PLAY_FF_B                           0x0103
#define ICON_PLAY_FF_F                           0x0104
#define ICON_PM                                  0x0105
#define ICON_POWER_OFF                           0x0106
#define ICON_PROTECT                             0x0107
#define ICON_PSI                                 0x0108
#define ICON_QUALITY                             0x0109
#define ICON_QUALITY_BASIC                       0x010A
#define ICON_QUALITY_FINE                        0x010B
#define ICON_QUALITY_NORMAL                      0x010C
#define ICON_QUICK_REVIEW                        0x010D
#define ICON_REC_ELIPPSE                         0x010E
#define ICON_REC_RECOVERY                        0x010F
#define ICON_RESOLUTION                          0x0110
#define ICON_ROTATE                              0x0111
#define ICON_SCREEN_SAVER                        0x0112
#define ICON_SD_CARD                             0x0113
#define ICON_SD_LOCK                             0x0114
#define ICON_SEL_BAR_BEGIN                       0x0115
#define ICON_SEL_BAR_DATE                        0x0116
#define ICON_SEL_BAR_END                         0x0117
#define ICON_SEL_BAR_ITEM                        0x0118
#define ICON_SEL_BAR_MED                         0x0119
#define ICON_SEL_BAR_YEAR                        0x011A
#define ICON_SEL_FOCUS                           0x011B
#define ICON_SELFTIMER_2SEC                      0x011C
#define ICON_SELFTIMER_5SEC                      0x011D
#define ICON_SELFTIMER_10SEC                     0x011E
#define ICON_SEQUENCE_NO                         0x011F
#define ICON_SET                                 0x0120
#define ICON_SET_LOCK                            0x0121
#define ICON_SHAKE_OFF                           0x0122
#define ICON_SHAKE_ON                            0x0123
#define ICON_SHARPNESS                           0x0124
#define ICON_SLIDE_SHOW                          0x0125
#define ICON_SMILE                               0x0126
#define ICON_SOUTH                               0x0127
#define ICON_SOUTH_EAST                          0x0128
#define ICON_SOUTH_WEST                          0x0129
#define ICON_SPEED_0                             0x012A
#define ICON_SPEED_1                             0x012B
#define ICON_SPEED_2                             0x012C
#define ICON_SPEED_3                             0x012D
#define ICON_SPEED_4                             0x012E
#define ICON_SPEED_5                             0x012F
#define ICON_SPEED_6                             0x0130
#define ICON_SPEED_7                             0x0131
#define ICON_SPEED_8                             0x0132
#define ICON_SPEED_9                             0x0133
#define ICON_SSID                                0x0134
#define ICON_TIME_0                              0x0135
#define ICON_TIME_1                              0x0136
#define ICON_TIME_2                              0x0137
#define ICON_TIME_3                              0x0138
#define ICON_TIME_4                              0x0139
#define ICON_TIME_5                              0x013A
#define ICON_TIME_6                              0x013B
#define ICON_TIME_7                              0x013C
#define ICON_TIME_8                              0x013D
#define ICON_TIME_9                              0x013E
#define ICON_TIME_COLON                          0x013F
#define ICON_TIRE_BG                             0x0140
#define ICON_TIRE_F_ALARM                        0x0141
#define ICON_TIRE_F_NORMAL                       0x0142
#define ICON_TIRE_INFLAT_BG                      0x0143
#define ICON_TIRE_R_ALARM                        0x0144
#define ICON_TIRE_R_NORMAL                       0x0145
#define ICON_TITLE_BAR                           0x0146
#define ICON_TPMS_ALARM                          0x0147
#define ICON_TPMS_BATTERY                        0x0148
#define ICON_TPMS_NORMAL                         0x0149
#define ICON_TRANSPAENT                          0x014A
#define ICON_TV_MODE                             0x014B
#define ICON_U_STOP_ORI                          0x014C
#define ICON_USB                                 0x014D
#define ICON_VERSION                             0x014E
#define ICON_VOICE                               0x014F
#define ICON_VOICE_OFF                           0x0150
#define ICON_VOICE_ON                            0x0151
#define ICON_WARING                              0x0152
#define ICON_WARN_MOVIE_CAPTURE                  0x0153
#define ICON_WB_AUTO                             0x0154
#define ICON_WB_CLOUDY                           0x0155
#define ICON_WB_DAYLIGHT                         0x0156
#define ICON_WB_FLUORESCENT                      0x0157
#define ICON_WB_TUNGSTEN                         0x0158
#define ICON_WDR                                 0x0159
#define ICON_WEST                                0x015A
#define ICON_WIFI                                0x015B
#define ICON_WIFI_CONNECT                        0x015C
#define ICON_WIFI_CONNECTED                      0x015D
#define ICON_WIFI_CONNECTED_SMALL                0x015E
#define ICON_WIFI_DISCONNECTED                   0x015F
#define ICON_WIFI_DOT_CONNECTING_OFF             0x0160
#define ICON_WIFI_DOT_CONNECTING_ON              0x0161
#define ICON_WIFI_FAIL                           0x0162
#define ICON_WIFI_ON                             0x0163
#define ICON_WIFI_ON_M                           0x0164
#define OPEN_EN                                  0x0165
#define OPEN_PAPAGO                              0x0166
#define OPEN_SC                                  0x0167
#define OPEN_TC                                  0x0168
#define BYE_EN                                   0x0169

#endif //_DEMOKIT_IMAGE_H_
