/**
    Copyright   Novatek Microelectronics Corp. 2005.  All rights reserved.

    @file       SoundData.c
    @ingroup    mIPRJAPKey

    @brief      Keypad tone, Startup... sound data
                This file contain the PCM (ADPCM) data of keypad tone, Startup...

    @note       Nothing.

    @date       2005/01/23
*/

/** \addtogroup mIPRJAPKey */
//@{

#ifndef _SOUNDDATA_H
#define _SOUNDDATA_H

#include "PrjCfg.h"

#define AUDIO_SR_8000		8000	///< 8 KHz
#define AUDIO_SR_11025		11025	///< 11.025 KHz
#define AUDIO_SR_12000		12000	///< 12 KHz
#define AUDIO_SR_16000		16000	///< 16 KHz
#define AUDIO_SR_22050		22050	///< 22.05 KHz
#define AUDIO_SR_24000		24000	///< 24 KHz
#define AUDIO_SR_32000		32000	///< 32 KHz
#define AUDIO_SR_44100		44100	///< 44.1 KHz
#define AUDIO_SR_48000		48000	///< 48 KHz

#define ENGLISH_VOICESOUND           	ENABLE
#define ARBIC_VOICESOUND         	DISABLE
#define CHINESE_VOICESOUND         	ENABLE
#define RUSSIAN_VOICESOUND           	ENABLE
#define SPANISH_VOICESOUND         	ENABLE
#define POLISH_VOICESOUND          	ENABLE
#define TURKEY_VOICESOUND             	ENABLE
#define CESKA_VOICESOUND             	ENABLE
#define ROM_VOICESOUND             	ENABLE
#define SLOVEN_VOICESOUND             	ENABLE
#define DEUTSCH_VOICESOUND             	ENABLE
#define JAPANESE_VOICESOUND             	ENABLE
#define ITALIAN_VOICESOUND             	ENABLE
#define FRANCE_VOICESOUND             	ENABLE



typedef enum {
	DEMOSOUND_SOUND_MICEN_TONE=0,
	DEMOSOUND_SOUND_MICDIS_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_TONE,
}DEMOVOICE_DATA_LIST;

typedef enum {
	DEMOSOUND_SOUND_NONE = 0,
	DEMOSOUND_SOUND_KEY_TONE,
#if (ENGLISH_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_ENGLISH_TONE,
	DEMOSOUND_SOUND_MICDIS_ENGLISH_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_ENGLISH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_ENGLISH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_ENGLISH_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_ENGLISH_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_ENGLISH_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_ENGLISH_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_ENGLISH_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_ENGLISH_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_ENGLISH_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_ENGLISH_TONE,
#endif

#if (ARBIC_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_ARBIC_TONE,
	DEMOSOUND_SOUND_MICDIS_ARBIC_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_ARBIC_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_ARBIC_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_ARBIC_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_ARBIC_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_ARBIC_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_ARBIC_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_ARBIC_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_ARBIC_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_ARBIC_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_ARBIC_TONE,
#endif

#if (CHINESE_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_CHINESE_TONE,
	DEMOSOUND_SOUND_MICDIS_CHINESE_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_CHINESE_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_CHINESE_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_CHINESE_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_CHINESE_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_CHINESE_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_CHINESE_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_CHINESE_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_CHINESE_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_CHINESE_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_CHINESE_TONE,
#endif

#if (RUSSIAN_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_RUSSIAN_TONE,
	DEMOSOUND_SOUND_MICDIS_RUSSIAN_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_RUSSIAN_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_RUSSIAN_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_RUSSIAN_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_RUSSIAN_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_RUSSIAN_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_RUSSIAN_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_RUSSIAN_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_RUSSIAN_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_RUSSIAN_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_RUSSIAN_TONE,
#endif

#if (SPANISH_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_SPANISH_TONE,
	DEMOSOUND_SOUND_MICDIS_SPANISH_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_SPANISH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_SPANISH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_SPANISH_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_SPANISH_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_SPANISH_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_SPANISH_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_SPANISH_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_SPANISH_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_SPANISH_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_SPANISH_TONE,
#endif

#if (POLISH_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_POLISH_TONE,
	DEMOSOUND_SOUND_MICDIS_POLISH_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_POLISH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_POLISH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_POLISH_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_POLISH_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_POLISH_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_POLISH_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_POLISH_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_POLISH_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_POLISH_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_POLISH_TONE,
#endif

#if (TURKEY_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_TURKEY_TONE,
	DEMOSOUND_SOUND_MICDIS_TURKEY_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_TURKEY_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_TURKEY_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_TURKEY_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_TURKEY_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_TURKEY_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_TURKEY_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_TURKEY_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_TURKEY_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_TURKEY_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_TURKEY_TONE,
#endif

#if (CESKA_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_CESKA_TONE,
	DEMOSOUND_SOUND_MICDIS_CESKA_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_CESKA_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_CESKA_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_CESKA_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_CESKA_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_CESKA_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_CESKA_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_CESKA_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_CESKA_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_CESKA_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_CESKA_TONE,
#endif

#if (ROM_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_ROM_TONE,
	DEMOSOUND_SOUND_MICDIS_ROM_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_ROM_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_ROM_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_ROM_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_ROM_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_ROM_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_ROM_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_ROM_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_ROM_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_ROM_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_ROM_TONE,
#endif

#if (SLOVEN_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_SLOVEN_TONE,
	DEMOSOUND_SOUND_MICDIS_SLOVEN_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_SLOVEN_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_SLOVEN_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_SLOVEN_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_SLOVEN_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_SLOVEN_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_SLOVEN_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_SLOVEN_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_SLOVEN_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_SLOVEN_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_SLOVEN_TONE,
#endif

#if (DEUTSCH_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_DEUTSCH_TONE,
	DEMOSOUND_SOUND_MICDIS_DEUTSCH_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_DEUTSCH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_DEUTSCH_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_DEUTSCH_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_DEUTSCH_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_DEUTSCH_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_DEUTSCH_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_DEUTSCH_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_DEUTSCH_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_DEUTSCH_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_DEUTSCH_TONE,
#endif

#if (JAPANESE_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_JAPANESE_TONE,
	DEMOSOUND_SOUND_MICDIS_JAPANESE_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_JAPANESE_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_JAPANESE_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_JAPANESE_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_JAPANESE_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_JAPANESE_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_JAPANESE_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_JAPANESE_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_JAPANESE_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_JAPANESE_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_JAPANESE_TONE,
#endif

#if (ITALIAN_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_ITALIAN_TONE,
	DEMOSOUND_SOUND_MICDIS_ITALIAN_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_ITALIAN_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_ITALIAN_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_ITALIAN_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_ITALIAN_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_ITALIAN_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_ITALIAN_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_ITALIAN_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_ITALIAN_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_ITALIAN_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_ITALIAN_TONE,
#endif

#if (FRANCE_VOICESOUND == ENABLE)
	DEMOSOUND_SOUND_MICEN_FRANCE_TONE,
	DEMOSOUND_SOUND_MICDIS_FRANCE_TONE,
	DEMOSOUND_SOUND_MCARDERRORFORMAT_FRANCE_TONE,
	DEMOSOUND_SOUND_MCARDFORMATFAIL_FRANCE_TONE,
	DEMOSOUND_SOUND_MCARDFORMATSUCCESSFUL_FRANCE_TONE,
	DEMOSOUND_SOUND_PARRECORDSTART_FRANCE_TONE,
	DEMOSOUND_SOUND_PINSERTCARD_FRANCE_TONE,
	DEMOSOUND_SOUND_RECORDINGSTART_FRANCE_TONE,
	DEMOSOUND_SOUND_VIDEOPROTECT_FRANCE_TONE,
	DEMOSOUND_SOUND_WIFICONNECT_FRANCE_TONE,
	DEMOSOUND_SOUND_WIFIDISABLE_FRANCE_TONE,
	DEMOSOUND_SOUND_WIFIENADLE_FRANCE_TONE,
#endif



#if(PHOTO_MODE==ENABLE)
	DEMOSOUND_SOUND_SHUTTER_TONE,
#endif
	DEMOSOUND_SOUND_POWERON_TONE,
#if (_ADAS_FUNC_ == ENABLE)
	DEMOSOUND_SOUND_LDWS_TONE,
	DEMOSOUND_SOUND_FCS_TONE,
	DEMOSOUND_SOUND_SNG_TONE,  //STOP and Go
	DEMOSOUND_SOUND_PCW_TONE,
	DEMOSOUND_SOUND_LCAWS_TONE,
	DEMOSOUND_SOUND_RCW_TONE,
	DEMOSOUND_SOUND_VIRTUAL_BUMPERS_TONE,
#endif  // #if (_ADAS_FUNC_ == ENABLE)
//#NT#2016/07/20#Brain Yen -begin
//#NT#DDD alarm sound
#if (_DDD_FUNC_ == ENABLE)
	DEMOSOUND_SOUND_DDDWARNING1_TONE,
	DEMOSOUND_SOUND_DDDWARNING2_TONE,
	DEMOSOUND_SOUND_DDDWARNING3_TONE,
#endif  //#if (_DDD_FUNC_ == ENABLE)
//#NT#2016/07/20#Brain Yen -end
#if (_GPS_EDOG_UNIQUE_SKY_==ENABLE)
	DEMOSOUND_SOUND_EP0_TONE_WRONGDIRECT,//160
	DEMOSOUND_SOUND_EP1_TONE_CAMERA_OVERSPEED,
	DEMOSOUND_SOUND_EP2_TONE_CAMERA_FXIED,
	DEMOSOUND_SOUND_EP3_TONE_RADAR_SPEED_DETECT,
	DEMOSOUND_SOUND_EP4_TONE_CAMERA_BRIDGE_UP,
	DEMOSOUND_SOUND_EP5_TONE_GPS_OK,//Satellite positioning succeeded
	DEMOSOUND_SOUND_EP6_TONE_HIGHWAY_ENTER,
	DEMOSOUND_SOUND_EP7_TONE_OIL_STATION,
	DEMOSOUND_SOUND_EP8_TONE_CAMERA_BRIDGE_FIXED,
	DEMOSOUND_SOUND_EP9_TONE_CAMERA_HIGHWAY_FIXED,//170
	DEMOSOUND_SOUND_EP10_TONE_CAMERA_HIGHWAY_RADAR,
	DEMOSOUND_SOUND_EP11_TONE_BIG_BEND,
	DEMOSOUND_SOUND_EP12_TONE_M,//m //SOUND  NG,no use
	DEMOSOUND_SOUND_EP13_TONE_DIANZIJIANKONG,
	DEMOSOUND_SOUND_EP14_TONE_CAMERA_BRIDGE_DOWN,//
	DEMOSOUND_SOUND_EP15_TONE_SINGLE_ROAD,//
	DEMOSOUND_SOUND_EP16_TONE_TIELUKOU,	//SOUND  NG,no use
	DEMOSOUND_SOUND_EP17_TONE_BUS_ROAD,	
	DEMOSOUND_SOUND_EP18_TONE_DANGE_ROAD,	
	DEMOSOUND_SOUND_EP19_TONE_CAREFULLY_DRIVE,	//180
	DEMOSOUND_SOUND_EP20_TONE_TURNON_LIGHT,	
	DEMOSOUND_SOUND_EP21_TONE,	
	DEMOSOUND_SOUND_EP22_TONE_REST_STATION,
	DEMOSOUND_SOUND_EP23_TONE_HOLE_ENTER,	
	DEMOSOUND_SOUND_EP24_TONE_SELECT_A_ROAD,	
	DEMOSOUND_SOUND_EP25_TONE_SPEED_TEST_START,//Interval Speed Start Point	
	DEMOSOUND_SOUND_EP26_TONE_SCHOOL_AREA,	
	DEMOSOUND_SOUND_EP27_TONE_CHECK_TRAFFIC_LAW,	//
	DEMOSOUND_SOUND_EP28_TONE_FORBID_PARKING,	
	DEMOSOUND_SOUND_EP29_TONE_DOWNHILL,	//
	DEMOSOUND_SOUND_EP30_TONE_JIAOLIUDAO,	
	DEMOSOUND_SOUND_EP31_TONE_FORBID_TURNLEFT,
	DEMOSOUND_SOUND_EP32_TONE_HIGH_BRIDGE_RED_LIGHT,	
	DEMOSOUND_SOUND_EP33_TONE_ON_LINE_PHOTO,	
	DEMOSOUND_SOUND_EP34_TONE_TOLL_STATION,	//SOUND  NG,no use
	DEMOSOUND_SOUND_EP35_TONE_END_TESTSPEED_AREA,	
	DEMOSOUND_SOUND_EP36_TONE_PLEASE_SLOW_DOWN,	
	DEMOSOUND_SOUND_EP37_TONE_DRINK_DRIVE,	
	DEMOSOUND_SOUND_EP38_TONE_GAS_STATION,	//SOUND  NG,no use
	DEMOSOUND_SOUND_EP39_TONE_HIGHWAY_EXIT,	//200
	DEMOSOUND_SOUND_EP42_TONE_DIDONG,//edog start point 	
	DEMOSOUND_SOUND_EP43_TONE_DONDDD,//edog end point	60
	DEMOSOUND_SOUND_EP44_TONE_CARE_FRONT1,//注意前有
	DEMOSOUND_SOUND_EP45_TONE_FRONT,	//前方//
	DEMOSOUND_SOUND_EP46_TONE_CARE_FRONT2,//注意前为   
	DEMOSOUND_SOUND_EP51_TONE_OVERSPEED,//You have exceeded the speed limit.  
	DEMOSOUND_SOUND_EP75_TONE_100,//100
	DEMOSOUND_SOUND_EP76_TONE_200,//200   
	DEMOSOUND_SOUND_EP77_TONE_300,//300  
	DEMOSOUND_SOUND_EP78_TONE_400,//400  //210 
	DEMOSOUND_SOUND_EP79_TONE_500,//500   
	DEMOSOUND_SOUND_EP80_TONE_600,//600 
	DEMOSOUND_SOUND_EP81_TONE_700,//700    
	DEMOSOUND_SOUND_EP82_TONE_800,//800   
	DEMOSOUND_SOUND_EP87_TONE_20KM,//20 km speed limit
	DEMOSOUND_SOUND_EP88_TONE_30KM,//30 km speed limit   
	DEMOSOUND_SOUND_EP89_TONE_40KM,//40 km speed limit	
	DEMOSOUND_SOUND_EP90_TONE_50KM,//50 km speed limit	
	DEMOSOUND_SOUND_EP91_TONE_60KM,//60 km speed limit
	DEMOSOUND_SOUND_EP92_TONE_70KM,//70 km speed limit 220 
	DEMOSOUND_SOUND_EP93_TONE_80KM,//80 km speed limit
	DEMOSOUND_SOUND_EP94_TONE_90KM,//90 km speed limit
	DEMOSOUND_SOUND_EP95_TONE_100KM,//100 km speed limit NG END
	DEMOSOUND_SOUND_EP96_TONE_110KM,//110 km speed limit NGEND
	DEMOSOUND_SOUND_EP97_TONE_120KM,//120 km speed limit 
	DEMOSOUND_SOUND_KEJIZHIFA,//kejizhifa 
	DEMOSOUND_SOUND_XIANSU,//kejizhifa  
#endif
	DEMOSOUND_SOUND_DDD_TONE,//key sound data

	DEMOSOUND_SOUND_MAX_CNT
}
DEMOSOUND_DATA_LIST;


extern void UISound_RegTable(void);
extern void UISound_EnableKey(BOOL bEn);
extern void UISound_Play(UINT32 index);
extern void UIVoice_Play(UINT32 index);


extern void DogSoundPlayID(UINT32 SoID);
extern void DogSoundCycPlay(void);
extern void UIDogSound_Enable(BOOL bEn);

#endif

//@}
