#include "PrjInc.h"
#include "UIWnd/UIFlow.h"

// --------------------------------------------------------------------------
// OPTIONS
// --------------------------------------------------------------------------
// MOVIE_SIZE_TAG
// Movie Size Options
TMDEF_BEGIN_OPTIONS(MOVIE_SIZE)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,				TM_OPTION_ENABLE)	
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,				TM_OPTION_ENABLE)	
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,				TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P60,				TM_OPTION_ENABLE)	
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,				TM_OPTION_ENABLE)	
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,				TM_OPTION_ENABLE)	
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,				TM_OPTION_ENABLE)	
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30,	TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30,	TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,	TM_OPTION_ENABLE)

TMDEF_END_OPTIONS()

// Cyclic recroding Options
TMDEF_BEGIN_OPTIONS(MOVIE_CYCLIC_REC)
//TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_1MIN, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_2MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_3MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_5MIN, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_10MIN, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_HDR)
TMDEF_OPTION_TEXT_S(MOVIE_HDR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_HDR_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_HDR_DET)
TMDEF_OPTION_TEXT_S(MOVIE_HDR_DET_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_HDR_DET_ON, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(MOVIE_HDR_DET_AUTO, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_WDR)
TMDEF_OPTION_TEXT_S(MOVIE_WDR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_WDR_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_MOTION_DET)
TMDEF_OPTION_TEXT_S(MOVIE_MOTION_DET_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_MOTION_DET_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_AUDIO)
TMDEF_OPTION_TEXT_S(MOVIE_AUDIO_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_AUDIO_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DATEIMPRINT)
TMDEF_OPTION_TEXT_S(MOVIE_DATEIMPRINT_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DATEIMPRINT_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_RSC)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_RSC_EFFECT)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_LOW, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_MED, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_HIGH, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_SUPER_HIGH, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_GSENSOR)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_LOW, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_MED, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_HIGH, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_TIMELAPSE_REC)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_5SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_10SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_30SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_5MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_10MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_30MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1HOUR, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_2HOUR, TM_OPTION_NOT_SUPPORT)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_3HOUR, TM_OPTION_NOT_SUPPORT)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1DAY, TM_OPTION_NOT_SUPPORT)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_IR_CUT)
TMDEF_OPTION_TEXT_S(MOVIE_IR_CUT_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_IR_CUT_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_SENSOR_ROTATE)
TMDEF_OPTION_TEXT_S(MOVIE_SENSOR_ROTATE_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SENSOR_ROTATE_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_PTZ)
TMDEF_OPTION_TEXT_S(MOVIE_PTZ_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_PTZ_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_URGENT_PROTECT_AUTO)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_AUTO_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_AUTO_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_URGENT_PROTECT_MANUAL)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_MANUAL_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_MANUAL_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_PIM)
TMDEF_OPTION_TEXT_S(MOVIE_PIM_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_PIM_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_LDWS)
TMDEF_OPTION_TEXT_S(MOVIE_LDWS_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_LDWS_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_FCW)
TMDEF_OPTION_TEXT_S(MOVIE_FCW_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_FCW_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DDD)
TMDEF_OPTION_TEXT_S(MOVIE_DDD_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DDD_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_ADAS_CAL)
TMDEF_OPTION_TEXT_S(MOVIE_ADAS_CAL_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_ADAS_CAL_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DUAL_CAM)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_FRONT, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_BEHIND, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_BOTH, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_BOTH2, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_CODEC)
TMDEF_OPTION_TEXT_S(MOVIE_H264, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_H265, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(MOVIE_MJPG, TM_OPTION_DISABLE)
TMDEF_END_OPTIONS()

// Sensor Rotate
TMDEF_BEGIN_OPTIONS(SENSOR_ROTATE)
    TMDEF_OPTION_TEXT_S(SEN_ROTATE_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SEN_ROTATE_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Sensor2 Rotate
TMDEF_BEGIN_OPTIONS(SENSOR2_ROTATE)
    TMDEF_OPTION_TEXT_S(SEN_ROTATE_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SEN_ROTATE_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Timelapse recroding Options
TMDEF_BEGIN_OPTIONS(MOVIE_TIMERLAPS)
    TMDEF_OPTION_TEXT_S(MOVIE_TIMER_LAPS_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_TIMER_LAPS_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Power Saving Options
TMDEF_BEGIN_OPTIONS(AUTO_POWER_OFF)
    TMDEF_OPTION_TEXT_S(OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(1MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(2MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(3MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(5MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(10MIN, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Beep Options
TMDEF_BEGIN_OPTIONS(BEEP)
    TMDEF_OPTION_TEXT_S(BEEP_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(BEEP_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Volume Options
TMDEF_BEGIN_OPTIONS(VOLUME)
	TMDEF_OPTION_TEXT_S(VOLUME20,TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(VOLUME40,TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(VOLUME60,TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(VOLUME80,TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(VOLUME100,TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(MUTE,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Language Options
TMDEF_BEGIN_OPTIONS(LANGUAGE)
#if (!defined(COUNTRY_JP))
    TMDEF_OPTION_TEXT_S(LANG_TC, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_SC, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_EN, TM_OPTION_ENABLE)
#else
	TMDEF_OPTION_TEXT_S(LANG_JP, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(LANG_SC, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(LANG_EN, TM_OPTION_ENABLE)
#endif
    /*
    TMDEF_OPTION_TEXT_S(LANG_FR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_ES, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_DE, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_IT, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_JP, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_PO, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LANG_RU, TM_OPTION_ENABLE)
    */
TMDEF_END_OPTIONS()
// EV Options
TMDEF_BEGIN_OPTIONS(EV2)
//TMDEF_OPTION_TEXT_S(EV_P20, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(EV_P16, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(EV_P13, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_N10, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_N06, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_N03, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_00, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_P03, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_P06, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(EV_P10, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(EV_N13, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(EV_N16, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(EV_N20, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()
TMDEF_BEGIN_OPTIONS(MOVIE_VOICE)
TMDEF_OPTION_TEXT_S(MOVIE_VOICE_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_VOICE_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(ASR)
TMDEF_OPTION_TEXT_S(ASR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(ASR_STANDARD, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(ASR_LOW, TM_OPTION_DISABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(ASR_CONTENT)
TMDEF_OPTION_TEXT_S(ASR_TAKEPHOTO, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(ASR_VIDEOSTART, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(ASR_VIDEOSTOP, TM_OPTION_DISABLE)
TMDEF_OPTION_TEXT_S(ASR_TURNONAUDIO, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(ASR_TURNOFFAUDIO, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(ASR_TURNONSCREEN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(ASR_TURNOFFSCREEN, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(ASR_TURNONHOTSPOT, TM_OPTION_DISABLE)
//TMDEF_OPTION_TEXT_S(ASR_TURNOFFHOTSPOT, TM_OPTION_DISABLE)
//TMDEF_OPTION_TEXT_S(ASR_LOCKVIDEO, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(ASR_TURNONWIFI, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(ASR_TURNOFFWIFI, TM_OPTION_ENABLE)
//TMDEF_OPTION_TEXT_S(ASR_SHOW_FRONT_CAMERA , TM_OPTION_DISABLE)
//TMDEF_OPTION_TEXT_S(ASR_SHOW_REAR_CAMERA, TM_OPTION_DISABLE)
//TMDEF_OPTION_TEXT_S(ASR_SHOW_BOTH_CAMERAS, TM_OPTION_DISABLE)
//TMDEF_OPTION_TEXT_S(ASR_INSIDE_VIDEO_ON, TM_OPTION_DISABLE)
//TMDEF_OPTION_TEXT_S(ASR_BACK_TO_HOMEPAGE , TM_OPTION_DISABLE)
TMDEF_END_OPTIONS()

// TV Mode Options
TMDEF_BEGIN_OPTIONS(TV_MODE)
    TMDEF_OPTION_TEXT_S(TV_NTSC, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(TV_PAL, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Frequency Options
TMDEF_BEGIN_OPTIONS(FREQUENCY)
    TMDEF_OPTION_TEXT_S(50HZ, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(60HZ, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Screen Saver
TMDEF_BEGIN_OPTIONS(SCREEN_SAVE)
    TMDEF_OPTION_TEXT_S(AUTO_OFF_OFF, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(AUTO_OFF_1SEC, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(AUTO_OFF_3SEC, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(AUTO_OFF_15SEC, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(AUTO_OFF_30SEC, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(AUTO_OFF_1MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(AUTO_OFF_3MIN, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(AUTO_OFF_5MIN, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(AUTO_OFF_10MIN, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// GPS Options
TMDEF_BEGIN_OPTIONS(GPS)
    TMDEF_OPTION_TEXT_S(GPS_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GPS_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

//Disable GPS in ParkingMode
TMDEF_BEGIN_OPTIONS(PARKINGMODE_DISABLE_GPS)
    TMDEF_OPTION_TEXT_S(PARKINGMODE_DISABLE_GPS_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(PARKINGMODE_DISABLE_GPS_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Time Zone
TMDEF_BEGIN_OPTIONS(TIME_ZONE)
    TMDEF_OPTION_TEXT_S(GMT_0, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P1, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P2, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P3, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P3_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P4, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P4_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P5, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P5_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P6, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(GMT_P6_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P7, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P8, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P9, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P9_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P10, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P10_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P11, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P12, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_P13, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M1, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M2, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(GMT_M2_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M3, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M3_30, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M4, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M5, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M6, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M7, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M8, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M9, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M10, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M11, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(GMT_M12, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Speed Unit
TMDEF_BEGIN_OPTIONS(SPEED_UNIT)
    TMDEF_OPTION_TEXT_S(SPEED_MPH,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SPEED_KPH,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// LED
TMDEF_BEGIN_OPTIONS(LED)
    TMDEF_OPTION_TEXT_S(LED_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(LED_ON,TM_OPTION_ENABLE)    
TMDEF_END_OPTIONS()

// Format Warning
TMDEF_BEGIN_OPTIONS(FORMAT_WARNING)
	TMDEF_OPTION_TEXT_S(FORMAT_WARNING_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(FORMAT_WARNING_15_DAY,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(FORMAT_WARNING_30_DAY,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(FORMAT_WARNING_60_DAY,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Wi-Fi
TMDEF_BEGIN_OPTIONS(WIFI)
    //TMDEF_OPTION_TEXT_S(WIFI_OFF, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(WIFI_ON, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(WIFI_ON_24G, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(WIFI_ON_52G, TM_OPTION_ENABLE)
    //5.8G 149 channel
    TMDEF_OPTION_TEXT_S(WIFI_ON_58G, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Boot Delay
TMDEF_BEGIN_OPTIONS(BOOT_DELAY)
    TMDEF_OPTION_TEXT_S(BOOT_DELAY_5SEC,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(BOOT_DELAY_15SEC,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(BOOT_DELAY_30SEC,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// GPS Stamp
TMDEF_BEGIN_OPTIONS(GPS_STAMP)
    TMDEF_OPTION_TEXT_S(GPS_STAMP_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(BOTH,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(COORDINATES,TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(SPEED,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Model Stamp
TMDEF_BEGIN_OPTIONS(MODEL_STAMP)
    TMDEF_OPTION_TEXT_S(MODEL_STAMP_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MODEL_STAMP_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Parking Mode
TMDEF_BEGIN_OPTIONS(PARKING_MODE)
    TMDEF_OPTION_TEXT_S(PARKING_MODE_OFF, TM_OPTION_ENABLE)    
    TMDEF_OPTION_TEXT_S(PARKING_MODE_ON_1FPS, TM_OPTION_ENABLE)
	//TMDEF_OPTION_TEXT_S(PARKING_MODE_MOTION_DET, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(PARKING_MODE_LOW_BITRATE, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(PARKING_MODE_ON_2FPS, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(PARKING_MODE_ON_3FPS, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(PARKING_MODE_ON_5FPS, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(PARKING_MODE_ON_10FPS, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(PARKING_MODE_ON_15FPS, TM_OPTION_ENABLE)
	//TMDEF_OPTION_TEXT_S(PARKING_MODE_GSENSOR_DET, TM_OPTION_ENABLE)
	//TMDEF_OPTION_TEXT_S(PARKING_MODE_MOTION_GSENSOR_DET, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Parking Mode G-Sensor
TMDEF_BEGIN_OPTIONS(PARKING_GSENSOR)
	//TMDEF_OPTION_TEXT_S(PARKING_GSENSOR_OFF, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(PARKING_GSENSOR_LOW, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(PARKING_GSENSOR_MED, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(PARKING_GSENSOR_HIGH, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()
	
// Parking Mode Motion Detect
TMDEF_BEGIN_OPTIONS(PARKING_MOTION_DET)
	//TMDEF_OPTION_TEXT_S(PARKING_MOTIONDET_OFF, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(PARKING_MOTIONDET_LOW, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(PARKING_MOTIONDET_MED, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(PARKING_MOTIONDET_HIGH, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Movie Bitrate
TMDEF_BEGIN_OPTIONS(MOVIE_BITRATE)
    TMDEF_OPTION_TEXT_S(MOVIE_BITRATE_HIGH, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_BITRATE_MED, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_BITRATE_LOW, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Video Format
TMDEF_BEGIN_OPTIONS(VIDEO_FORMAT)
    TMDEF_OPTION_TEXT_S(VIDEO_FORMAT_TS, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(VIDEO_FORMAT_MP4, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// IR Rear Color
TMDEF_BEGIN_OPTIONS(IR_REAR_COLOR)
    TMDEF_OPTION_TEXT_S(IR_REAR_COLOR_BW, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(IR_REAR_COLOR_AUTO, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(IR_REAR_COLOR_NORMAL, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Rear Sensor Mirror
TMDEF_BEGIN_OPTIONS(REAR_SENSOR_MIRROR)
    TMDEF_OPTION_TEXT_S(REAR_SENSOR_MIRROR_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(REAR_SENSOR_MIRROR_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Shutdown Timer
TMDEF_BEGIN_OPTIONS(SHUTDOWN_TIMER)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_OFF, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_5MIN, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_10MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_30MIN, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_1HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_2HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_3HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_4HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_6HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_8HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_12HOUR, TM_OPTION_ENABLE)
    //TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_18HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_24HOUR, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(SHUTDOWN_TIMER_48HOUR, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// Enter Parking Timer
TMDEF_BEGIN_OPTIONS(ENTER_PARKING_TIMER)
    TMDEF_OPTION_TEXT_S(ENTER_PARKING_TIMER_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(ENTER_PARKING_TIMER_90SEC, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()
TMDEF_BEGIN_OPTIONS(AMBIANCE_LIGHT)
	TMDEF_OPTION_TEXT_S(AMBIANCE_LIGHT_OFF, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(AMBIANCE_LIGHT_ON, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(AMBIANCE_LIGHT_BREATH, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(AMBIANCE_LIGHT_ON_OFF, TM_OPTION_ENABLE)
	TMDEF_OPTION_TEXT_S(AMBIANCE_LIGHT_INTERIOR, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

// EDOG set up
TMDEF_BEGIN_OPTIONS(EDOG_MODE)
    TMDEF_OPTION_TEXT_S(EDOG_MODE_OFF, TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(EDOG_MODE_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()


// --------------------------------------------------------------------------
// ITEMS
// --------------------------------------------------------------------------
/*
static int MenuCustom_MovieSize(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndMovieSizeCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_MovieEV(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndMovieEVCtrl, 0);
    return TMF_PROCESSED;
}*/

static int MenuCustom_DateTime(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupDateTimeCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_Format(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_Default(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupDefaultSettingCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_Version(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupVersionCtrl, 0);
    return TMF_PROCESSED;
}


static int MenuCustom_GPSStatus(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupGPSCtrl, 0);
    return TMF_PROCESSED;
}
/*
static int MenuCustom_CarNo(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupCarNoCtrl, 0);
    return TMF_PROCESSED;
}
static int MenuCustom_Customize(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupCustomizeCtrl, 0);
    return TMF_PROCESSED;
}
*/
// Movie Menu Items
TMDEF_BEGIN_ITEMS(MOVIE)
    TMDEF_ITEM_TEXTID(MOVIE_SIZE)
    //TMDEF_ITEM_CUSTOM(MOVIE_SIZE, MenuCustom_MovieSize)
    //TMDEF_ITEM_TEXTID(MOVIE_BITRATE)
    //TMDEF_ITEM_TEXTID(VIDEO_FORMAT)
#if ((SENSOR_CAPS_COUNT > 1)||((ETH_REARCAM_CAPS_COUNT+SENSOR_CAPS_COUNT)  == 2))
	TMDEF_ITEM_TEXTID(MOVIE_DUAL_CAM)
#endif
#if (SHDR_FUNC == ENABLE)
	TMDEF_ITEM_TEXTID(MOVIE_HDR)
	//TMDEF_ITEM_TEXTID(MOVIE_HDR_DET)
#endif
    TMDEF_ITEM_TEXTID(MOVIE_CYCLIC_REC)
	TMDEF_ITEM_CUSTOM(DATE_TIME, MenuCustom_DateTime)
    TMDEF_ITEM_TEXTID(WIFI)
    TMDEF_ITEM_TEXTID(MOVIE_AUDIO)
    TMDEF_ITEM_TEXTID(VOLUME)//TBD_HTK
    //TMDEF_ITEM_TEXTID(MOVIE_WDR)
    TMDEF_ITEM_TEXTID(PARKING_MODE)
    //TMDEF_ITEM_TEXTID(ENTER_PARKING_TIMER)
    //TMDEF_ITEM_TEXTID(SHUTDOWN_TIMER)
    //TMDEF_ITEM_TEXTID(PARKING_GSENSOR)
    //TMDEF_ITEM_TEXTID(PARKING_MOTION_DET)
    //TMDEF_ITEM_TEXTID(MOVIE_TIMELAPSE_REC)
    //TMDEF_ITEM_TEXTID(MOVIE_CODEC)
    //TMDEF_ITEM_TEXTID(MOVIE_MOTION_DET)
    //TMDEF_ITEM_TEXTID(GPS)
    //TMDEF_ITEM_TEXTID(PARKINGMODE_DISABLE_GPS)
	TMDEF_ITEM_TEXTID(MOVIE_GSENSOR)
	TMDEF_ITEM_TEXTID(MOVIE_DATEIMPRINT)
    TMDEF_ITEM_TEXTID(REAR_SENSOR_MIRROR)
#if (PHOTO_MODE == ENABLE)
	TMDEF_ITEM_TEXTID(EV)
	//TMDEF_ITEM_TEXTID(EV2)
	//TMDEF_ITEM_CUSTOM(EV, MenuCustom_MovieEV)
#endif
    //TMDEF_ITEM_TEXTID(EDOG_MODE)
    TMDEF_ITEM_TEXTID(BEEP)
    //TMDEF_ITEM_TEXTID(MOVIE_SENSOR_ROTATE)
    TMDEF_ITEM_TEXTID(SCREEN_SAVE)
    TMDEF_ITEM_TEXTID(LANGUAGE)
    TMDEF_ITEM_TEXTID(SPEED_UNIT)
    TMDEF_ITEM_TEXTID(GPS_STAMP)
    //TMDEF_ITEM_TEXTID(MODEL_STAMP)
    //TMDEF_ITEM_TEXTID(BOOT_DELAY)
    //TMDEF_ITEM_TEXTID(LED)
    //TMDEF_ITEM_TEXTID(MOVIE_TIMERLAPS)
    TMDEF_ITEM_TEXTID(TIME_ZONE)
    TMDEF_ITEM_TEXTID(MOVIE_VOICE)
    TMDEF_ITEM_TEXTID(ASR)
   	TMDEF_ITEM_TEXTID(ASR_CONTENT)
    //TMDEF_ITEM_TEXTID(AUTO_POWER_OFF)
    TMDEF_ITEM_TEXTID(FREQUENCY)
#if TV_FUNC
    //TMDEF_ITEM_TEXTID(TV_MODE)
#endif

    TMDEF_ITEM_CUSTOM(GPS_STATUS1, MenuCustom_GPSStatus)
    TMDEF_ITEM_CUSTOM(FORMAT, MenuCustom_Format)
    TMDEF_ITEM_TEXTID(FORMAT_WARNING)
    TMDEF_ITEM_CUSTOM(DEFAULT, MenuCustom_Default)
    //TMDEF_ITEM_CUSTOM(CARNO, MenuCustom_CarNo)
    //TMDEF_ITEM_CUSTOM(CUSTOMIZE, MenuCustom_Customize)
    TMDEF_ITEM_CUSTOM(VERSION, MenuCustom_Version)
#if (MOVIE_EIS == ENABLE)
	TMDEF_ITEM_TEXTID(MOVIE_RSC)
	TMDEF_ITEM_TEXTID(MOVIE_RSC_EFFECT)
#endif
	////TMDEF_ITEM_TEXTID(MOVIE_IR_CUT)
	////TMDEF_ITEM_TEXTID(MOVIE_PTZ)
	//TMDEF_ITEM_TEXTID(MOVIE_URGENT_PROTECT_AUTO)
	//TMDEF_ITEM_TEXTID(MOVIE_URGENT_PROTECT_MANUAL)
	//TMDEF_ITEM_TEXTID(MOVIE_PIM)
	////TMDEF_ITEM_TEXTID(MOVIE_LDWS)
	////TMDEF_ITEM_TEXTID(MOVIE_FCW)
	////TMDEF_ITEM_TEXTID(MOVIE_DDD)
	////TMDEF_ITEM_TEXTID(MOVIE_ADAS_CAL)
TMDEF_END_ITEMS()

// --------------------------------------------------------------------------
// PAGES
// --------------------------------------------------------------------------
// Movie Menu Pages
TMDEF_BEGIN_PAGES(MOVIE)
TMDEF_PAGE_TEXT_ICON(MOVIE)
TMDEF_END_PAGES()

TMDEF_EMNU(gMovieMenu, MOVIE, Movie_MenuCallback)

// --------------------------------------------------------------------------
// Menu Callback
// --------------------------------------------------------------------------
int Movie_MenuCallback(UINT32 uiMessage, UINT32 uiParam)
{
	UINT16  uwItemId;
	UINT16  uwOption;

	if (uiMessage == TMM_CONFIRM_OPTION) {
		uwItemId = LO_WORD(uiParam);
		uwOption = HI_WORD(uiParam);

		switch (uwItemId) {
		case IDM_MOVIE_SIZE:
			//Set Movie size event until menu is closed.
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, uwOption);
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_IMAGE_RATIO, 1, GetMovieSizeRatio(UI_GetData(FL_MOVIE_SIZE)));
			break;

		case IDM_MOVIE_CYCLIC_REC:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_CYCLIC_REC, 1, uwOption);
			break;

		case IDM_MOVIE_WDR:
#if(!defined(_NVT_ETHREARCAM_RX_))//67x tx must cvhg movie mode
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_WDR, 1, uwOption);
#endif
			break;

		case IDM_MOVIE_HDR:
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_SHDR, 1, uwOption);
			break;
		case IDM_MOVIE_HDR_DET:
			if ((SysGetFlag(FL_MOVIE_HDR_DET) == MOVIE_HDR_DET_OFF) || (SysGetFlag(FL_MOVIE_HDR_DET) == MOVIE_HDR_DET_ON)) {
				SysSetFlag(FL_MOVIE_HDR_MENU, SysGetFlag(FL_MOVIE_HDR_DET));
			}
			break;

		case IDM_EV:
#if (PHOTO_MODE==ENABLE)
			Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_EV, 1, uwOption);
#endif
			break;

		case IDM_MOVIE_MOTION_DET:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOTION_DET, 1, uwOption);
			break;

		case IDM_MOVIE_AUDIO:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_AUDIO, 1, uwOption);
			break;

		case IDM_MOVIE_VOICE:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_VOICE, 1, uwOption);
			break;

		case IDM_MOVIE_DATEIMPRINT:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_DATE_IMPRINT, 1, uwOption);
			break;

		case IDM_MOVIE_RSC:
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_RSC, 1, uwOption);
			break;

		case IDM_MOVIE_GSENSOR:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_GSENSOR, 1, uwOption);
			break;

		case IDM_MOVIE_TIMELAPSE_REC:
			//#NT#2016/09/20#KCHong -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
			//SysSetFlag(FL_MOVIE_TIMELAPSE_REC,uwOption);
			//#NT#2016/09/20#KCHong -end
			break;

		case IDM_MOVIE_IR_CUT:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_IR_CUT, 1, uwOption);
			break;

		case IDM_MOVIE_SENSOR_ROTATE:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_SENSOR_ROTATE, 1, uwOption);
			break;

		case IDM_MOVIE_PTZ:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_PTZ, 1, uwOption);
			break;

		case IDM_MOVIE_URGENT_PROTECT_AUTO:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_PROTECT_AUTO, 1, uwOption);
			break;

		case IDM_MOVIE_URGENT_PROTECT_MANUAL:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_PROTECT_MANUAL, 1, uwOption);
			break;

		case IDM_MOVIE_PIM:
			SysSetFlag(FL_MOVIE_PIM, uwOption);
			break;

		case IDM_MOVIE_LDWS:
			//#NT#2016/10/12#KCHong#[0111054] -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_LDWS, 1, uwOption);
			//#NT#2016/10/12#KCHong#[0111054] -end
			break;

		case IDM_MOVIE_FCW:
			//#NT#2016/10/12#KCHong#[0111054] -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_FCW, 1, uwOption);
			//#NT#2016/10/12#KCHong#[0111054] -end
			break;

		case IDM_MOVIE_DDD:
			break;

		case IDM_MOVIE_DUAL_CAM:
			break;

		case IDM_MOVIE_ADAS_CAL:
			break;

		case IDM_MOVIE_CODEC:
			//mark for jira IVOT_N12078_CO-77
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_CODEC, 1, uwOption);
			break;

		case IDM_AUTO_POWER_OFF:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_POWEROFF, 1, uwOption);
			break;

		case IDM_SCREEN_SAVE:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LCDOFF, 1, uwOption);
			break;

		case IDM_BEEP:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_BEEPKEY, 1, uwOption);
			break;

		case IDM_LANGUAGE:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LANGUAGE, 1, uwOption);
			break;

		case IDM_TV_MODE:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_TVFORMAT, 1, uwOption);
			break;

		case IDM_FREQUENCY:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_FREQ, 1, uwOption);
			break;

        case IDM_TIME_ZONE:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_TIMEZONE, 1, uwOption);
            break;

        case IDM_SPEED_UNIT:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_SPEED_UNIT, 1, uwOption);
            break;

        case IDM_LED:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LED, 1, uwOption);
            break;

        case IDM_FORMAT_WARNING:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_FORMAT_WARNING, 1, uwOption);
            break;

        case IDM_WIFI:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI_OFF_ON, 1, uwOption);
            break;

        case IDM_MOVIE_BITRATE:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_BITRATE, 1, uwOption);
            break;

        case IDM_VIDEO_FORMAT:
            break;

        case IDM_PARKING_MODE:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_PARKING_MODE, 1, uwOption);
            break;

		case IDM_PARKING_GSENSOR:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_PARKING_GSENSOR, 1, uwOption);
			break;

		case IDM_PARKING_MOTION_DET:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_PARKING_MOTION_DET, 1, uwOption);
			break;

        case IDM_IR_REAR_COLOR:
            //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_IR_REAR_COLOR, 1, uwOption);
            break;

        case IDM_REAR_SENSOR_MIRROR:
            Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_SENSOR_ROTATE, 1, SysGetFlag(FL_MOVIE_SENSOR_ROTATE));//uwOption
            break;

        case IDM_ENTER_PARKING_TIMER:
			Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_ENTER_PARKING_TIMER, 1, uwOption);
            break;

		default:
			//Setup_MenuCallback(uiMessage, uiParam);
			break;
		}
	}

	return TMF_PROCESSED;
}
