//This source code is generated by UI Designer Studio.

#include "PrjInc.h"
#include "UIWnd/UIFlow.h"
#include "MenuCommonOptionRes.c"
#include "MenuCommonOption.h"
#include "DxInput.h"
//---------------------MenuCommonOptionCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption)
CTRL_LIST_ITEM(MenuCommonOption_Panel)
CTRL_LIST_ITEM(MenuCommonOption_PageNum)
CTRL_LIST_END

//----------------------MenuCommonOptionCtrl Event---------------------------
INT32 MenuCommonOption_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_OnBatteryLow(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(MenuCommonOption)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonOption_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonOption_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,MenuCommonOption_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,MenuCommonOption_OnKeyLeft)
//EVENT_ITEM(NVTEVT_KEY_MENU,MenuCommonOption_OnKeyMenu)
//EVENT_ITEM(NVTEVT_KEY_MODE,MenuCommonOption_OnKeyMode)
//EVENT_ITEM(NVTEVT_KEY_SHUTTER2,MenuCommonOption_OnKeyShutter2)
EVENT_END

static UINT32 g_uiMenuCommonOption_Sel = 0;
static UINT8  g_Option_PageNumBuf[8];

void MenuCommonOption_CalcPageInfo(VControl *pCtrl,UINT32 Sel)
{
    UINT32  i, uiItem, uiCurrItem, uiTotalItem, uiTotalItemOri;
    UINT32  uiItemPerPage, uiCurrPage, uiTotalPage;

    #if 0
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;

    pPage = &pMenu->pPages[pMenu->SelPage];
    pItem = &pPage->pItems[pPage->SelItem];
    #endif

    uiItem = UxMenu_GetData(pCtrl, MNU_CURITM);          // current item number in menu (include disabled items)
    uiItemPerPage = UxMenu_GetData(pCtrl, MNU_PAGEITEM); // items per page
    uiTotalItemOri = UxMenu_GetData(pCtrl, MNU_TOTITM);  // total item number

    // check total item number and current item number (skip disabled items)
    uiCurrItem = 0;
    uiTotalItem = 0;

    for (i = 0; i < uiTotalItemOri; i++) {
        if (UxMenu_GetItemData(pCtrl, i, MNUITM_STATUS) == STATUS_ENABLE) {
            uiTotalItem++;
            if (i < uiItem)
                uiCurrItem++;
        }
    }

    uiCurrPage = (uiCurrItem / uiItemPerPage) + 1;
    uiTotalPage = ((uiTotalItem % uiItemPerPage) == 0) ? (uiTotalItem / uiItemPerPage) : (uiTotalItem / uiItemPerPage + 1);

    //debug_msg("*** uiTotalPage= %d ***\r\n",uiTotalPage);
    if (1)//(uiTotalPage > 1)
    {
        sprintf((char *)g_Option_PageNumBuf, "%02d/%02d", uiCurrPage, uiTotalPage);
        UxStatic_SetData(&MenuCommonOption_PageNumCtrl, STATIC_VALUE, Txt_Pointer(g_Option_PageNumBuf));
        UxCtrl_SetShow(&MenuCommonOption_PageNumCtrl, TRUE);
        UxCtrl_SetDirty(&MenuCommonOption_PageNumCtrl, TRUE);
    }
    else
    {
        UxCtrl_SetShow(&MenuCommonOption_PageNumCtrl, FALSE);
    }
}

void MenuCommonOption_UpdateContent(TM_MENU* pMenu)
{
    UINT32      i;
    UINT32      j;
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    TM_OPTION*  pOption;

    pPage = &pMenu->pPages[pMenu->SelPage];
    pItem = &pPage->pItems[pPage->SelItem];

    UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_TOTITM, pItem->Count);
    for (i = 0; i < pItem->Count; i++) {
    pOption = &pItem->pOptions[i];

    //tab option status to menu status
    if ((pOption->Status & TM_OPTION_STATUS_MASK) == TM_OPTION_ENABLE) {
        UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);
    } else {
        UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STATUS, STATUS_DISABLE);
    }

	#if (SENSOR_CAPS_COUNT==2)
    if (pItem->ItemId == IDM_MOVIE_SIZE) {
        if (System_GetEnableSensor() == (SENSOR_1|SENSOR_2)) {
            for (j = 0; j < MOVIE_SIZE_ID_MAX; j++)
            {
                UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, j, MNUITM_STATUS, STATUS_DISABLE);//|STATUS_FOCUS_DISABLE
            }
            for (j = MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30; j < MOVIE_SIZE_ID_MAX; j++)
            {
                UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, j, MNUITM_STATUS, STATUS_ENABLE);
            }                
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_ICONID, pOption->IconId);
        } 
		else
        {
            //g_uiMenuCommonOption_Sel = 0;  //for display show
            for (j = 0; j < MOVIE_SIZE_ID_MAX; j++)
            {
                UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, j, MNUITM_STATUS, STATUS_DISABLE);//|STATUS_FOCUS_DISABLE
            }
            for (j = 0; j < MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30; j++)
            {
                UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, j, MNUITM_STATUS, STATUS_ENABLE);
            }                
			//UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
			//UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_ICONID, pOption->IconId);

			//H.265 support 4K
			/*
			if (SysGetFlag(FL_MOVIE_CODEC) == MOVIE_CODEC_H265) {
				UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, 0, MNUITM_STATUS, STATUS_ENABLE);
			} else {
				UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, 0, MNUITM_STATUS, STATUS_DISABLE);//|STATUS_FOCUS_DISABLE
			}
			//HDR not support 2KP60,2KP60 21:9
			if (SysGetFlag(FL_MOVIE_HDR_MENU) == MOVIE_HDR_ON) {
				UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, MOVIE_SIZE_FRONT_2560x1440P60, MNUITM_STATUS, STATUS_DISABLE);//|STATUS_FOCUS_DISABLE
				//UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, MOVIE_SIZE_FRONT_2560x1080P60, MNUITM_STATUS, STATUS_DISABLE);//|STATUS_FOCUS_DISABLE
				UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, MOVIE_SIZE_FRONT_1920x1080P60, MNUITM_STATUS, STATUS_DISABLE);//|STATUS_FOCUS_DISABLE 
				UI_SetData(FL_MOVIE_HDR_STATECHANGE, MOVIE_HDR_STATE_DISCHANGE);
			}*/
			UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
			UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_ICONID, pOption->IconId);
        }
    } else 
    #endif
	if (pItem->ItemId == IDM_MOVIE_DUAL_CAM) 
	{
		//if(GPIOMap_EthCam1Det()){ 
        if (System_GetEnableSensor() == (SENSOR_1|SENSOR_2)) {
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STATUS, STATUS_ENABLE);//|STATUS_NORMAL_BIT
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  pOption->TextId);
        } 
		else
		{
            g_uiMenuCommonOption_Sel = 0;  //for display show
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STATUS, (STATUS_DISABLE|STATUS_FOCUS_DISABLE));
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, 0, MNUITM_STATUS, STATUS_ENABLE);
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  pOption->TextId);
        }
    } 
	else 
	{
        //display user define string
        if (pOption->TextId & STRID_USER_START) 
		{
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
			//printf("pOption->TextId=0x%x\r\n",pOption->TextId);
        } 
		else 
		{
			//printf("pOption->TextId=0x%x\r\n",pOption->TextId);
            UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_STRID,  pOption->TextId);
        }
    }
	#if 0//R-for viofo 20241206
	if (pItem->ItemId == IDM_ASR_CONTENT) 
	{
		switch(SysGetFlag(FL_LANGUAGE)) 
		{
		case LANG_EN:
		case LANG_JP:
			UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, ASR_VIDEOSTOP, MNUITM_STATUS, STATUS_ENABLE);
		break;
		}
	}
	#endif
    if (SysGetFlag(pItem->SysFlag)==i){
		if(pItem->ItemId != IDM_ASR_CONTENT){
			UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_ICONID, ICON_SEL_FOCUS);
		}else{
        	UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_ICONID, ICON_OK);
		}
    }else{
        UxMenu_SetItemData(&MenuCommonOption_MenuCtrl, i, MNUITM_ICONID, ICON_OK);
    }
    }

    UxCtrl_SetDirty(&MenuCommonOptionCtrl, TRUE);
    //Ux_RedrawAllWind();
}

INT32 MenuCommonOption_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;

    pPage = &pMenu->pPages[pMenu->SelPage];
    pItem = &pPage->pItems[pPage->SelItem];

    g_uiMenuCommonOption_Sel = SysGetFlag(pItem->SysFlag);

    //UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_CURITM, SysGetFlag(pItem->SysFlag));
    UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_CURITM, g_uiMenuCommonOption_Sel);

    if (pItem->ItemId == IDM_MOVIE_DUAL_CAM) {
		//if (!GPIOMap_EthCam1Det()) {
        if (System_GetEnableSensor() == SENSOR_1) {
            UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_CURITM, 0);		
        } else {
            UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_CURITM, SysGetFlag(pItem->SysFlag));
        }
    } else if ((pItem->ItemId == IDM_MOVIE_ADAS) /*|| (pItem->ItemId == IDM_MOVIE_IMPRINT) || (pItem->ItemId == IDM_VOLUME)*/) {
        UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_CURITM, 0);
		SysSetFlag(FL_MOVIE_ADAS, 0);
		//SysSetFlag(FL_MOVIE_IMPRINT, 0);
		//SysSetFlag(FL_VOLUME, 0);
		g_uiMenuCommonOption_Sel = 0;
    } else {
        UxMenu_SetData(&MenuCommonOption_MenuCtrl, MNU_CURITM, SysGetFlag(pItem->SysFlag));
    }

    MenuCommonOption_UpdateContent(pMenu);
    MenuCommonOption_CalcPageInfo(&MenuCommonOption_MenuCtrl, g_uiMenuCommonOption_Sel);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_RedrawAllWind();
    return NVTEVT_CONSUME;
}

INT32 MenuCommonOption_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        Ux_CloseWindow(pCtrl,0); // close option menu
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_CURR);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_1SEC);
    return NVTEVT_CONSUME;
}
//---------------------MenuCommonOption_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonOption_Panel)
CTRL_LIST_ITEM(MenuCommonOption_Menu)
CTRL_LIST_END

//----------------------MenuCommonOption_PanelCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_Panel)
EVENT_END

//----------------------MenuCommonOption_MenuCtrl Event---------------------------
INT32 MenuCommonOption_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MenuCommonOption_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonOption_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,MenuCommonOption_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,MenuCommonOption_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,MenuCommonOption_Menu_OnKeyEnter)
EVENT_END

INT32 MenuCommonOption_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    UINT32      state = 0;
    UINT32      uiSelOption = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        pPage = &pMenu->pPages[pMenu->SelPage];
        pItem = &pPage->pItems[pPage->SelItem];
        uiSelOption = SysGetFlag(pItem->SysFlag);

        if (pItem->ItemId == IDM_MOVIE_DUAL_CAM) {
            //if (GPIOMap_EthCam1Det()) {
            if (System_GetEnableSensor() == (SENSOR_1|SENSOR_2)) {
                Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
            } else {
                return NVTEVT_CONSUME;
            }
        }else {
            Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        }
        MenuCommonOption_CalcPageInfo(&MenuCommonOption_MenuCtrl, uiSelOption);
        break;
    }

    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    UINT32      state = 0;
    UINT32      uiSelOption = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        pPage = &pMenu->pPages[pMenu->SelPage];
        pItem = &pPage->pItems[pPage->SelItem];
        uiSelOption = SysGetFlag(pItem->SysFlag);

        if (pItem->ItemId == IDM_MOVIE_DUAL_CAM) {
            //if (GPIOMap_EthCam1Det()) {
            if (System_GetEnableSensor() == (SENSOR_1|SENSOR_2)) {
                Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
            } else {
                return NVTEVT_CONSUME;
            }
        }else {
            Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        }
        MenuCommonOption_CalcPageInfo(&MenuCommonOption_MenuCtrl, uiSelOption);
        break;
    }

    return NVTEVT_CONSUME;
}
INT32 MenuCommonOption_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    TM_MENU*    pMenu = TM_GetMenu();
    TM_PAGE*    pPage;
    TM_ITEM*    pItem;
    UINT32      uiSelOption;
    UINT32      state = 0;

    if (paramNum > 0) {
        state = paramArray[0];
    }

    switch (state) {
    case NVTEVT_KEY_PRESS:
        pPage = &pMenu->pPages[pMenu->SelPage];
        pItem = &pPage->pItems[pPage->SelItem];

        if (pItem->ItemId == IDM_MOVIE_DUAL_CAM) {
            //if (!GPIOMap_EthCam1Det()) {
            if (System_GetEnableSensor() == SENSOR_1) {
                Ux_CloseWindow(&MenuCommonOptionCtrl, 0);
                return NVTEVT_CONSUME;
            }
        }

        uiSelOption = UxMenu_GetData(&MenuCommonOption_MenuCtrl, MNU_CURITM); // selected option

        //if parking mode on, turn off motion det & timelapse rec
        if ((pItem->SysFlag == FL_PARKING_MODE) && (uiSelOption != PARKING_MODE_OFF)) {
            SysSetFlag(FL_MOVIE_MOTION_DET, MOVIE_MOTIONDET_OFF);
            SysSetFlag(FL_MOVIE_TIMELAPSE_REC_MENU, MOVIE_TIMELAPSEREC_OFF);
        }
        //if motion det on, turn off parking mode
        if ((pItem->SysFlag == FL_MOVIE_MOTION_DET) && (uiSelOption != MOVIE_MOTIONDET_OFF)) {
            SysSetFlag(FL_PARKING_MODE, PARKING_MODE_OFF);
            SysSetFlag(FL_PARKING_MODE_TIMELAPSE_REC, PARKING_MODE_TIMELAPSEREC_OFF);
        }
        //if timelapse rec on, turn off parking mode
        if ((pItem->SysFlag == FL_MOVIE_TIMELAPSE_REC_MENU) && (uiSelOption != MOVIE_TIMELAPSEREC_OFF)) {
            SysSetFlag(FL_PARKING_MODE, PARKING_MODE_OFF);
            SysSetFlag(FL_PARKING_MODE_TIMELAPSE_REC, PARKING_MODE_TIMELAPSEREC_OFF);
        }

        // set system flag by selected Option
        SysSetFlag(pItem->SysFlag, uiSelOption);

        switch (pItem->ItemId) {
        //case IDM_CAR_SAFE:
        //    Ux_OpenWindow(&UIMenuWndCustomerComfirmCtrl, 2, pItem->ItemId, uiSelOption);
       //     TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
       //      break;

        /*
        case IDM_MOVIE_IMPRINT:
            if (uiSelOption == MOVIE_IMPRINT_GPS) {
                Get_GpsSpeedString();
                Get_GpsSpeedString();
                Get_GpsSpeedString();
                Delay_DelayMs(1000);

                gpsstatus = GetGPSSignalStatus();
                //debug_msg("*** gpsstatus = %d ***\r\n", gpsstatus);
                if (gpsstatus == -1) {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_GPS_ERR, FLOWWRNMSG_TIMER_3SEC);
                    return NVTEVT_CONSUME;
                } else {
                    Ux_OpenWindow(&UIMenuWndCustomerComfirmCtrl, 2,pItem->ItemId,uiSelOption);
                    TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption)); 
                }
            } else {
                Ux_OpenWindow(&UIMenuWndCustomerComfirmCtrl, 2, pItem->ItemId, uiSelOption);
                TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
            }
            break;*/

        case IDM_MOVIE_HDR_DET:
            if (uiSelOption == MOVIE_HDR_DET_AUTO) {
                Ux_OpenWindow(&UIMenuWndSetupHDRTimeCtrl, 0);
            } else {
                // Close current UI Window now
                Ux_CloseWindow(&MenuCommonOptionCtrl, 2,pItem->ItemId,uiSelOption);
            }
            TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
            break;
		case IDM_MOVIE_HDR:
			Ux_CloseWindow(&MenuCommonOptionCtrl, 2,pItem->ItemId,uiSelOption);
			TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
			if ((SysGetFlag(FL_MOVIE_SIZE_MENU) == MOVIE_SIZE_FRONT_2560x1440P60) && \
				(uiSelOption == MOVIE_HDR_ON)) {
				SysSetFlag(pItem->SysFlag, MOVIE_HDR_OFF);
				Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_CANT_BE_SET, FLOWWRNMSG_TIMER_4SEC);
			}
			break;
		case IDM_MOVIE_SIZE:
			Ux_CloseWindow(&MenuCommonOptionCtrl, 2,pItem->ItemId,uiSelOption);
			TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
			if(uiSelOption == MOVIE_SIZE_FRONT_2560x1440P60){
				UI_SetData(FL_MOVIE_HDR, MOVIE_HDR_OFF);
				UI_SetData(FL_MOVIE_HDR_MENU, MOVIE_HDR_OFF);
			}
			break;
		case IDM_MOVIE_ADAS:
            if(1) //(uiSelOption == PARKING_MODE_TIMELAPSE)
            {
                Ux_OpenWindow(&UIMenuWndSetupOption_LV3Ctrl, 2, pItem->ItemId, uiSelOption);
                TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
                MenuCommonOption_CalcPageInfo(&MenuCommonOption_MenuCtrl, uiSelOption);
            }
            else
            {
                // notify upper layer the Option had been confirmed
                TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
                MenuCommonOption_CalcPageInfo(&MenuCommonOption_MenuCtrl, uiSelOption);
            }
            break;
        default:
            Ux_CloseWindow(&MenuCommonOptionCtrl, 2,pItem->ItemId,uiSelOption);

            /*
            if (UI_GetData(FL_VIDEO_FORMAT_MENU) != UI_GetData(FL_VIDEO_FORMAT))
            {
                UI_SetData(FL_VIDEO_FORMAT, UI_GetData(FL_VIDEO_FORMAT_MENU));
                Save_MenuInfo();
                Delay_DelayMs(100);
                GxSystem_SWResetNOW();
            }*/

            // notify upper layer the Option had been confirmed
            TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, uiSelOption));
            break;
        }
        break;
    }

    return NVTEVT_CONSUME;
}
//----------------------MenuCommonOption_PageNumCtrl Event---------------------------
EVENT_BEGIN(MenuCommonOption_PageNum)
EVENT_END

