#ifndef __MENUID_H
#define __MENUID_H

#include "UIWnd/UIFlow.h"
#include "UIWnd/SPORTCAM/Resource/UIResource.h"

// Menu Item ID
enum _MENU_ID {
	IDM_NULL,

	// Menu common page
	IDM_COMMON_MODE,
	IDM_COMMON_MENU,
	IDM_COMMON_LOCAL,
	IDM_COMMON_LIVESTREAM,
	IDM_COMMON_CLOUD,
	IDM_COMMON_SETUP,
	IDM_COMMON_EXT_SETUP,

	// menu mode page
	IDM_MODE_MOVIE,
	IDM_MODE_PHOTO,
	IDM_MODE_PLAYBACK,
	// Photo Page
	IDM_SELFTIMER,
	IDM_PHOTO_SIZE,
	IDM_CONTINUE_SHOT,
	IDM_QUALITY,
	IDM_SHARPNESS,
	IDM_WB,
	IDM_ANTISHAKE,
	IDM_QUICK_REVIEW,
	IDM_DATE_STAMP,
	IDM_ISO,
	IDM_EV,
	IDM_EV2,
	IDM_FD,
	IDM_FLASH,
	IDM_RSC,
	IDM_HDR,
	IDM_WDR,
	IDM_METERING,
	IDM_SCENE,
	IDM_DUAL_CAM,

	// Movie Page
	IDM_MOVIE_SIZE,
	IDM_MOVIE_CYCLIC_REC,
	IDM_MOVIE_WDR,
	IDM_MOVIE_HDR,
	IDM_MOVIE_EV,
	IDM_MOVIE_MOTION_DET,
	IDM_MOVIE_AUDIO,
	IDM_MOVIE_DATEIMPRINT,
	IDM_MOVIE_RSC,
	IDM_MOVIE_RSC_EFFECT,
	IDM_MOVIE_GSENSOR,
	IDM_MOVIE_TIMELAPSE_REC,
	IDM_MOVIE_IR_CUT,
	IDM_MOVIE_SENSOR_ROTATE,
	IDM_MOVIE_PTZ,
	IDM_MOVIE_URGENT_PROTECT_AUTO,
	IDM_MOVIE_URGENT_PROTECT_MANUAL,
	IDM_MOVIE_PIM,
	IDM_MOVIE_FCW,
	IDM_MOVIE_LDWS,
	IDM_MOVIE_DDD,
	IDM_MOVIE_ADAS_CAL,
	IDM_MOVIE_QUALITY,
	IDM_MOVIE_WB,
	IDM_MOVIE_COLOR,
	IDM_MOVIE_DUAL_CAM,
	IDM_MOVIE_CODEC,
    IDM_MOVIE_TIMERLAPS,
	IDM_MOVIE_BITRATE,
	IDM_MOVIE_HDR_DET,
	// Playback Page
	IDM_PROTECT,
	IDM_VOLUME,

	// Setup Page
	IDM_DATE_TIME,
	IDM_AUTO_POWER_OFF,
	IDM_BEEP,
	IDM_SILENT,
	IDM_LANGUAGE,
	IDM_MOVIE_VOICE,
	IDM_ASR,
	IDM_ASR_CONTENT,
	IDM_TV_MODE,
	IDM_FREQUENCY,
	IDM_FORMAT,
	IDM_DEFAULT,
	IDM_OPENING_LOGO,
	IDM_SCREEN_SAVE,
	IDM_FW_UPDATE,
	IDM_DELETE_ALL,
	IDM_PROTECT_ALL,
	IDM_UNPROTECT_ALL,
	IDM_WIFI,
	IDM_VERSION,
	IDM_DELETE_THIS,
    IDM_GPS,
    IDM_PARKINGMODE_DISABLE_GPS,
    IDM_TIME_ZONE,
    IDM_SPEED_UNIT,
    IDM_GPS_STAMP,
    IDM_LED,
    IDM_FORMAT_WARNING,
    IDM_SENSOR_ROTATE,
    IDM_SENSOR2_ROTATE,
    IDM_BOOT_DELAY,
    IDM_GPS_STATUS1,
    IDM_MODEL_STAMP,
    IDM_PARKING_MODE,
    IDM_PARKING_GSENSOR,
	IDM_PARKING_MOTION_DET,
    IDM_VIDEO_FORMAT,
    IDM_CARNO,
    IDM_CUSTOMIZE,
    IDM_IR_REAR_COLOR,
    IDM_REAR_SENSOR_MIRROR,
    IDM_SHUTDOWN_TIMER,
    IDM_ENTER_PARKING_TIMER,

	// Extra Setup Page
	IDM_MCTF,
	IDM_EDGE,
	IDM_NR,
	IDM_IPP_ISO,
	//TPMS_START
    IDM_PERPHERAL,
    IDM_TPMS,
    IDM_TPMS_TEMP_UNIT,
    IDM_PRSR_UNIT,
	//TPMS_END
	IDM_AMBIANCE_LIGHT,
    IDM_EDOG_MODE,
};

// Menu String ID
enum _MENU_IDS {
	// Photo Page

    IDS_SELFTIMER           = STRID_CAP_MODE,//STRID_SELFTIMER,
	IDS_PHOTO_SIZE          = STRID_RESOLUTION,
	IDS_CONTINUE_SHOT       = STRID_CAP_BURST,
	IDS_QUALITY             = STRID_QUALITY,
	IDS_SHARPNESS           = STRID_SHARPNESS,
	IDS_WB                  = STRID_WB,
	IDS_ANTISHAKE          = STRID_ANTI_SHAKING,
	IDS_QUICK_REVIEW        = STRID_QUICK_VIEW,
	IDS_DATE_STAMP          = STRID_DATE_STAMP,
	IDS_ISO                 = STRID_ISO,
    IDS_EV                  = STRID_FRONT_EV,//STRID_EXPOSURE,
    IDS_EV2                 = STRID_REAR_EV,//STRID_EXPOSURE,
	IDS_FD                  = STRID_FACE_DET,
	IDS_FLASH               = STRID_FLASHMODE,
    IDS_RSC                 = STRID_OK,//STRID_RSC,
	IDS_HDR                 = STRID_HDR,
	IDS_WDR                 = STRID_WDR,//STRID_OK,
	IDS_METERING            = STRID_METERING,
	IDS_SCENE               = STRID_SCENE,
    IDS_DUAL_CAM            = STRID_DISPLAY_MODE,//STRID_DUAL_CAM,
	IDS_PHOTO               = STRID_STILL,

	// Photo Capture Options
	IDS_SELFTIMER_OFF       = STRID_OFF,
	IDS_SELFTIMER_2SEC      = STRID_CAP_TIMER2S,
	IDS_SELFTIMER_5SEC      = STRID_CAP_TIMER5S,
	IDS_SELFTIMER_10SEC     = STRID_CAP_TIMER10S,

	// Photo Size Options
	IDS_PHOTO_SIZE_15M      = STRID_NULL_,
	IDS_PHOTO_SIZE_14M      = STRID_NULL_,
	IDS_PHOTO_SIZE_12M      = STRID_12MWXH,
	IDS_PHOTO_SIZE_10M      = STRID_10MWXH,
	IDS_PHOTO_SIZE_8M       = STRID_8MWXH,
	IDS_PHOTO_SIZE_7M       = STRID_7MWXH,
	IDS_PHOTO_SIZE_7MHD     = STRID_NULL_,
    IDS_PHOTO_SIZE_5M       = STRID_5MWXH,
	IDS_PHOTO_SIZE_4M       = STRID_4MWXH,
	IDS_PHOTO_SIZE_3M       = STRID_3MWXH,
	IDS_PHOTO_SIZE_2M       = STRID_2MWXH,
	IDS_PHOTO_SIZE_2MHD     = STRID_2MHDWXH,
	IDS_PHOTO_SIZE_1M       = STRID_1MWXH,
	IDS_PHOTO_SIZE_VGA      = STRID_VGAWXH,

	//Continue shot
	IDS_CONTINUE_SHOT_OFF   = STRID_CAP_SINGLE,
	IDS_CONTINUE_SHOT_3     = STRID_CAP_BURST_3,
	IDS_CONTINUE_SHOT_ON    = STRID_CAP_BURST,
	IDS_CONTINUE_SHOT_SIDE    = STRID_CAP_SIDE,
	IDS_CONTINUE_SHOT_30    = STRID_CAP_BURST_30,

	// Metering Options
	IDS_AVERAGE             = STRID_METER_AVG,
	IDS_CENTER              = STRID_METER_CENTER,
	IDS_SPOT                = STRID_METER_SPOT,

	//ISO
	IDS_ISO_AUTO            = STRID_AUTO,
	IDS_ISO_100             = STRID_ISO100,
	IDS_ISO_200             = STRID_ISO200,
	IDS_ISO_400             = STRID_ISO400,
    IDS_ISO_800             = STRID_OK,//STRID_ISO800,
    IDS_ISO_1600            = STRID_OK,//STRID_ISO1600,

	// Sharpness Options
	IDS_SHARP_STRONG        = STRID_STRONG,
	IDS_SHARP_NORMAL        = STRID_NORMAL,
	IDS_SHARP_SOFT          = STRID_SOFT,

	// WB Options
	IDS_WB_AUTO             = STRID_AUTO,
	IDS_WB_DAYLIGHT         = STRID_WB_DAY,
	IDS_WB_CLOUDY           = STRID_WB_CLOUDY,
	IDS_WB_TUNGSTEN         = STRID_WB_TUNGSTEN,
	IDS_WB_FLUORESCENT      = STRID_WB_FLUORESCENT,

	// EV Options
	IDS_EV_P20              = STRID_EV_P2P0,
	IDS_EV_P16              = STRID_EV_P1P6,
	IDS_EV_P13              = STRID_EV_P1P3,
	IDS_EV_P10              = STRID_EV_P1P0,
	IDS_EV_P06              = STRID_EV_P0P6,
	IDS_EV_P03              = STRID_EV_P0P3,
	IDS_EV_00               = STRID_EV_P0P0,
	IDS_EV_N03              = STRID_EV_M0P3,
	IDS_EV_N06              = STRID_EV_M0P6,
	IDS_EV_N10              = STRID_EV_M1P0,
	IDS_EV_N13              = STRID_EV_M1P3,
	IDS_EV_N16              = STRID_EV_M1P6,
	IDS_EV_N20              = STRID_EV_M2P0,

	// Face Detection Options
	IDS_FD_OFF              = STRID_OFF,
	IDS_FD_ON               = STRID_ON,

	// Anti-shaking Options
	IDS_ANTISHAKE_OFF       = STRID_OFF,
	IDS_ANTISHAKE_ON        = STRID_ON,

	// Quick View Time Options
	IDS_QV_OFF              = STRID_OFF,
	IDS_QV_2SEC             = STRID_2SEC,
	IDS_QV_5SEC             = STRID_5SEC,

	// Date Stamp Options
	IDS_DATE_STAMP_OFF      = STRID_OFF,
	IDS_DATE_STAMP_DATE     = STRID_DATE,
	IDS_DATE_STAMP_DATE_TIME = STRID_DATE_TIME,

	// Flash Options
	IDS_FLASH_AUTO          = STRID_FLASHAUTO,
	IDS_FLASH_ON            = STRID_ON,
	IDS_FLASH_OFF           = STRID_OFF,
	IDS_FLASH_RED_EYE       = STRID_REDEYE,

	// RSC Options
	IDS_RSC_ON              = STRID_ON,
	IDS_RSC_OFF             = STRID_OFF,

	// HDR Options
	IDS_HDR_ON              = STRID_ON,
	IDS_HDR_OFF             = STRID_OFF,

	// WDR Options
	IDS_WDR_ON              = STRID_ON,
	IDS_WDR_OFF             = STRID_OFF,

	// SCENE Options
	IDS_SCENE_AUTO          = STRID_AUTO,
	IDS_SCENE_PORTRAIT      = STRID_PORTRAIT,
	IDS_SCENE_LANDSCAPE     = STRID_LANDSCAPE,

	// DUAL CAM Options
    IDS_DUAL_CAM_FRONT      = STRID_FRONT_CAMERA,//STRID_FRONT,
    IDS_DUAL_CAM_BEHIND     = STRID_BACK_CAMERA,//STRID_BEHIND,
    IDS_DUAL_CAM_BOTH       = STRID_PICTURE_IN_PICTURE,//STRID_BOTH,
	IDS_DUAL_CAM_BOTH2      = STRID_BOTH2,

	// Movie Page
	IDS_MOVIE_SIZE          = STRID_RESOLUTION,
    IDS_MOVIE_EV            = STRID_EV,//STRID_EXPOSURE,
	IDS_MOVIE_CYCLIC_REC    = STRID_CYCLIC_REC,
	IDS_MOVIE_HDR           = STRID_HDR,
    IDS_MOVIE_WDR           = STRID_OK,//STRID_WDR,
	IDS_MOVIE_MOTION_DET    = STRID_MOTION_DET,
	IDS_MOVIE_AUDIO         = STRID_RECORD_AUDIO,
	IDS_MOVIE_DATEIMPRINT   = STRID_DATE_STAMP,
    IDS_MOVIE_RSC           = STRID_EIS,//STRID_RSC,
	IDS_MOVIE_RSC_EFFECT    = STRID_OK,//STRID_RSC_EFFECT,
    IDS_MOVIE_GSENSOR       = STRID_GSENSOR,//STRID_G_SENSOR,
    IDS_MOVIE_TIMELAPSE_REC = STRID_OK,//STRID_TIMELAPSE_REC,
    IDS_MOVIE_IR_CUT        = STRID_OK,//STRID_IRCUT,
	IDS_MOVIE_SENSOR_ROTATE = STRID_SENSOR_ROTATE,
    IDS_MOVIE_PTZ           = STRID_OK,//STRID_PTZ,
    IDS_MOVIE_URGENT_PROTECT_AUTO   = STRID_OK,//STRID_URGENT_PROTECT_AUTO,
    IDS_MOVIE_URGENT_PROTECT_MANUAL = STRID_OK,//STRID_URGENT_PROTECT_MANUAL,
    IDS_MOVIE_PIM           = STRID_OK,//STRID_PIM,
    IDS_MOVIE_FCW           = STRID_OK,//STRID_FCW,
    IDS_MOVIE_LDWS          = STRID_OK,//STRID_LDWS,
    IDS_MOVIE_DDD           = STRID_OK,//STRID_DDD,
    IDS_MOVIE_ADAS_CAL      = STRID_OK,//STRID_ADAS,
	IDS_MOVIE_QUALITY       = STRID_QUALITY,
	IDS_MOVIE_WB            = STRID_WB,
	IDS_MOVIE_COLOR         = STRID_COLOR,
    IDS_MOVIE_TIMERLAPS     = STRID_TIMER_LAPSE,
	IDS_MOVIE_BITRATE       = STRID_OK,//STRID_MOVIE_BITRATE,
	IDS_MOVIE_HDR_DET       = STRID_HDR,	
    IDS_MOVIE               = STRID_SETUP,//STRID_MOVIE,
    IDS_MOVIE_DUAL_CAM      = STRID_DISPLAY_MODE,//STRID_DUAL_CAM,
	IDS_MOVIE_CODEC         = STRID_CODEC,

	// Movie Size Options
	IDS_MOVIE_SIZE_2880x2160P50  = STRID_NULL_,//STRID_2880X2160P50, // 2160P  50fps 2880x2160 (DAR)
	IDS_MOVIE_SIZE_3840x2160P30  = STRID_NULL_,//STRID_3840X2160P30, // 2160P  30fps 3840x2160
    IDS_MOVIE_SIZE_2880x2160P24  = STRID_OK,//STRID_2880X2160P24, // 2160P  24fps 2880x2160
	IDS_MOVIE_SIZE_2880x2160P30  = STRID_OK,//STRID_2880X2160P24, // 2160P  24fps 2880x2160 (DAR)
	//IDS_MOVIE_SIZE_2704x2032P60  = STRID_2704X2032P60, // 2.7K   60fps 2704x2032
	//IDS_MOVIE_SIZE_2560x1440P60  = STRID_2560X1440P80, // 1440P  80fps 2560x1440
	//IDS_MOVIE_SIZE_2560x1440P60  = STRID_2560X1440P60, // 1440P  60fps 2560x1440
	IDS_MOVIE_SIZE_2560x1440P30  = STRID_NULL_,//STRID_2560X1440P30, // 1440P  30fps 2560x1440
#if 0
	IDS_MOVIE_SIZE_2304x1296P30  = STRID_2304X1296P30, // 1296P  30fps 2304x1296
	IDS_MOVIE_SIZE_1080P96       = STRID_1080P96,      // 1080P  96fps 1920x1080
	IDS_MOVIE_SIZE_1080P_DUAL    = STRID_1080P_DUAL,   // 1080PD 30fps 1920x1080
	IDS_MOVIE_SIZE_720P120       = STRID_720P120WXH,   // 720P  120fps 1280x720
#endif
	//MOVIE_SIZE_TAG
	IDS_MOVIE_SIZE_FRONT_2880x2160P50   = STRID_FRONT_2880x2160P50, //UHD P50 (DAR)
	IDS_MOVIE_SIZE_FRONT_3840x2160P30   = STRID_FRONT_3840x2160P30, //UHD P30
	IDS_MOVIE_SIZE_FRONT_2880x2160P24   = STRID_FRONT_2880x2160P24, //UHD P24 (DAR)
	IDS_MOVIE_SIZE_FRONT_2704x2032P60   = STRID_FRONT_2704x2032P60, //2.7K P60
	IDS_MOVIE_SIZE_FRONT_2592x1944P30   = STRID_FRONT_2592x1944P30, //1944 P30
	IDS_MOVIE_SIZE_FRONT_2560x1600P30   = STRID_FRONT_2560x1600P30, //1600 P30
	IDS_MOVIE_SIZE_FRONT_2560x1440P80   = STRID_FRONT_2560x1440P80, //QHD P60
	IDS_MOVIE_SIZE_FRONT_2560x1440P60   = STRID_FRONT_2560x1440P60, //QHD P60
	IDS_MOVIE_SIZE_FRONT_2560x1440P30   = STRID_FRONT_2560x1440P30, //QHD P30
	IDS_MOVIE_SIZE_FRONT_2560x1080P60   = STRID_FRONT_2560x1080P60, //QHD P60 21:9
	IDS_MOVIE_SIZE_FRONT_2560x1080P30   = STRID_FRONT_2560x1080P30, //QHD P30 21:9
	IDS_MOVIE_SIZE_FRONT_2304x1296P60   = STRID_FRONT_2304x1296P60, //3MHD P60
	IDS_MOVIE_SIZE_FRONT_2304x1296P30   = STRID_FRONT_2304x1296P30, //3MHD P30
	IDS_MOVIE_SIZE_FRONT_1920x1080P120  = STRID_FRONT_1920x1080P120, //FHD
	IDS_MOVIE_SIZE_FRONT_1920x1080P96   = STRID_FRONT_1920x1080P96, //FHD
	IDS_MOVIE_SIZE_FRONT_1920x1080P60   = STRID_FRONT_1920x1080P60, //FHD
	IDS_MOVIE_SIZE_FRONT_1920x1080P30   = STRID_FRONT_1920x1080P30, //FHD
	IDS_MOVIE_SIZE_FRONT_1280x720P240   = STRID_FRONT_1280x720P240, //HD
	IDS_MOVIE_SIZE_FRONT_1280x720P120   = STRID_FRONT_1280x720P120, //HD
	IDS_MOVIE_SIZE_FRONT_1280x720P60    = STRID_FRONT_1280x720P60, //HD
	IDS_MOVIE_SIZE_FRONT_1280x720P30    = STRID_FRONT_1280x720P30,  //HD
	IDS_MOVIE_SIZE_FRONT_848x480P30     = STRID_FRONT_848x480P30,   //WVGA
	IDS_MOVIE_SIZE_FRONT_640x480P240    = STRID_FRONT_640x480P240,   //VGA
	IDS_MOVIE_SIZE_FRONT_640x480P30     = STRID_FRONT_640x480P30,   //VGA
	IDS_MOVIE_SIZE_FRONT_320x240P30     = STRID_FRONT_320x240P30,   //QVGA
	IDS_MOVIE_SIZE_DUAL_3840x2160P30_1920x1080P30   = STRID_DUAL_3840x2160P30_1920x1080P30,
	IDS_MOVIE_SIZE_DUAL_2560x1440P30_1280x720P30   = STRID_DUAL_2560x1440P30_1280x720P30, //QHD HD
	IDS_MOVIE_SIZE_DUAL_2560x1440P30_1920x1080P30   = STRID_DUAL_2560x1440P30_1920x1080P30, //QHD FHD
	IDS_MOVIE_SIZE_DUAL_2304x1296P30_1280x720P30   = STRID_DUAL_2304x1296P30_1280x720P30, //3MHD HD
	IDS_MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30  = STRID_DUAL_1080P30_1080P30, //FHD FHD
	IDS_MOVIE_SIZE_DUAL_1920x1080P60_1920x1080P60  = STRID_DUAL_1080P60_1080P60, //FHD FHD
	IDS_MOVIE_SIZE_DUAL_1920x1080P30_1280x720P30  = STRID_DUAL_1920x1080P30_1280x720P30, //FHD HD
	IDS_MOVIE_SIZE_DUAL_1920x1080P30_848x480P30  = STRID_DUAL_1920x1080P30_848x480P30, //FHD WVGA
	IDS_MOVIE_SIZE_TRI_1920x1080P30=STRID_TRI_1920x1080P30, // 3 x FHD
	IDS_MOVIE_SIZE_TRI_2560x1440P30_1920x1080P30_1920x1080P30=STRID_TRI_2560x1440P30_1920x1080P30_1920x1080P30, //QHD + 3 x FHD
	IDS_MOVIE_SIZE_QUAD_1920x1080P30=STRID_QUAD_1920x1080P30,   // 4 x FHD
	IDS_MOVIE_SIZE_CLONE_1920x1080P30_1920x1080P30 = STRID_CLONE_1920x1080P30_1920x1080P30,  //FHD FHD
	IDS_MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30  = STRID_CLONE_1920x1080P30_1280x720P30,   //FHD HD
	IDS_MOVIE_SIZE_CLONE_2560x1440P30_848x480P30   = STRID_CLONE_2560x1440P30_848x480P30,  //QHD WVGA
	IDS_MOVIE_SIZE_CLONE_2304x1296P30_848x480P30   = STRID_CLONE_2304x1296P30_848x480P30,  //3MHD WVGA
	IDS_MOVIE_SIZE_CLONE_1920x1080P60_848x480P30   = STRID_CLONE_1920x1080P60_848x480P30,  //FHD WVGA
	IDS_MOVIE_SIZE_CLONE_1920x1080P60_640x360P30   = STRID_CLONE_1920x1080P60_640x360P30,  //FHD WVGA
	IDS_MOVIE_SIZE_CLONE_1920x1080P30_848x480P30   = STRID_CLONE_1920x1080P30_848x480P30,  //FHD WVGA
	IDS_MOVIE_SIZE_CLONE_2048x2048P30_480x480P30   = STRID_CLONE_2048x2048P30_480x480P30,


#if 0
	IDS_MOVIE_SIZE_1080FHD  = STRID_1080FHDWXH,
	IDS_MOVIE_SIZE_1080P_DUAL = STRID_1080P_DUAL,
	IDS_MOVIE_SIZE_720P120 = STRID_720P120WXH,
	IDS_MOVIE_SIZE_1080P    = STRID_1080PWXH,
	IDS_MOVIE_SIZE_1440P    = STRID_1080PWXH,
	IDS_MOVIE_SIZE_720P     = STRID_720PWXH,
	IDS_MOVIE_SIZE_WVGA     = STRID_WVGAWXH,
	IDS_MOVIE_SIZE_VGA      = STRID_VGAWXH,
	IDS_MOVIE_SIZE_QVGA     = STRID_QVGAWXH,
#endif

	// EV Options
	IDS_MOVIE_EV_P20        = STRID_EV_P2P0,
	IDS_MOVIE_EV_P16        = STRID_EV_P1P6,
	IDS_MOVIE_EV_P13        = STRID_EV_P1P3,
	IDS_MOVIE_EV_P10        = STRID_EV_P1P0,
	IDS_MOVIE_EV_P06        = STRID_EV_P0P6,
	IDS_MOVIE_EV_P03        = STRID_EV_P0P3,
	IDS_MOVIE_EV_00         = STRID_EV_P0P0,
	IDS_MOVIE_EV_N03        = STRID_EV_M0P3,
	IDS_MOVIE_EV_N06        = STRID_EV_M0P6,
	IDS_MOVIE_EV_N10        = STRID_EV_M1P0,
	IDS_MOVIE_EV_N13        = STRID_EV_M1P3,
	IDS_MOVIE_EV_N16        = STRID_EV_M1P6,
	IDS_MOVIE_EV_N20        = STRID_EV_M2P0,


	// Movie loop rec Options
	IDS_MOVIE_CYCLIC_REC_OFF    = STRID_OFF,
	IDS_MOVIE_CYCLIC_REC_1MIN   = STRID_1MIN,
    IDS_MOVIE_CYCLIC_REC_2MIN   = STRID_2MIN,
	IDS_MOVIE_CYCLIC_REC_3MIN   = STRID_3MIN,
	IDS_MOVIE_CYCLIC_REC_5MIN   = STRID_5MIN,
	IDS_MOVIE_CYCLIC_REC_10MIN  = STRID_10MIN,

	// Movie motion detect Options
	IDS_MOVIE_MOTION_DET_OFF  = STRID_OFF,
	IDS_MOVIE_MOTION_DET_ON   = STRID_ON,

	// Movie HDR options
	IDS_MOVIE_HDR_OFF  = STRID_OFF,
	IDS_MOVIE_HDR_ON   = STRID_ON,

	// Movie HDR Det options
	IDS_MOVIE_HDR_DET_OFF  = STRID_OFF,
	IDS_MOVIE_HDR_DET_ON   = STRID_ON,
	IDS_MOVIE_HDR_DET_AUTO = STRID_HDR_TIMER,//STRID_AUTO,

	// Movie WDR options
	IDS_MOVIE_WDR_OFF  = STRID_OFF,
	IDS_MOVIE_WDR_ON   = STRID_ON,

	// Movie audio Options
	IDS_MOVIE_AUDIO_OFF     = STRID_OFF,
	IDS_MOVIE_AUDIO_ON      = STRID_ON,

	// Movie dateImprint Options
	IDS_MOVIE_DATEIMPRINT_OFF = STRID_OFF,
	IDS_MOVIE_DATEIMPRINT_ON  = STRID_ON,

	// Movie RSC Options
	IDS_MOVIE_RSC_OFF         = STRID_OFF,
	IDS_MOVIE_RSC_ON          = STRID_ON,

    IDS_MOVIE_RSC_LOW         = STRID_LOW,
    IDS_MOVIE_RSC_MED      = STRID_MED,
    IDS_MOVIE_RSC_HIGH        = STRID_HIGH,
    IDS_MOVIE_RSC_SUPER_HIGH        = STRID_OK,//STRID_SUPER_HIGH,

	// Movie G Sensor Options
	IDS_MOVIE_GSENSOR_OFF     = STRID_OFF,
    IDS_MOVIE_GSENSOR_LOW     = STRID_LOW_SENSITIVITY,
    IDS_MOVIE_GSENSOR_MED     = STRID_MIDDLE_SENSITIVITY,
    IDS_MOVIE_GSENSOR_HIGH    = STRID_HIGH_SENSITIVITY,

	// Movie Timelapse record Options
	IDS_MOVIE_TIMELAPSE_REC_OFF     = STRID_OFF,
	IDS_MOVIE_TIMELAPSE_REC_100MS 	= STRID_OK,//STRID_100MS,
    IDS_MOVIE_TIMELAPSE_REC_200MS 	= STRID_OK,//STRID_200MS,
    IDS_MOVIE_TIMELAPSE_REC_500MS 	= STRID_OK,//STRID_500MS,
    IDS_MOVIE_TIMELAPSE_REC_1SEC    = STRID_OK,//STRID_1SEC,
    IDS_MOVIE_TIMELAPSE_REC_2SEC    = STRID_2SEC,
	IDS_MOVIE_TIMELAPSE_REC_5SEC    = STRID_5SEC,
	IDS_MOVIE_TIMELAPSE_REC_10SEC   = STRID_10SEC,
    IDS_MOVIE_TIMELAPSE_REC_30SEC   = STRID_OK,//STRID_30SEC,
	IDS_MOVIE_TIMELAPSE_REC_1MIN    = STRID_1MIN,
	IDS_MOVIE_TIMELAPSE_REC_5MIN    = STRID_5MIN,
	IDS_MOVIE_TIMELAPSE_REC_10MIN   = STRID_10MIN,
	IDS_MOVIE_TIMELAPSE_REC_30MIN   = STRID_30MIN,
    IDS_MOVIE_TIMELAPSE_REC_1HOUR   = STRID_OK,//STRID_1HOUR,
    IDS_MOVIE_TIMELAPSE_REC_2HOUR   = STRID_OK,//STRID_2HOUR,
    IDS_MOVIE_TIMELAPSE_REC_3HOUR   = STRID_OK,//STRID_3HOUR,
    IDS_MOVIE_TIMELAPSE_REC_1DAY    = STRID_OK,//STRID_1DAY,

	// Movie IR Cut Options
	IDS_MOVIE_IR_CUT_OFF         = STRID_OFF,
	IDS_MOVIE_IR_CUT_ON          = STRID_ON,

	// Movie Sensor Rotate Options
	IDS_MOVIE_SENSOR_ROTATE_OFF  = STRID_OFF,
	IDS_MOVIE_SENSOR_ROTATE_ON   = STRID_ON,

	// Movie PTZ Options
	IDS_MOVIE_PTZ_OFF            = STRID_OFF,
	IDS_MOVIE_PTZ_ON             = STRID_ON,

	// Movie auto urgent protect Options
	IDS_MOVIE_URGENT_PROTECT_AUTO_OFF   = STRID_OFF,
	IDS_MOVIE_URGENT_PROTECT_AUTO_ON    = STRID_ON,

	// Movie manual urgent protect Options
	IDS_MOVIE_URGENT_PROTECT_MANUAL_OFF   = STRID_OFF,
	IDS_MOVIE_URGENT_PROTECT_MANUAL_ON    = STRID_ON,

	// Movie PIM Options
	IDS_MOVIE_PIM_OFF                   = STRID_OFF,
	IDS_MOVIE_PIM_ON                    = STRID_ON,

	// Movie FCW Options
	IDS_MOVIE_FCW_OFF                   = STRID_OFF,
	IDS_MOVIE_FCW_ON                    = STRID_ON,

	// Movie LDWS Options
	IDS_MOVIE_LDWS_OFF                   = STRID_OFF,
	IDS_MOVIE_LDWS_ON                    = STRID_ON,

	// Movie DDD Options
	IDS_MOVIE_DDD_OFF                   = STRID_OFF,
	IDS_MOVIE_DDD_ON                    = STRID_ON,

	// Movie ADAS CAL Options
	IDS_MOVIE_ADAS_CAL_OFF              = STRID_OFF,
	IDS_MOVIE_ADAS_CAL_ON               = STRID_ON,

	// Movie DUAL CAM Options
    IDS_MOVIE_DUAL_CAM_FRONT            = STRID_FRONT_CAMERA,//STRID_FRONT,
    IDS_MOVIE_DUAL_CAM_BEHIND           = STRID_BACK_CAMERA,//STRID_BEHIND,
    IDS_MOVIE_DUAL_CAM_BOTH             = STRID_PICTURE_IN_PICTURE,//STRID_BOTH,
	IDS_MOVIE_DUAL_CAM_BOTH2            = STRID_BOTH2,

	// Movie codec Options
	IDS_MOVIE_MJPG                      = STRID_MJPG,//,
	IDS_MOVIE_H264                      = STRID_H264,//,
	IDS_MOVIE_H265                      = STRID_H265,//,

	// Movie Quality Options
	IDS_QUALITY_FINE        = STRID_FINE,
	IDS_QUALITY_NORMAL      = STRID_NORMAL,
	IDS_QUALITY_ECONOMY     = STRID_ECONOMY,

    // Movie timelapse
    IDS_MOVIE_TIMER_LAPS_ON   = STRID_ON,
    IDS_MOVIE_TIMER_LAPS_OFF  = STRID_OFF,

    // Movie Bitrate
    IDS_MOVIE_BITRATE_LOW   = STRID_LOW,
    IDS_MOVIE_BITRATE_MED   = STRID_MED,
    IDS_MOVIE_BITRATE_HIGH  = STRID_HIGH,

	// Playback Page
	IDS_PROTECT             = STRID_PROTECT,
	IDS_VOLUME              = STRID_VOLUME,
	IDS_PLAYBACK            = STRID_PLAYBACK,

	// Volume Options
    IDS_VOL0                = STRID_OK,//STRID_0 ,
    IDS_VOL1                = STRID_OK,//STRID_1 ,
    IDS_VOL2                = STRID_OK,//STRID_2 ,
    IDS_VOL3                = STRID_OK,//STRID_3 ,
    IDS_VOL4                = STRID_OK,//STRID_4 ,
    IDS_VOL5                = STRID_OK,//STRID_5 ,
    IDS_VOL6                = STRID_OK,//STRID_6 ,
    IDS_VOL7                = STRID_OK,//STRID_7 ,
    IDS_VOL8                = STRID_OK,//STRID_8 ,
    IDS_VOL9                = STRID_OK,//STRID_9 ,
    IDS_VOL10               = STRID_OK,//STRID_10,

	// Common Page
	IDS_COMMON              = STRID_MODE,
	IDS_COMMON_MODE         = STRID_MODE,
	IDS_COMMON_MENU         = STRID_SETUP,
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
    IDS_COMMON_LOCAL        = STRID_OK,//STRID_WIFI,
	IDS_COMMON_LIVESTREAM   = STRID_OK,//STRID_LIVESTREAM,
#else
	IDS_COMMON_LOCAL        = STRID_WIFI_ETH,
#endif
	IDS_COMMON_CLOUD        = STRID_OK,//STRID_CLOUD,
	IDS_COMMON_SETUP        = STRID_SETUP,
	IDS_COMMON_EXT_SETUP    = STRID_SETUP,

	IDS_COMMON_LOCAL_OFF    = STRID_OFF,
	IDS_COMMON_LOCAL_ON     = STRID_ON,

	IDS_COMMON_LIVESTREAM_OFF    = STRID_OFF,
	IDS_COMMON_LIVESTREAM_ON     = STRID_ON,

	IDS_COMMON_CLOUD_OFF    = STRID_OFF,
	IDS_COMMON_CLOUD_ON     = STRID_ON,

	IDS_MODE                = STRID_MODE,
	IDS_MODE_MOVIE          = STRID_MOVIE,
	IDS_MODE_PHOTO          = STRID_PHOTO_PAPER,
	IDS_MODE_PLAYBACK       = STRID_PLAYBACK,

	// Setup Page
	IDS_DATE_TIME           = STRID_DATE_TIME,
	IDS_AUTO_POWER_OFF      = STRID_AUTO_OFF,
	IDS_BEEP                = STRID_BEEPER,
	IDS_SILENT              = STRID_BEEPER,
	IDS_LANGUAGE            = STRID_LANGUAGE,
	IDS_MOVIE_VOICE         = STRID_SPEEDLIMIT_VOICE,
	IDS_ASR         		= STRID_ASR,
	IDS_ASR_CONTENT        = STRID_ASR_CONTENT,
	IDS_TV_MODE             = STRID_TV_MODE,
	IDS_FREQUENCY           = STRID_FREQUENCY,
	IDS_FORMAT              = STRID_FORMAT,
    IDS_DEFAULT             = STRID_DEFAULT,//STRID_DEFAULT_SETTING,
	IDS_OPENING_LOGO        = STRID_LOGO_DISPLAY,
	IDS_VERSION             = STRID_VERSION,
    IDS_WIFI                = STRID_WIFI_AUTO,//STRID_WIFI,
	IDS_SCREEN_SAVE         = STRID_SCREEN_SAVER,
    IDS_FW_UPDATE           = STRID_OK,//STRID_FW_UPDATE,
	IDS_DELETE_ALL          = STRID_DELETEALL,
	IDS_PROTECT_ALL         = STRID_LOCKALL,
	IDS_UNPROTECT_ALL       = STRID_UNLOCKALL,
    IDS_GPS                 = STRID_GPS,
    IDS_PARKINGMODE_DISABLE_GPS = STRID_DISABLE_GPS_IN_PARKINGMODE,
    IDS_TIME_ZONE           = STRID_TIME_ZONE,
    IDS_SPEED_UNIT          = STRID_SPEED_UNIT,
    IDS_GPS_STAMP           = STRID_GPS_STAMP,
    IDS_LED                 = STRID_LED_DET,
    IDS_FORMAT_WARNING      = STRID_FORMAT_WARNING,
    IDS_SENSOR_ROTATE       = STRID_FRONT_CAMERA,
    IDS_SENSOR2_ROTATE      = STRID_BACK_CAMERA,
    IDS_BOOT_DELAY          = STRID_BOOT_DELAY,
    IDS_GPS_STATUS1         = STRID_GPS_STATUS,
    IDS_MODEL_STAMP         = STRID_OK,//STRID_MODEL_STAMP,
    IDS_PARKING_MODE        = STRID_PARKING_MODE,
    IDS_PARKING_GSENSOR     = STRID_PARKING_GSENSOR,
    IDS_PARKING_MOTION_DET  = STRID_PARKING_MOTION_DET,
    IDS_VIDEO_FORMAT        = STRID_VIDEO_FORMAT,
    IDS_CARNO               = STRID_CARNO,
    IDS_CUSTOMIZE           = STRID_OK,//STRID_CUSTOMIZE,
    IDS_IR_REAR_COLOR       = STRID_OK,//STRID_IR_CAMERA_COLOR,
    IDS_REAR_SENSOR_MIRROR  = STRID_REAR_CAMERA_MIRROR,
    IDS_SHUTDOWN_TIMER      = STRID_SHUTDOWN_TIMER,
    IDS_ENTER_PARKING_TIMER = STRID_ENTERPARKING_TIMER,
	IDS_SETUP               = STRID_SETUP,

	// Power Saving Options
	IDS_OFF                 = STRID_OFF,
	IDS_1MIN                = STRID_AUTO_OFF_1MIN,
	IDS_2MIN                = STRID_AUTO_OFF_2MIN,
	IDS_3MIN                = STRID_AUTO_OFF_3MIN,
	IDS_5MIN                = STRID_AUTO_OFF_5MIN,
	IDS_10MIN               = STRID_AUTO_OFF_10MIN,

	// Beep Options
	IDS_SILENT_ON            = STRID_OFF,
	IDS_SILENT_OFF           = STRID_ON,

	IDS_BEEP_OFF            = STRID_OFF,
	IDS_BEEP_ON             = STRID_ON,

	// Language Options
	IDS_LANG_EN             = STRID_LANG_EN,
	IDS_LANG_DE             = STRID_LANG_DE,
	IDS_LANG_FR             = STRID_LANG_FR,
	IDS_LANG_ES             = STRID_LANG_ES,
	IDS_LANG_IT             = STRID_LANG_IT,
	IDS_LANG_PO             = STRID_LANG_PO,
	IDS_LANG_SC             = STRID_LANG_SC,
	IDS_LANG_TC             = STRID_LANG_TC,
	IDS_LANG_JP             = STRID_LANG_JP,
	IDS_LANG_RU             = STRID_LANG_RU,
	IDS_LANG_DU             = STRID_NULL_,
	IDS_LANG_TU             = STRID_NULL_,
	IDS_LANG_PB             = STRID_NULL_,
	IDS_LANG_YI             = STRID_NULL_,
	IDS_LANG_PL             = STRID_NULL_,
	IDS_LANG_RO             = STRID_OK,//STRID_LANG_RO,
    IDS_LANG_TR             = STRID_OK,//STRID_LANG_TR,
    IDS_LANG_CZ             = STRID_OK,//STRID_LANG_CZ,
    IDS_LANG_SK             = STRID_OK,//STRID_LANG_SK,
    IDS_LANG_AZ             = STRID_OK,//STRID_LANG_AZ,
    IDS_LANG_NL             = STRID_OK,//STRID_LANG_NL,
    IDS_LANG_NO             = STRID_OK,//STRID_LANG_NO,
	// Movie voice Options
	IDS_MOVIE_VOICE_OFF     = STRID_OFF,
	IDS_MOVIE_VOICE_ON      = STRID_ON,

	// ASR Options
	IDS_ASR_OFF     = STRID_OFF,
	IDS_ASR_LOW      = STRID_LOW_SENSITIVITY,
	IDS_ASR_STANDARD	= STRID_ON,

	// ASR content Options
	IDS_ASR_TAKEPHOTO     = STRID_ASR_TAKEPHOTO,
	IDS_ASR_VIDEOSTART      = STRID_ASR_VIDEOSTART,
	IDS_ASR_VIDEOSTOP          =  STRID_ASR_VIDEOSTOP,
	IDS_ASR_TURNONAUDIO		= STRID_ASR_TURNONAUDIO,
	IDS_ASR_TURNOFFAUDIO		= STRID_ASR_TURNOFFAUDIO,
	IDS_ASR_TURNONSCREEN		= STRID_ASR_TURNONSCREEN,
	IDS_ASR_TURNOFFSCREEN		= STRID_ASR_TURNOFFSCREEN,
	IDS_ASR_TURNONHOTSPOT		= STRID_ASR_TURNONHOTSPOT,
	IDS_ASR_TURNOFFHOTSPOT		= STRID_ASR_TURNOFFHOTSPOT,
	IDS_ASR_LOCKVIDEO		= STRID_ASR_LOCKVIDEO,
	IDS_ASR_TURNONWIFI		= STRID_ASR_TURNONWIFI,
	IDS_ASR_TURNOFFWIFI		= STRID_ASR_TURNOFFWIFI,
	IDS_ASR_SHOW_FRONT_CAMERA		= STRID_ASR_SHOW_FRONT_CAMERA,
	IDS_ASR_SHOW_REAR_CAMERA		= STRID_ASR_SHOW_REAR_CAMERA,
	IDS_ASR_SHOW_BOTH_CAMERAS		= STRID_ASR_SHOW_BOTH_CAMERAS,
	IDS_ASR_INSIDE_VIDEO_ON		= STRID_ASR_INSIDE_VIDEO_ON,
	IDS_ASR_BACK_TO_HOMEPAGE		= STRID_ASR_BACK_TO_HOMEPAGE,

	// TV Mode Options
	IDS_TV_NTSC             = STRID_TV_NTSC,
	IDS_TV_PAL              = STRID_TV_PAL,

	// Frequency Options
	IDS_50HZ                = STRID_50HZ,
	IDS_60HZ                = STRID_60HZ,

	// Wi-Fi Options
	IDS_WIFI_OFF            = STRID_OFF,
	IDS_WIFI_ON             = STRID_ON,
	IDS_WIFI_ON_24G         = STRID_WIFI_24G,
	IDS_WIFI_ON_52G          = STRID_WIFI_52G,
	IDS_WIFI_ON_58G      = STRID_WIFI_58G,
	// Opening Logo Display Options
	IDS_LOGO_OFF            = STRID_OFF,
	IDS_LOGO_ON             = STRID_ON,

	// Screen Save Option
	IDS_AUTO_OFF_OFF        = STRID_OFF,
	IDS_AUTO_OFF_1SEC       = STRID_OK,//STRID_1SEC,
	IDS_AUTO_OFF_3SEC       = STRID_3SEC,
	IDS_AUTO_OFF_15SEC      = STRID_15SEC,
	IDS_AUTO_OFF_30SEC      = STRID_30SEC,
	IDS_AUTO_OFF_1MIN       = STRID_AUTO_OFF_1MIN,
	IDS_AUTO_OFF_3MIN       = STRID_AUTO_OFF_3MIN,
	IDS_AUTO_OFF_5MIN       = STRID_AUTO_OFF_5MIN,
	IDS_AUTO_OFF_10MIN      = STRID_AUTO_OFF_10MIN,

	// Extra Setup Page
	IDS_MCTF                = STRID_MCTF,
	IDS_EDGE                = STRID_EDGE,
	IDS_NR                  = STRID_NR,
	IDS_IPP_ISO             = STRID_ISO,
	IDS_EXT_SETUP           = STRID_SETUP,

	// MCTF Options
	IDS_MCTF_OFF            = STRID_OFF,
	IDS_MCTF_ON             = STRID_ON,

	// EDGE Options
	IDS_EDGE_OFF            = STRID_OFF,
	IDS_EDGE_ON             = STRID_ON,

	// NR Options
	IDS_NR_OFF              = STRID_OFF,
	IDS_NR_ON               = STRID_ON,

	// IPP ISO Options
	IDS_IPP_ISO_AUTO        = STRID_AUTO,
	IDS_IPP_ISO_50          = STRID_ISO50,
	IDS_IPP_ISO_200         = STRID_ISO200,
    IDS_IPP_ISO_800         = STRID_OK,//STRID_ISO800,
    IDS_IPP_ISO_3200        = STRID_OK,//STRID_ISO3200,
	IDS_IPP_ISO_6400        = STRID_ISO6400,
	IDS_IPP_ISO_12800       = STRID_ISO12800,

    // GPS Options
    IDS_GPS_OFF     = STRID_OFF,
    IDS_GPS_ON      = STRID_ON,

    IDS_PARKINGMODE_DISABLE_GPS_OFF = STRID_OFF,
    IDS_PARKINGMODE_DISABLE_GPS_ON = STRID_ON,
    // Time Zone Options
    IDS_GMT_0       = STRID_GMT_N0,
    IDS_GMT_P1      = STRID_GMT_P1,
    IDS_GMT_P2      = STRID_GMT_P2,
    IDS_GMT_P3      = STRID_GMT_P3,
    IDS_GMT_P3_30   = STRID_GMT_P330,
    IDS_GMT_P4      = STRID_GMT_P4,
    IDS_GMT_P4_30   = STRID_GMT_P430,
    IDS_GMT_P5      = STRID_GMT_P5,
    IDS_GMT_P5_30   = STRID_GMT_P530,
    IDS_GMT_P6      = STRID_GMT_P6,
    IDS_GMT_P6_30   = STRID_OK,//STRID_GMT_P630,
    IDS_GMT_P7      = STRID_GMT_P7,
    IDS_GMT_P8      = STRID_GMT_P8,
    IDS_GMT_P9      = STRID_GMT_P9,
    IDS_GMT_P9_30   = STRID_GMT_P930,
    IDS_GMT_P10     = STRID_GMT_P10,
    IDS_GMT_P10_30  = STRID_GMT_P1030,
    IDS_GMT_P11     = STRID_GMT_P11,
    IDS_GMT_P12     = STRID_GMT_P12,
    IDS_GMT_P13     = STRID_GMT_P13,
    IDS_GMT_M1      = STRID_GMT_N1,
    IDS_GMT_M2      = STRID_GMT_N2,
    IDS_GMT_M2_30   = STRID_OK,//STRID_GMT_N230,
    IDS_GMT_M3      = STRID_GMT_N3,
    IDS_GMT_M3_30   = STRID_GMT_N330,
    IDS_GMT_M4      = STRID_GMT_N4,
    IDS_GMT_M5      = STRID_GMT_N5,
    IDS_GMT_M6      = STRID_GMT_N6,
    IDS_GMT_M7      = STRID_GMT_N7,
    IDS_GMT_M8      = STRID_GMT_N8,
    IDS_GMT_M9      = STRID_GMT_N9,
    IDS_GMT_M10     = STRID_GMT_N10,
    IDS_GMT_M11     = STRID_GMT_N11,
    IDS_GMT_M12     = STRID_GMT_N12,

    // Speed Unit Options
    IDS_SPEED_KPH   = STRID_SPEED_KPH,
    IDS_SPEED_MPH   = STRID_SPEED_MPH,

    // GPS Stamp Options
    IDS_GPS_STAMP_OFF = STRID_OFF,
    IDS_BOTH          = STRID_COORDINATES_SPEED,
    IDS_COORDINATES   = STRID_COORDINATES,
    IDS_SPEED         = STRID_SPEED,

    // LED Options
    IDS_LED_ON      = STRID_ON,
    IDS_LED_OFF     = STRID_OFF,

    // Format Waring Options
    IDS_FORMAT_WARNING_15_DAY = STRID_FORMAT_WARNING_15_DAY,
    IDS_FORMAT_WARNING_30_DAY = STRID_FORMAT_WARNING_30_DAY,
    IDS_FORMAT_WARNING_60_DAY = STRID_FORMAT_WARNING_60_DAY,
    IDS_FORMAT_WARNING_OFF    = STRID_OFF,

    // Sensor & Sensor2 Rotate Options
    IDS_SEN_ROTATE_OFF     = STRID_NORMAL,
    IDS_SEN_ROTATE_ON      = STRID_SENSOR_ROTATE,

    // Boot Delay Options
    IDS_BOOT_DELAY_5SEC    = STRID_5SEC,
    IDS_BOOT_DELAY_15SEC   = STRID_15SEC,
    IDS_BOOT_DELAY_30SEC   = STRID_30SEC,

    // Model Stamp Options
    IDS_MODEL_STAMP_OFF    = STRID_OFF,
    IDS_MODEL_STAMP_ON     = STRID_ON,

    // Parking Mode Options
    IDS_PARKING_MODE_OFF         = STRID_OFF,
    IDS_PARKING_MODE_MOTION_DET  = STRID_AUTO_EVENT_DETECTION,
    IDS_PARKING_MODE_ON_1FPS     = STRID_ON,// STRID_TL_1FPS,
    IDS_PARKING_MODE_ON_2FPS     = STRID_TL_2FPS,
    IDS_PARKING_MODE_ON_3FPS     = STRID_TL_3FPS,
    IDS_PARKING_MODE_ON_5FPS     = STRID_TL_5FPS,
    IDS_PARKING_MODE_ON_10FPS    = STRID_TL_10FPS,
    IDS_PARKING_MODE_ON_15FPS    = STRID_OK,//STRID_PM_15FPS,
    IDS_PARKING_MODE_LOW_BITRATE = STRID_LOW_BITRATE,

	// Parking Mode G Sensor Options
	IDS_PARKING_GSENSOR_OFF      = STRID_OFF,
    IDS_PARKING_GSENSOR_LOW      = STRID_LOW_SENSITIVITY,
    IDS_PARKING_GSENSOR_MED      = STRID_MIDDLE_SENSITIVITY,
    IDS_PARKING_GSENSOR_HIGH     = STRID_HIGH_SENSITIVITY,

	// Parking Mode Motion Detect Options
	IDS_PARKING_MOTIONDET_OFF    = STRID_OFF,
    IDS_PARKING_MOTIONDET_LOW    = STRID_LOW_SENSITIVITY,
    IDS_PARKING_MOTIONDET_MED    = STRID_MIDDLE_SENSITIVITY,
    IDS_PARKING_MOTIONDET_HIGH   = STRID_HIGH_SENSITIVITY,

    // Video Format Options
    IDS_VIDEO_FORMAT_TS    = STRID_VIDEO_FORMAT_TS,
    IDS_VIDEO_FORMAT_MP4   = STRID_VIDEO_FORMAT_SUPER_MP4,

    // IR Rear Color Options
    IDS_IR_REAR_COLOR_BW      = STRID_OK,//STRID_COLOR_MONO,//STRID_COLOR_BW,
    IDS_IR_REAR_COLOR_NORMAL  = STRID_OK,//STRID_IR_COLOR,//STRID_COLOR_FULL,
    IDS_IR_REAR_COLOR_AUTO    = STRID_AUTO,
    //Voiume Set
    //IDS_VOLUME = STRID_VOLUME,
    IDS_VOLUME20                = STRID_PERCENT20,
    IDS_VOLUME40                = STRID_PERCENT40,
    IDS_VOLUME60                = STRID_PERCENT60,
    IDS_VOLUME80                = STRID_PERCENT80,
    IDS_VOLUME100               = STRID_PERCENT100,
    IDS_MUTE                    = STRID_MUTE,
    // Rear Sensor Mirror Options
    IDS_REAR_SENSOR_MIRROR_OFF = STRID_OFF,
    IDS_REAR_SENSOR_MIRROR_ON  = STRID_ON,

    // Shutdown Timer Options
    IDS_SHUTDOWN_TIMER_OFF      = STRID_OFF,
    IDS_SHUTDOWN_TIMER_5MIN     = STRID_5MIN,
    IDS_SHUTDOWN_TIMER_10MIN    = STRID_10MIN,
    IDS_SHUTDOWN_TIMER_30MIN    = STRID_30MIN,
    IDS_SHUTDOWN_TIMER_1HOUR    = STRID_OK,//STRID_1HOUR,
    IDS_SHUTDOWN_TIMER_2HOUR    = STRID_OK,//STRID_2HOUR,
    IDS_SHUTDOWN_TIMER_3HOUR    = STRID_OK,//STRID_3HOUR,
    IDS_SHUTDOWN_TIMER_4HOUR    = STRID_OK,//STRID_4HOUR,
    IDS_SHUTDOWN_TIMER_6HOUR    = STRID_OK,//STRID_6HOUR,
    IDS_SHUTDOWN_TIMER_8HOUR    = STRID_OK,//STRID_8HOUR,
    IDS_SHUTDOWN_TIMER_12HOUR   = STRID_12HOUR,
    IDS_SHUTDOWN_TIMER_18HOUR   = STRID_OK,//STRID_18HOUR,
    IDS_SHUTDOWN_TIMER_24HOUR   = STRID_24HOUR,
    IDS_SHUTDOWN_TIMER_48HOUR   = STRID_48HOUR,

    // Enter Parking Timer Options
    IDS_ENTER_PARKING_TIMER_OFF   = STRID_OFF,
    IDS_ENTER_PARKING_TIMER_90SEC = STRID_90SEC,
	//TPMS_START
    IDS_PERPHERAL =STRID_OK,//STRID_PERIPHERAL,
    IDS_TPMS        =STRID_TPMS,
    IDS_TPMS_TEMP_UNIT  = STRID_OK,//STRID_TPMS_TEMP_UNIT,
    IDS_PRSR_UNIT  =STRID_OK,//STRID_TPMS_PRSR_UNIT,
   	//TPMS_END 

	IDS_AMBIANCE_LIGHT				= STRID_HOST_LIGHT,//STRID_AMBIANCE_LIGHT,
	IDS_AMBIANCE_LIGHT_ON			= STRID_PERMANENT_LIGHT,
	IDS_AMBIANCE_LIGHT_BREATH	 	= STRID_BREATHING_LIGHT,
	IDS_AMBIANCE_LIGHT_INTERIOR	 	= STRID_TRUNK_LIGHT,
	IDS_AMBIANCE_LIGHT_OFF			= STRID_OFF,
	IDS_AMBIANCE_LIGHT_ON_OFF		= STRID_HORSE_RACE_LIGHT,

	IDS_EDOG_MODE				= STRID_SPEED_ALERT,
	IDS_EDOG_MODE_OFF			= STRID_OFF,
	IDS_EDOG_MODE_ON			= STRID_ON,


};

// Menu Icon ID
enum _MENU_IDI {
	// Photo Page
	IDI_SELFTIMER          = ICON_OK,//ICON_SELFTIMER_M,
	IDI_PHOTO_SIZE         = ICON_OK,//ICON_RESOLUTION_M,
	IDI_CONTINUE_SHOT      = ICON_OK,//ICON_BUST_M,
	IDI_QUALITY            = ICON_OK,//ICON_QUALITY_M,
	IDI_SHARPNESS          = ICON_OK,//ICON_SHARPNESS_M,
	IDI_WB                 = ICON_OK,//ICON_WB_M,
	IDI_ANTISHAKE          = ICON_OK,//ICON_SHAKE_ON_M,
	IDI_QUICK_REVIEW       = ICON_OK,//ICON_QUICK_REVIEW_M,
	IDI_DATE_STAMP         = ICON_OK,//ICON_DATE_PRINT_M,
	IDI_ISO                = ICON_OK,//ICON_ISO_M,
	IDI_EV                 = ICON_OK,//ICON_EV_M,
	IDI_EV2                 = ICON_OK,//ICON_EV_M,
	IDI_FD                 = ICON_OK,//ICON_FACE_ON_M,
	IDI_FLASH              = ICON_OK,//ICON_FLASH_ON_M,
	IDI_RSC                = ICON_OK,//ICON_RSC_ON_M,
	IDI_HDR                = ICON_OK,//ICON_HDR_M,
	IDI_WDR                = ICON_OK,//ICON_MENU_WDR_M,
	IDI_METERING           = ICON_OK,//ICON_METERING_M,
	IDI_SCENE              = ICON_OK,//ICON_SCENE_MODE_M,
	IDI_DUAL_CAM           = ICON_OK,//ICON_DUALCAM_BOTH_M,
	IDI_PHOTO              = 0,       // Photo menu enable icon
	IDIX_PHOTO             = 0,      // Photo menu disable icon

	// Movie size options
	IDI_MOVIE_SIZE_1080FHD  = ICON_OK,
	IDI_MOVIE_SIZE_1080P    = ICON_OK,
	IDI_MOVIE_SIZE_1440P    = ICON_OK,
	IDI_MOVIE_SIZE_720P     = ICON_OK,
	IDI_MOVIE_SIZE_WVGA     = ICON_OK,
	IDI_MOVIE_SIZE_VGA      = ICON_OK,
	IDI_MOVIE_SIZE_QVGA     = ICON_OK,

	// Photo Size Options
	IDI_PHOTO_SIZE_15M      = ICON_OK,
	IDI_PHOTO_SIZE_14M      = ICON_OK,
	IDI_PHOTO_SIZE_12M      = ICON_OK,
	IDI_PHOTO_SIZE_10M      = ICON_OK,
	IDI_PHOTO_SIZE_8M       = ICON_OK,
	IDI_PHOTO_SIZE_7M       = ICON_OK,
	IDI_PHOTO_SIZE_7MHD     = ICON_OK,
	IDI_PHOTO_SIZE_5M       = ICON_OK,
	IDI_PHOTO_SIZE_4M       = ICON_OK,
	IDI_PHOTO_SIZE_3M       = ICON_OK,
	IDI_PHOTO_SIZE_2M       = ICON_OK,
	IDI_PHOTO_SIZE_1M       = ICON_OK,
	IDI_PHOTO_SIZE_2MHD     = ICON_OK,
	IDI_PHOTO_SIZE_VGA      = ICON_OK,

	// Movie Page
	IDI_MOVIE_SIZE          = ICON_OK,//ICON_RESOLUTION_M,
	IDI_MOVIE_EV            = ICON_OK,//ICON_EV_M,
	IDI_MOVIE_CYCLIC_REC    = ICON_OK,//ICON_CYCLIC_REC_M,
	IDI_MOVIE_HDR           = ICON_OK,//ICON_HDR_M,
	IDI_MOVIE_WDR           = ICON_OK,//ICON_MENU_WDR_M,
	IDI_MOVIE_MOTION_DET    = ICON_OK,//ICON_MOTION_DET_ON_M,
	IDI_MOVIE_AUDIO         = ICON_OK,//ICON_SOUND_REC_ON_M,
	IDI_MOVIE_DATEIMPRINT   = ICON_OK,//ICON_DATE_PRINT_M,
	IDI_MOVIE_RSC           = ICON_OK,//ICON_RSC_ON_M,
	IDI_MOVIE_RSC_EFFECT    = ICON_OK,//ICON_RSC_ON_M,
	IDI_MOVIE_TIMELAPSE_REC = ICON_OK,//ICON_TIME_LAPSE_ON_M,
	IDI_MOVIE_GSENSOR       = ICON_OK,//ICON_G_SENSOR_M,
	IDI_MOVIE_IR_CUT        = ICON_OK,//ICON_IRCUT_ON_M,
	IDI_MOVIE_PTZ           = ICON_OK,//ICON_CAM_PTZ_ON_M,
	IDI_MOVIE_SENSOR_ROTATE = ICON_OK,//ICON_VIDEO_FLIP_ON_M,
	IDI_MOVIE_DUAL_REC      = ICON_OK,//ICON_DUALCAM_BOTH_M,
	IDI_MOVIE_URGENT_PROTECT_AUTO    = ICON_OK,//ICON_URGENT_PROTECT_AUTO_M,
	IDI_MOVIE_URGENT_PROTECT_MANUAL  = ICON_OK,//ICON_URGENT_PROTECT_MANUAL_M,
	IDI_MOVIE_PIM           = ICON_OK,//ICON_PIM_ON_M,
	IDI_MOVIE_FCW           = ICON_OK,//ICON_FCW_ON_M,
	IDI_MOVIE_LDWS          = ICON_OK,//ICON_LDWS_ON_M,
	IDI_MOVIE_DDD           = ICON_OK,//ICON_DDD_ON_M,
	IDI_MOVIE_ADAS_CAL      = ICON_OK,//ICON_ADAS_CAL_M,
	IDI_MOVIE_QUALITY       = ICON_QUALITY,
	IDI_MOVIE_WB            = ICON_WB_AUTO,
    IDI_MOVIE_TIMERLAPS     = ICON_OK,
    IDI_MOVIE               = ICON_OK,//NULL,      // Movie menu enable icon
    IDIX_MOVIE              = ICON_OK,//NULL,      // Movie menu disable icon
	IDI_MOVIE_DUAL_CAM      = ICON_OK,//ICON_DUALCAM_BOTH_M,
	IDI_MOVIE_CODEC         = ICON_OK,//ICON_MENU_SETUP_ON_M,

	// Playback Page
	IDI_PROTECT             = ICON_OK,//ICON_PROTECT_M,
	IDI_VOLUME              = ICON_OK,//ICON_VOICE_M,
    IDI_PLAYBACK            = ICON_OK,//NULL,   // Playback menu enable icon
    IDIX_PLAYBACK           = ICON_OK,//NULL,   // Playback menu disable icon

	// Common Page
	IDI_COMMON              = ICON_OK,//ICON_MENU_MODECHANG_M,
	IDI_COMMON_MODE         = ICON_OK,//ICON_MENU_MODECHANG_M,                // no menu icon
	IDI_COMMON_MENU         = ICON_OK,//ICON_MODE_VIDEO_M,
	IDI_COMMON_LOCAL        = ICON_OK,//ICON_WIFI_OFF_M,
	IDI_COMMON_LIVESTREAM   = ICON_WIFI_ON,
	IDI_COMMON_CLOUD        = ICON_OK,//ICON_CLOUD_OFF_M,
	IDI_COMMON_SETUP        = ICON_OK,//ICON_MENU_SETUP_ON_M,
	IDI_COMMON_EXT_SETUP    = ICON_OK,//ICON_MENU_SETUP_ON_M,
	IDIX_COMMON             = ICON_MODE_VIDEO,

	// Mode page
	IDI_MODE                = ICON_OK,//ICON_MODE_VIDEO_M,
	IDI_MODE_MOVIE          = ICON_OK,//ICON_MODE_VIDEO_M,
	IDI_MODE_PHOTO          = ICON_OK,//ICON_MODE_CAPTURE_M,
	IDI_MODE_PLAYBACK       = ICON_OK,//ICON_MODE_PLAYBACK_M,
	IDIX_MODE               = ICON_MODE_VIDEO,
	// Setup Page
	IDI_DATE_TIME           = ICON_OK,//ICON_DATETIME_SETUP_M,
	IDI_AUTO_POWER_OFF      = ICON_OK,//ICON_POWER_OFF_M,
	IDI_BEEP                = ICON_OK,//ICON_VOICE_M,
	IDI_LANGUAGE            = ICON_OK,//ICON_LANGUAGE_M,
	IDI_MOVIE_VOICE         = ICON_OK,//ICON_SPEAKER,//ICON_SOUND_REC_ON,
	IDI_ASR         = ICON_OK,//ICON_SPEAKER,//ICON_SOUND_REC_ON,
	IDI_ASR_CONTENT         = ICON_OK,//ICON_SPEAKER,//ICON_SOUND_REC_ON,
	IDI_FREQUENCY           = ICON_OK,//ICON_HZ_M,
	IDI_TV_MODE             = ICON_OK,//ICON_TV_MODE_M,
	IDI_FORMAT              = ICON_OK,//ICON_FORMAT_M,
	IDI_DEFAULT             = ICON_OK,//ICON_DEFAULT_M,
	IDI_WIFI                = ICON_WIFI_ON_M,
	IDI_VERSION             = ICON_OK,//ICON_VERSION_M,
	IDI_SCREEN_SAVE         = ICON_OK,//ICON_SCREENSAVER_M,
	IDI_FW_UPDATE           = ICON_OK,//ICON_FIRMWARE_UPDATE_M,
	IDI_DELETE_ALL          = ICON_OK,//ICON_DELETE_M,
	IDI_PROTECT_ALL         = ICON_OK,//ICON_LOCK_M,
	IDI_UNPROTECT_ALL       = ICON_OK,//ICON_LOCK_UNLOCK_M,
    IDI_GPS                 = ICON_OK,
    IDI_PARKINGMODE_DISABLE_GPS = ICON_GPS_ON_M,
    IDI_TIME_ZONE           = ICON_OK,
    IDI_SPEED_UNIT          = ICON_OK,
    IDI_GPS_STAMP           = ICON_OK,
    IDI_LED                 = ICON_OK,
    IDI_FORMAT_WARNING      = ICON_OK,
    IDI_SENSOR_ROTATE       = ICON_OK,
    IDI_SENSOR2_ROTATE      = ICON_OK,
    IDI_BOOT_DELAY          = ICON_OK,
    IDI_GPS_STATUS1         = ICON_OK,
    IDI_MODEL_STAMP         = ICON_METERING,
    IDI_PARKING_MODE        = ICON_CAR_CAMERA,
    IDI_PARKING_GSENSOR     = ICON_OK,//ICON_PARKINGMODE_GSENSOR,
    IDI_PARKING_MOTION_DET  = ICON_OK,//ICON_PARKINGMODE_MD,
    IDI_VIDEO_FORMAT        = ICON_OK,
    IDI_CARNO               = ICON_CAR_NO,//ICON_WIFI_CONNECTING1,
    IDI_CUSTOMIZE           = ICON_OK,//ICON_BUST,
    IDI_IR_REAR_COLOR       = ICON_OK,//ICON_IRCUT_AUTO,
    IDI_REAR_SENSOR_MIRROR  = ICON_OK,
    IDI_SHUTDOWN_TIMER      = ICON_OK,//ICON_AUTOSHUTDOWN,
    IDI_ENTER_PARKING_TIMER = ICON_OK,//ICON_AUTOSHUTDOWN,
    IDI_SETUP               = ICON_OK,//NULL,
    IDIX_SETUP              = ICON_OK,//NULL,

	// Extra Setup Page
	IDI_MCTF                = ICON_OK,//ICON_MENU_SETUP_ON_M,
	IDI_EDGE                = ICON_OK,//ICON_MENU_SETUP_ON_M,
	IDI_NR                  = ICON_OK,//ICON_MENU_SETUP_ON_M,
	IDI_IPP_ISO             = ICON_OK,//ICON_MENU_SETUP_ON_M,
    IDI_EXT_SETUP           = ICON_OK,//NULL,
    IDIX_EXT_SETUP          = ICON_OK,//NULL,

#if 0
	// Language Options
	IDI_LANG_EN             = ICON_OK,
	IDI_LANG_FR             = ICON_OK,
	IDI_LANG_ES             = ICON_OK,
	IDI_LANG_PO             = ICON_OK,
	IDI_LANG_DE             = ICON_OK,
	IDI_LANG_DU             = ICON_OK,
	IDI_LANG_IT             = ICON_OK,
	IDI_LANG_RU             = ICON_OK,
	IDI_LANG_TU             = ICON_OK,
	IDI_LANG_JP             = ICON_OK,
	IDI_LANG_TC             = ICON_OK,
	IDI_LANG_SC             = ICON_OK,
	IDI_LANG_PB             = ICON_OK,
	IDI_LANG_YI             = ICON_OK,
	IDI_LANG_PL             = ICON_OK
#endif
	//TPMS_START
 	IDI_PERPHERAL	= ICON_OK,//ICON_CAM_PTZ_ON,
 	IDI_TPMS		   =ICON_OK,//ICON_FLASH_RED_EYE,
 	IDI_TPMS_TEMP_UNIT   =ICON_OK,//ICON_LOCAL_STATION__OFF,
 	IDI_PRSR_UNIT	=ICON_OK,//ICON_WB,
 	//TPMS_END
 	IDI_AMBIANCE_LIGHT = ICON_OK,
 	IDI_EDOG_MODE			= ICON_SET,

};
// Menu Flag ID
enum _MENU_IDF {
	// Menu common page
	IDF_COMMON_MODE                      = FL_COMMON_MODE,
	IDF_COMMON_MENU                      = FL_COMMON_MENU,
	IDF_COMMON_LOCAL                     = FL_COMMON_LOCAL,
	IDF_COMMON_LIVESTREAM                = FL_COMMON_LIVESTREAM,
	IDF_COMMON_CLOUD                     = FL_COMMON_CLOUD,
	IDF_COMMON_SETUP                     = FL_COMMON_SETUP,
	IDF_COMMON_EXT_SETUP                 = FL_COMMON_EXT_SETUP,
	// Movie Page
	IDF_MOVIE_SIZE                       = FL_MOVIE_SIZE_MENU, //only keep in menu
	IDF_MOVIE_CYCLIC_REC                 = FL_MOVIE_CYCLIC_REC,
	IDF_MOVIE_HDR                        = FL_MOVIE_HDR_MENU,
	IDF_MOVIE_WDR                        = FL_MOVIE_WDR_MENU,
	IDF_MOVIE_MOTION_DET                 = FL_MOVIE_MOTION_DET,
	IDF_MOVIE_AUDIO                      = FL_MOVIE_AUDIO,
	IDF_MOVIE_DATEIMPRINT                = FL_MOVIE_DATEIMPRINT,
	IDF_MOVIE_RSC                        = FL_MovieRSCIndex_MENU,
	IDF_MOVIE_RSC_EFFECT                 = FL_MovieRSCEffect_MENU,
	IDF_MOVIE_GSENSOR                    = FL_GSENSOR,
	//#NT#2016/08/15#KCHong#[0106941] -begin
	//#NT#Fixed FCW/LDWS/Timelapse cannot reset to default
	IDF_MOVIE_TIMELAPSE_REC              = FL_MOVIE_TIMELAPSE_REC_MENU,
	//#NT#2016/08/15#KCHong -end
	IDF_MOVIE_IR_CUT                     = FL_MOVIE_IR_CUT,
	IDF_MOVIE_SENSOR_ROTATE              = FL_MOVIE_SENSOR_ROTATE_MENU,//FL_MOVIE_SENSOR_ROTATE,
	IDF_MOVIE_PTZ                        = FL_MOVIE_PTZ,
	IDF_MOVIE_URGENT_PROTECT_AUTO        = FL_MOVIE_URGENT_PROTECT_AUTO,
	IDF_MOVIE_URGENT_PROTECT_MANUAL      = FL_MOVIE_URGENT_PROTECT_MANUAL,
	IDF_MOVIE_PIM                        = FL_MOVIE_PIM,
	//#NT#2016/08/15#KCHong#[0106941] -begin
	//#NT#Fixed FCW/LDWS/Timelapse cannot reset to default
	IDF_MOVIE_LDWS                       = FL_MOVIE_LDWS_MENU,
	IDF_MOVIE_FCW                        = FL_MOVIE_FCW_MENU,
	//#NT#2016/08/15#KCHong -end
	IDF_MOVIE_DDD                        = FL_MOVIE_DDD,
	IDF_MOVIE_ADAS_CAL                   = FL_MOVIE_ADAS_CAL,
	IDF_MOVIE_DUAL_CAM                   = FL_DUAL_CAM_MENU,
	IDF_MOVIE_CODEC                      = FL_MOVIE_CODEC_MENU,
    IDF_MOVIE_TIMERLAPS                  = FL_MOVIE_TIMERLAPS,
	IDF_MOVIE_BITRATE                    = FL_MOVIE_BITRATE,
	IDF_MOVIE_HDR_DET                    = FL_MOVIE_HDR_DET,
	// Photo Page
	IDF_SELFTIMER                        = FL_SELFTIMER,
	IDF_PHOTO_SIZE                       = FL_PHOTO_SIZE,
	IDF_CONTINUE_SHOT                    = FL_CONTINUE_SHOT,
	IDF_QUALITY                          = FL_QUALITY,
	IDF_SHARPNESS                        = FL_SHARPNESS,
	IDF_WB                               = FL_WB,
	IDF_ANTISHAKE                        = FL_ANTISHAKE,
	IDF_QUICK_REVIEW                     = FL_QUICK_REVIEW,
	IDF_DATE_STAMP                       = FL_DATE_STAMP,
	IDF_ISO                              = FL_ISO,
	IDF_EV                               = FL_EV,
	IDF_EV2                              = FL_EV2,
	IDF_FD                               = FL_FD,
	IDF_FLASH                            = FL_FLASH_MODE,
	//#NT#2016/08/19#Lincy Lin#[0106935] -begin
	//#NT# Support change WDR, SHDR, RSC setting will change mode after exit menu
	IDF_RSC                              = FL_RSC_MENU,
	IDF_HDR                              = FL_SHDR_MENU,
	IDF_WDR                              = FL_WDR_MENU,
	//#NT#2016/08/19#Lincy Lin -end
	IDF_METERING                         = FL_METERING,
	IDF_SCENE                            = FL_SCENE,
	IDF_DUAL_CAM                         = FL_DUAL_CAM_MENU,
	// Playback page
	IDF_VOLUME                           = FL_VOLUME, //FL_MovieAudioPlayIndex,
	// Setup Page
	IDF_AUTO_POWER_OFF                   = FL_AUTO_POWER_OFF,
	IDF_BEEP                             = FL_BEEP,
	IDF_LANGUAGE                         = FL_LANGUAGE,
	IDF_MOVIE_VOICE                      = FL_MOVIE_VOICE,
	IDF_ASR                      = FL_ASR,
	IDF_ASR_CONTENT                     = FL_ASR_CONTENT,
	IDF_FREQUENCY                        = FL_FREQUENCY,
	IDF_TV_MODE                          = FL_TV_MODE,
    IDF_SCREEN_SAVE                      = FL_LCD_OFF,
    IDF_GPS                              = FL_GPS,
    IDF_PARKINGMODE_DISABLE_GPS = FL_PARKING_OFF_GPS,
    IDF_TIME_ZONE                        = FL_TIME_ZONE,
    IDF_SPEED_UNIT                       = FL_SPEED_UNIT,
    IDF_GPS_STAMP                        = FL_GPS_STAMP,
    IDF_LED                              = FL_LED,
    IDF_FORMAT_WARNING                   = FL_FORMAT_WARNING,
    IDF_SENSOR_ROTATE                    = FL_SENSOR_ROTATE_MENU,
    IDF_SENSOR2_ROTATE                   = FL_SENSOR2_ROTATE_MENU,
    IDF_WIFI                             = FL_WIFI,
    IDF_BOOT_DELAY                       = FL_BOOT_DELAY,
    IDF_MODEL_STAMP                      = FL_MODEL_STAMP,
    IDF_PARKING_MODE                     = FL_PARKING_MODE,
    IDF_PARKING_GSENSOR                  = FL_PARKING_GSENSOR,
    IDF_PARKING_MOTION_DET               = FL_PARKING_MOTION_DET,
    IDF_VIDEO_FORMAT                     = FL_VIDEO_FORMAT_MENU,
    IDF_IR_REAR_COLOR                    = FL_IR_REAR_COLOR,
    IDF_REAR_SENSOR_MIRROR               = FL_REAR_SENSOR_MIRROR,
    IDF_SHUTDOWN_TIMER                   = FL_SHUTDOWN_TIMER,
    IDF_ENTER_PARKING_TIMER              = FL_ENTER_PARKING_TIMER,
	// Extra Setup Page
	IDF_MCTF                             = FL_MovieMCTFIndex,
	IDF_EDGE                             = FL_EDGE,
	IDF_NR                               = FL_NR,
	IDF_IPP_ISO                          = FL_IPP_ISO,
	
	//TPMS_START
    IDF_PERPHERAL  						 = FL_PERPHERAL,
    IDF_TPMS          					 = FL_TPMS,
    IDF_TPMS_TEMP_UNIT   				 = FL_TEMP_UNIT,
    IDF_PRSR_UNIT  						 = FL_PRSR_UNIT,
	//TPMS_END
	IDF_AMBIANCE_LIGHT  				 = FL_AMBIANCE_LIGHT,
	IDF_EDOG_MODE					 	 = FL_EDOG_OVERSPEED_ALARM,

};

#endif // __MENUID_H

