//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDMOVIE_H
#define UIFLOWWNDMOVIE_H

#include "UIFramework.h"

extern VControl UIFlowWndMovieCtrl;//Panel type 

extern VControl UIFlowWndMovie_Panel_Normal_DisplayCtrl;//Panel type 

extern VControl UIFlowWndMovie_Static_cameraCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_CyclicRecCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_CyclicRec_ICONID_NULL,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_3MIN,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_5MIN,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_10MIN,
UIFlowWndMovie_Status_CyclicRec_MAX
}UIFlowWndMovie_Status_CyclicRec_Setting;

extern VControl UIFlowWndMovie_Status_MotionDetCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_MotionDet_ICONID_NULL,
UIFlowWndMovie_Status_MotionDet_ICON_MOTION_DET_ON,
UIFlowWndMovie_Status_MotionDet_MAX
}UIFlowWndMovie_Status_MotionDet_Setting;

extern VControl UIFlowWndMovie_Status_batteryCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_battery_ICON_BATTERY_FULL,
UIFlowWndMovie_Status_battery_ICON_BATTERY_MED,
UIFlowWndMovie_Status_battery_ICON_BATTERY_LOW,
UIFlowWndMovie_Status_battery_ICON_BATTERY_EMPTY,
UIFlowWndMovie_Status_battery_ICON_BATTERY_ZERO,
UIFlowWndMovie_Status_battery_ICON_BATTERY_CHARGE,
UIFlowWndMovie_Status_battery_MAX
}UIFlowWndMovie_Status_battery_Setting;

extern VControl UIFlowWndMovie_YMD_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_HMS_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_PanelCtrl;//Panel type 

extern VControl UIFlowWndMovie_Status_RECCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_REC_ICON_REC_TRANSPAENT,
UIFlowWndMovie_Status_REC_ICON_REC_ELLIPSE,
UIFlowWndMovie_Status_REC_MAX
}UIFlowWndMovie_Status_REC_Setting;

extern VControl UIFlowWndMovie_Status_StorageCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Storage_ICONID_NULL,
UIFlowWndMovie_Status_Storage_ICON_SD_CARD,
UIFlowWndMovie_Status_Storage_ICON_SD_LOCK,
UIFlowWndMovie_Status_Storage_MAX
}UIFlowWndMovie_Status_Storage_Setting;

extern VControl UIFlowWndMovie_Static_timeCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_maxtimeCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_resolutionCtrl;//Static type 

extern VControl UIFlowWndMovie_Zoom_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_AudioCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Audio_ICON_SOUND_REC_OFF,
UIFlowWndMovie_Status_Audio_ICON_SOUND_REC_ON,
UIFlowWndMovie_Status_Audio_MAX
}UIFlowWndMovie_Status_Audio_Setting;

extern VControl UIFlowWndMovie_StatusICN_EVCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusICN_EV_ICON_EV_P2P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M0P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M0P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M2P0,
UIFlowWndMovie_StatusICN_EV_MAX
}UIFlowWndMovie_StatusICN_EV_Setting;

extern VControl UIFlowWndMovie_Status_HDRCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_HDR_ICONID_NULL,
UIFlowWndMovie_Status_HDR_ICON_HDR,
UIFlowWndMovie_Status_HDR_MAX
}UIFlowWndMovie_Status_HDR_Setting;

extern VControl UIFlowWndMovie_Status_WIFICtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_WIFI_ICON_WIFI_OFF,
UIFlowWndMovie_Status_WIFI_ICON_WIFI_ON,
UIFlowWndMovie_Status_WIFI_ICON_CLOUD_ON,
UIFlowWndMovie_Status_WIFI_MAX
}UIFlowWndMovie_Status_WIFI_Setting;

extern VControl UIFlowWndMovie_StaticIcon_PIMCtrl;//Static type 

extern VControl UIFlowWndMovie_ADAS_DrawingLineCtrl;//Panel type 

extern VControl UIFlowWndMovie_ALG_DrawCtrl;//Panel type 

extern VControl UIFlowWndMovie_CUSTOMERCtrl;//Static type 

extern VControl UIFlowWndMovie_GPSCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_GPS_ICONID_NULL,
UIFlowWndMovie_GPS_ICON_GPS_OFF,
UIFlowWndMovie_GPS_ICON_GPS_ON,
UIFlowWndMovie_GPS_MAX
}UIFlowWndMovie_GPS_Setting;

extern VControl UIFlowWndMovie_GPSSignalCtrl;//Static type 

extern VControl UIFlowWndMovie_GPSSignalCCtrl;//Static type 

extern VControl UIFlowWndMovie_GPSSignalCCCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_MotionDet1Ctrl;//Static type 

extern VControl UIFlowWndMovie_Static_MotionDet2Ctrl;//Static type 

extern VControl UIFlowWndMovie_Static_TimeLapse1Ctrl;//Static type 

extern VControl UIFlowWndMovie_Static_TimeLapse2Ctrl;//Static type 

extern VControl UIFlowWndMovie_GPSN_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndMovie_GPS_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndMovie_SOSCtrl;//Static type 

extern VControl UIFlowWndMovie_SOS1Ctrl;//Static type 

extern VControl UIFlowWndMovie_SNG_SMALL_ICONCtrl;//Static type 

extern VControl UIFlowWndMovie_SNG_SMALL_ICON1Ctrl;//Static type 

extern VControl UIFlowWndMovie_SNG_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndMovie_TSR_SMALL_ICONCtrl;//Static type 

extern VControl UIFlowWndMovie_TSR_SMALL_ICON1Ctrl;//Static type 

extern VControl UIFlowWndMovie_TSR_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndMovie_TSR_SMALL_ICON3Ctrl;//Static type 

extern VControl UIFlowWndMovie_RL_SMALL_ICONCtrl;//Static type 

extern VControl UIFlowWndMovie_RL_SMALL_ICON1Ctrl;//Static type 

extern VControl UIFlowWndMovie_RL_SMALL_ICON2Ctrl;//Static type 

extern VControl UIFlowWndMovie_RL_SMALL_ICON3Ctrl;//Static type 

extern VControl UIFlowWndMovie_FolderCheck_StatusTxtCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_FolderCheck_StatusTxt_STRID_FORMAT_WARNING1,
UIFlowWndMovie_FolderCheck_StatusTxt_MAX
}UIFlowWndMovie_FolderCheck_StatusTxt_Setting;

extern VControl UIFlowWndMovie_MENU_SOSCtrl;//Static type 

extern VControl UIFlowWndMovie_MENU_PLAYBCAKCtrl;//Static type 

extern VControl UIFlowWndMovie_MENU_SETTINGCtrl;//Static type 

extern VControl UIFlowWndMovie_MENU_CLOSELCDCtrl;//Static type 

extern VControl UIFlowWndMovie_MENU_PowerKeyCtrl;//Static type 

extern VControl UIFlowWndMovie_ADAS_Alert_DisplayCtrl;//Panel type 

extern VControl UIFlowWndMovie_StatusICN_LDWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusICN_LDWS_Alert_ICON_LDWS_LEFT_ALERT,
UIFlowWndMovie_StatusICN_LDWS_Alert_ICON_LDWS_RIGHT_ALERT,
UIFlowWndMovie_StatusICN_LDWS_Alert_MAX
}UIFlowWndMovie_StatusICN_LDWS_Alert_Setting;

extern VControl UIFlowWndMovie_StatusICN_FCWS_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusICN_FCWS_Alert_ICON_FCW_FAR_ALERT,
UIFlowWndMovie_StatusICN_FCWS_Alert_ICON_FCW_NEAR_ALERT,
UIFlowWndMovie_StatusICN_FCWS_Alert_MAX
}UIFlowWndMovie_StatusICN_FCWS_Alert_Setting;

extern VControl UIFlowWndMovie_StatusICN_SNG_AlertCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusICN_SNG_Alert_ICON_SNG_ALERT,
UIFlowWndMovie_StatusICN_SNG_Alert_MAX
}UIFlowWndMovie_StatusICN_SNG_Alert_Setting;

#endif
