#include "UIFlowLVGL/UIFlowMenuCommonOption/UIFlowMenuCommonOption.h"
#include "UIFlowLVGL/UIFlowLVGL.h"

#include "Resource/Plugin/lvgl_plugin.h"
/**********************
 *       WIDGETS
 **********************/

/**********************
 *  STATIC VARIABLES
 **********************/
lv_obj_t* container_main_menu_scr_uiflowmenucommonoption;
lv_obj_t* button_1_scr_uiflowmenucommonoption;
lv_obj_t* label_1_scr_uiflowmenucommonoption;
lv_obj_t* image_select0_scr_uiflowmenucommonoption;
lv_obj_t* button_2_scr_uiflowmenucommonoption;
lv_obj_t* label_2_scr_uiflowmenucommonoption;
lv_obj_t* image_select1_scr_uiflowmenucommonoption;
lv_obj_t* button_3_scr_uiflowmenucommonoption;
lv_obj_t* label_3_scr_uiflowmenucommonoption;
lv_obj_t* image_select2_scr_uiflowmenucommonoption;
lv_obj_t* button_4_scr_uiflowmenucommonoption;
lv_obj_t* label_4_scr_uiflowmenucommonoption;
lv_obj_t* image_select3_scr_uiflowmenucommonoption;
lv_obj_t* container_1_scr_uiflowmenucommonoption;
lv_obj_t* image_title_bar_scr_uiflowmenucommonoption;
lv_obj_t* label_menu_title_scr_uiflowmenucommonoption;
lv_obj_t* label_menu_page_num_scr_uiflowmenucommonoption;

lv_obj_t* UIFlowMenuCommonOption_create(){
	lv_obj_t *parent = lv_plugin_scr_create();
	lv_obj_set_event_cb(parent, UIFlowMenuCommonOptionEventCallback);

	lv_color_t color = {0};
	STYLE_COLOR_PROP(0x00, 0x55, 0x1f, 0x57);
	_lv_obj_set_style_local_color(parent,0,LV_STYLE_BG_COLOR, color);

	if(color.full== LV_COLOR_TRANSP.full){
		_lv_obj_set_style_local_opa(parent,0,LV_STYLE_BG_OPA,0);
	}


	static lv_style_t container_main_menu_s0;
	lv_style_init(&container_main_menu_s0);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_DEFAULT,5);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_DEFAULT,5);
	lv_style_set_pad_left(&container_main_menu_s0,LV_STATE_DEFAULT,30);
	lv_style_set_pad_right(&container_main_menu_s0,LV_STATE_DEFAULT,30);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_DEFAULT,5);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_DEFAULT, color);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_CHECKED,0);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_CHECKED,0);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_CHECKED,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_CHECKED, color);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_FOCUSED,0);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_FOCUSED,0);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_FOCUSED,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_FOCUSED, color);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_EDITED,0);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_EDITED,0);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_EDITED,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_EDITED, color);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_HOVERED,0);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_HOVERED,0);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_HOVERED,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_HOVERED, color);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_PRESSED,0);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_PRESSED,0);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_PRESSED,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_PRESSED, color);
	lv_style_set_pad_top(&container_main_menu_s0,LV_STATE_DISABLED,0);
	lv_style_set_pad_bottom(&container_main_menu_s0,LV_STATE_DISABLED,0);
	lv_style_set_pad_inner(&container_main_menu_s0,LV_STATE_DISABLED,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&container_main_menu_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_main_menu_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x05, 0x00, 0xff, 0xff) ; lv_style_set_border_color(&container_main_menu_s0, LV_STATE_DISABLED, color);
	lv_obj_t *container_main_menu = lv_cont_create(parent, NULL);
	lv_obj_set_hidden(container_main_menu, false);
	lv_obj_set_click(container_main_menu, true);
	lv_obj_set_drag(container_main_menu, false);
	lv_obj_set_pos(container_main_menu, 50, 50);
	lv_obj_set_size(container_main_menu, 520, 150);
	lv_obj_add_style(container_main_menu, 0, &container_main_menu_s0);

	container_main_menu_scr_uiflowmenucommonoption = container_main_menu;


	static lv_style_t button_1_s0;
	lv_style_init(&button_1_s0);
	lv_style_set_radius(&button_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&button_1_s0,LV_STATE_DEFAULT,0);
	lv_style_set_border_side(&button_1_s0,LV_STATE_DEFAULT,3);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_1_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_FOCUSED, color);
	lv_style_set_outline_opa(&button_1_s0,LV_STATE_FOCUSED,255);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_value_color(&button_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_1 = lv_btn_create(container_main_menu, NULL);
	lv_obj_set_hidden(button_1, false);
	lv_obj_set_click(button_1, true);
	lv_obj_set_drag(button_1, false);
	lv_obj_set_pos(button_1, 20, 2);
	lv_obj_set_size(button_1, 480, 35);
	lv_btn_set_checkable(button_1, false);
	lv_btn_set_layout(button_1, LV_LAYOUT_OFF);
	lv_btn_set_fit(button_1, LV_FIT_NONE);
	lv_obj_add_style(button_1, 0, &button_1_s0);

	button_1_scr_uiflowmenucommonoption = button_1;


	static lv_style_t label_1_s0;
	lv_style_init(&label_1_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_1_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_1 = lv_label_create(button_1, NULL);
	lv_obj_set_hidden(label_1, false);
	lv_obj_set_click(label_1, false);
	lv_obj_set_drag(label_1, false);
	lv_plugin_label_allocate_ext_attr(label_1);
	lv_plugin_label_set_text(label_1, LV_PLUGIN_STRING_ID_STRID_A0);
	lv_label_set_text(label_1,"A0");
	lv_plugin_label_allocate_ext_attr(label_1);
	lv_plugin_label_set_font_type(label_1, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_label_set_align(label_1, LV_LABEL_ALIGN_CENTER);
	lv_label_set_long_mode(label_1, LV_LABEL_LONG_CROP);
	lv_obj_set_pos(label_1, 8, 8);
	lv_obj_set_size(label_1, 464, 21);
	lv_obj_add_style(label_1, 0, &label_1_s0);

	label_1_scr_uiflowmenucommonoption = label_1;


	static lv_style_t image_select0_s0;
	lv_style_init(&image_select0_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select0_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select0_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select0_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select0_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select0_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_select0 = lv_img_create(button_1, NULL);
	lv_obj_set_hidden(image_select0, false);
	lv_obj_set_click(image_select0, false);
	lv_obj_set_drag(image_select0, false);
	lv_obj_set_pos(image_select0, 4, 12);
	lv_obj_set_size(image_select0, 24, 17);
	lv_img_set_src(image_select0, &icon_sel_focus);
	lv_obj_add_style(image_select0, 0, &image_select0_s0);

	image_select0_scr_uiflowmenucommonoption = image_select0;


	static lv_style_t button_2_s0;
	lv_style_init(&button_2_s0);
	lv_style_set_radius(&button_2_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&button_2_s0,LV_STATE_DEFAULT,0);
	lv_style_set_border_side(&button_2_s0,LV_STATE_DEFAULT,3);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_2_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_2_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_FOCUSED, color);
	lv_style_set_outline_opa(&button_2_s0,LV_STATE_FOCUSED,255);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_2_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_2 = lv_btn_create(container_main_menu, NULL);
	lv_obj_set_hidden(button_2, false);
	lv_obj_set_click(button_2, true);
	lv_obj_set_drag(button_2, false);
	lv_obj_set_pos(button_2, 20, 37);
	lv_obj_set_size(button_2, 480, 35);
	lv_btn_set_checkable(button_2, false);
	lv_btn_set_layout(button_2, LV_LAYOUT_OFF);
	lv_btn_set_fit(button_2, LV_FIT_NONE);
	lv_obj_add_style(button_2, 0, &button_2_s0);

	button_2_scr_uiflowmenucommonoption = button_2;


	static lv_style_t label_2_s0;
	lv_style_init(&label_2_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_2_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_2_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_2 = lv_label_create(button_2, NULL);
	lv_obj_set_hidden(label_2, false);
	lv_obj_set_click(label_2, false);
	lv_obj_set_drag(label_2, false);
	lv_plugin_label_allocate_ext_attr(label_2);
	lv_label_set_text(label_2,"A1");
	lv_plugin_label_allocate_ext_attr(label_2);
	lv_plugin_label_set_font_type(label_2, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_label_set_align(label_2, LV_LABEL_ALIGN_CENTER);
	lv_label_set_long_mode(label_2, LV_LABEL_LONG_CROP);
	lv_obj_set_pos(label_2, 8, 8);
	lv_obj_set_size(label_2, 464, 18);
	lv_obj_add_style(label_2, 0, &label_2_s0);

	label_2_scr_uiflowmenucommonoption = label_2;


	static lv_style_t image_select1_s0;
	lv_style_init(&image_select1_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_select1 = lv_img_create(button_2, NULL);
	lv_obj_set_hidden(image_select1, false);
	lv_obj_set_click(image_select1, false);
	lv_obj_set_drag(image_select1, false);
	lv_obj_set_pos(image_select1, 4, 12);
	lv_obj_set_size(image_select1, 24, 17);
	lv_img_set_src(image_select1, &icon_sel_focus);
	lv_obj_add_style(image_select1, 0, &image_select1_s0);

	image_select1_scr_uiflowmenucommonoption = image_select1;


	static lv_style_t button_3_s0;
	lv_style_init(&button_3_s0);
	lv_style_set_radius(&button_3_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&button_3_s0,LV_STATE_DEFAULT,0);
	lv_style_set_border_side(&button_3_s0,LV_STATE_DEFAULT,3);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_3_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_3_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_FOCUSED, color);
	lv_style_set_outline_opa(&button_3_s0,LV_STATE_FOCUSED,255);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_3_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_3 = lv_btn_create(container_main_menu, NULL);
	lv_obj_set_hidden(button_3, false);
	lv_obj_set_click(button_3, true);
	lv_obj_set_drag(button_3, false);
	lv_obj_set_pos(button_3, 20, 72);
	lv_obj_set_size(button_3, 480, 35);
	lv_btn_set_checkable(button_3, false);
	lv_btn_set_layout(button_3, LV_LAYOUT_OFF);
	lv_btn_set_fit(button_3, LV_FIT_NONE);
	lv_obj_add_style(button_3, 0, &button_3_s0);

	button_3_scr_uiflowmenucommonoption = button_3;


	static lv_style_t label_3_s0;
	lv_style_init(&label_3_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_3_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_3_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_3 = lv_label_create(button_3, NULL);
	lv_obj_set_hidden(label_3, false);
	lv_obj_set_click(label_3, false);
	lv_obj_set_drag(label_3, false);
	lv_plugin_label_allocate_ext_attr(label_3);
	lv_label_set_text(label_3,"A2");
	lv_plugin_label_allocate_ext_attr(label_3);
	lv_plugin_label_set_font_type(label_3, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_label_set_align(label_3, LV_LABEL_ALIGN_CENTER);
	lv_label_set_long_mode(label_3, LV_LABEL_LONG_CROP);
	lv_obj_set_pos(label_3, 8, 8);
	lv_obj_set_size(label_3, 464, 18);
	lv_obj_add_style(label_3, 0, &label_3_s0);

	label_3_scr_uiflowmenucommonoption = label_3;


	static lv_style_t image_select2_s0;
	lv_style_init(&image_select2_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select2_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select2_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_select2 = lv_img_create(button_3, NULL);
	lv_obj_set_hidden(image_select2, false);
	lv_obj_set_click(image_select2, false);
	lv_obj_set_drag(image_select2, false);
	lv_obj_set_pos(image_select2, 4, 12);
	lv_obj_set_size(image_select2, 24, 17);
	lv_img_set_src(image_select2, &icon_sel_focus);
	lv_obj_add_style(image_select2, 0, &image_select2_s0);

	image_select2_scr_uiflowmenucommonoption = image_select2;


	static lv_style_t button_4_s0;
	lv_style_init(&button_4_s0);
	lv_style_set_radius(&button_4_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&button_4_s0,LV_STATE_DEFAULT,0);
	lv_style_set_border_side(&button_4_s0,LV_STATE_DEFAULT,3);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_DEFAULT, color);
	lv_style_set_outline_width(&button_4_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_DEFAULT, color);
	lv_style_set_value_font(&button_4_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_CHECKED, color);
	lv_style_set_outline_opa(&button_4_s0,LV_STATE_CHECKED,127);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_FOCUSED, color);
	lv_style_set_outline_opa(&button_4_s0,LV_STATE_FOCUSED,255);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x0e, 0x00, 0x00, 0xff) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_bg_color(&button_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&button_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_border_color(&button_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_outline_color(&button_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_shadow_color(&button_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_pattern_recolor(&button_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_value_color(&button_4_s0, LV_STATE_DISABLED, color);
	lv_obj_t *button_4 = lv_btn_create(container_main_menu, NULL);
	lv_obj_set_hidden(button_4, false);
	lv_obj_set_click(button_4, true);
	lv_obj_set_drag(button_4, false);
	lv_obj_set_pos(button_4, 20, 107);
	lv_obj_set_size(button_4, 480, 35);
	lv_btn_set_checkable(button_4, false);
	lv_btn_set_layout(button_4, LV_LAYOUT_OFF);
	lv_btn_set_fit(button_4, LV_FIT_NONE);
	lv_obj_add_style(button_4, 0, &button_4_s0);

	button_4_scr_uiflowmenucommonoption = button_4;


	static lv_style_t label_4_s0;
	lv_style_init(&label_4_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_4_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_4_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xcc, 0x02, 0x62, 0xb6) ; lv_style_set_text_sel_bg_color(&label_4_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_4 = lv_label_create(button_4, NULL);
	lv_obj_set_hidden(label_4, false);
	lv_obj_set_click(label_4, false);
	lv_obj_set_drag(label_4, false);
	lv_plugin_label_allocate_ext_attr(label_4);
	lv_label_set_text(label_4,"A3");
	lv_plugin_label_allocate_ext_attr(label_4);
	lv_plugin_label_set_font_type(label_4, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_label_set_align(label_4, LV_LABEL_ALIGN_CENTER);
	lv_label_set_long_mode(label_4, LV_LABEL_LONG_CROP);
	lv_obj_set_pos(label_4, 8, 8);
	lv_obj_set_size(label_4, 464, 18);
	lv_obj_add_style(label_4, 0, &label_4_s0);

	label_4_scr_uiflowmenucommonoption = label_4;


	static lv_style_t image_select3_s0;
	lv_style_init(&image_select3_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_select3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_select3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_select3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_select3_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xb1, 0x21, 0x4c, 0x3c) ; lv_style_set_image_recolor(&image_select3_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_select3 = lv_img_create(button_4, NULL);
	lv_obj_set_hidden(image_select3, false);
	lv_obj_set_click(image_select3, false);
	lv_obj_set_drag(image_select3, false);
	lv_obj_set_pos(image_select3, 4, 12);
	lv_obj_set_size(image_select3, 24, 17);
	lv_img_set_src(image_select3, &icon_sel_focus);
	lv_obj_add_style(image_select3, 0, &image_select3_s0);

	image_select3_scr_uiflowmenucommonoption = image_select3;


	static lv_style_t container_1_s0;
	lv_style_init(&container_1_s0);
	lv_style_set_radius(&container_1_s0,LV_STATE_DEFAULT,0);
	lv_style_set_pad_inner(&container_1_s0,LV_STATE_DEFAULT,5);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_bg_opa(&container_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_DEFAULT, color);
	lv_style_set_border_width(&container_1_s0,LV_STATE_DEFAULT,0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&container_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&container_1_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xe9, 0xdd, 0xdd, 0xdd) ; lv_style_set_border_color(&container_1_s0, LV_STATE_DISABLED, color);
	lv_obj_t *container_1 = lv_cont_create(parent, NULL);
	lv_obj_set_hidden(container_1, false);
	lv_obj_set_click(container_1, true);
	lv_obj_set_drag(container_1, false);
	lv_obj_set_pos(container_1, 0, 0);
	lv_obj_set_size(container_1, 620, 35);
	lv_obj_add_style(container_1, 0, &container_1_s0);

	container_1_scr_uiflowmenucommonoption = container_1;


	static lv_style_t image_title_bar_s0;
	lv_style_init(&image_title_bar_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&image_title_bar_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&image_title_bar_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&image_title_bar_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_outline_color(&image_title_bar_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_image_recolor(&image_title_bar_s0, LV_STATE_DISABLED, color);
	lv_obj_t *image_title_bar = lv_img_create(container_1, NULL);
	lv_obj_set_hidden(image_title_bar, false);
	lv_obj_set_click(image_title_bar, false);
	lv_obj_set_drag(image_title_bar, false);
	lv_obj_set_pos(image_title_bar, 0, 0);
	lv_obj_set_size(image_title_bar, 620, 40);
	lv_img_set_auto_size(image_title_bar, false);
	lv_img_set_src(image_title_bar, &icon_title_bar);
	lv_obj_add_style(image_title_bar, 0, &image_title_bar_s0);

	image_title_bar_scr_uiflowmenucommonoption = image_title_bar;


	static lv_style_t label_menu_title_s0;
	lv_style_init(&label_menu_title_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_menu_title_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_title_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_title_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_title_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_title_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_title_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_title_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_menu_title = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_menu_title, false);
	lv_obj_set_click(label_menu_title, false);
	lv_obj_set_drag(label_menu_title, false);
	lv_plugin_label_allocate_ext_attr(label_menu_title);
	lv_plugin_label_set_text(label_menu_title, LV_PLUGIN_STRING_ID_STRID_RESOLUTION);
	lv_label_set_text(label_menu_title,"Resolution");
	lv_plugin_label_allocate_ext_attr(label_menu_title);
	lv_plugin_label_set_font_type(label_menu_title, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_label_set_long_mode(label_menu_title, LV_LABEL_LONG_CROP);
	lv_obj_set_pos(label_menu_title, 14, 8);
	lv_obj_set_size(label_menu_title, 296, 18);
	lv_obj_add_style(label_menu_title, 0, &label_menu_title_s0);

	label_menu_title_scr_uiflowmenucommonoption = label_menu_title;


	static lv_style_t label_menu_page_num_s0;
	lv_style_init(&label_menu_page_num_s0);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_DEFAULT, color);
	lv_style_set_text_font(&label_menu_page_num_s0,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_DEFAULT, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_CHECKED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_FOCUSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_EDITED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_HOVERED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_PRESSED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_color(&label_menu_page_num_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_bg_grad_color(&label_menu_page_num_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x01, 0x00, 0x00, 0x00) ; lv_style_set_border_color(&label_menu_page_num_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x02, 0xff, 0xff, 0xff) ; lv_style_set_text_color(&label_menu_page_num_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0xd3, 0x3c, 0x3c, 0x3c) ; lv_style_set_text_sel_color(&label_menu_page_num_s0, LV_STATE_DISABLED, color);
	STYLE_COLOR_PROP(0x3a, 0x00, 0xb4, 0x95) ; lv_style_set_text_sel_bg_color(&label_menu_page_num_s0, LV_STATE_DISABLED, color);
	lv_obj_t *label_menu_page_num = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_menu_page_num, false);
	lv_obj_set_click(label_menu_page_num, false);
	lv_obj_set_drag(label_menu_page_num, false);
	lv_plugin_label_allocate_ext_attr(label_menu_page_num);
	lv_plugin_label_set_text(label_menu_page_num, LV_PLUGIN_STRING_ID_STRID_COMPRESSION);
	lv_label_set_text(label_menu_page_num,"Compression");
	lv_plugin_label_allocate_ext_attr(label_menu_page_num);
	lv_plugin_label_set_font_type(label_menu_page_num, LV_PLUGIN_LANGUAGE_FONT_TYPE_0);
	lv_label_set_align(label_menu_page_num, LV_LABEL_ALIGN_RIGHT);
	lv_label_set_long_mode(label_menu_page_num, LV_LABEL_LONG_CROP);
	lv_obj_set_pos(label_menu_page_num, 326, 9);
	lv_obj_set_size(label_menu_page_num, 277, 18);
	lv_obj_add_style(label_menu_page_num, 0, &label_menu_page_num_s0);

	label_menu_page_num_scr_uiflowmenucommonoption = label_menu_page_num;


	return parent;
}
